MADNESS: 3dharmonic.cc File Reference
3dharmonic.cc File Reference
Solves for the ground state of the quantum 3d harmonic oscillator.
#include <madness/mra/mra.h>
#include <madness/mra/funcplot.h>
#include "nonlinsol.h"
Functions
double guess (const coord_3d &r)
double potential (const coord_3d &r)
void plot (const char *filename, const real_function_3d &f)
double energy (World &world, const real_function_3d &phi, const real_function_3d &V)
int main (int argc, char **argv)
Variables
const double L = 7.0
const double DELTA = 7.0
Detailed Description
Solves for the ground state of the quantum 3d harmonic oscillator.
Function Documentation
double energy (World & world, const real_function_3d & phi, const real_function_3d & V)
References madness::inner().
Referenced by main().
double guess (const coord_3d & r)
References mpfr::exp().
Referenced by doit(), main(), and opt().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, DELTA, energy(), madness::finalize(), guess(), madness::initialize(), L, madness::norm(), madness::Function< T, NDIM >::norm2(), op(), plot(), potential(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), sqrt(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), V(), and madness::wall_time().
void plot (const char * filename, const real_function_3d & f)
References L, and madness::plot_line().
Referenced by madness::bandlimited_propagator_plot(), and main().
double potential (const coord_3d & r)
References DELTA.
Referenced by madness::Solver< T, NDIM >::build_fock_matrix(), madness::SCF::initial_guess(), madness::Solver< T, NDIM >::initial_guess(), main(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), and madness::Solver< T, NDIM >::print_potential_matrix_eigs().
Variable Documentation
const double DELTA = 7.0
Referenced by main(), and potential().
const double L = 7.0
Referenced by madness::add(), madness::FunctionImpl< T, NDIM >::add_scalar_inplace(), MolecularEntity::bounding_cube(), Molecule::bounding_cube(), madness::Molecule::bounding_cube(), madness::FunctionImpl< T, NDIM >::broaden(), madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::SlaterF12Interface::coeff(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::FunctionImpl< Q, NDIM >::do_mul(), energy(), madness::SDFParaboloid::eval_cubic(), madness::XCfunctional::exc(), XCfunctional::exc(), madness::SDFParaboloid::find_root(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), madness::GenericConvolution1D< Q, opT >::GenericConvolution1D(), madness::SDFParaboloid::get_roots(), KAIN(), madness::KAIN(), line_plot(), madness::trajectory< NDIM >::line_xyz(), main(), Molecule::Molecule(), madness::Molecule::Molecule(), Molecule::orient(), madness::Molecule::orient(), plot(), projectPsi(), madness::SDFParaboloid::sdf(), madness::SDFParaboloid::SDFParaboloid(), madness::BaseTensor::set_dims_and_size(), madness::EigSolver< T, NDIM >::solve(), solve(), madness::sub(), Test1(), test_modified(), test_recursive_application(), madness::FunctionImpl< T, NDIM >::truncate_tol(), madness::vmulXX(), madness::XCfunctional::vxc(), XCfunctional::vxc(), and testing::internal::WideStringToUtf8().