MADNESS: hello.cc File Reference
apps/nick/hello.cc File Reference
#include <madness/mra/mra.h>
#include <complex>
#include <string>
#include <fstream>
#include <nick/wavef.h>
#include "mpreal.h"
Typedefs
typedef std::complex< double > complexd
typedef Function< complexd, NDIM > complex_functionT
Functions
const char * wave_function_filename (int step)
bool wave_function_exists (World &world, int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
complex_functionT wave_function_load (World &world, int step)
void doWork (World &world)
int main (int argc, char **argv)
Detailed Description
We are projecting a time evolved wave function onto some bound states
Typedef Documentation
typedef Function<complexd,NDIM> complex_functionT
typedef std::complex<double> complexd
Function Documentation
void doWork (World & world)
References PRINTLINE, wave_function_exists(), and wave_function_load().
Referenced by main().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, doWork(), madness::error(), SafeMPI::Finalize(), SafeMPI::Init(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::startup().
bool wave_function_exists (World & world, int step)
References madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), and wave_function_filename().
Referenced by doWork().
const char* wave_function_filename (int step)
References prefix.
Referenced by wave_function_exists(), wave_function_load(), and wave_function_store().
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by doWork().
void wave_function_store (World & world, int step, const complex_functionT & psi)
References nIOProcessors, psi(), and wave_function_filename().