MADNESS: hatom_energy.cc File Reference
apps/ii/hatom_energy.cc File Reference
Compute the energy of the hydrogen atom ground state.
#include <madness/mra/mra.h>
Functions
double psi (const Vector< double, 3 > &r)
double V (const Vector< double, 3 > &r)
int main (int argc, char **argv)
Detailed Description
Compute the energy of the hydrogen atom ground state.
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::f, SafeMPI::Finalize(), SafeMPI::Init(), madness::print(), psi(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), and V().
double psi (const Vector< double, 3 > & r)
References mpfr::exp(), and sqrt().
Referenced by APPLY(), madness::SCF::APPLY(), madness::APPLY(), madness::GTHPseudopotential< double >::apply_potential(), madness::GTHPseudopotential< double >::apply_potential_simple(), madness::Solver< T, NDIM >::build_fock_matrix(), madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_pe_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_ke_sp(), madness::DFT< T, NDIM >::calculate_tot_ke_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_pe_sp(), compute_energy(), madness::Nemo::compute_fock_matrix(), converge(), converge2s(), madness::PotentialManager::core_projection(), madness::SCF::core_projection(), doit(), iterate(), iterate_ground(), iterate_xy(), line_plot(), main(), madness::HartreeFockExchangeOp< T, NDIM >::op_o(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::op_r(), madness::DFTNuclearPotentialOp< T, NDIM >::op_r(), madness::HartreeFockCoulombOp< T, NDIM >::op_r(), madness::DFTCoulombOp< T, NDIM >::op_r(), madness::DFTCoulombPeriodicOp< T, NDIM >::op_r(), madness::XCFunctionalLDA< T, NDIM >::op_r(), madness::DFTNuclearChargeDensityOp< T, NDIM >::op_r(), print_info(), projectL(), propagate(), psi_exact(), madness::EigSolver< T, NDIM >::solve(), sympgrad4(), sympgrad6(), test_modified(), trotter(), madness::Nemo::value(), wave_function_load(), and wave_function_store().
double V (const Vector< double, 3 > & r)
References sqrt().
Referenced by converge(), dft_xc_lda_ene(), dft_xc_lda_V(), doit(), madness::GMRES(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp(), main(), propagate(), test_modified(), madness::test_syev(), and madness::test_sygv().