MADNESS: clapack.h File Reference
clapack.h File Reference
C++ prototypes for Fortran LAPACK with associated typedefs and macos.
#include <madness/fortran_ctypes.h>
#include <madness/tensor/lapack_functions.h>
Functions
double dlamch_ (const char *mode, int modelen)
float slamch_ (const char *mode, int modelen)
void sgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, real4 *a, integer *lda, real4 *s, real4 *u, integer *ldu, real4 *vt, integer *ldvt, real4 *work, integer *lwork, integer *info, char_len jobulen, char_len jobvtlen)
void dgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, real8 *a, integer *lda, real8 *s, real8 *u, integer *ldu, real8 *vt, integer *ldvt, real8 *work, integer *lwork, integer *info, char_len jobulen, char_len jobvtlen)
void cgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, complex_real4 *a, integer *lda, real4 *s, complex_real4 *u, integer *ldu, complex_real4 *vt, integer *ldvt, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobulen, char_len jobvtlen)
void zgesvd_ (const char *jobu, const char *jobvt, integer *m, integer *n, complex_real8 *a, integer *lda, real8 *s, complex_real8 *u, integer *ldu, complex_real8 *vt, integer *ldvt, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobulen, char_len jobvtlen)
void sgesv_ (integer *n, integer *nrhs, real4 *AT, integer *lda, integer *piv, real4 *x, integer *ldx, integer *info)
void dgesv_ (integer *n, integer *nrhs, real8 *AT, integer *lda, integer *piv, real8 *x, integer *ldx, integer *info)
void cgesv_ (integer *n, integer *nrhs, complex_real4 *AT, integer *lda, integer *piv, complex_real4 *x, integer *ldx, integer *info)
void zgesv_ (integer *n, integer *nrhs, complex_real8 *AT, integer *lda, integer *piv, complex_real8 *x, integer *ldx, integer *info)
void sgelss_ (integer *m, integer *n, integer *nrhs, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *sOUT, real4 *rcondIN, integer *rankOUT, real4 *work, integer *lwork, integer *infoOUT)
void dgelss_ (integer *m, integer *n, integer *nrhs, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *sOUT, real8 *rcondIN, integer *rankOUT, real8 *work, integer *lwork, integer *infoOUT)
void cgelss_ (integer *m, integer *n, integer *nrhs, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, real4 *sOUT, real4 *rcondIN, integer *rankOUT, complex_real4 *work, integer *lwork, real4 *rwork, integer *infoOUT)
void zgelss_ (integer *m, integer *n, integer *nrhs, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, real8 *sOUT, real8 *rcondIN, integer *rankOUT, complex_real8 *work, integer *lwork, real8 *rwork, integer *infoOUT)
void ssyev_ (const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *w, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void dsyev_ (const char *jobz, const char *uplo, integer *n, real8 *a, integer *lda, real8 *w, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void cheev_ (const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, real4 *w, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zheev_ (const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, real8 *w, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void ssygv_ (integer *itype, const char *jobz, const char *uplo, integer *n, real4 *a, integer *lda, real4 *b, integer *ldb, real4 *w, real4 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void dsygv_ (integer *itype, const char *jobz, const char *uplo, integer *n, real8 *a, integer *lda, real8 *b, integer *ldb, real8 *w, real8 *work, integer *lwork, integer *info, char_len jobzlen, char_len uplo_len)
void chegv_ (integer *itype, const char *jobz, const char *uplo, integer *n, complex_real4 *a, integer *lda, complex_real4 *b, integer *ldb, real4 *w, complex_real4 *work, integer *lwork, real4 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void zhegv_ (integer *itype, const char *jobz, const char *uplo, integer *n, complex_real8 *a, integer *lda, complex_real8 *b, integer *ldb, real8 *w, complex_real8 *work, integer *lwork, real8 *rwork, integer *info, char_len jobzlen, char_len uplo_len)
void sgeqrf_ (integer *m, integer *n, real4 *a, integer *lda, real4 *tau, real4 *work, integer *lwork, integer *infoOUT)
void dgeqrf_ (integer *m, integer *n, real8 *a, integer *lda, real8 *tau, real8 *work, integer *lwork, integer *infoOUT)
void sgeqp3_ (integer *m, integer *n, real4 *a, integer *lda, integer *jpvt, real4 *tau, real4 *work, integer *lwork, integer *infoOUT)
void dgeqp3_ (integer *m, integer *n, real8 *a, integer *lda, integer *jpvt, real8 *tau, real8 *work, integer *lwork, integer *infoOUT)
void cgeqp3_ (integer *m, integer *n, complex_real4 *a, integer *lda, integer *jpvt, complex_real4 *tau, complex_real4 *work, integer *lwork, real4 *rwork, integer *infoOUT)
void zgeqp3_ (integer *m, integer *n, complex_real8 *a, integer *lda, integer *jpvt, complex_real8 *tau, complex_real8 *work, integer *lwork, real8 *rwork, integer *infoOUT)
void sorgqr_ (integer *m, integer *n, integer *k, real4 *a, integer *lda, real4 *tau, real4 *work, integer *lwork, integer *info)
void dorgqr_ (integer *m, integer *n, integer *k, real8 *a, integer *lda, real8 *tau, real8 *work, integer *lwork, integer *info)
void cungqr_ (integer *m, integer *n, integer *k, complex_real4 *a, integer *lda, complex_real4 *tau, complex_real4 *work, integer *lwork, integer *info)
void zungqr_ (integer *m, integer *n, integer *k, complex_real8 *a, integer *lda, complex_real8 *tau, complex_real8 *work, integer *lwork, integer *info)
void dpotrf_ (const char *uplo, const integer *n, real8 *a, const integer *lda, integer *info, char_len uplo_len)
void dtrsm_ (const char *side, const char *uplo, const char *transa, const char *diag, const integer *m, const integer *n, const real8 *alpha, const real8 *a, const integer *lda, real8 *b, const integer *ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void dtrtri_ (const char *uplo, const char *diag, const integer *n, const real8 *a, const integer *lda, integer *info)
Detailed Description
C++ prototypes for Fortran LAPACK with associated typedefs and macos.
Function Documentation
void cgelss_ (integer * m, integer * n, integer * nrhs, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, real4 * sOUT, real4 * rcondIN, integer * rankOUT, complex_real4 * work, integer * lwork, real4 * rwork, integer * infoOUT)
Referenced by dgelss_().
void cgeqp3_ (integer * m, integer * n, complex_real4 * a, integer * lda, integer * jpvt, complex_real4 * tau, complex_real4 * work, integer * lwork, real4 * rwork, integer * infoOUT)
void cgesv_ (integer * n, integer * nrhs, complex_real4 * AT, integer * lda, integer * piv, complex_real4 * x, integer * ldx, integer * info)
Referenced by dgesv_().
void cgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, complex_real4 * a, integer * lda, real4 * s, complex_real4 * u, integer * ldu, complex_real4 * vt, integer * ldvt, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by dgesvd_().
void cheev_ (const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, real4 * w, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsyev_().
void chegv_ (integer * itype, const char * jobz, const char * uplo, integer * n, complex_real4 * a, integer * lda, complex_real4 * b, integer * ldb, real4 * w, complex_real4 * work, integer * lwork, real4 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsygv_().
void cungqr_ (integer * m, integer * n, integer * k, complex_real4 * a, integer * lda, complex_real4 * tau, complex_real4 * work, integer * lwork, integer * info)
Referenced by dorgqr_().
void dgelss_ (integer * m, integer * n, integer * nrhs, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * sOUT, real8 * rcondIN, integer * rankOUT, real8 * work, integer * lwork, integer * infoOUT)
void dgeqp3_ (integer * m, integer * n, real8 * a, integer * lda, integer * jpvt, real8 * tau, real8 * work, integer * lwork, integer * infoOUT)
Referenced by madness::geqp3_result().
void dgeqrf_ (integer * m, integer * n, real8 * a, integer * lda, real8 * tau, real8 * work, integer * lwork, integer * infoOUT)
Referenced by madness::lq_result().
void dgesv_ (integer * n, integer * nrhs, real8 * AT, integer * lda, integer * piv, real8 * x, integer * ldx, integer * info)
void dgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, real8 * a, integer * lda, real8 * s, real8 * u, integer * ldu, real8 * vt, integer * ldvt, real8 * work, integer * lwork, integer * info, char_len jobulen, char_len jobvtlen)
double dlamch_ (const char * mode, int modelen)
Referenced by madness::init_tensor_lapack().
void dorgqr_ (integer * m, integer * n, integer * k, real8 * a, integer * lda, real8 * tau, real8 * work, integer * lwork, integer * info)
void dpotrf_ (const char * uplo, const integer * n, real8 * a, const integer * lda, integer * info, char_len uplo_len)
Referenced by madness::cholesky().
void dsyev_ (const char * jobz, const char * uplo, integer * n, real8 * a, integer * lda, real8 * w, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
void dsygv_ (integer * itype, const char * jobz, const char * uplo, integer * n, real8 * a, integer * lda, real8 * b, integer * ldb, real8 * w, real8 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
void dtrsm_ (const char * side, const char * uplo, const char * transa, const char * diag, const integer * m, const integer * n, const real8 * alpha, const real8 * a, const integer * lda, real8 * b, const integer * ldb, char_len sidelen, char_len uplolen, char_len transalen, char_len diaglen)
void dtrtri_ (const char * uplo, const char * diag, const integer * n, const real8 * a, const integer * lda, integer * info)
void sgelss_ (integer * m, integer * n, integer * nrhs, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * sOUT, real4 * rcondIN, integer * rankOUT, real4 * work, integer * lwork, integer * infoOUT)
Referenced by dgelss_().
void sgeqp3_ (integer * m, integer * n, real4 * a, integer * lda, integer * jpvt, real4 * tau, real4 * work, integer * lwork, integer * infoOUT)
void sgeqrf_ (integer * m, integer * n, real4 * a, integer * lda, real4 * tau, real4 * work, integer * lwork, integer * infoOUT)
void sgesv_ (integer * n, integer * nrhs, real4 * AT, integer * lda, integer * piv, real4 * x, integer * ldx, integer * info)
Referenced by dgesv_().
void sgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, real4 * a, integer * lda, real4 * s, real4 * u, integer * ldu, real4 * vt, integer * ldvt, real4 * work, integer * lwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by dgesvd_().
float slamch_ (const char * mode, int modelen)
Referenced by madness::init_tensor_lapack().
void sorgqr_ (integer * m, integer * n, integer * k, real4 * a, integer * lda, real4 * tau, real4 * work, integer * lwork, integer * info)
Referenced by dorgqr_().
void ssyev_ (const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * w, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsyev_().
void ssygv_ (integer * itype, const char * jobz, const char * uplo, integer * n, real4 * a, integer * lda, real4 * b, integer * ldb, real4 * w, real4 * work, integer * lwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsygv_().
void zgelss_ (integer * m, integer * n, integer * nrhs, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, real8 * sOUT, real8 * rcondIN, integer * rankOUT, complex_real8 * work, integer * lwork, real8 * rwork, integer * infoOUT)
Referenced by dgelss_().
void zgeqp3_ (integer * m, integer * n, complex_real8 * a, integer * lda, integer * jpvt, complex_real8 * tau, complex_real8 * work, integer * lwork, real8 * rwork, integer * infoOUT)
void zgesv_ (integer * n, integer * nrhs, complex_real8 * AT, integer * lda, integer * piv, complex_real8 * x, integer * ldx, integer * info)
Referenced by dgesv_().
void zgesvd_ (const char * jobu, const char * jobvt, integer * m, integer * n, complex_real8 * a, integer * lda, real8 * s, complex_real8 * u, integer * ldu, complex_real8 * vt, integer * ldvt, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobulen, char_len jobvtlen)
Referenced by dgesvd_().
void zheev_ (const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, real8 * w, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsyev_().
void zhegv_ (integer * itype, const char * jobz, const char * uplo, integer * n, complex_real8 * a, integer * lda, complex_real8 * b, integer * ldb, real8 * w, complex_real8 * work, integer * lwork, real8 * rwork, integer * info, char_len jobzlen, char_len uplo_len)
Referenced by dsygv_().
void zungqr_ (integer * m, integer * n, integer * k, complex_real8 * a, integer * lda, complex_real8 * tau, complex_real8 * work, integer * lwork, integer * info)
Referenced by dorgqr_().