MADNESS: madness::CorePotentialManager Class Reference
madness::CorePotentialManager Class Reference
#include <corepotential.h>
Public Member Functions
CorePotentialManager ()
CorePotentialManager (std::string filename, double eprec)
bool is_defined (const unsigned int atn) const
unsigned int n_core_orb (const unsigned int atn) const
unsigned int n_core_orb_base (const unsigned int atn) const
std::string guess_file () const
AtomCore get_atom_core (unsigned int atn) const
CorePotential get_potential (unsigned int atn) const
unsigned int get_core_l (unsigned int atn, unsigned int core) const
double get_core_bc (unsigned int atn, unsigned int core) const
double core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const
double core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const
double potential (unsigned int atn, double r) const
double potential_derivative (unsigned int atn, double xi, double r) const
void read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
void set_eprec (double value)
void set_rcut (double value)
template<typename Archive >
void serialize (Archive &ar)
Constructor & Destructor Documentation
madness::CorePotentialManager::CorePotentialManager () inline
madness::CorePotentialManager::CorePotentialManager (std::string filename, double eprec) inline
References read_file().
Member Function Documentation
double madness::CorePotentialManager::core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const inline
References get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::core_derivative().
double madness::CorePotentialManager::core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const inline
References get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::core_eval().
AtomCore madness::CorePotentialManager::get_atom_core (unsigned int atn) const inline
Referenced by core_derivative(), core_eval(), get_core_bc(), and get_core_l().
double madness::CorePotentialManager::get_core_bc (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::get_core_bc().
unsigned int madness::CorePotentialManager::get_core_l (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and madness::AtomCore::orbital.
Referenced by madness::Molecule::get_core_l().
CorePotential madness::CorePotentialManager::get_potential (unsigned int atn) const inline
std::string madness::CorePotentialManager::guess_file () const inline
Referenced by madness::Molecule::guess_file().
bool madness::CorePotentialManager::is_defined (const unsigned int atn) const inline
Referenced by madness::Molecule::is_potential_defined(), madness::Molecule::is_potential_defined_atom(), madness::Molecule::molecular_core_potential(), madness::Molecule::n_core_orb(), madness::Molecule::n_core_orb_all(), madness::Molecule::nuclear_dipole(), madness::Molecule::nuclear_repulsion_derivative(), madness::Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_energy_pseudo(), and madness::Molecule::read_core_file().
unsigned int madness::CorePotentialManager::n_core_orb (const unsigned int atn) const inline
Referenced by madness::Molecule::n_core_orb_all(), madness::Molecule::nuclear_dipole(), madness::Molecule::nuclear_repulsion_derivative(), madness::Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_energy_pseudo(), and madness::Molecule::read_core_file().
unsigned int madness::CorePotentialManager::n_core_orb_base (const unsigned int atn) const inline
Referenced by madness::Molecule::n_core_orb().
double madness::CorePotentialManager::potential (unsigned int atn, double r) const inline
References madness::CorePotential::eval(), and madness::AtomCore::potential.
Referenced by madness::Molecule::molecular_core_potential().
double madness::CorePotentialManager::potential_derivative (unsigned int atn, double xi, double r) const inline
References madness::CorePotential::eval_derivative(), and madness::AtomCore::potential.
Referenced by madness::Molecule::core_potential_derivative().
void madness::CorePotentialManager::read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
Referenced by CorePotentialManager(), and madness::Molecule::read_core_file().
template<typename Archive > void madness::CorePotentialManager::serialize (Archive & ar) inline
void CorePotentialManager::set_eprec (double value)
References madness::smoothing_parameter().
Referenced by madness::Molecule::set_core_eprec(), and madness::Molecule::set_eprec().
void CorePotentialManager::set_rcut (double value)
Referenced by madness::Molecule::set_core_rcut().
The documentation for this class was generated from the following files:
chem/corepotential.h
chem/corepotential.cc