MADNESS: madness::MutexFair Class Reference
madness::MutexFair Class Reference
A scalable and fair mutex (not recursive)
#include <worldmutex.h>
Public Member Functions
MutexFair ()
void lock () const
void unlock () const
bool try_lock () const
Detailed Description
A scalable and fair mutex (not recursive)
Needs rewriting to use the CV above and do we really need this if using pthread_mutex .. why not pthread_cv?
Constructor & Destructor Documentation
madness::MutexFair::MutexFair () inline
Member Function Documentation
void madness::MutexFair::lock () const inline
References b(), madness::cpu_relax(), madness::Spinlock::lock(), and madness::Spinlock::unlock().
bool madness::MutexFair::try_lock () const inline
References madness::Spinlock::lock(), and madness::Spinlock::unlock().
void madness::MutexFair::unlock () const inline
References madness::f, madness::Spinlock::lock(), and madness::Spinlock::unlock().
The documentation for this class was generated from the following file:
worldmutex.h