MADNESS: madness::tr1::shptr::detail::sp_counted_base Class Reference
madness::tr1::shptr::detail::sp_counted_base Class Reference abstract
#include <shared_ptr_bits.h>
Public Member Functions
sp_counted_base ()
virtual ~sp_counted_base ()
virtual void dispose ()=0
virtual void destroy ()
virtual void * get_deleter (std::type_info const &ti)=0
void add_ref_copy ()
bool add_ref_lock ()
void release ()
void weak_add_ref ()
void weak_release ()
long use_count () const
Constructor & Destructor Documentation
madness::tr1::shptr::detail::sp_counted_base::sp_counted_base () inline
virtual madness::tr1::shptr::detail::sp_counted_base::~sp_counted_base () inline virtual
Member Function Documentation
void madness::tr1::shptr::detail::sp_counted_base::add_ref_copy () inline
Referenced by madness::tr1::shptr::detail::shared_count::operator=(), and madness::tr1::shptr::detail::shared_count::shared_count().
bool madness::tr1::shptr::detail::sp_counted_base::add_ref_lock () inline
Referenced by madness::tr1::shptr::detail::shared_count::shared_count().
virtual void madness::tr1::shptr::detail::sp_counted_base::destroy () inline virtual
virtual void madness::tr1::shptr::detail::sp_counted_base::dispose () pure virtual
Implemented in madness::tr1::shptr::detail::sp_counted_impl_pd< Y, D >, and madness::tr1::shptr::detail::sp_counted_impl_p< X >.
virtual void* madness::tr1::shptr::detail::sp_counted_base::get_deleter (std::type_info const & ti) pure virtual
Implemented in madness::tr1::shptr::detail::sp_counted_impl_pd< Y, D >, and madness::tr1::shptr::detail::sp_counted_impl_p< X >.
Referenced by madness::tr1::shptr::detail::shared_count::get_deleter().
void madness::tr1::shptr::detail::sp_counted_base::release () inline
References madness::AtomicInt::dec_and_test().
Referenced by madness::tr1::shptr::detail::shared_count::operator=(), and madness::tr1::shptr::detail::shared_count::~shared_count().
long madness::tr1::shptr::detail::sp_counted_base::use_count () const inline
Referenced by madness::tr1::shptr::detail::shared_count::use_count(), and madness::tr1::shptr::detail::weak_count::use_count().
void madness::tr1::shptr::detail::sp_counted_base::weak_add_ref () inline
Referenced by madness::tr1::shptr::detail::weak_count::operator=(), and madness::tr1::shptr::detail::weak_count::weak_count().
void madness::tr1::shptr::detail::sp_counted_base::weak_release () inline
References madness::AtomicInt::dec_and_test().
Referenced by madness::tr1::shptr::detail::weak_count::operator=(), and madness::tr1::shptr::detail::weak_count::~weak_count().
The documentation for this class was generated from the following file:
shared_ptr_bits.h