MADNESS: madness::XCfunctional Class Reference
madness::XCfunctional Class Reference
Simplified interface to XC functionals.
#include <xcfunctional.h>
Public Member Functions
XCfunctional ()
Default constructor is required.
void initialize (const std::string &input_line, bool polarized)
Initialize the object from the user input data.
~XCfunctional ()
Destructor.
bool is_lda () const
Returns true if the potential is lda.
bool is_gga () const
Returns true if the potential is gga (needs first derivatives)
bool is_meta () const
Returns true if the potential is meta gga (needs second derivatives ... not yet supported)
bool is_dft () const
Returns true if there is a DFT functional (false probably means Hatree-Fock exchange only)
bool is_spin_polarized () const
Returns true if the functional is spin_polarized.
bool has_fxc () const
Returns true if the second derivative of the functional is available (not yet supported)
bool has_kxc () const
Returns true if the third derivative of the functional is available (not yet supported)
double hf_exchange_coefficient () const
Returns the value of the hf exact exchange coefficient.
madness::Tensor< double > exc (const std::vector< madness::Tensor< double > > &t, const int ispin) const
Computes the energy functional at given points.
madness::Tensor< double > vxc (const std::vector< madness::Tensor< double > > &t, const int ispin, const int what) const
Computes components of the potential (derivative of the energy functional) at np points.
madness::Tensor< double > fxc (const std::vector< madness::Tensor< double > > &t, const int ispin, const int what) const
void plot () const
Crude function to plot the energy and potential functionals.
Protected Member Functions
double munge (double rho) const
void munge2 (double &rho, double &sigma) const
void munge5 (double &rhoa, double &rhob, double &saa, double &sab, double &sbb) const
Static Protected Member Functions
static void polyn (const double x, double &p, double &dpdx)
Smoothly switches between constant (x<xmin) and linear function (x>xmax)
static double munge_old (double rho)
Protected Attributes
bool spin_polarized
True if the functional is spin polarized.
double hf_coeff
Factor multiplying HF exchange (+1.0 gives HF)
double rhomin
double rhotol
double sigmin
double sigtol
Detailed Description
Simplified interface to XC functionals.
Constructor & Destructor Documentation
XCfunctional::XCfunctional ()
Default constructor is required.
XCfunctional::~XCfunctional ()
Destructor.
Member Function Documentation
madness::Tensor< double > XCfunctional::exc (const std::vector< madness::Tensor< double > > & t, const int ispin) const
Computes the energy functional at given points.
This uses the convention that the total energy is
Any HF exchange contribution must be separately computed.
Items in the vector argument t are interpreted as follows
Spin un-polarized
t[0] =
t[1] = (GGA only)
Spin polarized
t[0] =
t[1] =
t[2] = (GGA only)
t[3] = (GGA only)
t[4] = (GGA only)
Parameters
t The input densities and derivatives as required by the functional
Returns
The exchange-correlation energy functional
References madness::c_rks_vwn5__(), madness::c_uks_vwn5__(), madness::f, L, munge(), spin_polarized, madness::x_rks_s__(), and madness::x_uks_s__().
Referenced by madness::xc_functional::operator()(), and plot().
madness::Tensor< double > XCfunctional::fxc (const std::vector< madness::Tensor< double > > & t, const int ispin, const int what) const
References MADNESS_EXCEPTION.
Referenced by madness::make_fxc::operator()(), madness::get_derivatives::operator()(), madness::perturbed_vxc::operator()(), madness::apply_kernel_functor::operator()(), and madness::xc_kernel::operator()().
bool XCfunctional::has_fxc () const
Returns true if the second derivative of the functional is available (not yet supported)
bool XCfunctional::has_kxc () const
Returns true if the third derivative of the functional is available (not yet supported)
double madness::XCfunctional::hf_exchange_coefficient () const inline
Returns the value of the hf exact exchange coefficient.
References hf_coeff.
Referenced by SCF::apply_potential(), and madness::SCF::apply_potential().
void XCfunctional::initialize (const std::string & input_line, bool polarized)
Initialize the object from the user input data.
Parameters
[in] input_line User input line (without beginning XC keyword)
[in] polarized Boolean flag indicating if the calculation is spin-polarized
References hf_coeff, rhomin, rhotol, sigmin, sigtol, spin_polarized, and madness::transform().
Referenced by main(), and madness::SCF::SCF().
bool XCfunctional::is_dft () const
Returns true if there is a DFT functional (false probably means Hatree-Fock exchange only)
References is_gga(), is_lda(), and is_meta().
Referenced by SCF::apply_potential(), madness::SCF::apply_potential(), and madness::SCF::solve().
bool XCfunctional::is_gga () const
Returns true if the potential is gga (needs first derivatives)
Referenced by madness::TDA_DFT::apply_kernel(), SCF::apply_potential(), madness::SCF::apply_potential(), WSTFunctional::apply_xc(), madness::TDA_DFT::convolution_with_kernel(), madness::TDA_DFT::evaluate_derivatives(), is_dft(), madness::TDA_DFT::is_gga(), main(), madness::perturbed_vxc::operator()(), madness::apply_kernel_functor::operator()(), madness::SCF::solve(), and madness::TDA_DFT::TDA_DFT().
bool XCfunctional::is_lda () const
Returns true if the potential is lda.
References hf_coeff.
Referenced by madness::TDA_DFT::convolution_with_kernel(), is_dft(), madness::perturbed_vxc::operator()(), and madness::TDA_DFT::TDA_DFT().
bool XCfunctional::is_meta () const
Returns true if the potential is meta gga (needs second derivatives ... not yet supported)
Referenced by is_dft().
bool madness::XCfunctional::is_spin_polarized () const inline
Returns true if the functional is spin_polarized.
References spin_polarized.
Referenced by SCF::apply_potential(), madness::SCF::apply_potential(), plot(), madness::SCF::solve(), and madness::TDA_DFT::TDA_DFT().
double madness::XCfunctional::munge (double rho) const inline protected
References rhomin.
Referenced by exc(), and vxc().
void madness::XCfunctional::munge2 (double & rho, double & sigma) const inline protected
References rhomin, and sigmin.
void madness::XCfunctional::munge5 (double & rhoa, double & rhob, double & saa, double & sab, double & sbb) const inline protected
References rhomin, and sigmin.
static double madness::XCfunctional::munge_old (double rho) inline static protected
References polyn().
void madness::XCfunctional::plot () const inline
Crude function to plot the energy and potential functionals.
References exc(), madness::f, is_spin_polarized(), and vxc().
static void madness::XCfunctional::polyn (const double x, double & p, double & dpdx) inline static protected
Smoothly switches between constant (x<xmin) and linear function (x>xmax)
where is the unique quintic polynomial that satisfies , , , and .
References a(), b(), and c.
Referenced by munge_old().
madness::Tensor< double > XCfunctional::vxc (const std::vector< madness::Tensor< double > > & t, const int ispin, const int what) const
Computes components of the potential (derivative of the energy functional) at np points.
Any HF exchange contribution must be separately computed.
See the documenation of the exc() method for contents of the input t[] argument
We define with or .
For unpolarized GGA, matrix elements of the potential are
For polarized GGA, matrix elements of the potential are
Integrating the above by parts and assuming free-space or periodic boundary conditions we obtain that the local multiplicative form of the GGA potential is
Until we get a madness::Function operation that can produce multiple results we need to compute components of the functional and potential separately:
Spin un-polarized
what=0
what=1 (GGA only)
Spin polarized
what=0
what=1
what=2
what=3
what=4
Parameters
[in] t The input densities and derivatives as required by the functional
[in] what Specifies which component of the potential is to be computed as described above
Returns
The component specified by the what parameter
References madness::c_rks_vwn5__(), madness::c_uks_vwn5__(), madness::f, L, munge(), spin_polarized, madness::x_rks_s__(), and madness::x_uks_s__().
Referenced by madness::unperturbed_vxc::operator()(), madness::perturbed_vxc::operator()(), madness::xc_potential::operator()(), and plot().
Member Data Documentation
double madness::XCfunctional::hf_coeff protected
Factor multiplying HF exchange (+1.0 gives HF)
Referenced by hf_exchange_coefficient(), initialize(), and is_lda().
double madness::XCfunctional::rhomin protected
Referenced by initialize(), munge(), munge2(), and munge5().
double madness::XCfunctional::rhotol protected
Referenced by initialize().
double madness::XCfunctional::sigmin protected
Referenced by initialize(), munge2(), and munge5().
double madness::XCfunctional::sigtol protected
Referenced by initialize().
bool madness::XCfunctional::spin_polarized protected
True if the functional is spin polarized.
Referenced by exc(), initialize(), is_spin_polarized(), and vxc().
The documentation for this class was generated from the following files:
chem/xcfunctional.h
chem/xcfunctional_ldaonly.cc
chem/xcfunctional_libxc.cc