MADNESS: madness::QuasiNewton Class Reference
madness::QuasiNewton Class Reference
MADNESS libraries » Iterative solvers for linear/non-linear equations and optimizers
Optimization via quasi-Newton (BFGS or SR1 update)
#include <solvers.h>
Public Member Functions
QuasiNewton (const std::shared_ptr< OptimizationTargetInterface > &tar, int maxiter=20, double tol=1e-6, double value_precision=1e-12, double gradient_precision=1e-12)
void set_update (const std::string &method)
Choose update method (currently only "BFGS" or "SR1")
void set_test (const bool &test_level)
Choose update method (currently only "BFGS" or "SR1")
bool optimize (Tensor< double > &x)
Runs the optimizer.
bool converged () const
After running the optimizer returns true if converged.
double value () const
Value of objective function.
void reset_hessian ()
Resets Hessian to default guess.
void set_hessian (const Tensor< double > &matrix)
Sets Hessian to given matrix.
double gradient_norm () const
Value of gradient norm.
virtual ~QuasiNewton ()
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Detailed Description
Optimization via quasi-Newton (BFGS or SR1 update)
This is presently not a low memory algorithm ... we really need one!
Constructor & Destructor Documentation
QuasiNewton::QuasiNewton (const std::shared_ptr< OptimizationTargetInterface > & tar, int maxiter = 20, double tol = 1e-6, double value_precision = 1e-12, double gradient_precision = 1e-12)
References madness::OptimizationTargetInterface::provides_gradient().
virtual madness::QuasiNewton::~QuasiNewton () inline virtual
Member Function Documentation
bool QuasiNewton::converged () const virtual
After running the optimizer returns true if converged.
Returns
True if converged
Implements madness::OptimizerInterface.
Referenced by optimize().
double QuasiNewton::gradient_norm () const virtual
Value of gradient norm.
Returns
Norm of gradient of objective function
Implements madness::OptimizerInterface.
bool QuasiNewton::optimize (Tensor< double > & x) virtual
Runs the optimizer.
Returns
True if converged
Implements madness::OptimizerInterface.
References converged(), madness::g, madness::print(), madness::OptimizationTargetInterface::test_gradient(), and madness::OptimizationTargetInterface::value_and_gradient().
Referenced by main().
void madness::QuasiNewton::reset_hessian () inline
Resets Hessian to default guess.
Referenced by main().
void madness::QuasiNewton::set_hessian (const Tensor< double > & matrix) inline
Sets Hessian to given matrix.
References madness::copy().
Referenced by main().
void QuasiNewton::set_test (const bool & test_level)
Choose update method (currently only "BFGS" or "SR1")
Referenced by main().
void QuasiNewton::set_update (const std::string & method)
Choose update method (currently only "BFGS" or "SR1")
Referenced by main().
double QuasiNewton::value () const virtual
Value of objective function.
Returns
Value of objective function
Implements madness::OptimizerInterface.
The documentation for this class was generated from the following files:
solvers.h
solvers.cc