MADNESS: madness::archive::VectorOutputArchive Class Reference
madness::archive::VectorOutputArchive Class Reference
Wraps an archive around an STL vector for output.
#include <vecar.h>
Public Member Functions
VectorOutputArchive (std::vector< unsigned char > &v, std::size_t hint=262144)
template<class T >
madness::enable_if
< madness::is_serializable< T >
, void >::type store (const T *t, long n) const
void open (std::size_t hint=262144)
void close ()
void flush ()
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Additional Inherited Members
Static Public Attributes inherited from madness::archive::BaseOutputArchive
static const bool is_output_archive = true
Static Public Attributes inherited from madness::archive::BaseArchive
static const bool is_archive = true
static const bool is_input_archive = false
static const bool is_output_archive = false
static const bool is_parallel_archive = false
Detailed Description
Wraps an archive around an STL vector for output.
Constructor & Destructor Documentation
madness::archive::VectorOutputArchive::VectorOutputArchive (std::vector< unsigned char > & v, std::size_t hint = 262144) inline
References open().
Member Function Documentation
void madness::archive::VectorOutputArchive::close () inline
void madness::archive::VectorOutputArchive::flush () inline
void madness::archive::VectorOutputArchive::open (std::size_t hint = 262144) inline
Referenced by VectorOutputArchive().
template<class T > madness::enable_if< madness::is_serializable<T>, void >::type madness::archive::VectorOutputArchive::store (const T * t, long n) const inline
References std::tr1::T().
Referenced by madness::archive::MPIOutputArchive::store().
The documentation for this class was generated from the following file:
vecar.h