MADNESS: madness::GaussianConvolution1D< Q > Class Template Reference
madness::GaussianConvolution1D< Q > Class Template Reference
MADNESS libraries » Multiresolution analaysis » Function
1D convolution with (derivative) Gaussian; coeff and expnt given in simulation coordinates [0,1]
#include <convolution1d.h>
Public Member Functions
GaussianConvolution1D (int k, Q coeff, double expnt, int m, bool periodic, double arg=0.0)
virtual ~GaussianConvolution1D ()
virtual Level natural_level () const
Returns the level for projection.
Tensor< Q > rnlp (Level n, Translation lx) const
Compute the projection of the operator onto the double order polynomials.
bool issmall (Level n, Translation lx) const
Returns true if the block is expected to be small.
Public Member Functions inherited from madness::Convolution1D< Q >
virtual ~Convolution1D ()
Convolution1D (int k, int npt, int maxR, double arg=0.0)
bool get_issmall (Level n, Translation lx) const
Returns true if the block of rnlp is expected to be small including periodicity.
const Tensor< Q > & rnlij (Level n, Translation lx, bool do_transpose=false) const
Computes the transition matrix elements for the convolution for n,l.
const ConvolutionData1D< Q > * mod_nonstandard (const Key< 2 > &op_key) const
Returns a pointer to the cached modified nonstandard form of the operator.
const ConvolutionData1D< Q > * nonstandard (Level n, Translation lx) const
Returns a pointer to the cached nonstandard form of the operator.
Q phase (double R) const
Q phase (double_complex R) const
const Tensor< Q > & get_rnlp (Level n, Translation lx) const
Public Attributes
const Q coeff
Coefficient.
const double expnt
Exponent.
const Level natlev
Level to evaluate.
const int m
Order of derivative (0, 1, or 2 only)
Public Attributes inherited from madness::Convolution1D< Q >
int k
Wavelet order.
int npt
Number of quadrature points (is this used?)
int maxR
Number of lattice translations for sum.
Tensor< double > quad_x
Tensor< double > quad_w
Tensor< double > c
Tensor< double > hgT
Tensor< double > hg
Tensor< double > hgT2k
double arg
SimpleCache< Tensor< Q >, 1 > rnlp_cache
SimpleCache< Tensor< Q >, 1 > rnlij_cache
SimpleCache< ConvolutionData1D
< Q >, 1 > ns_cache
SimpleCache< ConvolutionData1D
< Q >, 2 > mod_ns_cache
Additional Inherited Members
Public Types inherited from madness::Convolution1D< Q >
typedef Q opT
The apply function uses this to infer resultT=opT*inputT.
Detailed Description
template<typename Q>
class madness::GaussianConvolution1D< Q >
1D convolution with (derivative) Gaussian; coeff and expnt given in simulation coordinates [0,1]
Note that the derivative is computed in simulation coordinates so you must be careful to scale the coefficients correctly.
Constructor & Destructor Documentation
template<typename Q > madness::GaussianConvolution1D< Q >::GaussianConvolution1D (int k, Q coeff, double expnt, int m, bool periodic, double arg = 0.0) inline explicit
template<typename Q > virtual madness::GaussianConvolution1D< Q >::~GaussianConvolution1D () inline virtual
Member Function Documentation
template<typename Q > bool madness::GaussianConvolution1D< Q >::issmall (Level n, Translation lx) const inline virtual
Returns true if the block is expected to be small.
Implements madness::Convolution1D< Q >.
References beta.
template<typename Q > virtual Level madness::GaussianConvolution1D< Q >::natural_level () const inline virtual
Returns the level for projection.
Reimplemented from madness::Convolution1D< Q >.
References madness::GaussianConvolution1D< Q >::natlev.
template<typename Q > Tensor<Q> madness::GaussianConvolution1D< Q >::rnlp (Level n, Translation lx) const inline virtual
Compute the projection of the operator onto the double order polynomials.
The returned reference is to a cached tensor ... if you want to modify it, take a copy first.
Return in v[p] p=0..2*k-1
r(n,l,p) = 2^(-n) * int(K(2^(-n)*(z+l)) * phi(p,z), z=0..1)
The kernel is coeff*exp(-expnt*z^2)*z^m (with m>0). This is equivalent to
r(n,l,p) = 2^(-n*(m+1))*coeff * int(((d/dz)^m exp(-beta*z^2)) * phi(p,z-l), z=l..l+1)
where
beta = alpha * 2^(-2*n)
Implements madness::Convolution1D< Q >.
References beta, mpfr::exp(), madness::GaussianConvolution1D< Q >::expnt, madness::Convolution1D< Q >::k, madness::legendre_scaling_functions(), mpfr::log(), madness::Convolution1D< Q >::npt, madness::Convolution1D< Q >::quad_w, madness::Convolution1D< Q >::quad_x, and sqrt().
Member Data Documentation
template<typename Q > const Q madness::GaussianConvolution1D< Q >::coeff
Coefficient.
template<typename Q > const double madness::GaussianConvolution1D< Q >::expnt
Exponent.
Referenced by madness::GaussianConvolution1D< Q >::rnlp().
template<typename Q > const int madness::GaussianConvolution1D< Q >::m
Order of derivative (0, 1, or 2 only)
template<typename Q > const Level madness::GaussianConvolution1D< Q >::natlev
Level to evaluate.
Referenced by madness::GaussianConvolution1D< Q >::natural_level().
The documentation for this class was generated from the following file:
convolution1d.h