MADNESS: mu::Parser Class Reference
mu::Parser Class Reference
Mathematical expressions parser.
#include <muParser.h>
Public Member Functions
Parser ()
Constructor.
virtual void InitCharSets ()
Define the character sets.
virtual void InitFun ()
Initialize the default functions.
virtual void InitConst ()
Initialize constants.
virtual void InitOprt ()
Initialize operators.
void SetDecSep (char_type cDecSep)
Set the decimal separator.
void SetThousandsSep (char_type cThousandsSep)
Sets the thousands operator.
value_type Diff (value_type *a_Var, value_type a_fPos, value_type a_fEpsilon=0.00074) const
Numerically differentiate with regard to a variable.
Public Member Functions inherited from mu::ParserBase
ParserBase ()
Constructor.
ParserBase (const ParserBase &a_Parser)
ParserBase & operator= (const ParserBase &a_Parser)
Assignement operator.
virtual ~ParserBase ()
value_type Eval () const
Calculate the result.
void SetExpr (const string_type &a_sExpr)
Set the formula.
void SetVarFactory (facfun_type a_pFactory, void *pUserData=NULL)
void EnableOptimizer (bool a_bIsOn=true)
Enable or disable the formula optimization feature.
void EnableByteCode (bool a_bIsOn=true)
Enable or disable parsing from Bytecode.
void EnableBuiltInOprt (bool a_bIsOn=true)
Enable or disable the built in binary operators.
bool HasBuiltInOprt () const
Query status of built in variables.
void AddValIdent (identfun_type a_pCallback)
void DefineOprt (const string_type &a_strName, fun_type2 a_pFun, unsigned a_iPri=0, bool a_bAllowOpt=false)
Define a binary operator.
void DefineConst (const string_type &a_sName, value_type a_fVal)
Add a user defined constant.
void DefineStrConst (const string_type &a_sName, const string_type &a_strVal)
Define a new string constant.
void DefineVar (const string_type &a_sName, value_type *a_fVar)
Add a user defined variable.
void DefinePostfixOprt (const string_type &a_strFun, fun_type1 a_pOprt, bool a_bAllowOpt=true)
Add a user defined operator.
void DefineInfixOprt (const string_type &a_strName, fun_type1 a_pOprt, int a_iPrec=prINFIX, bool a_bAllowOpt=true)
Add a user defined operator.
void ClearVar ()
Clear all user defined variables.
void ClearFun ()
Clear all functions.
void ClearConst ()
Clear all user defined constants.
void ClearInfixOprt ()
Clear the user defined Prefix operators.
void ClearPostfixOprt ()
Clear all user defined postfix operators.
void ClearOprt ()
Clear all user defined binary operators.
void RemoveVar (const string_type &a_strVarName)
Remove a variable from internal storage.
const varmap_type & GetUsedVar () const
Return a map containing the used variables only.
const varmap_type & GetVar () const
Return a map containing the used variables only.
const valmap_type & GetConst () const
Return a map containing all parser constants.
const string_type & GetExpr () const
Retrieve the formula.
const funmap_type & GetFunDef () const
Return prototypes of all parser functions.
const char_type ** GetOprtDef () const
Get the default symbols used for the built in operators.
void DefineNameChars (const char_type *a_szCharset)
Define the set of valid characters to be used in names of functions, variables, constants.
void DefineOprtChars (const char_type *a_szCharset)
Define the set of valid characters to be used in names of binary operators and postfix operators.
void DefineInfixOprtChars (const char_type *a_szCharset)
Define the set of valid characters to be used in names of infix operators.
const char_type * ValidNameChars () const
Virtual function that defines the characters allowed in name identifiers.
const char_type * ValidOprtChars () const
Virtual function that defines the characters allowed in operator definitions.
const char_type * ValidInfixOprtChars () const
Virtual function that defines the characters allowed in infix operator definitions.
void SetArgSep (char_type cArgSep)
Set argument separator.
char_type GetArgSep () const
Get the argument separator character.
void Error (EErrorCodes a_iErrc, int a_iPos=(int) mu::string_type::npos, const string_type &a_strTok=string_type()) const
Create an error containing the parse error position.
Additional Inherited Members
Public Types inherited from mu::ParserBase
typedef ParserError exception_type
Type of the error class.
Protected Member Functions inherited from mu::ParserBase
void Init ()
Initialize user defined functions.
Static Protected Attributes inherited from mu::ParserBase
static const char_type * c_DefaultOprt []
Identifiers for built in binary operators.
Detailed Description
Mathematical expressions parser.
Standard implementation of the mathematical expressions parser. Can be used as a reference implementation for subclassing the parser.
(C) 2004-2008 Ingo Berg
ingo_berg(at)gmx.de
Constructor & Destructor Documentation
mu::Parser::Parser ()
Constructor.
Call ParserBase class constructor and trigger Function, Operator and Constant initialization.
References mu::ParserBase::AddValIdent(), InitCharSets(), InitConst(), InitFun(), and InitOprt().
Member Function Documentation
value_type mu::Parser::Diff (value_type * a_Var, value_type a_fPos, value_type a_fEpsilon = 0.00074) const
Numerically differentiate with regard to a variable.
Parameters
[in] a_Var Pointer to the differentiation variable.
[in] a_fPos Position at which the differentiation should take place.
[in] a_fEpsilon Epsilon used for the numerical differentiation.
Numerical differentiation uses a 5 point operator yielding a 4th order formula. The default value for epsilon is 0.00074 which is numerical_limits<double>::epsilon() ^ (1/5) as suggested in the muparser forum:
http://sourceforge.net/forum/forum.php?thread_id=1994611&forum_id=462843
References mu::ParserBase::Eval(), and madness::f.
void mu::Parser::InitCharSets () virtual
Define the character sets.
See also
DefineNameChars, DefineOprtChars, DefineInfixOprtChars
This function is used for initializing the default character sets that define the characters to be useable in function and variable names and operators.
Implements mu::ParserBase.
References _T, mu::ParserBase::DefineInfixOprtChars(), mu::ParserBase::DefineNameChars(), and mu::ParserBase::DefineOprtChars().
Referenced by Parser().
void mu::Parser::InitConst () virtual
Initialize constants.
By default the parser recognizes two constants. Pi ("pi") and the eulerian number ("_e").
Implements mu::ParserBase.
References _T, mu::ParserBase::DefineConst(), PARSER_CONST_E, and PARSER_CONST_PI.
Referenced by Parser().
void mu::Parser::InitFun () virtual
Initialize the default functions.
Implements mu::ParserBase.
References _T.
Referenced by Parser().
void mu::Parser::InitOprt () virtual
Initialize operators.
By default only the unary minus operator is added.
Implements mu::ParserBase.
References _T, and mu::ParserBase::DefineInfixOprt().
Referenced by Parser().
void mu::Parser::SetDecSep (char_type cDecSep)
Set the decimal separator.
Parameters
cDecSep Decimal separator as a character value.
See also
SetThousandsSep
By default muparser uses the "C" locale. The decimal separator of this locale is overwritten by the one provided here.
void mu::Parser::SetThousandsSep (char_type cThousandsSep)
Sets the thousands operator.
Parameters
cThousandsSep The thousands separator as a character
See also
SetDecSep
By default muparser uses the "C" locale. The thousands separator of this locale is overwritten by the one provided here.
The documentation for this class was generated from the following files:
muParser.h
muParser.cpp