MADNESS: madness::archive::TextFstreamInputArchive Class Reference
madness::archive::TextFstreamInputArchive Class Reference
Wraps an archive around a text file stream for input.
#include <textfsar.h>
Public Member Functions
TextFstreamInputArchive (const char *filename=0, std::ios_base::openmode mode=std::ios_base::in)
template<class T >
void check_start_tag (bool end=false) const
template<class T >
void check_end_tag () const
template<class T >
madness::enable_if
< madness::is_serializable< T >
>::type load (T *t, long n) const
void load (unsigned char *t, long n) const
void load (char *t, long n) const
void open (const char *filename, std::ios_base::openmode mode=std::ios_base::in)
void close ()
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Additional Inherited Members
Static Public Attributes inherited from madness::archive::BaseInputArchive
static const bool is_input_archive = true
Static Public Attributes inherited from madness::archive::BaseArchive
static const bool is_archive = true
static const bool is_input_archive = false
static const bool is_output_archive = false
static const bool is_parallel_archive = false
Detailed Description
Wraps an archive around a text file stream for input.
Constructor & Destructor Documentation
madness::archive::TextFstreamInputArchive::TextFstreamInputArchive (const char * filename = 0, std::ios_base::openmode mode = std::ios_base::in) inline
References open().
Member Function Documentation
template<class T > void madness::archive::TextFstreamInputArchive::check_end_tag () const inline
Referenced by madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::postamble_load().
template<class T > void madness::archive::TextFstreamInputArchive::check_start_tag (bool end = false) const inline
References madness::archive::archive_type_names, and MADNESS_EXCEPTION.
Referenced by madness::archive::ArchivePrePostImpl< TextFstreamInputArchive, T >::preamble_load().
void madness::archive::TextFstreamInputArchive::close () inline
template<class T > madness::enable_if< madness::is_serializable<T> >::type madness::archive::TextFstreamInputArchive::load (T * t, long n) const inline
void madness::archive::TextFstreamInputArchive::load (unsigned char * t, long n) const
void madness::archive::TextFstreamInputArchive::load (char * t, long n) const
References MADNESS_EXCEPTION.
void madness::archive::TextFstreamInputArchive::open (const char * filename, std::ios_base::openmode mode = std::ios_base::in)
References ARCHIVE_MAJOR_VERSION, ARCHIVE_MINOR_VERSION, and MADNESS_EXCEPTION.
Referenced by TextFstreamInputArchive().
The documentation for this class was generated from the following files:
textfsar.h
textfsar.cc