MADNESS: CorePotentialManager Class Reference
CorePotentialManager Class Reference
#include <corepotential.h>
Public Member Functions
CorePotentialManager ()
CorePotentialManager (std::string filename, double eprec)
bool is_defined (const unsigned int atn) const
unsigned int n_core_orb (const unsigned int atn) const
unsigned int n_core_orb_base (const unsigned int atn) const
std::string guess_file () const
AtomCore get_atom_core (unsigned int atn) const
CorePotential get_potential (unsigned int atn) const
unsigned int get_core_l (unsigned int atn, unsigned int core) const
double get_core_bc (unsigned int atn, unsigned int core) const
double core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const
double core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const
double potential (unsigned int atn, double r) const
double potential_derivative (unsigned int atn, double xi, double r) const
void read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
void set_eprec (double value)
void set_rcut (double value)
template<typename Archive >
void serialize (Archive &ar)
CorePotentialManager ()
CorePotentialManager (std::string filename, double eprec)
bool is_defined (const unsigned int atn) const
unsigned int n_core_orb (const unsigned int atn) const
unsigned int n_core_orb_base (const unsigned int atn) const
std::string guess_file () const
AtomCore get_atom_core (unsigned int atn) const
CorePotential get_potential (unsigned int atn) const
unsigned int get_core_l (unsigned int atn, unsigned int core) const
double get_core_bc (unsigned int atn, unsigned int core) const
double core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const
double core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const
double potential (unsigned int atn, double r) const
double potential_derivative (unsigned int atn, double xi, double r) const
void read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
void set_eprec (double value)
void set_rcut (double value)
template<typename Archive >
void serialize (Archive &ar)
Constructor & Destructor Documentation
CorePotentialManager::CorePotentialManager () inline
CorePotentialManager::CorePotentialManager (std::string filename, double eprec) inline
References read_file().
CorePotentialManager::CorePotentialManager () inline
CorePotentialManager::CorePotentialManager (std::string filename, double eprec) inline
References read_file().
Member Function Documentation
double CorePotentialManager::core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const inline
References get_atom_core(), and AtomCore::orbital.
Referenced by Molecule::core_derivative().
double CorePotentialManager::core_derivative (unsigned int atn, unsigned int core, int m, int axis, double xi, double rsq, double x, double y, double z) const inline
References get_atom_core(), and AtomCore::orbital.
double CorePotentialManager::core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const inline
References get_atom_core(), and AtomCore::orbital.
Referenced by Molecule::core_eval().
double CorePotentialManager::core_eval (unsigned int atn, unsigned int core, int m, double rsq, double x, double y, double z) const inline
References get_atom_core(), and AtomCore::orbital.
AtomCore CorePotentialManager::get_atom_core (unsigned int atn) const inline
Referenced by core_derivative(), core_eval(), get_core_bc(), and get_core_l().
AtomCore CorePotentialManager::get_atom_core (unsigned int atn) const inline
double CorePotentialManager::get_core_bc (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and AtomCore::orbital.
Referenced by Molecule::get_core_bc().
double CorePotentialManager::get_core_bc (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and AtomCore::orbital.
unsigned int CorePotentialManager::get_core_l (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and AtomCore::orbital.
unsigned int CorePotentialManager::get_core_l (unsigned int atn, unsigned int core) const inline
References get_atom_core(), and AtomCore::orbital.
Referenced by Molecule::get_core_l().
CorePotential CorePotentialManager::get_potential (unsigned int atn) const inline
CorePotential CorePotentialManager::get_potential (unsigned int atn) const inline
std::string CorePotentialManager::guess_file () const inline
Referenced by Molecule::guess_file().
std::string CorePotentialManager::guess_file () const inline
bool CorePotentialManager::is_defined (const unsigned int atn) const inline
bool CorePotentialManager::is_defined (const unsigned int atn) const inline
Referenced by Molecule::is_potential_defined(), Molecule::is_potential_defined_atom(), Molecule::molecular_core_potential(), Molecule::n_core_orb(), Molecule::n_core_orb_all(), Molecule::nuclear_dipole(), Molecule::nuclear_repulsion_derivative(), Molecule::nuclear_repulsion_energy(), and Molecule::read_core_file().
unsigned int CorePotentialManager::n_core_orb (const unsigned int atn) const inline
Referenced by Molecule::n_core_orb_all(), Molecule::nuclear_dipole(), Molecule::nuclear_repulsion_derivative(), Molecule::nuclear_repulsion_energy(), and Molecule::read_core_file().
unsigned int CorePotentialManager::n_core_orb (const unsigned int atn) const inline
unsigned int CorePotentialManager::n_core_orb_base (const unsigned int atn) const inline
unsigned int CorePotentialManager::n_core_orb_base (const unsigned int atn) const inline
Referenced by Molecule::n_core_orb().
double CorePotentialManager::potential (unsigned int atn, double r) const inline
References CorePotential::eval(), and AtomCore::potential.
Referenced by Molecule::molecular_core_potential().
double CorePotentialManager::potential (unsigned int atn, double r) const inline
References CorePotential::eval(), and AtomCore::potential.
double CorePotentialManager::potential_derivative (unsigned int atn, double xi, double r) const inline
References CorePotential::eval_derivative(), and AtomCore::potential.
Referenced by Molecule::core_potential_derivative().
double CorePotentialManager::potential_derivative (unsigned int atn, double xi, double r) const inline
References CorePotential::eval_derivative(), and AtomCore::potential.
void CorePotentialManager::read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
void CorePotentialManager::read_file (std::string filename, std::set< unsigned int > atomset, double eprec)
Referenced by CorePotentialManager(), and Molecule::read_core_file().
template<typename Archive > void CorePotentialManager::serialize (Archive & ar) inline
template<typename Archive > void CorePotentialManager::serialize (Archive & ar) inline
void CorePotentialManager::set_eprec (double value)
void CorePotentialManager::set_eprec (double value)
Referenced by Molecule::set_core_eprec(), and Molecule::set_eprec().
void CorePotentialManager::set_rcut (double value)
Referenced by Molecule::set_core_rcut().
void CorePotentialManager::set_rcut (double value)
The documentation for this class was generated from the following file:
DFcode/corepotential.h