MADNESS: madness::EigSolverOp< T, NDIM > Class Template Reference
madness::EigSolverOp< T, NDIM > Class Template Reference abstract
#include <eigsolver.h>
Public Member Functions
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
virtual bool is_od ()=0
Is there an orbitally-dependent term?
virtual bool is_rd ()=0
Is there a density-dependent term?
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
double coeff ()
std::string messsageME ()
Public Attributes
World & _world
Protected Member Functions
double thresh ()
void messageME (std::string messageME)
Constructor & Destructor Documentation
template<typename T, int NDIM> madness::EigSolverOp< T, NDIM >::EigSolverOp (World & world, double coeff, double thresh) inline
template<typename T, int NDIM> virtual madness::EigSolverOp< T, NDIM >::~EigSolverOp () inline virtual
Member Function Documentation
template<typename T, int NDIM> double madness::EigSolverOp< T, NDIM >::coeff () inline
Referenced by madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolver< T, NDIM >::multi_solve(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
template<typename T, int NDIM> virtual bool madness::EigSolverOp< T, NDIM >::is_od () pure virtual
Is there an orbitally-dependent term?
Implemented in madness::DFTNuclearChargeDensityOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::HartreeFockExchangeOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, madness::HartreeFockCoulombOp< T, NDIM >, madness::DFTNuclearPotentialOp< T, NDIM >, and madness::HartreeFockNuclearPotentialOp< T, NDIM >.
Referenced by madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolver< T, NDIM >::multi_solve(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
template<typename T, int NDIM> virtual bool madness::EigSolverOp< T, NDIM >::is_rd () pure virtual
Is there a density-dependent term?
Implemented in madness::DFTNuclearChargeDensityOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::HartreeFockExchangeOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, madness::HartreeFockCoulombOp< T, NDIM >, madness::DFTNuclearPotentialOp< T, NDIM >, and madness::HartreeFockNuclearPotentialOp< T, NDIM >.
Referenced by madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolver< T, NDIM >::multi_solve(), madness::EigSolver< T, NDIM >::prepare_ops(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
template<typename T, int NDIM> void madness::EigSolverOp< T, NDIM >::messageME (std::string messageME) inline protected
Referenced by madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::DFTNuclearPotentialOp< T, NDIM >::DFTNuclearPotentialOp(), madness::HartreeFockCoulombOp< T, NDIM >::HartreeFockCoulombOp(), madness::HartreeFockExchangeOp< T, NDIM >::HartreeFockExchangeOp(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::HartreeFockNuclearPotentialOp(), and madness::XCFunctionalLDA< T, NDIM >::XCFunctionalLDA().
template<typename T, int NDIM> std::string madness::EigSolverOp< T, NDIM >::messsageME () inline
Referenced by madness::EigSolver< T, NDIM >::print_matrix_elements().
template<typename T, int NDIM> virtual std::vector<funcT> madness::EigSolverOp< T, NDIM >::multi_op_o (const std::vector< funcT > & phis) inline virtual
Orbital-dependent portion of operator.
References madness::EigSolverOp< T, NDIM >::_world, madness::WorldGopInterface::fence(), madness::World::gop, madness::EigSolverOp< T, NDIM >::op_o(), and pi.
Referenced by madness::EigSolver< T, NDIM >::multi_solve().
template<typename T, int NDIM> virtual std::vector<funcT> madness::EigSolverOp< T, NDIM >::multi_op_r (const funcT & rho, const std::vector< funcT > & phis) inline virtual
Density-dependent portion of operator.
References madness::EigSolverOp< T, NDIM >::_world, madness::WorldGopInterface::fence(), madness::World::gop, madness::EigSolverOp< T, NDIM >::op_r(), and pi.
Referenced by madness::EigSolver< T, NDIM >::multi_solve().
template<typename T, int NDIM> virtual funcT madness::EigSolverOp< T, NDIM >::op_o (const std::vector< funcT > & phis, const funcT & psi) inline virtual
Orbital-dependent portion of operator.
Reimplemented in madness::HartreeFockExchangeOp< T, NDIM >.
References madness::EigSolverOp< T, NDIM >::_world, and func().
Referenced by madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolverOp< T, NDIM >::multi_op_o(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
template<typename T, int NDIM> virtual funcT madness::EigSolverOp< T, NDIM >::op_r (const funcT & rho, const funcT & psi) inline virtual
Density-dependent portion of operator.
Reimplemented in madness::DFTNuclearChargeDensityOp< T, NDIM >, madness::XCFunctionalLDA< T, NDIM >, madness::DFTCoulombPeriodicOp< T, NDIM >, madness::DFTCoulombOp< T, NDIM >, and madness::DFTNuclearPotentialOp< T, NDIM >.
References madness::EigSolverOp< T, NDIM >::_world, and func().
Referenced by madness::EigSolver< T, NDIM >::matrix_element(), madness::EigSolverOp< T, NDIM >::multi_op_r(), madness::EigSolver< T, NDIM >::print_matrix_elements(), and madness::EigSolver< T, NDIM >::solve().
template<typename T, int NDIM> virtual void madness::EigSolverOp< T, NDIM >::prepare_op (funcT rho) inline virtual
Build the potential from a density if a density-dependent operator.
Referenced by madness::EigSolver< T, NDIM >::prepare_ops().
template<typename T, int NDIM> double madness::EigSolverOp< T, NDIM >::thresh () inline protected
Referenced by madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp().
Member Data Documentation
template<typename T, int NDIM> World& madness::EigSolverOp< T, NDIM >::_world
Referenced by madness::EigSolverOp< T, NDIM >::multi_op_o(), madness::EigSolverOp< T, NDIM >::multi_op_r(), madness::EigSolverOp< T, NDIM >::op_o(), and madness::EigSolverOp< T, NDIM >::op_r().
The documentation for this class was generated from the following file:
eigsolver.h