MADNESS: madness::FunctionImpl< T, NDIM >::do_err_box< opT > Class Template Reference
madness::FunctionImpl< T, NDIM >::do_err_box< opT > Class Template Reference
#include <funcimpl.h>
Public Member Functions
do_err_box ()
do_err_box (const implT *impl, const opT *func, int npt, const Tensor< double > &qx, const Tensor< double > &quad_phit, const Tensor< double > &quad_phiw)
do_err_box (const do_err_box &e)
double operator() (typename dcT::const_iterator &it) const
double operator() (double a, double b) const
template<typename Archive >
void serialize (const Archive &ar)
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::do_err_box< opT >::do_err_box () inline
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::do_err_box< opT >::do_err_box (const implT * impl, const opT * func, int npt, const Tensor< double > & qx, const Tensor< double > & quad_phit, const Tensor< double > & quad_phiw) inline
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::do_err_box< opT >::do_err_box (const do_err_box< opT > & e) inline
Member Function Documentation
template<typename T, std::size_t NDIM> template<typename opT > double madness::FunctionImpl< T, NDIM >::do_err_box< opT >::operator() (typename dcT::const_iterator & it) const inline
References madness::FunctionImpl< T, NDIM >::err_box(), and madness::FunctionNode< T, NDIM >::has_coeff().
template<typename T, std::size_t NDIM> template<typename opT > double madness::FunctionImpl< T, NDIM >::do_err_box< opT >::operator() (double a, double b) const inline
References b().
template<typename T, std::size_t NDIM> template<typename opT > template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_err_box< opT >::serialize (const Archive & ar) inline
The documentation for this class was generated from the following file:
funcimpl.h