MADNESS: madness::SpectralPropagatorGaussLobatto Class Reference
madness::SpectralPropagatorGaussLobatto Class Reference
#include <spectralprop.h>
Public Member Functions
SpectralPropagatorGaussLobatto (int NPT)
template<typename uT , typename expLT , typename NT >
uT step (double t, double Delta, const uT &u0, const expLT &expL, const NT &N, const double eps=1e-12, bool doprint=false)
Constructor & Destructor Documentation
madness::SpectralPropagatorGaussLobatto::SpectralPropagatorGaussLobatto (int NPT) inline
References sqrt().
Member Function Documentation
template<typename uT , typename expLT , typename NT > uT madness::SpectralPropagatorGaussLobatto::step (double t, double Delta, const uT & u0, const expLT & expL, const NT & N, const double eps = 1e-12, bool doprint = false) inline
References distance(), k, N, and madness::print().
The documentation for this class was generated from the following file:
spectralprop.h