MADNESS: ContractedGaussianShell Class Reference
ContractedGaussianShell Class Reference
Represents a single shell of contracted, Cartesian, Gaussian primitives.
#include <molecularbasis.h>
Public Member Functions
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
int angular_momentum () const
Returns the shell angular momentum.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
template<typename Archive >
void serialize (Archive &ar)
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
int angular_momentum () const
Returns the shell angular momentum.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
template<typename Archive >
void serialize (Archive &ar)
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
int angular_momentum () const
Returns the shell angular momentum.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
Represents a single shell of contracted, Cartesian, Gaussian primitives.
Constructor & Destructor Documentation
ContractedGaussianShell::ContractedGaussianShell () inline
ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References mpfr::min().
ContractedGaussianShell::ContractedGaussianShell () inline
ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References mpfr::min().
ContractedGaussianShell::ContractedGaussianShell () inline
ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References mpfr::min().
Member Function Documentation
int ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
int ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
int ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
Referenced by operator<<().
double* ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References madness::ContractedGaussianShell::eval_radial(), mpfr::fabs(), and R.
double* ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References madness::ContractedGaussianShell::eval_radial(), mpfr::fabs(), and R.
double* ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References madness::ContractedGaussianShell::eval_radial(), mpfr::fabs(), and R.
double ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References mpfr::exp(), and mpfr::sum().
double ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References mpfr::exp(), and mpfr::sum().
double ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References mpfr::exp(), and mpfr::sum().
const std::vector<double>& ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
const std::vector<double>& ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
const std::vector<double>& ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
Referenced by operator<<().
const char* ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
const char* ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
const char* ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
const std::vector<double>& ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
const std::vector<double>& ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
const std::vector<double>& ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
Referenced by operator<<().
int ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
int ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
int ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
int ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
int ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
int ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
Referenced by operator<<().
double ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
double ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
double ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
template<typename Archive > void ContractedGaussianShell::serialize (Archive & ar) inline
template<typename Archive > void ContractedGaussianShell::serialize (Archive & ar) inline
template<typename Archive > void ContractedGaussianShell::serialize (Archive & ar) inline
The documentation for this class was generated from the following file:
DFcode/molecularbasis.h