MADNESS: madness::archive::TextFstreamOutputArchive Class Reference
madness::archive::TextFstreamOutputArchive Class Reference
Wraps an archive around a text file stream for output.
#include <textfsar.h>
Public Member Functions
TextFstreamOutputArchive (const char *filename=0, std::ios_base::openmode mode=std::ios_base::binary|std::ios_base::out|std::ios_base::trunc)
template<class T >
void store_start_tag () const
template<class T >
void store_end_tag () const
template<class T >
madness::enable_if
< madness::is_serializable< T >
>::type store (const T *t, long n) const
void store (const char *t, long) const
void store (const unsigned char *t, long n) const
void open (const char *filename, std::ios_base::openmode mode=std::ios_base::out|std::ios_base::trunc)
void close ()
void flush ()
~TextFstreamOutputArchive ()
Public Member Functions inherited from madness::archive::BaseArchive
BaseArchive ()
Additional Inherited Members
Static Public Attributes inherited from madness::archive::BaseOutputArchive
static const bool is_output_archive = true
Static Public Attributes inherited from madness::archive::BaseArchive
static const bool is_archive = true
static const bool is_input_archive = false
static const bool is_output_archive = false
static const bool is_parallel_archive = false
Detailed Description
Wraps an archive around a text file stream for output.
Constructor & Destructor Documentation
madness::archive::TextFstreamOutputArchive::TextFstreamOutputArchive (const char * filename = 0, std::ios_base::openmode mode = std::ios_base::binary | std::ios_base::out | std::ios_base::trunc) inline
References open().
madness::archive::TextFstreamOutputArchive::~TextFstreamOutputArchive () inline
References close().
Member Function Documentation
void madness::archive::TextFstreamOutputArchive::close ()
Referenced by ~TextFstreamOutputArchive().
void madness::archive::TextFstreamOutputArchive::flush () inline
void madness::archive::TextFstreamOutputArchive::open (const char * filename, std::ios_base::openmode mode = std::ios_base::out | std::ios_base::trunc)
References ARCHIVE_MAJOR_VERSION, ARCHIVE_MINOR_VERSION, madness::archive::archive_type_names, and store().
Referenced by TextFstreamOutputArchive().
template<class T > madness::enable_if< madness::is_serializable<T> >::type madness::archive::TextFstreamOutputArchive::store (const T * t, long n) const inline
Referenced by open().
void madness::archive::TextFstreamOutputArchive::store (const char * t, long) const
References c.
void madness::archive::TextFstreamOutputArchive::store (const unsigned char * t, long n) const inline
template<class T > void madness::archive::TextFstreamOutputArchive::store_end_tag () const inline
Referenced by madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::postamble_store().
template<class T > void madness::archive::TextFstreamOutputArchive::store_start_tag () const inline
References MAD_ARCHIVE_DEBUG.
Referenced by madness::archive::ArchivePrePostImpl< TextFstreamOutputArchive, T >::preamble_store().
The documentation for this class was generated from the following files:
textfsar.h
textfsar.cc