MADNESS: madness::MolecularEnergy Class Reference
madness::MolecularEnergy Class Reference
#include <SCF.h>
Public Member Functions
MolecularEnergy (World &world, SCF &calc)
bool provides_gradient () const
Override this to return true if the derivative is implemented.
double value (const Tensor< double > &x)
Should return the value of the objective function.
madness::Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual ~OptimizationTargetInterface ()
Constructor & Destructor Documentation
madness::MolecularEnergy::MolecularEnergy (World & world, SCF & calc) inline
Member Function Documentation
madness::Tensor<double> madness::MolecularEnergy::gradient (const Tensor< double > & x) inline virtual
Should return the derivative of the function.
Reimplemented from madness::OptimizationTargetInterface.
References madness::SCF::derivatives(), and value().
bool madness::MolecularEnergy::provides_gradient () const inline virtual
Override this to return true if the derivative is implemented.
Reimplemented from madness::OptimizationTargetInterface.
double madness::MolecularEnergy::value (const Tensor< double > & x) inline virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References madness::CalculationParameters::aobasis, madness::SCF::current_energy, madness::SCF::initial_guess(), madness::SCF::load_mos(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::Molecule::natom(), madness::CalculationParameters::no_compute, madness::SCF::param, madness::SCF::project(), madness::SCF::project_ao_basis(), madness::CalculationParameters::protocol_data, madness::CalculationParameters::restart, madness::CalculationParameters::save, madness::SCF::save_mos(), madness::Molecule::set_all_coords(), madness::SCF::set_protocol(), and madness::SCF::solve().
Referenced by gradient(), and main().
The documentation for this class was generated from the following files:
chem/SCF.h
jacob/moldft.cc
moldft-elem.cc