MADNESS: AtomicBasisSet Class Reference
AtomicBasisSet Class Reference
Contracted Gaussian basis.
#include <molecularbasis.h>
Classes
class AnalysisSorter
Public Member Functions
AtomicBasisSet ()
AtomicBasisSet (std::string filename)
void read_file (std::string filename)
void atoms_to_bfn (const Molecule &molecule, std::vector< int > &at_to_bf, std::vector< int > &at_nbf)
Makes map from atoms to first basis function on atom and number of basis functions on atom.
int basisfn_to_atom (const Molecule &molecule, int ibf) const
Returns the number of the atom the ibf'th basis function is on.
AtomicBasisFunction get_atomic_basis_function (const Molecule &molecule, int ibf) const
Returns the ibf'th atomic basis function.
int nbf (const Molecule &molecule) const
Given a molecule count the number of basis functions.
void eval (const Molecule &molecule, double x, double y, double z, double *bf) const
Evaluates the basis functions.
double eval_guess_density (const Molecule &molecule, double x, double y, double z) const
Evaluates the guess density.
bool is_supported (int atomic_number) const
void print (const Molecule &molecule) const
Print basis info for atoms in the molecule (once for each unique atom type)
template<typename T >
void print_anal (const Molecule &molecule, const Tensor< T > &v)
Given a vector of AO coefficients prints an analysis.
void print_all () const
Print basis info for all supported atoms.
template<typename Archive >
void serialize (Archive &ar)
AtomicBasisSet ()
AtomicBasisSet (std::string filename)
void read_file (std::string filename)
void atoms_to_bfn (const MolecularEntity &mentity, std::vector< int > &at_to_bf, std::vector< int > &at_nbf)
Makes map from atoms to first basis function on atom and number of basis functions on atom.
int basisfn_to_atom (const MolecularEntity &mentity, int ibf) const
Returns the number of the atom the ibf'th basis function is on.
AtomicBasisFunction get_atomic_basis_function (const MolecularEntity &mentity, int ibf) const
Returns the ibf'th atomic basis function.
int nbf (const MolecularEntity &mentity) const
Given a molecule count the number of basis functions.
void eval (const MolecularEntity &mentity, double x, double y, double z, double *bf) const
Evaluates the basis functions.
double eval_guess_density (const MolecularEntity &mentity, double x, double y, double z) const
Evaluates the guess density.
bool is_supported (int atomic_number) const
void print (const MolecularEntity &mentity) const
Print basis info for atoms in the molecule (once for each unique atom type)
template<typename T >
void print_anal (const MolecularEntity &mentity, const Tensor< T > &v)
Given a vector of AO coefficients prints an analysis.
void print_all () const
Print basis info for all supported atoms.
template<typename Archive >
void serialize (Archive &ar)
AtomicBasisSet ()
AtomicBasisSet (std::string filename)
void read_file (std::string filename)
void atoms_to_bfn (const Molecule &molecule, std::vector< int > &at_to_bf, std::vector< int > &at_nbf)
Makes map from atoms to first basis function on atom and number of basis functions on atom.
int basisfn_to_atom (const Molecule &molecule, int ibf) const
Returns the number of the atom the ibf'th basis function is on.
AtomicBasisFunction get_atomic_basis_function (const Molecule &molecule, int ibf) const
Returns the ibf'th atomic basis function.
int nbf (const Molecule &molecule) const
Given a molecule count the number of basis functions.
void eval (const Molecule &molecule, double x, double y, double z, double *bf) const
Evaluates the basis functions.
double eval_guess_density (const Molecule &molecule, double x, double y, double z) const
Evaluates the guess density.
bool is_supported (int atomic_number) const
void print (const Molecule &molecule) const
Print basis info for atoms in the molecule (once for each unique atom type)
template<typename T >
void print_anal (const Molecule &molecule, const Tensor< T > &v)
Given a vector of AO coefficients prints an analysis.
void print_all () const
Print basis info for all supported atoms.
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
Contracted Gaussian basis.
Constructor & Destructor Documentation
AtomicBasisSet::AtomicBasisSet () inline
AtomicBasisSet::AtomicBasisSet (std::string filename) inline
References madness::AtomicBasisSet::read_file().
AtomicBasisSet::AtomicBasisSet () inline
AtomicBasisSet::AtomicBasisSet (std::string filename) inline
References madness::AtomicBasisSet::read_file().
AtomicBasisSet::AtomicBasisSet () inline
AtomicBasisSet::AtomicBasisSet (std::string filename) inline
References madness::AtomicBasisSet::read_file().
Member Function Documentation
void AtomicBasisSet::atoms_to_bfn (const Molecule & molecule, std::vector< int > & at_to_bf, std::vector< int > & at_nbf) inline
Makes map from atoms to first basis function on atom and number of basis functions on atom.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), and madness::Molecule::natom().
void AtomicBasisSet::atoms_to_bfn (const Molecule & molecule, std::vector< int > & at_to_bf, std::vector< int > & at_nbf) inline
Makes map from atoms to first basis function on atom and number of basis functions on atom.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), and madness::Molecule::natom().
void AtomicBasisSet::atoms_to_bfn (const MolecularEntity & mentity, std::vector< int > & at_to_bf, std::vector< int > & at_nbf) inline
Makes map from atoms to first basis function on atom and number of basis functions on atom.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), madness::AtomicBasisSet::is_supported(), and MolecularEntity::natom().
int AtomicBasisSet::basisfn_to_atom (const Molecule & molecule, int ibf) const inline
Returns the number of the atom the ibf'th basis function is on.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, and madness::Molecule::natom().
int AtomicBasisSet::basisfn_to_atom (const Molecule & molecule, int ibf) const inline
Returns the number of the atom the ibf'th basis function is on.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, and madness::Molecule::natom().
int AtomicBasisSet::basisfn_to_atom (const MolecularEntity & mentity, int ibf) const inline
Returns the number of the atom the ibf'th basis function is on.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, and MolecularEntity::natom().
void AtomicBasisSet::eval (const Molecule & molecule, double x, double y, double z, double * bf) const inline
Evaluates the basis functions.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::Molecule::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
void AtomicBasisSet::eval (const Molecule & molecule, double x, double y, double z, double * bf) const inline
Evaluates the basis functions.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::Molecule::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
void AtomicBasisSet::eval (const MolecularEntity & mentity, double x, double y, double z, double * bf) const inline
Evaluates the basis functions.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), MolecularEntity::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
double AtomicBasisSet::eval_guess_density (const Molecule & molecule, double x, double y, double z) const inline
Evaluates the guess density.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::Molecule::natom(), mpfr::sum(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
double AtomicBasisSet::eval_guess_density (const Molecule & molecule, double x, double y, double z) const inline
Evaluates the guess density.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::Molecule::natom(), mpfr::sum(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
double AtomicBasisSet::eval_guess_density (const MolecularEntity & mentity, double x, double y, double z) const inline
Evaluates the guess density.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), MolecularEntity::natom(), mpfr::sum(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
AtomicBasisFunction AtomicBasisSet::get_atomic_basis_function (const Molecule & molecule, int ibf) const inline
Returns the ibf'th atomic basis function.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, madness::Molecule::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
AtomicBasisFunction AtomicBasisSet::get_atomic_basis_function (const Molecule & molecule, int ibf) const inline
Returns the ibf'th atomic basis function.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, madness::Molecule::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
AtomicBasisFunction AtomicBasisSet::get_atomic_basis_function (const MolecularEntity & mentity, int ibf) const inline
Returns the ibf'th atomic basis function.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), madness::AtomicBasisSet::is_supported(), MADNESS_EXCEPTION, MolecularEntity::natom(), madness::Atom::x, madness::Atom::y, and madness::Atom::z.
bool AtomicBasisSet::is_supported (int atomic_number) const inline
bool AtomicBasisSet::is_supported (int atomic_number) const inline
bool AtomicBasisSet::is_supported (int atomic_number) const inline
int AtomicBasisSet::nbf (const Molecule & molecule) const inline
Given a molecule count the number of basis functions.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), and madness::Molecule::natom().
int AtomicBasisSet::nbf (const Molecule & molecule) const inline
Given a molecule count the number of basis functions.
References madness::Atom::atomic_number, madness::Molecule::get_atom(), madness::AtomicBasisSet::is_supported(), and madness::Molecule::natom().
Referenced by print_all(), and SCFParameters::set_molecular_info().
int AtomicBasisSet::nbf (const MolecularEntity & mentity) const inline
Given a molecule count the number of basis functions.
References madness::Atom::atomic_number, MolecularEntity::get_atom(), madness::AtomicBasisSet::is_supported(), and MolecularEntity::natom().
void AtomicBasisSet::print (const Molecule & molecule) const
Print basis info for atoms in the molecule (once for each unique atom type)
void AtomicBasisSet::print (const Molecule & molecule) const
Print basis info for atoms in the molecule (once for each unique atom type)
void AtomicBasisSet::print (const MolecularEntity & mentity) const inline
Print basis info for atoms in the molecule (once for each unique atom type)
References madness::Atom::atomic_number, MolecularEntity::get_atom(), madness::get_atomic_data(), MolecularEntity::natom(), and madness::AtomicData::symbol.
void AtomicBasisSet::print_all () const
Print basis info for all supported atoms.
void AtomicBasisSet::print_all () const
Print basis info for all supported atoms.
References madness::get_atomic_data(), nbf(), and madness::AtomicData::symbol.
void AtomicBasisSet::print_all () const inline
Print basis info for all supported atoms.
References madness::get_atomic_data(), madness::AtomicBasisSet::nbf(), and madness::AtomicData::symbol.
template<typename T > void AtomicBasisSet::print_anal (const Molecule & molecule, const Tensor< T > & v) inline
Given a vector of AO coefficients prints an analysis.
For each significant coeff it prints
atomic symbol
atom number
basis function type (e.g., dxy)
basis function number
MO coeff
References madness::Atom::atomic_number, madness::AtomicBasisSet::basisfn_to_atom(), madness::Molecule::get_atom(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::get_atomic_data(), madness::AtomicBasisFunction::get_desc(), madness::Molecule::natom(), madness::AtomicBasisSet::nbf(), madness::AtomicData::symbol, and thresh.
template<typename T > void AtomicBasisSet::print_anal (const Molecule & molecule, const Tensor< T > & v) inline
Given a vector of AO coefficients prints an analysis.
For each significant coeff it prints
atomic symbol
atom number
basis function type (e.g., dxy)
basis function number
MO coeff
References madness::Atom::atomic_number, madness::AtomicBasisSet::basisfn_to_atom(), madness::Molecule::get_atom(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::get_atomic_data(), madness::AtomicBasisFunction::get_desc(), madness::Molecule::natom(), madness::AtomicBasisSet::nbf(), madness::AtomicData::symbol, and thresh.
template<typename T > void AtomicBasisSet::print_anal (const MolecularEntity & mentity, const Tensor< T > & v) inline
Given a vector of AO coefficients prints an analysis.
For each significant coeff it prints
atomic symbol
atom number
basis function type (e.g., dxy)
basis function number
MO coeff
References madness::Atom::atomic_number, madness::AtomicBasisSet::basisfn_to_atom(), MolecularEntity::get_atom(), madness::AtomicBasisSet::get_atomic_basis_function(), madness::get_atomic_data(), madness::AtomicBasisFunction::get_desc(), MolecularEntity::natom(), madness::AtomicBasisSet::nbf(), madness::AtomicData::symbol, and thresh.
void AtomicBasisSet::read_file (std::string filename) inline
References TiXmlElement::Attribute(), debug, TiXmlDocument::ErrorCol(), TiXmlDocument::ErrorDesc(), TiXmlDocument::ErrorRow(), TiXmlNode::FirstChildElement(), madness::g, TiXmlElement::GetText(), madness::AtomicBasisSet::is_supported(), TiXmlDocument::LoadFile(), MADNESS_EXCEPTION, madness::AtomicBasisSet::nbf(), TiXmlNode::NextSiblingElement(), madness::symbol_to_atomic_number(), and TiXmlNode::Value().
void AtomicBasisSet::read_file (std::string filename) inline
References TiXmlElement::Attribute(), debug, TiXmlDocument::ErrorCol(), TiXmlDocument::ErrorDesc(), TiXmlDocument::ErrorRow(), TiXmlNode::FirstChildElement(), madness::g, TiXmlElement::GetText(), madness::AtomicBasisSet::is_supported(), TiXmlDocument::LoadFile(), MADNESS_EXCEPTION, madness::AtomicBasisSet::nbf(), TiXmlNode::NextSiblingElement(), madness::symbol_to_atomic_number(), and TiXmlNode::Value().
void AtomicBasisSet::read_file (std::string filename) inline
References TiXmlElement::Attribute(), debug, TiXmlDocument::ErrorCol(), TiXmlDocument::ErrorDesc(), TiXmlDocument::ErrorRow(), TiXmlNode::FirstChildElement(), madness::g, TiXmlElement::GetText(), madness::AtomicBasisSet::is_supported(), TiXmlDocument::LoadFile(), MADNESS_EXCEPTION, madness::AtomicBasisSet::nbf(), TiXmlNode::NextSiblingElement(), madness::symbol_to_atomic_number(), and TiXmlNode::Value().
template<typename Archive > void AtomicBasisSet::serialize (Archive & ar) inline
template<typename Archive > void AtomicBasisSet::serialize (Archive & ar) inline
template<typename Archive > void AtomicBasisSet::serialize (Archive & ar) inline
The documentation for this class was generated from the following files:
DFcode/molecularbasis.h
jacob/molecularbasis.cc