MADNESS: testing::internal::HasNewFatalFailureHelper Class Reference
testing::internal::HasNewFatalFailureHelper Class Reference
#include <gtest-test-part.h>
Public Member Functions
HasNewFatalFailureHelper ()
virtual ~HasNewFatalFailureHelper ()
virtual void ReportTestPartResult (const TestPartResult &result)
bool has_new_fatal_failure () const
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
Constructor & Destructor Documentation
testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper ()
References testing::internal::GetUnitTestImpl(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper () virtual
References testing::internal::GetUnitTestImpl(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Member Function Documentation
bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure () const inline
void testing::internal::HasNewFatalFailureHelper::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
References testing::TestPartResult::fatally_failed(), and testing::TestPartResultReporterInterface::ReportTestPartResult().
The documentation for this class was generated from the following files:
gtest-test-part.h
gtest-test-part.cc