MADNESS: madness::tr1::shptr::detail::shared_count Class Reference
madness::tr1::shptr::detail::shared_count Class Reference
#include <shared_ptr_bits.h>
Public Member Functions
shared_count ()
template<class Y >
shared_count (Y *p)
template<class Y , class D >
shared_count (Y *p, D d)
~shared_count ()
shared_count (shared_count const &r)
shared_count (weak_count const &r)
shared_count & operator= (shared_count const &r)
void swap (shared_count &r)
long use_count () const
bool unique () const
bool empty () const
void * get_deleter (std::type_info const &ti) const
Friends
class weak_count
bool operator== (shared_count const &a, shared_count const &b)
bool operator< (shared_count const &a, shared_count const &b)
Constructor & Destructor Documentation
madness::tr1::shptr::detail::shared_count::shared_count () inline
template<class Y > madness::tr1::shptr::detail::shared_count::shared_count (Y * p) inline explicit
References madness::detail::checked_delete().
template<class Y , class D > madness::tr1::shptr::detail::shared_count::shared_count (Y * p, D d) inline
madness::tr1::shptr::detail::shared_count::~shared_count () inline
References madness::tr1::shptr::detail::sp_counted_base::release().
madness::tr1::shptr::detail::shared_count::shared_count (shared_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::add_ref_copy().
madness::tr1::shptr::detail::shared_count::shared_count (weak_count const & r) inline explicit
References madness::tr1::shptr::detail::sp_counted_base::add_ref_lock().
Member Function Documentation
bool madness::tr1::shptr::detail::shared_count::empty () const inline
void* madness::tr1::shptr::detail::shared_count::get_deleter (std::type_info const & ti) const inline
References madness::tr1::shptr::detail::sp_counted_base::get_deleter().
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::_internal_get_deleter().
shared_count& madness::tr1::shptr::detail::shared_count::operator= (shared_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::add_ref_copy(), and madness::tr1::shptr::detail::sp_counted_base::release().
void madness::tr1::shptr::detail::shared_count::swap (shared_count & r) inline
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::swap().
bool madness::tr1::shptr::detail::shared_count::unique () const inline
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::unique().
long madness::tr1::shptr::detail::shared_count::use_count () const inline
References madness::tr1::shptr::detail::sp_counted_base::use_count().
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::use_count().
Friends And Related Function Documentation
bool operator< (shared_count const & a, shared_count const & b) friend
bool operator== (shared_count const & a, shared_count const & b) friend
friend class weak_count friend
The documentation for this class was generated from the following file:
shared_ptr_bits.h