MADNESS: madness::LocalizeBoys< T > Class Template Reference
madness::LocalizeBoys< T > Class Template Reference
#include <systolic.h>
Public Member Functions
LocalizeBoys (DistributedMatrix< T > &M, const std::vector< int > &set, long nmo, int tag, const double thresh=1e-6, const double thetamax=0.5, const bool randomized=true, const bool doprint=false)
virtual ~LocalizeBoys ()
void start_iteration_hook (const TaskThreadEnv &env)
Invoked by all threads at the start of each iteration.
void kernel (int i, int j, T *rowi, T *rowj)
Threadsafe routine to apply the operation to rows i and j of the matrix.
void end_iteration_hook (const TaskThreadEnv &env)
Invoked by all threads at the end of each iteration.
bool converged (const TaskThreadEnv &env) const
Invoked simultaneously by all threads after each sweep to test for convergence.
Public Member Functions inherited from madness::SystolicMatrixAlgorithm< T >
SystolicMatrixAlgorithm (DistributedMatrix< T > &A, int tag, int nthread=ThreadPool::size()+1)
A must be a column distributed matrix with an even column tile >= 2.
virtual ~SystolicMatrixAlgorithm ()
void run (World &world, const TaskThreadEnv &env)
Invoked by the task queue to run the algorithm with multiple threads.
void solve ()
Invoked by the user to run the algorithm with one thread.
int get_rowdim () const
Returns length of row.
int get_coldim () const
Returns length of column.
World & get_world () const
Returns a reference to the world.
ProcessID get_rank () const
Returns rank of this process in the world.
SystolicMatrixAlgorithm (DistributedMatrix< T > &A, int tag, int nthread=ThreadPool::size()+1)
A must be a column distributed matrix with an even column tile >= 2.
virtual ~SystolicMatrixAlgorithm ()
void run (World &world, const TaskThreadEnv &env)
Invoked by the task queue to run the algorithm with multiple threads.
void solve_sequential ()
Invoked by the user to run the algorithm with one thread mostly for debugging.
int64_t get_rowdim () const
Returns length of row.
int64_t get_coldim () const
Returns length of column.
World & get_world () const
Returns a reference to the world.
ProcessID get_rank () const
Returns rank of this process in the world.
Public Member Functions inherited from madness::TaskInterface
TaskInterface (int ndepend=0, const TaskAttributes attr=TaskAttributes())
Create a new task with ndepend dependencies (default 0) and given attributes.
TaskInterface (const TaskAttributes &attr)
Create a new task with zero dependencies and given attributes.
virtual void run (World &)
Runs a single-threaded task ... derived classes must implement this.
World * get_world () const
virtual ~TaskInterface ()
Public Member Functions inherited from madness::PoolTaskInterface
PoolTaskInterface ()
PoolTaskInterface (const TaskAttributes &attr)
void set_nthread (int nthread)
Call this to reset the number of threads before the task is submitted.
virtual ~PoolTaskInterface ()
Public Member Functions inherited from madness::TaskAttributes
TaskAttributes (unsigned long flags=0)
TaskAttributes (const TaskAttributes &attr)
virtual ~TaskAttributes ()
bool is_generator () const
bool is_stealable () const
bool is_high_priority () const
void set_generator (bool generator_hint)
void set_stealable (bool stealable)
void set_highpriority (bool hipri)
void set_nthread (int nthread)
Are you sure this is what you want to call?
int get_nthread () const
template<typename Archive >
void serialize (Archive &ar)
Public Member Functions inherited from madness::DependencyInterface
DependencyInterface (int ndep=0)
int ndep () const
Returns the number of unsatisfied dependencies.
bool probe () const
Returns true if ndepend == 0.
void notify ()
Invoked by callbacks to notifiy of dependencies being satisfied.
void register_callback (CallbackInterface *callback)
Registers a callback for when ndepend==0 , immediately invoked if ndepend==0.
void inc ()
Increment the number of dependencies.
void dec ()
Decrement the number of dependencies and invoke callback if ndepend=0.
virtual ~DependencyInterface ()
Public Member Functions inherited from madness::CallbackInterface
virtual ~CallbackInterface ()
Additional Inherited Members
Static Public Member Functions inherited from madness::PoolTaskInterface
static void operator delete (void *p, std::size_t size) throw ()
Destroy task object.
Static Public Member Functions inherited from madness::TaskAttributes
static TaskAttributes generator ()
static TaskAttributes hipri ()
static TaskAttributes multi_threaded (int nthread)
Static Public Attributes inherited from madness::TaskInterface
static bool debug = false
Static Public Attributes inherited from madness::TaskAttributes
static const unsigned long NTHREAD = 0xff
static const unsigned long GENERATOR = 1ul<<8
static const unsigned long STEALABLE = GENERATOR<<1
static const unsigned long HIGHPRIORITY = GENERATOR<<2
Protected Member Functions inherited from madness::TaskInterface
virtual void run (const TaskThreadEnv &env)
Override this method to implement a multi-threaded task.
Static Protected Member Functions inherited from madness::PoolTaskInterface
template<typename fnT >
static enable_if_c
< detail::function_traits< fnT >
::value||detail::memfunc_traits
< fnT >::value >::type make_id (std::pair< void *, unsigned short > &id, fnT fn)
template<typename fnobjT >
static disable_if_c
< detail::function_traits
< fnobjT >::value||detail::memfunc_traits
< fnobjT >::value >::type make_id (std::pair< void *, unsigned short > &id, const fnobjT &)
Constructor & Destructor Documentation
template<typename T> madness::LocalizeBoys< T >::LocalizeBoys (DistributedMatrix< T > & M, const std::vector< int > & set, long nmo, int tag, const double thresh = 1e-6, const double thetamax = 0.5, const bool randomized = true, const bool doprint = false) inline
References madness::print().
template<typename T> virtual madness::LocalizeBoys< T >::~LocalizeBoys () inline virtual
Member Function Documentation
template<typename T > bool madness::LocalizeBoys< T >::converged (const TaskThreadEnv & env) const virtual
Invoked simultaneously by all threads after each sweep to test for convergence.
There is a thread barrier before and after the invocation of this routine
Implements madness::SystolicMatrixAlgorithm< T >.
References madness::TaskThreadEnv::barrier(), and madness::print().
template<typename T > void madness::LocalizeBoys< T >::end_iteration_hook (const TaskThreadEnv & env) virtual
Invoked by all threads at the end of each iteration.
There is a thread barrier before and after the invocation of this routine
Reimplemented from madness::SystolicMatrixAlgorithm< T >.
References madness::TaskThreadEnv::barrier(), madness::TaskThreadEnv::id(), and max.
template<typename T> void madness::LocalizeBoys< T >::kernel (int i, int j, T * rowi, T * rowj) virtual
Threadsafe routine to apply the operation to rows i and j of the matrix.
restriction
Implements madness::SystolicMatrixAlgorithm< T >.
References c, mpfr::cos(), doit(), madness::drot(), mpfr::fabs(), madness::g, madness::inner(), madness::print(), mpfr::sin(), and std::tr1::T().
template<typename T > void madness::LocalizeBoys< T >::start_iteration_hook (const TaskThreadEnv & env) virtual
Invoked by all threads at the start of each iteration.
There is a thread barrier before and after the invocation of this routine
number of rotation in this iteration
maximum rotation angle in this iteration
Reimplemented from madness::SystolicMatrixAlgorithm< T >.
References madness::TaskThreadEnv::barrier(), madness::TaskThreadEnv::id(), mpfr::sum(), and std::tr1::T().
The documentation for this class was generated from the following file:
apps/ii/systolic.h