MADNESS: madness::LBDeuxPmap< NDIM > Class Template Reference
madness::LBDeuxPmap< NDIM > Class Template Reference
#include <lbdeux.h>
Public Member Functions
LBDeuxPmap (const std::vector< pairT > &v)
ProcessID owner (const keyT &key) const
Maps key to processor.
void print () const
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< NDIM > >
virtual ~WorldDCPmapInterface ()
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< NDIM > >
typedef
WorldDCRedistributeInterface
< Key< NDIM > > * ptrT
Constructor & Destructor Documentation
template<std::size_t NDIM> madness::LBDeuxPmap< NDIM >::LBDeuxPmap (const std::vector< pairT > & v) inline
Member Function Documentation
template<std::size_t NDIM> ProcessID madness::LBDeuxPmap< NDIM >::owner (const keyT & key) const inline virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implements madness::WorldDCPmapInterface< Key< NDIM > >.
References madness::Key< NDIM >::level(), madness::Key< NDIM >::parent(), and madness::print().
template<std::size_t NDIM> void madness::LBDeuxPmap< NDIM >::print () const inline virtual
Reimplemented from madness::WorldDCPmapInterface< Key< NDIM > >.
References madness::print().
The documentation for this class was generated from the following file:
lbdeux.h