MADNESS: madness::detail::DeferredCleanup Class Reference
madness::detail::DeferredCleanup Class Reference
Deferred cleanup of shared_ptr's.
#include <deferred_cleanup.h>
Public Types
typedef std::shared_ptr< void > void_ptr
input pointer type
Public Member Functions
DeferredCleanup ()
Construct a deferred deleter object.
void destroy (bool mode)
Set the destruction mode.
bool destroy () const
Get the current destruction mode mode.
void add (const void_ptr &obj)
Adds item to cleanup list.
void do_cleanup ()
Deletes/frees any pointers that are in the list.
Friends
template<typename , typename >
class ::madness::DeferredDeleter
Detailed Description
Deferred cleanup of shared_ptr's.
Holds dynamically allocated pointers until it is ready for cleanup.
Note
This object is considered an implementation detail and should not be used directly, instead use DeferredDeleter with a std::shared_ptr.
Member Typedef Documentation
typedef std::shared_ptr<void> madness::detail::DeferredCleanup::void_ptr
input pointer type
Constructor & Destructor Documentation
madness::detail::DeferredCleanup::DeferredCleanup () inline
Construct a deferred deleter object.
Member Function Documentation
void madness::detail::DeferredCleanup::add (const void_ptr & obj)
Adds item to cleanup list.
If destroy mode is true then the pointer is destroyed immediately. Otherwise it is stored until do_cleanup() is called.
Parameters
obj Object that is ready for destruction
Referenced by madness::DeferredDeleter< ptrT, deleterT >::operator()().
void madness::detail::DeferredCleanup::destroy (bool mode)
Set the destruction mode.
Parameters
mode true for immediate destruction, false for deferred destruction.
References madness::RecursiveMutex::lock(), and madness::RecursiveMutex::unlock().
Referenced by madness::WorldGopInterface::~WorldGopInterface().
bool madness::detail::DeferredCleanup::destroy () const
Get the current destruction mode mode.
Returns
true for immediate destruction and false for deferred destruction.
References madness::RecursiveMutex::lock(), and madness::RecursiveMutex::unlock().
void madness::detail::DeferredCleanup::do_cleanup ()
Deletes/frees any pointers that are in the list.
References madness::RecursiveMutex::lock(), and madness::RecursiveMutex::unlock().
Referenced by madness::WorldGopInterface::fence(), and madness::WorldGopInterface::~WorldGopInterface().
Friends And Related Function Documentation
template<typename , typename > friend class ::madness::DeferredDeleter friend
The documentation for this class was generated from the following files:
deferred_cleanup.h
deferred_cleanup.cc