MADNESS: madness::ConvolutionND< Q, NDIM > Class Template Reference
madness::ConvolutionND< Q, NDIM > Class Template Reference
MADNESS libraries » Multiresolution analaysis » Function
Array of 1D convolutions (one / dimension)
#include <convolution1d.h>
Public Member Functions
ConvolutionND ()
ConvolutionND (const ConvolutionND &other)
ConvolutionND (std::shared_ptr< Convolution1D< Q > > op, Q fac=1.0)
void setop (int dim, const std::shared_ptr< Convolution1D< Q > > &op)
std::shared_ptr< Convolution1D
< Q > > getop (int dim) const
void setfac (Q value)
Q getfac () const
Detailed Description
template<typename Q, int NDIM>
class madness::ConvolutionND< Q, NDIM >
Array of 1D convolutions (one / dimension)
data for 1 term and all dimensions
Constructor & Destructor Documentation
template<typename Q , int NDIM> madness::ConvolutionND< Q, NDIM >::ConvolutionND () inline
template<typename Q , int NDIM> madness::ConvolutionND< Q, NDIM >::ConvolutionND (const ConvolutionND< Q, NDIM > & other) inline
template<typename Q , int NDIM> madness::ConvolutionND< Q, NDIM >::ConvolutionND (std::shared_ptr< Convolution1D< Q > > op, Q fac = 1.0) inline
References madness::tr1::array::array< T, N >::begin(), madness::tr1::array::array< T, N >::end(), and op().
Member Function Documentation
template<typename Q , int NDIM> Q madness::ConvolutionND< Q, NDIM >::getfac () const inline
template<typename Q , int NDIM> std::shared_ptr<Convolution1D<Q> > madness::ConvolutionND< Q, NDIM >::getop (int dim) const inline
References mpfr::dim().
template<typename Q , int NDIM> void madness::ConvolutionND< Q, NDIM >::setfac (Q value) inline
template<typename Q , int NDIM> void madness::ConvolutionND< Q, NDIM >::setop (int dim, const std::shared_ptr< Convolution1D< Q > > & op) inline
References mpfr::dim(), and op().
The documentation for this class was generated from the following file:
convolution1d.h