MADNESS: madness::TaskThreadEnv Class Reference
madness::TaskThreadEnv Class Reference
Used to pass info about thread environment into users task.
#include <worldthread.h>
Public Member Functions
TaskThreadEnv (int nthread, int id, Barrier *barrier)
int nthread () const
int id () const
bool barrier () const
Detailed Description
Used to pass info about thread environment into users task.
Constructor & Destructor Documentation
madness::TaskThreadEnv::TaskThreadEnv (int nthread, int id, Barrier * barrier) inline
Member Function Documentation
bool madness::TaskThreadEnv::barrier () const inline
References madness::Barrier::enter().
Referenced by madness::LocalizeBoys< T >::converged(), madness::LocalizeBoys< T >::end_iteration_hook(), madness::SystolicMatrixAlgorithm< double >::run(), and madness::LocalizeBoys< T >::start_iteration_hook().
int madness::TaskThreadEnv::id () const inline
Referenced by madness::LocalizeBoys< T >::end_iteration_hook(), madness::SystolicMatrixAlgorithm< double >::run(), and madness::LocalizeBoys< T >::start_iteration_hook().
int madness::TaskThreadEnv::nthread () const inline
Referenced by madness::TaskInterface::run().
The documentation for this class was generated from the following file:
worldthread.h