MADNESS: madness::RecursiveMutex Class Reference
madness::RecursiveMutex Class Reference
Recursive mutex using pthread mutex operations.
#include <worldmutex.h>
Public Member Functions
RecursiveMutex ()
Make and initialize a mutex ... initial state is unlocked.
bool try_lock () const
Try to acquire the mutex ... return true on success, false on failure.
void lock () const
Acquire the mutex waiting if necessary.
void unlock () const
Free a mutex owned by this thread.
pthread_mutex_t * ptr () const
Return a pointer to the pthread mutex for use by a condition variable.
~RecursiveMutex ()
Detailed Description
Recursive mutex using pthread mutex operations.
Constructor & Destructor Documentation
madness::RecursiveMutex::RecursiveMutex ()
Make and initialize a mutex ... initial state is unlocked.
References MADNESS_EXCEPTION.
madness::RecursiveMutex::~RecursiveMutex () inline
Member Function Documentation
void madness::RecursiveMutex::lock () const inline
Acquire the mutex waiting if necessary.
References MADNESS_EXCEPTION.
Referenced by madness::detail::DeferredCleanup::destroy(), and madness::detail::DeferredCleanup::do_cleanup().
pthread_mutex_t* madness::RecursiveMutex::ptr () const inline
Return a pointer to the pthread mutex for use by a condition variable.
bool madness::RecursiveMutex::try_lock () const inline
Try to acquire the mutex ... return true on success, false on failure.
void madness::RecursiveMutex::unlock () const inline
Free a mutex owned by this thread.
References MADNESS_EXCEPTION.
Referenced by madness::detail::DeferredCleanup::destroy(), and madness::detail::DeferredCleanup::do_cleanup().
The documentation for this class was generated from the following files:
worldmutex.h
worldmutex.cc