MADNESS: madness::GFit< T, NDIM > Class Template Reference
madness::GFit< T, NDIM > Class Template Reference
#include <gfit.h>
Public Member Functions
GFit ()
default ctor does nothing
Tensor< T > coeffs () const
return the coefficients of the fit
Tensor< T > exponents () const
return the exponents of the fit
void truncate_periodic_expansion (Tensor< double > &c, Tensor< double > &e, double L, bool discardG0) const
Static Public Member Functions
static GFit CoulombFit (double lo, double hi, double eps, bool prnt=false)
return a fit for the Coulomb function
static GFit BSHFit (double mu, double lo, double hi, double eps, bool prnt=false)
return a fit for the bound-state Helmholtz function
static GFit SlaterFit (double gamma, double lo, double hi, double eps, bool prnt=false)
return a fit for the Slater function
static GFit GeneralFit ()
return a fit for a general isotropic function
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::GFit< T, NDIM >::GFit () inline
default ctor does nothing
Referenced by madness::GFit< T, NDIM >::GeneralFit().
Member Function Documentation
template<typename T, std::size_t NDIM> static GFit madness::GFit< T, NDIM >::BSHFit (double mu, double lo, double hi, double eps, bool prnt = false) inline static
return a fit for the bound-state Helmholtz function
the BSH function is defined by f(r) = exp(- r)/r
Parameters
[in] mu the exponent of the BSH
[in] lo the smallest length scale that needs to be precisely represented
[in] hi the largest length scale that needs to be precisely represented
[in] eps the precision threshold [in] prnt print level
References fit(), and NDIM.
Referenced by madness::GFit< T, NDIM >::CoulombFit().
template<typename T, std::size_t NDIM> Tensor<T> madness::GFit< T, NDIM >::coeffs () const inline
return the coefficients of the fit
Referenced by madness::TwoElectronInterface< double, 6 >::initialize().
template<typename T, std::size_t NDIM> static GFit madness::GFit< T, NDIM >::CoulombFit (double lo, double hi, double eps, bool prnt = false) inline static
return a fit for the Coulomb function
References madness::GFit< T, NDIM >::BSHFit(), fit(), and madness::constants::pi.
template<typename T, std::size_t NDIM> Tensor<T> madness::GFit< T, NDIM >::exponents () const inline
return the exponents of the fit
Referenced by madness::TwoElectronInterface< double, 6 >::initialize().
template<typename T, std::size_t NDIM> static GFit madness::GFit< T, NDIM >::GeneralFit () inline static
return a fit for a general isotropic function
note that the error is controlled over a uniform grid, the boundaries will be poorly represented in general. Following Beylkin 2005
References madness::GFit< T, NDIM >::GFit(), and MADNESS_EXCEPTION.
template<typename T, std::size_t NDIM> static GFit madness::GFit< T, NDIM >::SlaterFit (double gamma, double lo, double hi, double eps, bool prnt = false) inline static
return a fit for the Slater function
the Slater function is defined by f(r) = exp(- r)
Parameters
[in] gamma the exponent of the Slater function
[in] lo the smallest length scale that needs to be precisely represented
[in] hi the largest length scale that needs to be precisely represented
[in] eps the precision threshold [in] prnt print level
References fit().
template<typename T, std::size_t NDIM> void madness::GFit< T, NDIM >::truncate_periodic_expansion (Tensor< double > & c, Tensor< double > & e, double L, bool discardG0) const inline
References c.
The documentation for this class was generated from the following file:
gfit.h