MADNESS: madness::SteepestDescent Class Reference
madness::SteepestDescent Class Reference
MADNESS libraries » Iterative solvers for linear/non-linear equations and optimizers
Unconstrained minimization via steepest descent.
#include <solvers.h>
Public Member Functions
SteepestDescent (const std::shared_ptr< OptimizationTargetInterface > &tar, double tol=1e-6, double value_precision=1e-12, double gradient_precision=1e-12)
bool optimize (Tensor< double > &x)
bool converged () const
double gradient_norm () const
double value () const
virtual ~SteepestDescent ()
Public Member Functions inherited from madness::OptimizerInterface
virtual ~OptimizerInterface ()
Detailed Description
Unconstrained minimization via steepest descent.
Constructor & Destructor Documentation
SteepestDescent::SteepestDescent (const std::shared_ptr< OptimizationTargetInterface > & tar, double tol = 1e-6, double value_precision = 1e-12, double gradient_precision = 1e-12)
References madness::OptimizationTargetInterface::provides_gradient().
virtual madness::SteepestDescent::~SteepestDescent () inline virtual
Member Function Documentation
bool SteepestDescent::converged () const virtual
Implements madness::OptimizerInterface.
Referenced by optimize().
double SteepestDescent::gradient_norm () const virtual
Implements madness::OptimizerInterface.
bool SteepestDescent::optimize (Tensor< double > & x) virtual
Implements madness::OptimizerInterface.
References converged(), madness::g, madness::OptimizationTargetInterface::gradient(), madness::print(), and madness::OptimizationTargetInterface::value_and_gradient().
double SteepestDescent::value () const virtual
Implements madness::OptimizerInterface.
The documentation for this class was generated from the following files:
solvers.h
solvers.cc