MADNESS: mu::ParserCallback Class Reference
mu::ParserCallback Class Reference
Encapsulation of prototypes for a numerical parser function.
#include <muParserCallback.h>
Public Member Functions
ParserCallback (fun_type0 a_pFun, bool a_bAllowOpti)
ParserCallback (fun_type1 a_pFun, bool a_bAllowOpti, int a_iPrec=-1, ECmdCode a_iCode=cmFUNC)
ParserCallback (fun_type2 a_pFun, bool a_bAllowOpti, int a_iPrec=-1, ECmdCode a_iCode=cmFUNC)
ParserCallback (fun_type3 a_pFun, bool a_bAllowOpti)
ParserCallback (fun_type4 a_pFun, bool a_bAllowOpti)
ParserCallback (fun_type5 a_pFun, bool a_bAllowOpti)
ParserCallback (multfun_type a_pFun, bool a_bAllowOpti)
ParserCallback (strfun_type1 a_pFun, bool a_bAllowOpti)
ParserCallback (strfun_type2 a_pFun, bool a_bAllowOpti)
ParserCallback (strfun_type3 a_pFun, bool a_bAllowOpti)
ParserCallback ()
Default constructor.
ParserCallback (const ParserCallback &a_Fun)
Copy constructor.
ParserCallback * Clone () const
Clone this instance and return a pointer to the new instance.
bool IsOptimizable () const
Return tru if the function is conservative.
void * GetAddr () const
Get the callback address for the parser function.
ECmdCode GetCode () const
Return the callback code.
ETypeCode GetType () const
int GetPri () const
Return the operator priority.
int GetArgc () const
Returns the number of function Arguments.
Detailed Description
Encapsulation of prototypes for a numerical parser function.
Encapsulates the prototyp for numerical parser functions. The class stores the number of arguments for parser functions as well as additional flags indication the function is non optimizeable. The pointer to the callback function pointer is stored as void* and needs to be casted according to the argument count. Negative argument counts indicate a parser function with a variable number of arguments. This class is not used for string function prototyping.
Author
(C) 2004-2007 Ingo Berg
Constructor & Destructor Documentation
mu::ParserCallback::ParserCallback (fun_type0 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (fun_type1 a_pFun, bool a_bAllowOpti, int a_iPrec = -1, ECmdCode a_iCode = cmFUNC)
mu::ParserCallback::ParserCallback (fun_type2 a_pFun, bool a_bAllowOpti, int a_iPrec = -1, ECmdCode a_iCode = cmFUNC)
mu::ParserCallback::ParserCallback (fun_type3 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (fun_type4 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (fun_type5 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (multfun_type a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (strfun_type1 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (strfun_type2 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback (strfun_type3 a_pFun, bool a_bAllowOpti)
mu::ParserCallback::ParserCallback ()
Default constructor.
Exceptions
nothrow
Referenced by Clone().
mu::ParserCallback::ParserCallback (const ParserCallback & a_Fun)
Copy constructor.
Exceptions
nothrow
Member Function Documentation
ParserCallback * mu::ParserCallback::Clone () const
Clone this instance and return a pointer to the new instance.
References ParserCallback().
void * mu::ParserCallback::GetAddr () const
Get the callback address for the parser function.
The type of the address is void. It needs to be recasted according to the argument number to the right type.
Exceptions
nothrow
Returns
#pFun
Referenced by mu::ParserToken< value_type, string_type >::Set().
int mu::ParserCallback::GetArgc () const
Returns the number of function Arguments.
ECmdCode mu::ParserCallback::GetCode () const
Return the callback code.
Referenced by mu::ParserToken< value_type, string_type >::Set().
int mu::ParserCallback::GetPri () const
Return the operator priority.
Only valid if the callback token is an operator token (binary or infix).
ETypeCode mu::ParserCallback::GetType () const
bool mu::ParserCallback::IsOptimizable () const
Return tru if the function is conservative.
Conservative functions return always the same result for the same argument.
Exceptions
nothrow
The documentation for this class was generated from the following files:
muParserCallback.h
muParserCallback.cpp