MADNESS: MolecularMaskBase Class Reference
MolecularMaskBase Class Reference
#include <molecularmask.h>
Public Member Functions
MolecularMaskBase (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords)
std::vector< madness::Vector
< double, 3 > > special_points () const
Protected Member Functions
double sdf (const madness::coord_3d &r, const madness::coord_3d &center, double R) const
madness::coord_3d grad_sdf (const madness::coord_3d &r, const madness::coord_3d &center) const
double mask (double s) const
double cmask (double s) const
double dmask (double s) const
double atomic_mask (const madness::coord_3d &r, unsigned int i) const
double atomic_cmask (const madness::coord_3d &r, unsigned int i) const
madness::coord_3d grad_atomic_mask (const madness::coord_3d &r, unsigned int i) const
madness::coord_3d gradient (const madness::coord_3d &r) const
Protected Attributes
const double sigma
const std::vector< double > atomic_radii
const std::vector
< madness::coord_3d > atomic_coords
const int natom
Constructor & Destructor Documentation
MolecularMaskBase::MolecularMaskBase (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords) inline
Member Function Documentation
double MolecularMaskBase::atomic_cmask (const madness::coord_3d & r, unsigned int i) const inline protected
References cmask(), and sdf().
Referenced by gradient(), MolecularVolumeMask::operator()(), and MolecularVolumeComplementMask::operator()().
double MolecularMaskBase::atomic_mask (const madness::coord_3d & r, unsigned int i) const inline protected
References mask(), and sdf().
double MolecularMaskBase::cmask (double s) const inline protected
References mask().
Referenced by atomic_cmask().
double MolecularMaskBase::dmask (double s) const inline protected
References mpfr::exp(), mpfr::fabs(), madness::constants::pi, and sqrt().
Referenced by grad_atomic_mask().
madness::coord_3d MolecularMaskBase::grad_atomic_mask (const madness::coord_3d & r, unsigned int i) const inline protected
References dmask(), grad_sdf(), sdf(), and sigma.
Referenced by gradient().
madness::coord_3d MolecularMaskBase::grad_sdf (const madness::coord_3d & r, const madness::coord_3d & center) const inline protected
References distance().
Referenced by grad_atomic_mask().
madness::coord_3d MolecularMaskBase::gradient (const madness::coord_3d & r) const inline protected
References atomic_cmask(), grad_atomic_mask(), m, and natom.
Referenced by MolecularSurface::operator()(), and MolecularVolumeMaskGrad::operator()().
double MolecularMaskBase::mask (double s) const inline protected
References mpfr::erfc().
Referenced by atomic_mask(), and cmask().
double MolecularMaskBase::sdf (const madness::coord_3d & r, const madness::coord_3d & center, double R) const inline protected
References distance().
Referenced by atomic_cmask(), atomic_mask(), and grad_atomic_mask().
std::vector< madness::Vector<double,3> > MolecularMaskBase::special_points () const inline
References mpfr::cos(), natom, madness::constants::pi, mpfr::sin(), and madness::vec().
Referenced by MolecularVolumeMask::special_points(), MolecularVolumeComplementMask::special_points(), MolecularSurface::special_points(), and MolecularVolumeMaskGrad::special_points().
Member Data Documentation
const std::vector<madness::coord_3d> MolecularMaskBase::atomic_coords protected
const std::vector<double> MolecularMaskBase::atomic_radii protected
const int MolecularMaskBase::natom protected
Referenced by gradient(), MolecularVolumeMask::operator()(), MolecularVolumeComplementMask::operator()(), and special_points().
const double MolecularMaskBase::sigma protected
Referenced by grad_atomic_mask().
The documentation for this class was generated from the following file:
molecularmask.h