MADNESS: ScatteringWF Class Reference
ScatteringWF Class Reference abstract
#include <wavef.h>
Classes
struct MemberFuncPtr
Public Member Functions
ScatteringWF (madness::World &world, const double Z, double cutoff)
ScatteringWF (const double Z, double cutoff)
void Init (madness::World &world)
virtual complexd f11 (const double r) const =0
virtual double getk () const =0
virtual complexd setAA ()=0
virtual complexd setBB ()=0
complexd aForm (complexd ZZ) const
complexd gamma (double re, double im)
complexd gamma (complexd AA)
Public Member Functions inherited from baseWF
virtual complexd operator() (const vector3D &x) const =0
You should implement this to return f(x)
Public Member Functions inherited from madness::FunctionFunctorInterface< complexd, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, complexd *fvals, int npts) const
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Public Attributes
CubicInterpolationTable< complexd > fit1F1
const double Z_
const double cutoff_
complexd one
double dx
double k_
complexd AA
complexd BB
complexd gammaBB
complexd expmIPIAArGammaBBmAA
complexd expPIZ_2kXgamma1pIZ_k
complexd rGammaAA
complexd AAmBB
complexd mAA
double domain
int n
Additional Inherited Members
Public Types inherited from baseWF
typedef std::complex< double > complexd
typedef madness::Vector
< double, NDIM > vector3D
Public Types inherited from madness::FunctionFunctorInterface< complexd, NDIM >
typedef GenTensor< complexd > coeffT
typedef Key< NDIM > keyT
Static Public Attributes inherited from baseWF
static const complexd I
static const double PI = M_PI
Constructor & Destructor Documentation
ScatteringWF::ScatteringWF (madness::World & world, const double Z, double cutoff)
ScatteringWF::ScatteringWF (const double Z, double cutoff)
Member Function Documentation
complexd ScatteringWF::aForm (complexd ZZ) const
References AA, AAmBB, BB, mpfr::exp(), expmIPIAArGammaBBmAA, gammaBB, mAA, n, and rGammaAA.
Referenced by compare1F1(), PhiK::f11(), and Phikl::f11().
virtual complexd ScatteringWF::f11 (const double r) const pure virtual
Implemented in Phikl, and PhiK.
Referenced by ScatteringWF::MemberFuncPtr::operator()().
complexd ScatteringWF::gamma (double re, double im)
References madness::arg(), mpfr::cos(), mpfr::exp(), and mpfr::sin().
Referenced by Init().
complexd ScatteringWF::gamma (complexd AA)
References madness::arg(), mpfr::cos(), mpfr::exp(), madness::imag(), real(), and mpfr::sin().
virtual double ScatteringWF::getk () const pure virtual
Implemented in Phikl, and PhiK.
Referenced by Init().
void ScatteringWF::Init (madness::World & world)
References AA, AAmBB, BB, cutoff_, domain, dx, mpfr::exp(), expmIPIAArGammaBBmAA, expPIZ_2kXgamma1pIZ_k, fit1F1, mpfr::floor(), gamma(), gammaBB, getk(), baseWF::I, k_, mAA, n, one, baseWF::PI, rGammaAA, setAA(), setBB(), sqrt(), and Z_.
Referenced by belkic(), debugSlice(), projectPsi(), and testIntegral().
virtual complexd ScatteringWF::setAA () pure virtual
Implemented in Phikl, and PhiK.
Referenced by Init().
virtual complexd ScatteringWF::setBB () pure virtual
Implemented in Phikl, and PhiK.
Referenced by Init().
Member Data Documentation
complexd ScatteringWF::AA
Referenced by aForm(), PhiK::f11(), and Init().
complexd ScatteringWF::AAmBB
Referenced by aForm(), and Init().
complexd ScatteringWF::BB
Referenced by aForm(), PhiK::f11(), and Init().
const double ScatteringWF::cutoff_
Referenced by Init(), PhiK::operator()(), and Phikl::operator()().
double ScatteringWF::domain
Referenced by Init().
double ScatteringWF::dx
Referenced by Init().
complexd ScatteringWF::expmIPIAArGammaBBmAA
Referenced by aForm(), and Init().
complexd ScatteringWF::expPIZ_2kXgamma1pIZ_k
Referenced by Init(), and PhiK::operator()().
CubicInterpolationTable<complexd > ScatteringWF::fit1F1
Referenced by Init(), and PhiK::operator()().
complexd ScatteringWF::gammaBB
Referenced by aForm(), and Init().
double ScatteringWF::k_
Referenced by PhiK::f11(), Phikl::f11(), Phikl::getk(), Init(), PhiK::operator()(), PhiK::setAA(), and Phikl::setAA().
complexd ScatteringWF::mAA
Referenced by aForm(), and Init().
int ScatteringWF::n
Referenced by aForm(), and Init().
complexd ScatteringWF::one
Referenced by Phikl::f11(), and Init().
complexd ScatteringWF::rGammaAA
Referenced by aForm(), and Init().
const double ScatteringWF::Z_
Referenced by PhiK::f11(), Phikl::f11(), Init(), PhiK::setAA(), and Phikl::setAA().
The documentation for this class was generated from the following files:
wavef.h
wavef.cc