MADNESS: SafeMPI::Exception Class Reference
SafeMPI::Exception Class Reference
SafeMPI exception object.
#include <safempi.h>
Public Member Functions
Exception (const int mpi_error) throw ()
Exception (const Exception &other) throw ()
Exception & operator= (const Exception &other)
virtual ~Exception () throw ()
virtual const char * what () const throw ()
Friends
std::ostream & operator<< (std::ostream &os, const Exception &e)
Detailed Description
SafeMPI exception object.
This exception is thrown whenever an MPI error occurs.
Constructor & Destructor Documentation
SafeMPI::Exception::Exception (const int mpi_error) throw () inline
References MPI_Error_string(), MPI_MAX_ERROR_STRING, MPI_SUCCESS, and strncpy().
SafeMPI::Exception::Exception (const Exception & other) throw () inline
References MPI_MAX_ERROR_STRING, and strncpy().
virtual SafeMPI::Exception::~Exception () throw () inline virtual
Member Function Documentation
Exception& SafeMPI::Exception::operator= (const Exception & other) inline
References MPI_MAX_ERROR_STRING, and strncpy().
virtual const char* SafeMPI::Exception::what () const throw () inline virtual
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Exception & e) friend
The documentation for this class was generated from the following file:
safempi.h