MADNESS: Gaussian Class Reference
Gaussian Class Reference
#include <wavef.h>
Public Member Functions
Gaussian (double a)
complexd operator() (const vector3D &r) const
You should implement this to return f(x)
Gaussian (const coord_3d &center, double exponent, double coefficient)
double operator() (const coord_3d &x) const
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Public Member Functions inherited from madness::FunctionFunctorInterface< complexd, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, complexd *fvals, int npts) const
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Public Attributes
const coord_3d center
const double exponent
const double coefficient
std::vector< coord_3d > specialpt
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
Public Types inherited from baseWF
typedef std::complex< double > complexd
typedef madness::Vector
< double, NDIM > vector3D
Public Types inherited from madness::FunctionFunctorInterface< complexd, NDIM >
typedef GenTensor< complexd > coeffT
typedef Key< NDIM > keyT
Static Public Attributes inherited from baseWF
static const complexd I
static const double PI = M_PI
Constructor & Destructor Documentation
Gaussian::Gaussian (double a)
Gaussian::Gaussian (const coord_3d & center, double exponent, double coefficient) inline
Member Function Documentation
double Gaussian::operator() (const coord_3d & x) const inline
References mpfr::exp(), and mpfr::sum().
complexd Gaussian::operator() (const vector3D & x) const virtual
You should implement this to return f(x)
Implements baseWF.
References mpfr::exp(), and NDIM.
std::vector<coord_3d> Gaussian::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
Member Data Documentation
const coord_3d Gaussian::center
const double Gaussian::coefficient
const double Gaussian::exponent
std::vector<coord_3d> Gaussian::specialpt
The documentation for this class was generated from the following files:
wavef.h
dataloadbal.cc
wavef.cc