MADNESS: testing::ScopedFakeTestPartResultReporter Class Reference
testing::ScopedFakeTestPartResultReporter Class Reference
#include <gtest-spi.h>
Public Types
enum InterceptMode { INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS }
Public Member Functions
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
virtual void ReportTestPartResult (const TestPartResult &result)
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
Member Enumeration Documentation
enum testing::ScopedFakeTestPartResultReporter::InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Constructor & Destructor Documentation
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (TestPartResultArray * result) explicit
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () virtual
References testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Member Function Documentation
void testing::ScopedFakeTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
References testing::TestPartResultArray::Append().
The documentation for this class was generated from the following files:
gtest-spi.h
gtest.cc