MADNESS: madness::Timer Class Reference
madness::Timer Class Reference
#include <function_common_data.h>
Public Member Functions
Timer ()
start timer
void accumulate (const double time) const
accumulate timer
void reset () const
void print (std::string line="") const
print timer
Constructor & Destructor Documentation
madness::Timer::Timer () inline
start timer
Member Function Documentation
void madness::Timer::accumulate (const double time) const inline
accumulate timer
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), and madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert().
Referenced by madness::SeparatedConvolution< T, NDIM >::apply(), madness::SeparatedConvolution< T, NDIM >::apply2(), and madness::FunctionImpl< Q, NDIM >::do_apply_kernel2().
void madness::Timer::print (std::string line = "") const inline
print timer
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), and madness::print().
Referenced by madness::SeparatedConvolution< T, NDIM >::print_timer().
void madness::Timer::reset () const inline
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::clear().
Referenced by madness::SeparatedConvolution< T, NDIM >::reset_timer().
The documentation for this class was generated from the following file:
function_common_data.h