MADNESS: madness::ProjRLMFunctor Class Reference
madness::ProjRLMFunctor Class Reference
#include <gth_pseudopotential.h>
Public Member Functions
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
ProjRLMFunctor (double alpha, int l, int m, int i, const coord_3d &center)
double operator() (const coord_3d &r) const
virtual bool screened (const coord_3d &c1, const coord_3d &c2) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *restrict fvals, int npts) const
std::vector< coord_3d > special_points () const
Override this to return list of special points to be refined more deeply.
Level special_level ()
Override this change level refinement for special points (default is 6)
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const =0
You should implement this to return f(x)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Static Public Attributes
static const double gamma_data [17]
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
Constructor & Destructor Documentation
madness::ProjRLMFunctor::ProjRLMFunctor (double alpha, int l, int m, int i, const coord_3d & center) inline
References madness::constants::pi, and sqrt().
Member Function Documentation
double madness::ProjRLMFunctor::operator() (const coord_3d & r) const inline
References mpfr::exp(), MADNESS_EXCEPTION, madness::constants::pi, PI, and sqrt().
Referenced by screened().
virtual void madness::ProjRLMFunctor::operator() (const Vector< double *, 3 > & xvals, double *restrict fvals, int npts) const inline virtual
References mpfr::exp(), MADNESS_EXCEPTION, madness::constants::pi, PI, and sqrt().
virtual bool madness::ProjRLMFunctor::screened (const coord_3d & c1, const coord_3d & c2) const inline virtual
References k, MADNESS_EXCEPTION, operator()(), and madness::vec().
Level madness::ProjRLMFunctor::special_level () inline virtual
Override this change level refinement for special points (default is 6)
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
std::vector<coord_3d> madness::ProjRLMFunctor::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
virtual bool madness::ProjRLMFunctor::supports_vectorized () const inline virtual
Does the interface support a vectorized operator()?
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
Member Data Documentation
const double madness::ProjRLMFunctor::gamma_data static
Initial value:
= {1.0, 0.0, 1.0/2.0, 0.0, 3.0/4.0, 0.0, 15.0/8.0, 0.0, 105.0/16.0, 0.0,
        945.0/32.0, 0.0, 10395.0/64.0, 0.0, 135135.0/128.0, 0.0, 2027025.0/256.0}
The documentation for this class was generated from the following files:
gth_pseudopotential.h
gth_pseudopotential.cc