MADNESS: madness::Spinlock Class Reference
madness::Spinlock Class Reference
Spinlock using pthread spinlock operations.
#include <worldmutex.h>
Public Member Functions
Spinlock (int junk=0)
Make and initialize a spinlock ... initial state is unlocked.
bool try_lock () const
Try to acquire the spinlock ... return true on success, false on failure.
void lock () const
Acquire the spinlock waiting if necessary.
void unlock () const
Free a spinlock owned by this thread.
virtual ~Spinlock ()
Detailed Description
Spinlock using pthread spinlock operations.
Constructor & Destructor Documentation
madness::Spinlock::Spinlock (int junk = 0) inline
Make and initialize a spinlock ... initial state is unlocked.
virtual madness::Spinlock::~Spinlock () inline virtual
Member Function Documentation
void madness::Spinlock::lock () const inline
Acquire the spinlock waiting if necessary.
References MADNESS_EXCEPTION.
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::find(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::MutexFair::lock(), madness::WorldObject< DerivativeBase< T, NDIM > >::process_pending(), madness::MutexFair::try_lock(), madness::MutexFair::unlock(), and madness::ConditionVariable::wait().
bool madness::Spinlock::try_lock () const inline
Try to acquire the spinlock ... return true on success, false on failure.
Referenced by madness::MutexReaderWriter::lock().
void madness::Spinlock::unlock () const inline
Free a spinlock owned by this thread.
References MADNESS_EXCEPTION.
Referenced by madness::Hash_private::bin< keyT, valueT >::clear(), madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::find(), madness::Hash_private::bin< keyT, valueT >::insert(), madness::MutexFair::lock(), madness::WorldObject< DerivativeBase< T, NDIM > >::process_pending(), madness::MutexFair::try_lock(), madness::MutexFair::unlock(), and madness::ConditionVariable::wait().
The documentation for this class was generated from the following file:
worldmutex.h