MADNESS: TiXmlNode Class Reference
TiXmlNode Class Reference abstract
#include <tinyxml.h>
Public Types
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Public Member Functions
virtual ~TiXmlNode ()
const char * Value () const
const std::string & ValueStr () const
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
const TiXmlDocument * GetDocument () const
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlNode * Clone () const =0
virtual bool Accept (TiXmlVisitor *visitor) const =0
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
virtual void Print (FILE *cfile, int depth) const =0
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)=0
Protected Member Functions
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)=0
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Protected Attributes
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Friends
class TiXmlDocument
class TiXmlElement
std::istream & operator>> (std::istream &in, TiXmlNode &base)
std::ostream & operator<< (std::ostream &out, const TiXmlNode &base)
std::string & operator<< (std::string &out, const TiXmlNode &base)
Appends the XML node or attribute to a std::string.
Additional Inherited Members
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
The parent class for everything in the Document Object Model. (Except for attributes). Nodes have siblings, a parent, and children. A node can be in a document, or stand on its own. The type of a TiXmlNode can be queried, and it can be cast to its more defined type.
Member Enumeration Documentation
enum TiXmlNode::NodeType
The types of XML nodes supported by TinyXml. (All the unsupported types are picked up by UNKNOWN.)
Enumerator
DOCUMENT
ELEMENT
COMMENT
UNKNOWN
TEXT
DECLARATION
TYPECOUNT
Constructor & Destructor Documentation
TiXmlNode::~TiXmlNode () virtual
References firstChild, and next.
TiXmlNode::TiXmlNode (NodeType _type) protected
References firstChild, lastChild, next, parent, prev, and type.
Member Function Documentation
virtual bool TiXmlNode::Accept (TiXmlVisitor * visitor) const pure virtual
Accept a hierchical visit the nodes in the TinyXML DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, and TiXmlElement.
Referenced by TiXmlDocument::Accept(), and operator<<().
void TiXmlNode::Clear ()
Delete all the children of this node. Does not affect 'this'.
References firstChild, lastChild, and next.
Referenced by TiXmlElement::ClearThis(), TiXmlDocument::LoadFile(), TiXmlComment::operator=(), TiXmlDeclaration::operator=(), and TiXmlDocument::operator=().
virtual TiXmlNode* TiXmlNode::Clone () const pure virtual
Create an exact duplicate of this node and return it. The memory must be deleted by the caller.
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, and TiXmlElement.
Referenced by TiXmlElement::CopyTo(), InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and ReplaceChild().
void TiXmlNode::CopyTo (TiXmlNode * target) const protected
References SetValue(), TiXmlBase::userData, and value.
Referenced by TiXmlElement::CopyTo(), TiXmlComment::CopyTo(), TiXmlText::CopyTo(), TiXmlDeclaration::CopyTo(), and TiXmlUnknown::CopyTo().
const TiXmlNode* TiXmlNode::FirstChild () const inline
The first child of this node. Will be null if there are no children.
References firstChild.
Referenced by TiXmlElement::Accept(), TiXmlDocument::Accept(), TiXmlHandle::Child(), TiXmlHandle::FirstChild(), FirstChildElement(), TiXmlElement::GetText(), IterateChildren(), TiXmlDocument::Print(), TiXmlPrinter::VisitEnter(), and TiXmlPrinter::VisitExit().
TiXmlNode* TiXmlNode::FirstChild () inline
References firstChild.
const TiXmlNode * TiXmlNode::FirstChild (const char * value) const
The first child of this node with the matching 'value'. Will be null if none found.
References firstChild, next, and Value().
TiXmlNode* TiXmlNode::FirstChild (const char * _value) inline
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode* TiXmlNode::FirstChild (const std::string & _value) const inline
STL std::string form.
References FirstChild().
Referenced by FirstChild().
TiXmlNode* TiXmlNode::FirstChild (const std::string & _value) inline
STL std::string form.
References FirstChild().
Referenced by FirstChild().
const TiXmlElement * TiXmlNode::FirstChildElement () const
Convenience function to get through elements.
References FirstChild(), NextSibling(), and ToElement().
Referenced by TiXmlHandle::ChildElement(), TiXmlHandle::FirstChildElement(), madness::get_charge_from_file(), madness::GTHPseudopotential< double >::load_pseudo_from_file(), AtomicBasisSet::read_file(), madness::AtomicBasisSet::read_file(), and TiXmlDocument::RootElement().
TiXmlElement* TiXmlNode::FirstChildElement () inline
const TiXmlElement * TiXmlNode::FirstChildElement (const char * _value) const
Convenience function to get through elements.
References FirstChild(), NextSibling(), and ToElement().
TiXmlElement* TiXmlNode::FirstChildElement (const char * _value) inline
const TiXmlElement* TiXmlNode::FirstChildElement (const std::string & _value) const inline
STL std::string form.
References FirstChildElement().
Referenced by FirstChildElement().
TiXmlElement* TiXmlNode::FirstChildElement (const std::string & _value) inline
STL std::string form.
References FirstChildElement().
Referenced by FirstChildElement().
const TiXmlDocument * TiXmlNode::GetDocument () const
Return a pointer to the Document this node lives in. Returns null if not in a document.
References parent, and ToDocument().
Referenced by Identify(), InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), LinkEndChild(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlElement::ReadValue(), TiXmlElement::SetAttribute(), TiXmlElement::StreamIn(), TiXmlComment::StreamIn(), TiXmlText::StreamIn(), TiXmlDeclaration::StreamIn(), and TiXmlUnknown::StreamIn().
TiXmlDocument* TiXmlNode::GetDocument () inline
TiXmlNode * TiXmlNode::Identify (const char * start, TiXmlEncoding encoding) protected
References GetDocument(), TiXmlBase::IsAlpha(), parent, TiXmlText::SetCDATA(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::StringEqual(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_OUT_OF_MEMORY, and TiXmlElement.
Referenced by TiXmlDocument::Parse(), TiXmlElement::ReadValue(), TiXmlElement::StreamIn(), and TiXmlDocument::StreamIn().
TiXmlNode * TiXmlNode::InsertAfterChild (TiXmlNode * afterThis, const TiXmlNode & addThis)
Add a new node related to this. Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone(), DOCUMENT, GetDocument(), lastChild, next, parent, prev, TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
TiXmlNode * TiXmlNode::InsertBeforeChild (TiXmlNode * beforeThis, const TiXmlNode & addThis)
Add a new node related to this. Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone(), DOCUMENT, firstChild, GetDocument(), next, parent, prev, TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
TiXmlNode * TiXmlNode::InsertEndChild (const TiXmlNode & addThis)
Add a new node related to this. Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
References Clone(), DOCUMENT, GetDocument(), LinkEndChild(), TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
const TiXmlNode * TiXmlNode::IterateChildren (const TiXmlNode * previous) const
An alternate way to walk the children of a node. One way to iterate over nodes is:
        for( child = parent->FirstChild(); child; child = child->NextSibling() )
IterateChildren does the same thing with the syntax:
        child = 0;
        while( child = parent->IterateChildren( child ) )
IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
References FirstChild(), NextSibling(), and parent.
TiXmlNode* TiXmlNode::IterateChildren (const TiXmlNode * previous) inline
const TiXmlNode * TiXmlNode::IterateChildren (const char * value, const TiXmlNode * previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
References FirstChild(), NextSibling(), and parent.
TiXmlNode* TiXmlNode::IterateChildren (const char * _value, const TiXmlNode * previous) inline
const TiXmlNode* TiXmlNode::IterateChildren (const std::string & _value, const TiXmlNode * previous) const inline
STL std::string form.
References IterateChildren().
Referenced by IterateChildren().
TiXmlNode* TiXmlNode::IterateChildren (const std::string & _value, const TiXmlNode * previous) inline
STL std::string form.
References IterateChildren().
Referenced by IterateChildren().
const TiXmlNode* TiXmlNode::LastChild () const inline
References lastChild.
Referenced by TiXmlPrinter::VisitEnter().
TiXmlNode* TiXmlNode::LastChild () inline
The last child of this node. Will be null if there are no children.
References lastChild.
const TiXmlNode * TiXmlNode::LastChild (const char * value) const
References lastChild, prev, and Value().
TiXmlNode* TiXmlNode::LastChild (const char * _value) inline
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode* TiXmlNode::LastChild (const std::string & _value) const inline
STL std::string form.
References LastChild().
Referenced by LastChild().
TiXmlNode* TiXmlNode::LastChild (const std::string & _value) inline
STL std::string form.
References LastChild().
Referenced by LastChild().
TiXmlNode * TiXmlNode::LinkEndChild (TiXmlNode * addThis)
Add a new node related to this. Adds a child past the LastChild.
NOTE: the node to be added is passed by pointer, and will be
henceforth owned (and deleted) by tinyXml. This method is efficient
and avoids an extra copy, but should be used with care as it
uses a different memory model than the other insert functions.
@sa InsertEndChild
References DOCUMENT, firstChild, GetDocument(), lastChild, next, parent, prev, TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by TiXmlElement::CopyTo(), InsertEndChild(), TiXmlDocument::Parse(), and TiXmlElement::ReadValue().
const TiXmlNode* TiXmlNode::NextSibling (const std::string & _value) const inline
STL std::string form.
References NextSibling().
Referenced by TiXmlElement::Accept(), TiXmlDocument::Accept(), TiXmlHandle::Child(), TiXmlElement::CopyTo(), FirstChildElement(), IterateChildren(), NextSibling(), NextSiblingElement(), TiXmlElement::Print(), and TiXmlDocument::Print().
TiXmlNode* TiXmlNode::NextSibling (const std::string & _value) inline
STL std::string form.
References NextSibling().
Referenced by NextSibling().
const TiXmlNode* TiXmlNode::NextSibling () const inline
Navigate to a sibling node.
References next.
Referenced by NextSiblingElement().
TiXmlNode* TiXmlNode::NextSibling () inline
References next.
const TiXmlNode * TiXmlNode::NextSibling (const char * _value) const
Navigate to a sibling node with the given 'value'.
References next, and Value().
TiXmlNode* TiXmlNode::NextSibling (const char * _next) inline
const TiXmlElement * TiXmlNode::NextSiblingElement () const
Convenience function to get through elements. Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling(), and ToElement().
Referenced by TiXmlHandle::ChildElement(), madness::get_charge_from_file(), madness::GTHPseudopotential< double >::load_pseudo_from_file(), AtomicBasisSet::read_file(), and madness::AtomicBasisSet::read_file().
TiXmlElement* TiXmlNode::NextSiblingElement () inline
const TiXmlElement * TiXmlNode::NextSiblingElement (const char * _value) const
Convenience function to get through elements. Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling(), and ToElement().
TiXmlElement* TiXmlNode::NextSiblingElement (const char * _next) inline
const TiXmlElement* TiXmlNode::NextSiblingElement (const std::string & _value) const inline
STL std::string form.
References NextSiblingElement().
Referenced by NextSiblingElement().
TiXmlElement* TiXmlNode::NextSiblingElement (const std::string & _value) inline
STL std::string form.
References NextSiblingElement().
Referenced by NextSiblingElement().
bool TiXmlNode::NoChildren () const inline
Returns true if this node has no children.
References firstChild.
TiXmlNode* TiXmlNode::Parent () inline
One step up the DOM.
References parent.
const TiXmlNode* TiXmlNode::Parent () const inline
References parent.
const TiXmlNode* TiXmlNode::PreviousSibling () const inline
Navigate to a sibling node.
References prev.
TiXmlNode* TiXmlNode::PreviousSibling () inline
References prev.
const TiXmlNode * TiXmlNode::PreviousSibling (const char * _value) const
Navigate to a sibling node.
References prev, and Value().
TiXmlNode* TiXmlNode::PreviousSibling (const char * _prev) inline
const TiXmlNode* TiXmlNode::PreviousSibling (const std::string & _value) const inline
STL std::string form.
References PreviousSibling().
Referenced by PreviousSibling().
TiXmlNode* TiXmlNode::PreviousSibling (const std::string & _value) inline
STL std::string form.
References PreviousSibling().
Referenced by PreviousSibling().
bool TiXmlNode::RemoveChild (TiXmlNode * removeThis)
Delete a child of this node.
References firstChild, lastChild, next, parent, and prev.
TiXmlNode * TiXmlNode::ReplaceChild (TiXmlNode * replaceThis, const TiXmlNode & withThis)
Replace a child of this node. Returns a pointer to the new object or NULL if an error occured.
References Clone(), firstChild, lastChild, next, parent, and prev.
void TiXmlNode::SetValue (const char * _value) inline
Changes the value of the node. Defined as:
    Document:   filename of the xml file
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
References value.
Referenced by CopyTo(), TiXmlComment::TiXmlComment(), and TiXmlText::TiXmlText().
void TiXmlNode::SetValue (const std::string & _value) inline
STL std::string form.
virtual void TiXmlNode::StreamIn (std::istream * in, TIXML_STRING * tag) protected pure virtual
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, and TiXmlElement.
Referenced by operator>>(), TiXmlElement::StreamIn(), and TiXmlDocument::StreamIn().
virtual const TiXmlComment* TiXmlNode::ToComment () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlComment.
virtual TiXmlComment* TiXmlNode::ToComment () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlComment.
virtual const TiXmlDeclaration* TiXmlNode::ToDeclaration () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDeclaration.
Referenced by TiXmlDocument::Parse().
virtual TiXmlDeclaration* TiXmlNode::ToDeclaration () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDeclaration.
virtual const TiXmlDocument* TiXmlNode::ToDocument () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDocument.
Referenced by GetDocument().
virtual TiXmlDocument* TiXmlNode::ToDocument () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDocument.
virtual const TiXmlElement* TiXmlNode::ToElement () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlElement.
Referenced by FirstChildElement(), NextSiblingElement(), TiXmlDocument::StreamIn(), and TiXmlHandle::ToElement().
virtual TiXmlElement* TiXmlNode::ToElement () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlElement.
virtual const TiXmlText* TiXmlNode::ToText () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlText.
Referenced by TiXmlElement::GetText(), TiXmlElement::Print(), TiXmlHandle::ToText(), and TiXmlPrinter::VisitEnter().
virtual TiXmlText* TiXmlNode::ToText () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlText.
virtual const TiXmlUnknown* TiXmlNode::ToUnknown () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlUnknown.
Referenced by TiXmlHandle::ToUnknown().
virtual TiXmlUnknown* TiXmlNode::ToUnknown () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlUnknown.
int TiXmlNode::Type () const inline
Query the type (as an enumerated value, above) of this node. The possible types are: DOCUMENT, ELEMENT, COMMENT, UNKNOWN, TEXT, and DECLARATION.
References type.
Referenced by InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and LinkEndChild().
const char* TiXmlNode::Value () const inline
The meaning of 'value' changes for the specific type of TiXmlNode.
    Document:   filename of the xml file
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
The subclasses will wrap this function.
References value.
Referenced by TiXmlElement::Clone(), FirstChild(), TiXmlElement::GetText(), LastChild(), TiXmlDocument::LoadFile(), NextSibling(), PreviousSibling(), AtomicBasisSet::read_file(), TiXmlDocument::SaveFile(), TiXmlPrinter::Visit(), TiXmlPrinter::VisitEnter(), and TiXmlPrinter::VisitExit().
const std::string& TiXmlNode::ValueStr () const inline
Return Value() as a std::string. If you only use STL, this is more efficient than calling Value(). Only available in STL mode.
References value.
const TIXML_STRING& TiXmlNode::ValueTStr () const inline
References value.
Referenced by TiXmlPrinter::Visit().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const TiXmlNode & base) friend
An output stream operator, for every class. Note that this outputs without any newlines or formatting, as opposed to Print(), which includes tabs and new lines.
The operator<< and operator>> are not completely symmetric. Writing a node to a stream is very well defined. You'll get a nice stream of output, without any extra whitespace or newlines.
But reading is not as well defined. (As it always is.) If you create a TiXmlElement (for example) and read that from an input stream, the text needs to define an element or junk will result. This is true of all input streams, but it's worth keeping in mind.
A TiXmlDocument will read nodes until it reads a root element, and all the children of that root element.
std::string& operator<< (std::string & out, const TiXmlNode & base) friend
Appends the XML node or attribute to a std::string.
std::istream& operator>> (std::istream & in, TiXmlNode & base) friend
An input stream operator, for every class. Tolerant of newlines and formatting, but doesn't expect them.
friend class TiXmlDocument friend
friend class TiXmlElement friend
Referenced by Identify().
Member Data Documentation
TiXmlNode* TiXmlNode::firstChild protected
Referenced by Clear(), TiXmlElement::CopyTo(), FirstChild(), InsertBeforeChild(), LinkEndChild(), NoChildren(), TiXmlDocument::Parse(), TiXmlElement::Print(), RemoveChild(), ReplaceChild(), TiXmlElement::TiXmlElement(), TiXmlNode(), and ~TiXmlNode().
TiXmlNode* TiXmlNode::lastChild protected
Referenced by Clear(), InsertAfterChild(), LastChild(), LinkEndChild(), TiXmlElement::Print(), RemoveChild(), ReplaceChild(), TiXmlElement::TiXmlElement(), and TiXmlNode().
TiXmlNode* TiXmlNode::next protected
Referenced by Clear(), TiXmlAttributeSet::Find(), FirstChild(), InsertAfterChild(), InsertBeforeChild(), LinkEndChild(), NextSibling(), RemoveChild(), ReplaceChild(), TiXmlNode(), and ~TiXmlNode().
TiXmlNode* TiXmlNode::parent protected
Referenced by GetDocument(), Identify(), InsertAfterChild(), InsertBeforeChild(), IterateChildren(), LinkEndChild(), Parent(), RemoveChild(), ReplaceChild(), and TiXmlNode().
TiXmlNode* TiXmlNode::prev protected
Referenced by InsertAfterChild(), InsertBeforeChild(), LastChild(), LinkEndChild(), PreviousSibling(), RemoveChild(), ReplaceChild(), and TiXmlNode().
NodeType TiXmlNode::type protected
Referenced by TiXmlNode(), and Type().
TIXML_STRING TiXmlNode::value protected
Referenced by TiXmlText::Blank(), CopyTo(), TiXmlDocument::LoadFile(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Print(), TiXmlComment::Print(), TiXmlText::Print(), TiXmlUnknown::Print(), SetValue(), TiXmlDocument::TiXmlDocument(), TiXmlElement::TiXmlElement(), Value(), ValueStr(), and ValueTStr().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc