MADNESS: madness::PotentialManager Class Reference
madness::PotentialManager Class Reference
#include <potentialmanager.h>
Public Member Functions
PotentialManager (const Molecule &molecule, const std::string &core_type)
real_function_3d vnuclear ()
vector_real_function_3d core_projection (World &world, const vector_real_function_3d &psi, const bool include_Bc=true)
double core_projector_derivative (World &world, const vector_real_function_3d &mo, const real_tensor &occ, int atom, int axis)
void apply_nonlocal_potential (World &world, const vector_real_function_3d &amo, vector_real_function_3d Vpsi)
void make_nuclear_potential (World &world)
Constructor & Destructor Documentation
madness::PotentialManager::PotentialManager (const Molecule & molecule, const std::string & core_type) inline
Member Function Documentation
void madness::PotentialManager::apply_nonlocal_potential (World & world, const vector_real_function_3d & amo, vector_real_function_3d Vpsi) inline
References core_projection(), and madness::gaxpy().
vector_real_function_3d madness::PotentialManager::core_projection (World & world, const vector_real_function_3d & psi, const bool include_Bc = true) inline
References madness::Atom::atomic_number, c, madness::Function< T, NDIM >::fence(), madness::Molecule::get_atom(), madness::Molecule::get_core_bc(), madness::Molecule::get_core_l(), madness::inner(), m, madness::Molecule::n_core_orb(), madness::Molecule::natom(), madness::print(), psi(), and madness::Function< T, NDIM >::scale().
Referenced by apply_nonlocal_potential().
double madness::PotentialManager::core_projector_derivative (World & world, const vector_real_function_3d & mo, const real_tensor & occ, int atom, int axis) inline
References madness::Atom::atomic_number, c, func(), madness::Molecule::get_atom(), madness::Molecule::get_core_bc(), madness::Molecule::get_core_l(), madness::inner(), m, and madness::Molecule::n_core_orb().
void madness::PotentialManager::make_nuclear_potential (World & world) inline
References madness::FunctionDefaults< NDIM >::get_thresh(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::set_thresh(), and madness::Function< T, NDIM >::truncate().
real_function_3d madness::PotentialManager::vnuclear () inline
The documentation for this class was generated from the following file:
potentialmanager.h