MADNESS: madness::vecfunc< T, NDIM > Class Template Reference
madness::vecfunc< T, NDIM > Class Template Reference
#include <nemo.h>
Public Member Functions
vecfunc (World &world, const std::vector< Function< T, NDIM > > &x1)
vecfunc (const std::vector< Function< T, NDIM > > &x1)
vecfunc (const vecfunc &other)
vecfunc & operator= (const vecfunc &other)
vecfunc operator- (const vecfunc &b) const
vecfunc operator+= (const vecfunc &b)
vecfunc operator* (double a) const
Public Attributes
World & world
std::vector< Function< T, NDIM > > x
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::vecfunc< T, NDIM >::vecfunc (World & world, const std::vector< Function< T, NDIM > > & x1) inline
Referenced by madness::vecfunc< T, NDIM >::operator-().
template<typename T, std::size_t NDIM> madness::vecfunc< T, NDIM >::vecfunc (const std::vector< Function< T, NDIM > > & x1) inline
template<typename T, std::size_t NDIM> madness::vecfunc< T, NDIM >::vecfunc (const vecfunc< T, NDIM > & other) inline
Member Function Documentation
template<typename T, std::size_t NDIM> vecfunc madness::vecfunc< T, NDIM >::operator* (double a) const inline
References madness::WorldGopInterface::fence(), madness::World::gop, madness::mul(), and PROFILE_BLOCK.
template<typename T, std::size_t NDIM> vecfunc madness::vecfunc< T, NDIM >::operator+= (const vecfunc< T, NDIM > & b) inline
References madness::add(), and madness::vecfunc< T, NDIM >::x.
template<typename T, std::size_t NDIM> vecfunc madness::vecfunc< T, NDIM >::operator- (const vecfunc< T, NDIM > & b) const inline
References madness::sub(), madness::vecfunc< T, NDIM >::vecfunc(), and madness::vecfunc< T, NDIM >::x.
template<typename T, std::size_t NDIM> vecfunc& madness::vecfunc< T, NDIM >::operator= (const vecfunc< T, NDIM > & other) inline
References madness::vecfunc< T, NDIM >::x.
Member Data Documentation
template<typename T, std::size_t NDIM> World& madness::vecfunc< T, NDIM >::world
Referenced by madness::inner().
template<typename T, std::size_t NDIM> std::vector<Function<T, NDIM> > madness::vecfunc< T, NDIM >::x
Referenced by madness::inner(), madness::vecfunc< T, NDIM >::operator+=(), madness::vecfunc< T, NDIM >::operator-(), and madness::vecfunc< T, NDIM >::operator=().
The documentation for this class was generated from the following file:
nemo.h