MADNESS: SVPEColloidSolver Class Reference
SVPEColloidSolver Class Reference
#include <svpe_molecule_colloid.h>
Public Member Functions
SVPEColloidSolver (World &world, double sigma, double epsilon_0, double epsilon_1, const vector_real &atomic_radii, const vector_coord_3d &atomic_coords, const double minlen, double L, const int maxiter)
real_function_3d make_surface_charge (const real_function_3d &u) const
real_function_3d make_Laplace_surface_charge (const real_function_3d &u, std::vector< double > E=std::vector< double >(3, 0.0)) const
vector_real_function_3d make_electric_field (const real_function_3d &u) const
real_function_3d solve (const real_function_3d &rho) const
Solve for the full Coulomb potential using the free-particle GF.
real_function_3d solve_Laplace (std::vector< double >E) const
Solve for the full Coulomb potential using the free-particle GF.
double ave_rxn_field (const real_function_3d &u, const real_function_3d &mask) const
Constructor & Destructor Documentation
SVPEColloidSolver::SVPEColloidSolver (World & world, double sigma, double epsilon_0, double epsilon_1, const vector_real & atomic_radii, const vector_coord_3d & atomic_coords, const double minlen, double L, const int maxiter) inline
References madness::truncate(), and madness::Function< T, NDIM >::truncate().
Member Function Documentation
double SVPEColloidSolver::ave_rxn_field (const real_function_3d & u, const real_function_3d & mask) const inline
References sqrt(), and madness::Function< T, NDIM >::trace().
vector_real_function_3d SVPEColloidSolver::make_electric_field (const real_function_3d & u) const inline
References op(), madness::constants::pi, madness::plot_line(), madness::scale(), and madness::Function< T, NDIM >::world().
real_function_3d SVPEColloidSolver::make_Laplace_surface_charge (const real_function_3d & u, std::vector< double > E = std::vector<double>(3,0.0)) const inline
References madness::Function< T, NDIM >::truncate().
real_function_3d SVPEColloidSolver::make_surface_charge (const real_function_3d & u) const inline
References madness::Function< T, NDIM >::truncate().
real_function_3d SVPEColloidSolver::solve (const real_function_3d & rho) const inline
Solve for the full Coulomb potential using the free-particle GF.
volume.trace();
References maxiter, madness::norm2(), madness::Function< T, NDIM >::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::print(), madness::World::rank(), madness::scale(), madness::Function< T, NDIM >::trace(), madness::truncate(), madness::NonlinearSolverND< NDIM >::update(), and madness::wall_time().
real_function_3d SVPEColloidSolver::solve_Laplace (std::vector< double > E) const inline
Solve for the full Coulomb potential using the free-particle GF.
References maxiter, mpfr::min(), madness::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::print(), madness::World::rank(), madness::scale(), madness::Function< T, NDIM >::trace(), madness::truncate(), madness::NonlinearSolverND< NDIM >::update(), and madness::wall_time().
The documentation for this class was generated from the following file:
svpe_molecule_colloid.h