MADNESS: madness::TDA_DFT Class Reference
madness::TDA_DFT Class Reference
#include <TDA_XC.h>
Public Member Functions
TDA_DFT (World &world, const SCF &calc)
TDA_DFT (const TDA_DFT &other)
Disable copy constructor.
void print_information ()
vecfuncT evaluate_derivatives () const
real_function_3d get_perturbed_potential (const real_function_3d &perturbed_density)
real_function_3d convolution_with_kernel (real_function_3d &perturbed_density) const
vecfuncT apply_kernel (const vecfuncT &x) const
real_function_3d get_unperturbed_vxc () const
XCfunctional get_xcfunctional () const
real_function_3d calculate_unperturbed_vxc (const real_function_3d &rho) const
vecfuncT get_lda_intermediate (vecfuncT &mos) const
bool is_gga () const
Public Attributes
World & world
The world.
Constructor & Destructor Documentation
madness::TDA_DFT::TDA_DFT (World & world, const SCF & calc) inline
References madness::SCF::amo, madness::WorldGopInterface::fence(), madness::World::gop, gradop, madness::inner(), madness::XCfunctional::is_gga(), madness::XCfunctional::is_lda(), madness::XCfunctional::is_spin_polarized(), madness::Function< T, NDIM >::norm2(), madness::plot_plane(), madness::Function< T, NDIM >::reconstruct(), and world.
madness::TDA_DFT::TDA_DFT (const TDA_DFT & other)
Disable copy constructor.
Member Function Documentation
vecfuncT TDA_DFT::apply_kernel (const vecfuncT & x) const
References madness::SCF::amo, madness::XCfunctional::is_gga(), MADNESS_EXCEPTION, madness::reconstruct(), madness::Function< T, NDIM >::refine_to_common_level(), madness::Function< T, NDIM >::scale(), and world.
real_function_3d madness::TDA_DFT::calculate_unperturbed_vxc (const real_function_3d & rho) const inline
real_function_3d TDA_DFT::convolution_with_kernel (real_function_3d & perturbed_density) const
DEBUG
DEBUG END
References madness::WorldGopInterface::fence(), madness::World::gop, gradop, madness::XCfunctional::is_gga(), madness::XCfunctional::is_lda(), MADNESS_EXCEPTION, madness::mul(), madness::plot_plane(), madness::reconstruct(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::refine_to_common_level(), madness::scale(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), and world.
vecfuncT TDA_DFT::evaluate_derivatives () const
References madness::XCfunctional::is_gga(), and MADNESS_EXCEPTION.
vecfuncT madness::TDA_DFT::get_lda_intermediate (vecfuncT & mos) const inline
real_function_3d madness::TDA_DFT::get_perturbed_potential (const real_function_3d & perturbed_density) inline
real_function_3d madness::TDA_DFT::get_unperturbed_vxc () const inline
XCfunctional madness::TDA_DFT::get_xcfunctional () const inline
bool madness::TDA_DFT::is_gga () const inline
References madness::XCfunctional::is_gga().
void madness::TDA_DFT::print_information ()
Member Data Documentation
World& madness::TDA_DFT::world
The world.
Referenced by apply_kernel(), convolution_with_kernel(), and TDA_DFT().
The documentation for this class was generated from the following files:
TDA_XC.h
TDA_XC.cc