MADNESS: madness::Stack< T, N > Class Template Reference
madness::Stack< T, N > Class Template Reference
A simple, fixed-size, stack.
#include <array.h>
Public Member Functions
Stack ()
void push (const T &value)
T & pop ()
T & front ()
T & top ()
std::size_t size () const
bool empty () const
void clear ()
void reset ()
Detailed Description
template<typename T, std::size_t N>
class madness::Stack< T, N >
A simple, fixed-size, stack.
Constructor & Destructor Documentation
template<typename T , std::size_t N> madness::Stack< T, N >::Stack () inline
Member Function Documentation
template<typename T , std::size_t N> void madness::Stack< T, N >::clear () inline
Referenced by madness::Stack< T, N >::reset().
template<typename T , std::size_t N> bool madness::Stack< T, N >::empty () const inline
template<typename T , std::size_t N> T& madness::Stack< T, N >::front () inline
Referenced by madness::Stack< T, N >::top().
template<typename T , std::size_t N> T& madness::Stack< T, N >::pop () inline
template<typename T , std::size_t N> void madness::Stack< T, N >::push (const T & value) inline
References N.
template<typename T , std::size_t N> void madness::Stack< T, N >::reset () inline
References madness::Stack< T, N >::clear().
template<typename T , std::size_t N> std::size_t madness::Stack< T, N >::size () const inline
template<typename T , std::size_t N> T& madness::Stack< T, N >::top () inline
References madness::Stack< T, N >::front().
The documentation for this class was generated from the following file:
array.h