MADNESS: madness::SimpleCache< Q, NDIM > Class Template Reference
madness::SimpleCache< Q, NDIM > Class Template Reference
Simplified interface around hash_map to cache stuff for 1D.
#include <simplecache.h>
Public Member Functions
SimpleCache ()
SimpleCache (const SimpleCache &c)
SimpleCache & operator= (const SimpleCache &c)
const Q * getptr (const Key< NDIM > &key) const
If key is present return pointer to cached value, otherwise return NULL.
const Q * getptr (Level n, Translation l) const
If key=(n,l) is present return pointer to cached value, otherwise return NULL.
const Q * getptr (Level n, const Key< NDIM > &disp) const
If key=(n,l) is present return pointer to cached value, otherwise return NULL.
void set (const Key< NDIM > &key, const Q &val)
Set value associated with key ... gives ownership of a new copy to the container.
void set (Level n, Translation l, const Q &val)
void set (Level n, const Key< NDIM > &disp, const Q &val)
Detailed Description
template<typename Q, std::size_t NDIM>
class madness::SimpleCache< Q, NDIM >
Simplified interface around hash_map to cache stuff for 1D.
This is a write once cache — subsequent writes of elements have no effect (so that pointers/references to cached data cannot be invalidated)
Constructor & Destructor Documentation
template<typename Q, std::size_t NDIM> madness::SimpleCache< Q, NDIM >::SimpleCache () inline
template<typename Q, std::size_t NDIM> madness::SimpleCache< Q, NDIM >::SimpleCache (const SimpleCache< Q, NDIM > & c) inline
Member Function Documentation
template<typename Q, std::size_t NDIM> const Q* madness::SimpleCache< Q, NDIM >::getptr (const Key< NDIM > & key) const inline
If key is present return pointer to cached value, otherwise return NULL.
Referenced by madness::Convolution1D< Q >::get_rnlp(), madness::SimpleCache< madness::SeparatedConvolutionData< Q, NDIM >, 2 *NDIM >::getptr(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Convolution1D< Q >::nonstandard(), and madness::Convolution1D< Q >::rnlij().
template<typename Q, std::size_t NDIM> const Q* madness::SimpleCache< Q, NDIM >::getptr (Level n, Translation l) const inline
If key=(n,l) is present return pointer to cached value, otherwise return NULL.
This for the convenience (backward compatibility) of 1D routines
template<typename Q, std::size_t NDIM> const Q* madness::SimpleCache< Q, NDIM >::getptr (Level n, const Key< NDIM > & disp) const inline
If key=(n,l) is present return pointer to cached value, otherwise return NULL.
This for the convenience (backward compatibility) of 1D routines
template<typename Q, std::size_t NDIM> SimpleCache& madness::SimpleCache< Q, NDIM >::operator= (const SimpleCache< Q, NDIM > & c) inline
template<typename Q, std::size_t NDIM> void madness::SimpleCache< Q, NDIM >::set (const Key< NDIM > & key, const Q & val) inline
Set value associated with key ... gives ownership of a new copy to the container.
Referenced by madness::Convolution1D< Q >::get_rnlp(), madness::Convolution1D< Q >::mod_nonstandard(), madness::Convolution1D< Q >::nonstandard(), madness::Convolution1D< Q >::rnlij(), and madness::SimpleCache< madness::SeparatedConvolutionData< Q, NDIM >, 2 *NDIM >::set().
template<typename Q, std::size_t NDIM> void madness::SimpleCache< Q, NDIM >::set (Level n, Translation l, const Q & val) inline
template<typename Q, std::size_t NDIM> void madness::SimpleCache< Q, NDIM >::set (Level n, const Key< NDIM > & disp, const Q & val) inline
The documentation for this class was generated from the following file:
simplecache.h