MADNESS: madness::LoadBalanceDeux< NDIM > Class Template Reference
madness::LoadBalanceDeux< NDIM > Class Template Reference
#include <lbdeux.h>
Classes
struct CostPerProc
Public Member Functions
LoadBalanceDeux (World &world)
template<typename T , typename costT >
void add_tree (const Function< T, NDIM > &f, const costT &costfn, bool fence=false)
Accumulates cost from a function.
void print_tree (const keyT &key=keyT(0))
Printing for the curious.
std::shared_ptr
< WorldDCPmapInterface< keyT > > load_balance (double fac=1.0, bool printstuff=false)
Actually does the partitioning of the tree.
Constructor & Destructor Documentation
template<std::size_t NDIM> madness::LoadBalanceDeux< NDIM >::LoadBalanceDeux (World & world) inline
References madness::WorldGopInterface::fence(), and madness::World::gop.
Member Function Documentation
template<std::size_t NDIM> template<typename T , typename costT > void madness::LoadBalanceDeux< NDIM >::add_tree (const Function< T, NDIM > & f, const costT & costfn, bool fence = false) inline
Accumulates cost from a function.
References madness::f.
Referenced by doit(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), initial_loadbal(), iterate(), madness::load_balance(), load_balance(), loadbal(), madness::SCF::loadbal(), main(), preloadbal(), projectL(), test(), and trotter().
template<std::size_t NDIM> std::shared_ptr< WorldDCPmapInterface<keyT> > madness::LoadBalanceDeux< NDIM >::load_balance (double fac = 1.0, bool printstuff = false) inline
Actually does the partitioning of the tree.
References madness::WorldContainer< keyT, valueT, hashfunT >::begin(), madness::WorldGopInterface::broadcast_serializable(), madness::WorldGopInterface::concat0(), madness::LoadBalanceDeux< NDIM >::CostPerProc::cost, madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, madness::WorldContainer< keyT, valueT, hashfunT >::owner(), madness::LBNodeDeux< NDIM >::partition(), madness::print(), madness::LoadBalanceDeux< NDIM >::CostPerProc::proc, madness::World::rank(), madness::WorldContainer< keyT, valueT, hashfunT >::send(), and madness::World::size().
Referenced by doit(), madness::SCF::initial_guess(), madness::SCF::initial_load_bal(), initial_loadbal(), iterate(), load_balance(), loadbal(), madness::SCF::loadbal(), main(), preloadbal(), projectL(), test(), and trotter().
template<std::size_t NDIM> void madness::LoadBalanceDeux< NDIM >::print_tree (const keyT & key = keyT(0)) inline
Printing for the curious.
References madness::WorldContainer< keyT, valueT, hashfunT >::end(), madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::Future< T >::get(), and madness::print().
The documentation for this class was generated from the following file:
lbdeux.h