MADNESS: madness::SubspaceK< T, NDIM > Class Template Reference
madness::SubspaceK< T, NDIM > Class Template Reference
MADNESS applications » Periodic Solver
The SubspaceK class is a container class holding previous orbitals and residuals.
#include <solver.h>
Public Member Functions
SubspaceK (World &world, const ElectronicStructureParams &params, const std::vector< KPoint > &kpoints)
void update_subspace (vecfuncT &awfs_new, vecfuncT &bwfs_new, const vecfuncT &awfs_old, const vecfuncT &bwfs_old)
Detailed Description
template<typename T, int NDIM>
class madness::SubspaceK< T, NDIM >
The SubspaceK class is a container class holding previous orbitals and residuals.
The Solver class uses the Krylov Accelerated Inexact Newton Solver (KAIN) accelerate the convergence a given calculation. The KAIN solver needs to store a subspace of previous orbitals and residuals. In the case is this implementation, the orbitals are store according to which k-point to which they belong.
Constructor & Destructor Documentation
template<typename T , int NDIM> madness::SubspaceK< T, NDIM >::SubspaceK (World & world, const ElectronicStructureParams & params, const std::vector< KPoint > & kpoints) inline
Member Function Documentation
template<typename T , int NDIM> void madness::SubspaceK< T, NDIM >::update_subspace (vecfuncT & awfs_new, vecfuncT & bwfs_new, const vecfuncT & awfs_old, const vecfuncT & bwfs_old) inline
References madness::abs(), c, madness::compress(), madness::gaxpy(), madness::KAIN(), m, madness::ElectronicStructureParams::maxsub, one(), madness::print(), madness::ElectronicStructureParams::spinpol, and madness::sub().
The documentation for this class was generated from the following file:
solver.h