MADNESS: madness::WorldProfile Class Reference
madness::WorldProfile Class Reference
Singleton-like class for holding profiling data and functionality.
#include <worldprofile.h>
Static Public Member Functions
static int register_id (const char *name)
Returns id for the name, registering if necessary.
static int register_id (const char *classname, const char *function)
Returns id for the name, registering if necessary.
static void clear ()
Clears all profiling information.
static WorldProfileEntry & get_entry (int id)
Returns a reference to the specified entry. Throws if id is invalid.
static void print (World &world)
Prints global profiling information. Global fence involved. Implemented in worldstuff.cc.
Detailed Description
Singleton-like class for holding profiling data and functionality.
Use the macros PROFILE_FUNC, PROFILE_BLOCK, PROFILE_MEMBER_FUNC
Member Function Documentation
void madness::WorldProfile::clear () static
Clears all profiling information.
References fred(), and madness::wall_time().
WorldProfileEntry & madness::WorldProfile::get_entry (int id) static
Returns a reference to the specified entry. Throws if id is invalid.
References MADNESS_EXCEPTION.
Referenced by madness::WorldProfileObj::pause(), print(), madness::WorldProfileObj::WorldProfileObj(), and madness::WorldProfileObj::~WorldProfileObj().
void madness::WorldProfile::print (World & world) static
Prints global profiling information. Global fence involved. Implemented in worldstuff.cc.
References madness::WorldProfileEntry::count, madness::WorldProfileEntry::exclusivecmp(), madness::WorldGopInterface::fence(), get_entry(), madness::World::gop, madness::WorldProfileEntry::inclusivecmp(), madness::World::rank(), madness::ProfileStat< T >::sum, madness::wall_time(), and madness::WorldProfileEntry::xcpu.
Referenced by main(), and madness::print_stats().
int madness::WorldProfile::register_id (const char * name) static
Returns id for the name, registering if necessary.
References fred().
int madness::WorldProfile::register_id (const char * classname, const char * function) static
Returns id for the name, registering if necessary.
References fred().
The documentation for this class was generated from the following files:
worldprofile.h
worldprofile.cc