MADNESS: BoundWF Class Reference
BoundWF Class Reference
#include <wavef.h>
Public Member Functions
BoundWF (double Z, int nn, int ll, int mm)
complexd operator() (const vector3D &x) const
You should implement this to return f(x)
Public Member Functions inherited from madness::FunctionFunctorInterface< complexd, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, complexd *fvals, int npts) const
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Additional Inherited Members
Public Types inherited from baseWF
typedef std::complex< double > complexd
typedef madness::Vector
< double, NDIM > vector3D
Public Types inherited from madness::FunctionFunctorInterface< complexd, NDIM >
typedef GenTensor< complexd > coeffT
typedef Key< NDIM > keyT
Static Public Attributes inherited from baseWF
static const complexd I
static const double PI = M_PI
Constructor & Destructor Documentation
BoundWF::BoundWF (double Z, int nn, int ll, int mm)
References madness::abs().
Member Function Documentation
complexd BoundWF::operator() (const vector3D & x) const virtual
You should implement this to return f(x)
Implements baseWF.
References madness::abs(), mpfr::exp(), MADNESS_EXCEPTION, NDIM, sqrt(), and mpfr::sum().
The documentation for this class was generated from the following files:
wavef.h
wavef.cc