MADNESS: ParserHandler< T, NDIM > Class Template Reference
ParserHandler< T, NDIM > Class Template Reference
#include <phandler.h>
Public Member Functions
ParserHandler (std::string expr)
virtual T operator() (const coordT &vals_in) const
You should implement this to return f(x)
void changeExpr (const std::string newExpr)
Public Member Functions inherited from madness::FunctionFunctorInterface< T, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, T *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, T *fvals, int npts) const
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< T, NDIM >
typedef GenTensor< T > coeffT
typedef Key< NDIM > keyT
Constructor & Destructor Documentation
template<typename T , int NDIM> ParserHandler< T, NDIM >::ParserHandler (std::string expr) inline
References mu::ParserBase::DefineVar(), mu::ParserError::GetMsg(), MADNESS_EXCEPTION, NDIM, and mu::ParserBase::SetExpr().
Member Function Documentation
template<typename T , int NDIM> void ParserHandler< T, NDIM >::changeExpr (const std::string newExpr) inline
References mu::ParserError::GetMsg(), and mu::ParserBase::SetExpr().
template<typename T , int NDIM> virtual T ParserHandler< T, NDIM >::operator() (const coordT & x) const inline virtual
You should implement this to return f(x)
Implements madness::FunctionFunctorInterface< T, NDIM >.
References mu::ParserBase::Eval(), mu::ParserError::GetMsg(), NDIM, and sqrt().
The documentation for this class was generated from the following file:
phandler.h