MADNESS: PhiK Class Reference
PhiK Class Reference
#include <wavef.h>
Public Member Functions
PhiK (madness::World &world, const double Z, const vector3D &kVec, double cutoff)
PhiK (const double Z, const vector3D &kVec, double cutoff)
complexd operator() (const vector3D &x) const
You should implement this to return f(x)
complexd f11 (const double r) const
f11(double) determines when to use the series conhyp and when to use the asymptotic aForm
complexd setAA ()
complexd setBB ()
double getk () const
Public Member Functions inherited from ScatteringWF
ScatteringWF (madness::World &world, const double Z, double cutoff)
ScatteringWF (const double Z, double cutoff)
void Init (madness::World &world)
complexd aForm (complexd ZZ) const
complexd gamma (double re, double im)
complexd gamma (complexd AA)
Public Member Functions inherited from madness::FunctionFunctorInterface< complexd, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, complexd *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, complexd *fvals, int npts) const
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Additional Inherited Members
Public Types inherited from baseWF
typedef std::complex< double > complexd
typedef madness::Vector
< double, NDIM > vector3D
Public Types inherited from madness::FunctionFunctorInterface< complexd, NDIM >
typedef GenTensor< complexd > coeffT
typedef Key< NDIM > keyT
Public Attributes inherited from ScatteringWF
CubicInterpolationTable< complexd > fit1F1
const double Z_
const double cutoff_
complexd one
double dx
double k_
complexd AA
complexd BB
complexd gammaBB
complexd expmIPIAArGammaBBmAA
complexd expPIZ_2kXgamma1pIZ_k
complexd rGammaAA
complexd AAmBB
complexd mAA
double domain
int n
Static Public Attributes inherited from baseWF
static const complexd I
static const double PI = M_PI
Constructor & Destructor Documentation
PhiK::PhiK (madness::World & world, const double Z, const vector3D & kVec, double cutoff)
PhiK::PhiK (const double Z, const vector3D & kVec, double cutoff)
Member Function Documentation
complexd PhiK::f11 (const double r) const virtual
f11(double) determines when to use the series conhyp and when to use the asymptotic aForm
Implements ScatteringWF.
References ScatteringWF::AA, ScatteringWF::aForm(), ScatteringWF::BB, conhyp(), ScatteringWF::k_, and ScatteringWF::Z_.
double PhiK::getk () const virtual
Implements ScatteringWF.
References sqrt().
complexd PhiK::operator() (const vector3D & x) const virtual
You should implement this to return f(x)
Implements baseWF.
References ScatteringWF::cutoff_, mpfr::exp(), ScatteringWF::expPIZ_2kXgamma1pIZ_k, mpfr::fabs(), ScatteringWF::fit1F1, baseWF::I, ScatteringWF::k_, and sqrt().
complexd PhiK::setAA () virtual
Implements ScatteringWF.
References baseWF::I, ScatteringWF::k_, and ScatteringWF::Z_.
complexd PhiK::setBB () virtual
Implements ScatteringWF.
The documentation for this class was generated from the following files:
wavef.h
wavef.cc