MADNESS: madness::tr1::shptr::detail::weak_count Class Reference
madness::tr1::shptr::detail::weak_count Class Reference
#include <shared_ptr_bits.h>
Public Member Functions
weak_count ()
weak_count (shared_count const &r)
weak_count (weak_count const &r)
~weak_count ()
weak_count & operator= (shared_count const &r)
weak_count & operator= (weak_count const &r)
void swap (weak_count &r)
long use_count () const
bool empty () const
Friends
class shared_count
bool operator== (weak_count const &a, weak_count const &b)
bool operator< (weak_count const &a, weak_count const &b)
Constructor & Destructor Documentation
madness::tr1::shptr::detail::weak_count::weak_count () inline
madness::tr1::shptr::detail::weak_count::weak_count (shared_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::weak_add_ref().
madness::tr1::shptr::detail::weak_count::weak_count (weak_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::weak_add_ref().
madness::tr1::shptr::detail::weak_count::~weak_count () inline
References madness::tr1::shptr::detail::sp_counted_base::weak_release().
Member Function Documentation
bool madness::tr1::shptr::detail::weak_count::empty () const inline
weak_count& madness::tr1::shptr::detail::weak_count::operator= (shared_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::weak_add_ref(), and madness::tr1::shptr::detail::sp_counted_base::weak_release().
weak_count& madness::tr1::shptr::detail::weak_count::operator= (weak_count const & r) inline
References madness::tr1::shptr::detail::sp_counted_base::weak_add_ref(), and madness::tr1::shptr::detail::sp_counted_base::weak_release().
void madness::tr1::shptr::detail::weak_count::swap (weak_count & r) inline
Referenced by madness::tr1::shptr::weak_ptr< T >::swap().
long madness::tr1::shptr::detail::weak_count::use_count () const inline
References madness::tr1::shptr::detail::sp_counted_base::use_count().
Referenced by madness::tr1::shptr::weak_ptr< T >::expired(), and madness::tr1::shptr::weak_ptr< T >::use_count().
Friends And Related Function Documentation
bool operator< (weak_count const & a, weak_count const & b) friend
bool operator== (weak_count const & a, weak_count const & b) friend
friend class shared_count friend
The documentation for this class was generated from the following file:
shared_ptr_bits.h