MADNESS: madness::DistributedMatrixDistribution Class Reference
madness::DistributedMatrixDistribution Class Reference
#include <distributed_matrix.h>
Public Member Functions
DistributedMatrixDistribution ()
Default constructor makes an invalid distribution.
void clear ()
Resets state to same as default constructor.
bool operator== (const DistributedMatrixDistribution &d) const
int64_t coldim () const
Returns the column dimension of the matrix ... i.e., n for A(n,m)
int64_t rowdim () const
Returns the row dimension of the matrix ... i.e., m for A(n,m)
int64_t coltile () const
Returns the column tile size.
int64_t rowtile () const
Returns the row tile size.
int64_t process_coldim () const
Returns the no. of processors in the column dimension.
int64_t process_rowdim () const
Returns the no. of processors in the row dimension.
int64_t local_size () const
Returns the total no. of elements stored on this processor.
int64_t local_coldim () const
Returns the no. of column elements stored on this processor.
int64_t local_rowdim () const
Returns the no. of row elements stored on this processor.
void local_colrange (int64_t &ilow, int64_t &ihigh) const
Returns the inclusive range of column indices on this processor.
void local_rowrange (int64_t &jlow, int64_t &jhigh) const
Returns the inclusive range of row indices on this processor.
int64_t local_ilow () const
Returns the first column index on this processor (0 if no data present)
int64_t local_ihigh () const
Returns the last column index on this processor (-1 if no data present)
int64_t local_jlow () const
Returns the first row index on this processor (0 if no data present)
int64_t local_jhigh () const
Returns the last row index on this processor (0 if no data present)
void get_range (int p, int64_t &ilow, int64_t &ihigh, int64_t &jlow, int64_t &jhigh) const
Returns the inclusive ranges of column and row indicies on processor p.
void get_colrange (int p, int64_t &ilow, int64_t &ihigh) const
Returns the inclusive range of column indices on processor p.
void get_rowrange (int p, int64_t &jlow, int64_t &jhigh) const
Returns the inclusive range of row indices on processor p.
World & get_world () const
Returns the associated world.
bool is_column_distributed () const
Returns true if the matrix is column distributed (i.e., row dimension not distributed)
bool is_row_distributed () const
Returns true if the matrix is row distributed (i.e., column dimension not distributed)
const
DistributedMatrixDistribution & distribution () const
Returns the distribution (aka *this)
ProcessID owner (int64_t i, int64_t j) const
Returns the number of the process that owns element (i,j)
virtual ~DistributedMatrixDistribution ()
Protected Member Functions
DistributedMatrixDistribution (World &world, int64_t n, int64_t m, int64_t coltile, int64_t rowtile)
Constructs distribution and size info for a matrix (for use by factory functions only)
Protected Attributes
World * pworld
int64_t P
ProcessID rank
int64_t n
int64_t m
int64_t tilen
int64_t tilem
int64_t Pcoldim
int64_t Prowdim
int64_t Pcol
int64_t Prow
int64_t ilo
int64_t ihi
int64_t jlo
int64_t jhi
int64_t idim
int64_t jdim
Friends
template<typename T >
class DistributedMatrix
DistributedMatrixDistribution column_distributed_matrix_distribution (World &world, int64_t n, int64_t m, int64_t coltile)
Generates distribution for an (n,m) matrix distributed by columns (row dimension is not distributed)
DistributedMatrixDistribution row_distributed_matrix_distribution (World &world, int64_t n, int64_t m, int64_t rowtile)
Generates an (n,m) matrix distribution distributed by rows (column dimension is not distributed)
Constructor & Destructor Documentation
madness::DistributedMatrixDistribution::DistributedMatrixDistribution (World & world, int64_t n, int64_t m, int64_t coltile, int64_t rowtile) inline protected
Constructs distribution and size info for a matrix (for use by factory functions only)
This routine is dumb and just copies the given arguments, hence it can easily make an invalid matrix. The smarts are in the factory functions, hence this constructor is not for general use.
The matrix is tiled over a grid of processes as specified by the tile sizes.
Parameters
[in] World The world
[in] n The matrix column dimension
[in] m The matrix row dimension
[in] coltile Tile size for the columns
[in] rowtile Tile size for the rows
madness::DistributedMatrixDistribution::DistributedMatrixDistribution () inline
Default constructor makes an invalid distribution.
virtual madness::DistributedMatrixDistribution::~DistributedMatrixDistribution () inline virtual
Member Function Documentation
void madness::DistributedMatrixDistribution::clear () inline
Resets state to same as default constructor.
Referenced by madness::DistributedMatrix< double >::clear().
int64_t madness::DistributedMatrixDistribution::coldim () const inline
Returns the column dimension of the matrix ... i.e., n for A(n,m)
Returns
Column dimension of the matrix ... i.e., n for A(n,m)
References n.
int64_t madness::DistributedMatrixDistribution::coltile () const inline
Returns the column tile size.
Returns
Column tile size
References tilen.
Referenced by owner().
const DistributedMatrixDistribution& madness::DistributedMatrixDistribution::distribution () const inline
Returns the distribution (aka *this)
Referenced by madness::SCF::kinetic_energy_matrix().
void madness::DistributedMatrixDistribution::get_colrange (int p, int64_t & ilow, int64_t & ihigh) const inline
Returns the inclusive range of column indices on processor p.
If is no data on processor p it returns ilow=0 and ihigh=-1
Parameters
[in] p The processor p of interest
[out] ilow The first column index on the processor
[out] ihigh The last column index on the processor (-1 if none)
References get_range().
void madness::DistributedMatrixDistribution::get_range (int p, int64_t & ilow, int64_t & ihigh, int64_t & jlow, int64_t & jhigh) const inline
Returns the inclusive ranges of column and row indicies on processor p.
If is no data on processor p it returns ilow=jlow=0 and ihigh=jhigh=-1
Parameters
[in] p The processor p of interest
[out] ilow The first column index on the processor
[out] ihigh The last column index on the processor (-1 if none)
[out] jlow The first row index on the processor
[out] jhigh The last row index on the processor (-1 if none)
References mpfr::min(), pi, process_coldim(), process_rowdim(), Prowdim, tilem, and tilen.
Referenced by get_colrange(), and get_rowrange().
void madness::DistributedMatrixDistribution::get_rowrange (int p, int64_t & jlow, int64_t & jhigh) const inline
Returns the inclusive range of row indices on processor p.
If is no data on processor p it returns jlow=0 and jhigh=-1
Parameters
[in] p The processor p of interest
[out] jlow The first row index on the processor
[out] jhigh The last row index on the processor (-1 if none)
References get_range().
World& madness::DistributedMatrixDistribution::get_world () const inline
Returns the associated world.
Returns
The world
References pworld.
bool madness::DistributedMatrixDistribution::is_column_distributed () const inline
Returns true if the matrix is column distributed (i.e., row dimension not distributed)
Returns
True if the matrix is column distributed (i.e., row dimension not distributed)
References process_rowdim().
bool madness::DistributedMatrixDistribution::is_row_distributed () const inline
Returns true if the matrix is row distributed (i.e., column dimension not distributed)
Returns
True if the matrix is row distributed (i.e., column dimension not distributed)
References process_coldim().
int64_t madness::DistributedMatrixDistribution::local_coldim () const inline
Returns the no. of column elements stored on this processor.
Returns
No. of column elements stored on this processor (may be zero)
References idim.
void madness::DistributedMatrixDistribution::local_colrange (int64_t & ilow, int64_t & ihigh) const inline
Returns the inclusive range of column indices on this processor.
If there is no data on this processor it returns ilow=0 and ihigh=-1
Parameters
[out] ilow First column index on this processor (0 if no data)
[out] ihigh Last column index on this processor (-1 if no data)
References ihi, and ilo.
int64_t madness::DistributedMatrixDistribution::local_ihigh () const inline
Returns the last column index on this processor (-1 if no data present)
References ihi.
int64_t madness::DistributedMatrixDistribution::local_ilow () const inline
Returns the first column index on this processor (0 if no data present)
References ilo.
int64_t madness::DistributedMatrixDistribution::local_jhigh () const inline
Returns the last row index on this processor (0 if no data present)
References jhi.
int64_t madness::DistributedMatrixDistribution::local_jlow () const inline
Returns the first row index on this processor (0 if no data present)
References jlo.
int64_t madness::DistributedMatrixDistribution::local_rowdim () const inline
Returns the no. of row elements stored on this processor.
Returns
No. of row elements stored on this processor
References jdim.
void madness::DistributedMatrixDistribution::local_rowrange (int64_t & jlow, int64_t & jhigh) const inline
Returns the inclusive range of row indices on this processor.
If there is no data on this processor it returns jlow=0 and jhigh=-1
Parameters
[out] jlow First row index on this processor (0 if no data)
[out] jhigh Last row index on this processor (-1 if no data)
References jhi, and jlo.
int64_t madness::DistributedMatrixDistribution::local_size () const inline
Returns the total no. of elements stored on this processor.
Returns
Total no. of elements stored on this processor
References jdim.
bool madness::DistributedMatrixDistribution::operator== (const DistributedMatrixDistribution & d) const inline
References idim, ihi, ilo, jdim, jhi, jlo, m, n, P, Pcol, Pcoldim, Prow, Prowdim, pworld, rank, tilem, and tilen.
Referenced by madness::DistributedMatrix< double >::has_same_dimension_and_distribution().
ProcessID madness::DistributedMatrixDistribution::owner (int64_t i, int64_t j) const inline
Returns the number of the process that owns element (i,j)
References coltile(), process_rowdim(), and rowtile().
int64_t madness::DistributedMatrixDistribution::process_coldim () const inline
Returns the no. of processors in the column dimension.
Returns
No. of processors in the column dimension
References Pcoldim.
Referenced by get_range(), and is_row_distributed().
int64_t madness::DistributedMatrixDistribution::process_rowdim () const inline
Returns the no. of processors in the row dimension.
Returns
No. of processors in the rown dimension
References Prowdim.
Referenced by get_range(), is_column_distributed(), and owner().
int64_t madness::DistributedMatrixDistribution::rowdim () const inline
Returns the row dimension of the matrix ... i.e., m for A(n,m)
Returns
Row dimension of the matrix ... i.e., m for A(n,m)
References m.
int64_t madness::DistributedMatrixDistribution::rowtile () const inline
Returns the row tile size.
Returns
Row tile size
References tilem.
Referenced by owner().
Friends And Related Function Documentation
DistributedMatrixDistribution column_distributed_matrix_distribution (World & world, int64_t n, int64_t m, int64_t coltile) friend
Generates distribution for an (n,m) matrix distributed by columns (row dimension is not distributed)
Quietly forces an even column tile size for ease of use in the systolic matrix algorithms
Parameters
[in] World The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] coltile Tile size for columns forced to be even (default is to use all processes)
Returns
An object encoding the dimension and distribution information
template<typename T > friend class DistributedMatrix friend
DistributedMatrixDistribution row_distributed_matrix_distribution (World & world, int64_t n, int64_t m, int64_t rowtile) friend
Generates an (n,m) matrix distribution distributed by rows (column dimension is not distributed)
Parameters
[in] World The world
[in] n The column (first) dimension
[in] m The row (second) dimension
[in] rowtile Tile size for row (default is to use all processes)
Returns
An object encoding the dimension and distribution information
Member Data Documentation
int64_t madness::DistributedMatrixDistribution::idim protected
Referenced by local_coldim(), and operator==().
int64_t madness::DistributedMatrixDistribution::ihi protected
Referenced by local_colrange(), local_ihigh(), and operator==().
int64_t madness::DistributedMatrixDistribution::ilo protected
Referenced by local_colrange(), local_ilow(), and operator==().
int64_t madness::DistributedMatrixDistribution::jdim protected
Referenced by local_rowdim(), local_size(), and operator==().
int64_t madness::DistributedMatrixDistribution::jhi protected
Referenced by local_jhigh(), local_rowrange(), and operator==().
int64_t madness::DistributedMatrixDistribution::jlo protected
Referenced by local_jlow(), local_rowrange(), and operator==().
int64_t madness::DistributedMatrixDistribution::m protected
Referenced by operator==(), and rowdim().
int64_t madness::DistributedMatrixDistribution::n protected
Referenced by coldim(), and operator==().
int64_t madness::DistributedMatrixDistribution::P protected
Referenced by operator==().
int64_t madness::DistributedMatrixDistribution::Pcol protected
Referenced by operator==().
int64_t madness::DistributedMatrixDistribution::Pcoldim protected
Referenced by operator==(), and process_coldim().
int64_t madness::DistributedMatrixDistribution::Prow protected
Referenced by operator==().
int64_t madness::DistributedMatrixDistribution::Prowdim protected
Referenced by get_range(), operator==(), and process_rowdim().
World* madness::DistributedMatrixDistribution::pworld protected
Referenced by get_world(), and operator==().
ProcessID madness::DistributedMatrixDistribution::rank protected
Referenced by operator==().
int64_t madness::DistributedMatrixDistribution::tilem protected
Referenced by get_range(), operator==(), and rowtile().
int64_t madness::DistributedMatrixDistribution::tilen protected
Referenced by coltile(), get_range(), and operator==().
The documentation for this class was generated from the following file:
distributed_matrix.h