MADNESS: AtomicBasis Class Reference
AtomicBasis Class Reference
Represents multiple shells of contracted gaussians on a single center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasis ()
AtomicBasis (const std::vector< ContractedGaussianShell > &g)
void set_guess_info (const Tensor< double > &dmat, const Tensor< double > &avec, const Tensor< double > &bvec)
int nbf () const
Returns the number of basis functions on the center.
int nshell () const
Returns the number of shells on the center.
const std::vector
< ContractedGaussianShell > & get_shells () const
Returns a const reference to the shells.
double * eval (double x, double y, double z, double *bf) const
Evaluates the basis functions at point x, y, z relative to atomic center.
double eval_guess_density (double x, double y, double z) const
Evaluates the guess atomic density at point x, y, z relative to atomic center.
const ContractedGaussianShell & get_shell_from_basis_function (int ibf, int &ibf_in_shell) const
Return shell that contains basis function ibf and also return index of function in the shell.
bool has_guess_info () const
const Tensor< double > & get_dmat () const
const Tensor< double > & get_avec () const
const Tensor< double > & get_bvec () const
template<typename Archive >
void serialize (Archive &ar)
AtomicBasis ()
AtomicBasis (const std::vector< ContractedGaussianShell > &g)
void set_guess_info (const Tensor< double > &dmat, const Tensor< double > &avec, const Tensor< double > &bvec)
int nbf () const
Returns the number of basis functions on the center.
int nshell () const
Returns the number of shells on the center.
const std::vector
< ContractedGaussianShell > & get_shells () const
Returns a const reference to the shells.
double * eval (double x, double y, double z, double *bf) const
Evaluates the basis functions at point x, y, z relative to atomic center.
double eval_guess_density (double x, double y, double z) const
Evaluates the guess atomic density at point x, y, z relative to atomic center.
const ContractedGaussianShell & get_shell_from_basis_function (int ibf, int &ibf_in_shell) const
Return shell that contains basis function ibf and also return index of function in the shell.
bool has_guess_info () const
const Tensor< double > & get_dmat () const
const Tensor< double > & get_avec () const
const Tensor< double > & get_bvec () const
template<typename Archive >
void serialize (Archive &ar)
AtomicBasis ()
AtomicBasis (const std::vector< ContractedGaussianShell > &g)
void set_guess_info (const Tensor< double > &dmat, const Tensor< double > &avec, const Tensor< double > &bvec)
int nbf () const
Returns the number of basis functions on the center.
int nshell () const
Returns the number of shells on the center.
const std::vector
< ContractedGaussianShell > & get_shells () const
Returns a const reference to the shells.
double * eval (double x, double y, double z, double *bf) const
Evaluates the basis functions at point x, y, z relative to atomic center.
double eval_guess_density (double x, double y, double z) const
Evaluates the guess atomic density at point x, y, z relative to atomic center.
const ContractedGaussianShell & get_shell_from_basis_function (int ibf, int &ibf_in_shell) const
Return shell that contains basis function ibf and also return index of function in the shell.
bool has_guess_info () const
const Tensor< double > & get_dmat () const
const Tensor< double > & get_avec () const
const Tensor< double > & get_bvec () const
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
Represents multiple shells of contracted gaussians on a single center.
Constructor & Destructor Documentation
AtomicBasis::AtomicBasis () inline
AtomicBasis::AtomicBasis (const std::vector< ContractedGaussianShell > & g) inline
References max.
AtomicBasis::AtomicBasis () inline
AtomicBasis::AtomicBasis (const std::vector< ContractedGaussianShell > & g) inline
References max.
AtomicBasis::AtomicBasis () inline
AtomicBasis::AtomicBasis (const std::vector< ContractedGaussianShell > & g) inline
References max.
Member Function Documentation
double* AtomicBasis::eval (double x, double y, double z, double * bf) const inline
Evaluates the basis functions at point x, y, z relative to atomic center.
The array bf[] must be large enough to hold nbf() values.
Returned is the incremented pointer.
double* AtomicBasis::eval (double x, double y, double z, double * bf) const inline
Evaluates the basis functions at point x, y, z relative to atomic center.
The array bf[] must be large enough to hold nbf() values.
Returned is the incremented pointer.
double* AtomicBasis::eval (double x, double y, double z, double * bf) const inline
Evaluates the basis functions at point x, y, z relative to atomic center.
The array bf[] must be large enough to hold nbf() values.
Returned is the incremented pointer.
double AtomicBasis::eval_guess_density (double x, double y, double z) const inline
Evaluates the guess atomic density at point x, y, z relative to atomic center.
References madness::AtomicBasis::eval(), madness::AtomicBasis::has_guess_info(), and mpfr::sum().
double AtomicBasis::eval_guess_density (double x, double y, double z) const inline
Evaluates the guess atomic density at point x, y, z relative to atomic center.
References madness::AtomicBasis::eval(), madness::AtomicBasis::has_guess_info(), and mpfr::sum().
double AtomicBasis::eval_guess_density (double x, double y, double z) const inline
Evaluates the guess atomic density at point x, y, z relative to atomic center.
References madness::AtomicBasis::eval(), madness::AtomicBasis::has_guess_info(), and mpfr::sum().
const Tensor<double>& AtomicBasis::get_avec () const inline
const Tensor<double>& AtomicBasis::get_avec () const inline
const Tensor<double>& AtomicBasis::get_avec () const inline
const Tensor<double>& AtomicBasis::get_bvec () const inline
const Tensor<double>& AtomicBasis::get_bvec () const inline
const Tensor<double>& AtomicBasis::get_bvec () const inline
const Tensor<double>& AtomicBasis::get_dmat () const inline
const Tensor<double>& AtomicBasis::get_dmat () const inline
Referenced by operator<<().
const Tensor<double>& AtomicBasis::get_dmat () const inline
const ContractedGaussianShell& AtomicBasis::get_shell_from_basis_function (int ibf, int & ibf_in_shell) const inline
Return shell that contains basis function ibf and also return index of function in the shell.
References MADNESS_EXCEPTION, madness::ContractedGaussianShell::nbf(), and madness::AtomicBasis::nbf().
const ContractedGaussianShell& AtomicBasis::get_shell_from_basis_function (int ibf, int & ibf_in_shell) const inline
Return shell that contains basis function ibf and also return index of function in the shell.
References MADNESS_EXCEPTION, madness::ContractedGaussianShell::nbf(), and madness::AtomicBasis::nbf().
const ContractedGaussianShell& AtomicBasis::get_shell_from_basis_function (int ibf, int & ibf_in_shell) const inline
Return shell that contains basis function ibf and also return index of function in the shell.
References MADNESS_EXCEPTION, madness::ContractedGaussianShell::nbf(), and madness::AtomicBasis::nbf().
const std::vector<ContractedGaussianShell>& AtomicBasis::get_shells () const inline
Returns a const reference to the shells.
const std::vector<ContractedGaussianShell>& AtomicBasis::get_shells () const inline
Returns a const reference to the shells.
Referenced by operator<<().
const std::vector<ContractedGaussianShell>& AtomicBasis::get_shells () const inline
Returns a const reference to the shells.
bool AtomicBasis::has_guess_info () const inline
bool AtomicBasis::has_guess_info () const inline
Referenced by operator<<().
bool AtomicBasis::has_guess_info () const inline
int AtomicBasis::nbf () const inline
Returns the number of basis functions on the center.
int AtomicBasis::nbf () const inline
Returns the number of basis functions on the center.
int AtomicBasis::nbf () const inline
Returns the number of basis functions on the center.
int AtomicBasis::nshell () const inline
Returns the number of shells on the center.
int AtomicBasis::nshell () const inline
Returns the number of shells on the center.
Referenced by operator<<().
int AtomicBasis::nshell () const inline
Returns the number of shells on the center.
template<typename Archive > void AtomicBasis::serialize (Archive & ar) inline
template<typename Archive > void AtomicBasis::serialize (Archive & ar) inline
template<typename Archive > void AtomicBasis::serialize (Archive & ar) inline
void AtomicBasis::set_guess_info (const Tensor< double > & dmat, const Tensor< double > & avec, const Tensor< double > & bvec) inline
References madness::copy().
void AtomicBasis::set_guess_info (const Tensor< double > & dmat, const Tensor< double > & avec, const Tensor< double > & bvec) inline
References madness::copy().
void AtomicBasis::set_guess_info (const Tensor< double > & dmat, const Tensor< double > & avec, const Tensor< double > & bvec) inline
References madness::copy().
The documentation for this class was generated from the following file:
DFcode/molecularbasis.h