MADNESS: madness::Group Class Reference
madness::Group Class Reference
A collection of processes.
#include <group.h>
Public Member Functions
Group ()
Default constructor.
Group (const Group &other)
Copy constructor.
template<typename A >
Group (World &world, const A &group, const DistributedID &did)
Create a new group.
template<typename A >
Group (World &world, const A &group, const std::size_t tag)
Create a new group.
template<typename A >
Group (World &world, const A &group, const uniqueidT &uid, const std::size_t tag)
Create a new group.
Group & operator= (const Group &other)
Copy assignment operator.
void local_update () const
Update local usage count.
void remote_update () const
Update remote usage count.
bool empty () const
Quary empty group.
const DistributedID & id () const
Group id accessor.
World & get_world () const
Parent world accessor.
ProcessID rank () const
Group rank accessor.
ProcessID rank (const ProcessID world_rank) const
Map world rank to group rank.
ProcessID size () const
Group size accessor.
ProcessID world_rank (const ProcessID group_rank) const
Map group rank to world rank.
void make_tree (const ProcessID group_root, ProcessID &parent, ProcessID &child1, ProcessID &child2) const
Compute the binary tree parents and children.
template<typename Archive >
void serialize (const Archive &)
Static Public Member Functions
static madness::Future< Group > get_group (const DistributedID &did)
Get group from the registry.
Detailed Description
A collection of processes.
Group is a light weight object that can be used to specify a set of processes that will participate in Gop collective operations. The advantage of Group over MPI (or SafeMPI) groups is that it eliminates the need to construct new communicator and the associated barrier.
Note
This is NOT an MPI or SafeMPI group.
Constructor & Destructor Documentation
madness::Group::Group () inline
Default constructor.
Create an empty group
madness::Group::Group (const Group & other) inline
Copy constructor.
Parameters
other The group to be copied
Note
Copy is shallow.
template<typename A > madness::Group::Group (World & world, const A & group, const DistributedID & did) inline
Create a new group.
Template Parameters
A An array type
Parameters
world The parent world for this group
group An array with a list of process to be included in the
did The distributed id associated with this group
Note
All processes in the group list must be included in the parent world.
template<typename A > madness::Group::Group (World & world, const A & group, const std::size_t tag) inline
Create a new group.
Template Parameters
A An array type
Parameters
world The parent world for this group
group An array with a list of process to be included in the
tag The tag associated with this group group.
Note
All processes in the group list must be included in the parent world.
template<typename A > madness::Group::Group (World & world, const A & group, const uniqueidT & uid, const std::size_t tag) inline
Create a new group.
Template Parameters
A An array type
Parameters
world The parent world for this group
group An array with a list of process to be included in the
uid The unique id (used by WorldObject) associated with this group
tag The tag associated with this group group.
Note
All processes in the group list must be included in the parent world.
Member Function Documentation
bool madness::Group::empty () const inline
Quary empty group.
Returns
true when this group is empty
Referenced by madness::WorldGopInterface::all_reduce(), madness::WorldGopInterface::bcast(), madness::WorldGopInterface::lazy_sync(), and madness::WorldGopInterface::reduce().
Future< Group > madness::Group::get_group (const DistributedID & did) static
Get group from the registry.
Get a registered group.
This function is used to acquire the group in an active message handler.
Parameters
did The id associated with the group
Returns
A future to the group
World& madness::Group::get_world () const inline
Parent world accessor.
Returns
A reference to the parent world of this group
Referenced by madness::WorldGopInterface::all_reduce(), madness::WorldGopInterface::bcast(), madness::WorldGopInterface::lazy_sync(), and madness::WorldGopInterface::reduce().
const DistributedID& madness::Group::id () const inline
Group id accessor.
Returns
A const reference to the group id
void madness::Group::local_update () const inline
Update local usage count.
Calling this function indicates that this group will be used by a task function that was spawned by a remote process. For each call to this function, remote_update must be called exactly once.
Note
Users should not call this function. Normally, WorldGopInterface will call this function as needed. Users may call this function if a Group is used in user provided collective operations.
void madness::Group::make_tree (const ProcessID group_root, ProcessID & parent, ProcessID & child1, ProcessID & child2) const inline
Compute the binary tree parents and children.
Parameters
[in] root The head node of the binary tree in the group
[out] parent The parent node of the binary tree
[out] child1 The left child node of the binary tree
[out] child2 The right child node of the binary tree
Note
Output ranks are in the parent world.
Referenced by madness::WorldGopInterface::all_reduce(), madness::WorldGopInterface::lazy_sync(), and madness::WorldGopInterface::reduce().
Group& madness::Group::operator= (const Group & other) inline
Copy assignment operator.
Parameters
other The group to be copied
Note
Copy is shallow.
ProcessID madness::Group::rank () const inline
Group rank accessor.
Returns
The rank of this process in the group
Referenced by madness::WorldGopInterface::all_reduce(), and madness::WorldGopInterface::bcast().
ProcessID madness::Group::rank (const ProcessID world_rank) const inline
Map world rank to group rank.
Parameters
world_rank The world rank to be mapped
Returns
The rank of world_rank process in the group
void madness::Group::remote_update () const inline
Update remote usage count.
Calling this function indicates that this group has been used by a task function that was spawned by a remote process. For each call to this function, remote_update must be called exactly once.
Note
Users should not call this function. Normally, WorldGopInterface will call this function as needed. Users may call this function if a Group is used in user provided collective operations.
template<typename Archive > void madness::Group::serialize (const Archive &) inline
ProcessID madness::Group::size () const inline
Group size accessor.
Returns
The number of processes in the group
Referenced by madness::WorldGopInterface::all_reduce(), madness::WorldGopInterface::bcast(), madness::WorldGopInterface::lazy_sync(), and madness::WorldGopInterface::reduce().
ProcessID madness::Group::world_rank (const ProcessID group_rank) const inline
Map group rank to world rank.
Parameters
group_rank The group rank to be mapped to a world rank
Returns
The parent world rank of group_rank.
The documentation for this class was generated from the following files:
group.h
group.cc