MADNESS: PointGroup Class Reference
PointGroup Class Reference
#include <pointgroup.h>
Public Types
typedef madness::Vector
< double, 3 > coordT
typedef madness::Vector
< double, 3 > coordT
typedef madness::Vector
< double, 3 > coordT
Public Member Functions
PointGroup (const std::string name)
Constructs point group by name (D2h and subgroups only)
PointGroup (const PointGroup &other)
Copy constructor.
PointGroup & operator= (const PointGroup &other)
Assignment.
virtual ~PointGroup ()
Destructor.
int irmul (int ir1, int ir2) const
Returns irreducible representation corresponding to product.
coordT apply (int op, const coordT &r) const
Applies group operator number op (0,1,...,order-1) to point.
int cart_ir (int axis) const
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
coordT ircell () const
Returns irreducible cell.
const std::string & get_name () const
int get_order () const
const std::string & get_ir_name (int ir) const
const std::string & get_op_name (int op) const
int ctable (int ir, int op) const
PointGroup (const std::string name)
Constructs point group by name (D2h and subgroups only)
PointGroup (const PointGroup &other)
Copy constructor.
PointGroup & operator= (const PointGroup &other)
Assignment.
virtual ~PointGroup ()
Destructor.
int irmul (int ir1, int ir2) const
Returns irreducible representation corresponding to product.
coordT apply (int op, const coordT &r) const
Applies group operator number op (0,1,...,order-1) to point.
int cart_ir (int axis) const
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
coordT ircell () const
Returns irreducible cell.
const std::string & get_name () const
int get_order () const
const std::string & get_ir_name (int ir) const
const std::string & get_op_name (int op) const
int ctable (int ir, int op) const
PointGroup (const std::string name)
Constructs point group by name (D2h and subgroups only)
PointGroup (const PointGroup &other)
Copy constructor.
PointGroup & operator= (const PointGroup &other)
Assignment.
virtual ~PointGroup ()
Destructor.
int irmul (int ir1, int ir2) const
Returns irreducible representation corresponding to product.
coordT apply (int op, const coordT &r) const
Applies group operator number op (0,1,...,order-1) to point.
int cart_ir (int axis) const
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
coordT ircell () const
Returns irreducible cell.
const std::string & get_name () const
int get_order () const
const std::string & get_ir_name (int ir) const
const std::string & get_op_name (int op) const
int ctable (int ir, int op) const
Static Public Member Functions
static coordT apply (const std::string &op, const coordT &r)
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
static bool test ()
static coordT apply (const std::string &op, const coordT &r)
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
static bool test ()
static coordT apply (const std::string &op, const coordT &r)
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
static bool test ()
Member Typedef Documentation
typedef madness::Vector<double,3> PointGroup::coordT
typedef madness::Vector<double,3> PointGroup::coordT
typedef madness::Vector<double,3> PointGroup::coordT
Constructor & Destructor Documentation
PointGroup::PointGroup (const std::string name) inline
Constructs point group by name (D2h and subgroups only)
Referenced by test().
PointGroup::PointGroup (const PointGroup & other) inline
Copy constructor.
virtual PointGroup::~PointGroup () inline virtual
Destructor.
PointGroup::PointGroup (const std::string name) inline
Constructs point group by name (D2h and subgroups only)
PointGroup::PointGroup (const PointGroup & other) inline
Copy constructor.
virtual PointGroup::~PointGroup () inline virtual
Destructor.
PointGroup::PointGroup (const std::string name) inline
Constructs point group by name (D2h and subgroups only)
PointGroup::PointGroup (const PointGroup & other) inline
Copy constructor.
virtual PointGroup::~PointGroup () inline virtual
Destructor.
Member Function Documentation
coordT PointGroup::apply (int op, const coordT & r) const inline
Applies group operator number op (0,1,...,order-1) to point.
Referenced by apply(), cart_ir(), and ircell().
coordT PointGroup::apply (int op, const coordT & r) const inline
Applies group operator number op (0,1,...,order-1) to point.
References apply().
coordT PointGroup::apply (int op, const coordT & r) const inline
Applies group operator number op (0,1,...,order-1) to point.
References apply().
static coordT PointGroup::apply (const std::string & op, const coordT & r) inline static
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
static coordT PointGroup::apply (const std::string & op, const coordT & r) inline static
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
static coordT PointGroup::apply (const std::string & op, const coordT & r) inline static
Applies named operator (e, c2z, c2y, c2x, sxy, sxz, syz, i) to point.
int PointGroup::cart_ir (int axis) const inline
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
References apply(), op(), and mpfr::sum().
int PointGroup::cart_ir (int axis) const inline
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
References apply(), op(), and mpfr::sum().
Referenced by operator<<().
int PointGroup::cart_ir (int axis) const inline
Returns the irrep of the Cartesian axis (0, 1, 2 = x, y, z)
References apply(), op(), and mpfr::sum().
int PointGroup::ctable (int ir, int op) const inline
References op().
int PointGroup::ctable (int ir, int op) const inline
References op().
int PointGroup::ctable (int ir, int op) const inline
References op().
Referenced by operator<<().
const std::string& PointGroup::get_ir_name (int ir) const inline
const std::string& PointGroup::get_ir_name (int ir) const inline
Referenced by operator<<().
const std::string& PointGroup::get_ir_name (int ir) const inline
const std::string& PointGroup::get_name () const inline
const std::string& PointGroup::get_name () const inline
Referenced by operator<<().
const std::string& PointGroup::get_name () const inline
const std::string& PointGroup::get_op_name (int op) const inline
References op().
const std::string& PointGroup::get_op_name (int op) const inline
References op().
Referenced by operator<<().
const std::string& PointGroup::get_op_name (int op) const inline
References op().
int PointGroup::get_order () const inline
int PointGroup::get_order () const inline
Referenced by operator<<().
int PointGroup::get_order () const inline
coordT PointGroup::ircell () const inline
Returns irreducible cell.
The irreducible cell is defined by considering the cube -1<x<1, -1<y<1, -1<z<1. Use symmetry operations to map negative coordinates onto positive coordinates if possible. This leads to the unique cell for D2h being the cube 0<x<1, 0<y<1, 0<z<1.
If a coordinate in the cell is positive, it means that the irreducible cell has positive values of that coordinate.
References apply(), mpfr::min(), and op().
Referenced by operator<<().
coordT PointGroup::ircell () const inline
Returns irreducible cell.
The irreducible cell is defined by considering the cube -1<x<1, -1<y<1, -1<z<1. Use symmetry operations to map negative coordinates onto positive coordinates if possible. This leads to the unique cell for D2h being the cube 0<x<1, 0<y<1, 0<z<1.
If a coordinate in the cell is positive, it means that the irreducible cell has positive values of that coordinate.
References apply(), mpfr::min(), and op().
coordT PointGroup::ircell () const inline
Returns irreducible cell.
The irreducible cell is defined by considering the cube -1<x<1, -1<y<1, -1<z<1. Use symmetry operations to map negative coordinates onto positive coordinates if possible. This leads to the unique cell for D2h being the cube 0<x<1, 0<y<1, 0<z<1.
If a coordinate in the cell is positive, it means that the irreducible cell has positive values of that coordinate.
References apply(), mpfr::min(), and op().
int PointGroup::irmul (int ir1, int ir2) const inline
Returns irreducible representation corresponding to product.
int PointGroup::irmul (int ir1, int ir2) const inline
Returns irreducible representation corresponding to product.
int PointGroup::irmul (int ir1, int ir2) const inline
Returns irreducible representation corresponding to product.
PointGroup& PointGroup::operator= (const PointGroup & other) inline
Assignment.
References op().
PointGroup& PointGroup::operator= (const PointGroup & other) inline
Assignment.
References op().
PointGroup& PointGroup::operator= (const PointGroup & other) inline
Assignment.
References op().
static bool PointGroup::test () inline static
References PointGroup().
static bool PointGroup::test () inline static
References PointGroup().
static bool PointGroup::test () inline static
References PointGroup().
The documentation for this class was generated from the following file:
DFcode/pointgroup.h