MADNESS: madness::WorldProfileObj Class Reference
madness::WorldProfileObj Class Reference
#include <worldprofile.h>
Public Member Functions
WorldProfileObj (int id)
void pause (double now)
Pause profiling while we are not executing ... accumulate time in self.
void resume (double now)
Resume profiling.
~WorldProfileObj ()
Constructor & Destructor Documentation
madness::WorldProfileObj::WorldProfileObj (int id)
References madness::WorldProfileEntry::depth, madness::WorldProfile::get_entry(), and pause().
madness::WorldProfileObj::~WorldProfileObj ()
References madness::WorldProfileEntry::count, madness::WorldProfileEntry::depth, madness::WorldProfile::get_entry(), madness::WorldProfileEntry::icpu, resume(), madness::ProfileStat< T >::value, and madness::WorldProfileEntry::xcpu.
Member Function Documentation
void madness::WorldProfileObj::pause (double now)
Pause profiling while we are not executing ... accumulate time in self.
References madness::WorldProfile::get_entry(), madness::ProfileStat< T >::value, and madness::WorldProfileEntry::xcpu.
Referenced by WorldProfileObj().
void madness::WorldProfileObj::resume (double now)
Resume profiling.
Referenced by ~WorldProfileObj().
The documentation for this class was generated from the following files:
worldprofile.h
worldprofile.cc