MADNESS: madness::HartreeFock< T, NDIM > Class Template Reference
madness::HartreeFock< T, NDIM > Class Template Reference
#include <mp2.h>
Public Types
typedef Function< T, NDIM > funcT
Public Member Functions
HartreeFock (World &world, std::shared_ptr< SCF > calc1)
bool provides_gradient () const
double value ()
double value (const Tensor< double > &x)
Tensor< double > gradient (const Tensor< double > &x)
double coord_chksum () const
const SCF & get_calc () const
SCF & get_calc ()
real_function_3d orbital (const int i) const
return full orbital i, multiplied with the nuclear correlation factor
std::vector< real_function_3d > orbitals () const
return full orbitals, multiplied with the nuclear correlation factor
std::vector< real_function_3d > R2orbitals () const
return orbitals, multiplied with the square nuclear correlation factor
real_function_3d R2orbital (const int i) const
return orbital i, multiplied with the square nuclear correlation factor
real_function_3d nemo (const int i) const
return nemo i, which is the regularized orbital
std::vector< real_function_3d > nemos () const
return nemo, which are the regularized orbitals
double orbital_energy (const int i) const
return orbital energy i
real_function_3d get_coulomb_potential () const
return the Coulomb potential
real_function_3d get_nuclear_potential () const
return the nuclear potential
int nocc () const
return the number of occupied orbitals
HartreeFock (World &world, funcT V, std::vector< funcT > phis, std::vector< double > eigs, bool bCoulomb, bool bExchange, double thresh)
virtual ~HartreeFock ()
void hartree_fock (int maxits)
funcT calculate_coulomb (funcT psi)
funcT calculate_exchange (funcT psi)
double calculate_ke_sp (funcT psi)
double calculate_pe_sp (funcT psi)
double calculate_coulomb_energy (const std::vector< funcT > &phis, const funcT &psi)
double calculate_exchange_energy (const std::vector< funcT > &phis, const funcT &psi)
T matrix_element (const funcT &phii, const funcT &phij)
virtual void iterateOutput (const std::vector< funcT > &phis, const std::vector< double > &eigs, const funcT &rho, const int &iter)
bool include_coulomb ()
bool include_exchange ()
double get_eig (int indx)
funcT get_phi (int indx)
const std::vector< double > & eigs ()
const std::vector< funcT > & phis ()
double calculate_tot_ke_sp (const std::vector< funcT > &phis)
double calculate_tot_pe_sp (const std::vector< funcT > &phis)
double calculate_tot_coulomb_energy (const std::vector< funcT > &phis)
double calculate_tot_exchange_energy (const std::vector< funcT > &phis)
Public Member Functions inherited from madness::IEigSolverObserver< T, NDIM >
virtual void iterateOutput (const std::vector< funcT > &phis, const std::vector< double > &eigs, const Function< double, NDIM > &rho, const int &iter, bool periodic)=0
virtual ~IEigSolverObserver ()
Public Attributes
Nemo nemo_calc
Member Typedef Documentation
template<typename T , int NDIM> typedef Function<T,NDIM> madness::HartreeFock< T, NDIM >::funcT
Constructor & Destructor Documentation
template<typename T , int NDIM> madness::HartreeFock< T, NDIM >::HartreeFock (World & world, std::shared_ptr< SCF > calc1) inline
template<typename T , int NDIM> madness::HartreeFock< T, NDIM >::HartreeFock (World & world, funcT V, std::vector< funcT > phis, std::vector< double > eigs, bool bCoulomb, bool bExchange, double thresh)
References madness::HartreeFock< T, NDIM >::eigs(), and madness::HartreeFock< T, NDIM >::phis().
template<typename T , int NDIM> madness::HartreeFock< T, NDIM >::~HartreeFock () virtual
Member Function Documentation
template<typename T , int NDIM> funcT madness::HartreeFock< T, NDIM >::calculate_coulomb (funcT psi)
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_coulomb_energy (const std::vector< funcT > & phis, const funcT & psi)
References madness::apply(), madness::FunctionDefaults< NDIM >::get_k(), madness::inner(), op(), psi(), and madness::Function< T, NDIM >::truncate().
template<typename T , int NDIM> funcT madness::HartreeFock< T, NDIM >::calculate_exchange (funcT psi)
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_exchange_energy (const std::vector< funcT > & phis, const funcT & psi)
References madness::apply(), madness::FunctionDefaults< NDIM >::get_k(), madness::inner(), op(), psi(), and thresh.
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_ke_sp (funcT psi)
References madness::inner().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_pe_sp (funcT psi)
References psi().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_tot_coulomb_energy (const std::vector< funcT > & phis)
References pi, and psi().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_tot_exchange_energy (const std::vector< funcT > & phis)
References pi, and psi().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_tot_ke_sp (const std::vector< funcT > & phis)
References pi, and psi().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::calculate_tot_pe_sp (const std::vector< funcT > & phis)
References pi, and psi().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::coord_chksum () const inline
template<typename T , int NDIM> const std::vector<double>& madness::HartreeFock< T, NDIM >::eigs () inline
Referenced by madness::HartreeFock< T, NDIM >::HartreeFock().
template<typename T , int NDIM> const SCF& madness::HartreeFock< T, NDIM >::get_calc () const inline
Referenced by main().
template<typename T , int NDIM> SCF& madness::HartreeFock< T, NDIM >::get_calc () inline
template<typename T , int NDIM> real_function_3d madness::HartreeFock< T, NDIM >::get_coulomb_potential () const inline
return the Coulomb potential
References madness::SCF::aocc, madness::copy(), madness::Function< T, NDIM >::is_initialized(), madness::SCF::make_coulomb_potential(), madness::SCF::make_density(), madness::HartreeFock< T, NDIM >::orbitals(), madness::SCF::param, madness::Function< T, NDIM >::scale(), and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::get_eig (int indx) inline
template<typename T , int NDIM> real_function_3d madness::HartreeFock< T, NDIM >::get_nuclear_potential () const inline
return the nuclear potential
References madness::SCF::potentialmanager.
template<typename T , int NDIM> funcT madness::HartreeFock< T, NDIM >::get_phi (int indx) inline
template<typename T , int NDIM> Tensor<double> madness::HartreeFock< T, NDIM >::gradient (const Tensor< double > & x) inline
References madness::SCF::derivatives(), and madness::HartreeFock< T, NDIM >::value().
template<typename T , int NDIM> void madness::HartreeFock< T, NDIM >::hartree_fock (int maxits)
template<typename T , int NDIM> bool madness::HartreeFock< T, NDIM >::include_coulomb () inline
template<typename T , int NDIM> bool madness::HartreeFock< T, NDIM >::include_exchange () inline
template<typename T , int NDIM> void madness::HartreeFock< T, NDIM >::iterateOutput (const std::vector< funcT > & phis, const std::vector< double > & eigs, const funcT & rho, const int & iter) virtual
template<typename T , int NDIM> T madness::HartreeFock< T, NDIM >::matrix_element (const funcT & phii, const funcT & phij) inline
template<typename T , int NDIM> real_function_3d madness::HartreeFock< T, NDIM >::nemo (const int i) const inline
return nemo i, which is the regularized orbital
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::amo, madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> std::vector<real_function_3d> madness::HartreeFock< T, NDIM >::nemos () const inline
return nemo, which are the regularized orbitals
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::amo, madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> int madness::HartreeFock< T, NDIM >::nocc () const inline
return the number of occupied orbitals
References madness::CalculationParameters::nalpha, madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> real_function_3d madness::HartreeFock< T, NDIM >::orbital (const int i) const inline
return full orbital i, multiplied with the nuclear correlation factor
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::orbital_energy (const int i) const inline
return orbital energy i
References madness::SCF::aeps, madness::SCF::param, and madness::CalculationParameters::spin_restricted.
Referenced by madness::MP2::zeroth_order_energy().
template<typename T , int NDIM> std::vector<real_function_3d> madness::HartreeFock< T, NDIM >::orbitals () const inline
return full orbitals, multiplied with the nuclear correlation factor
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::param, and madness::CalculationParameters::spin_restricted.
Referenced by madness::HartreeFock< T, NDIM >::get_coulomb_potential().
template<typename T , int NDIM> const std::vector<funcT>& madness::HartreeFock< T, NDIM >::phis () inline
Referenced by madness::HartreeFock< T, NDIM >::HartreeFock().
template<typename T , int NDIM> bool madness::HartreeFock< T, NDIM >::provides_gradient () const inline
template<typename T , int NDIM> real_function_3d madness::HartreeFock< T, NDIM >::R2orbital (const int i) const inline
return orbital i, multiplied with the square nuclear correlation factor
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> std::vector<real_function_3d> madness::HartreeFock< T, NDIM >::R2orbitals () const inline
return orbitals, multiplied with the square nuclear correlation factor
note that nemo() and orbital() are the same if no nuclear correlation factor is used
References madness::SCF::param, and madness::CalculationParameters::spin_restricted.
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::value () inline
References madness::Molecule::get_all_coords(), and madness::SCF::molecule.
Referenced by madness::HartreeFock< T, NDIM >::gradient(), and main().
template<typename T , int NDIM> double madness::HartreeFock< T, NDIM >::value (const Tensor< double > & x) inline
References madness::CalculationParameters::aobasis, madness::SCF::current_energy, madness::CalculationParameters::econv, madness::Nemo::get_calc(), madness::SCF::initial_guess(), madness::SCF::load_mos(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::mul(), madness::Molecule::natom(), madness::CalculationParameters::no_compute, madness::Nemo::nuclear_correlation, madness::SCF::param, madness::SCF::potentialmanager, madness::SCF::project(), madness::SCF::project_ao_basis(), madness::Nemo::R, R2, madness::CalculationParameters::restart, madness::SCF::save_mos(), madness::Molecule::set_all_coords(), madness::SCF::set_protocol(), madness::SCF::solve(), and madness::Nemo::value().
Member Data Documentation
template<typename T , int NDIM> Nemo madness::HartreeFock< T, NDIM >::nemo_calc
The documentation for this class was generated from the following files:
mp2.h
hartreefock.h
hartreefock.cc