MADNESS: madness::tr1::array::array< T, 0 > Class Template Reference
madness::tr1::array::array< T, 0 > Class Template Reference
#include <stdarray_bits.h>
Public Types
enum { static_size = 0 }
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
reference at (size_type i)
const_reference at (size_type i) const
void swap (array< T, 0 > &y)
const T * data () const
T * data ()
template<typename T2 >
array< T, 0 > & operator= (const array< T2, 0 > &rhs)
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Static Public Member Functions
static size_type size ()
static bool empty ()
static size_type max_size ()
Public Attributes
char c
Member Typedef Documentation
template<typename T > typedef const T* madness::tr1::array::array< T, 0 >::const_iterator
template<typename T > typedef const T& madness::tr1::array::array< T, 0 >::const_reference
template<typename T > typedef std::reverse_iterator<const_iterator> madness::tr1::array::array< T, 0 >::const_reverse_iterator
template<typename T > typedef std::ptrdiff_t madness::tr1::array::array< T, 0 >::difference_type
template<typename T > typedef T* madness::tr1::array::array< T, 0 >::iterator
template<typename T > typedef T& madness::tr1::array::array< T, 0 >::reference
template<typename T > typedef std::reverse_iterator<iterator> madness::tr1::array::array< T, 0 >::reverse_iterator
template<typename T > typedef std::size_t madness::tr1::array::array< T, 0 >::size_type
template<typename T > typedef T madness::tr1::array::array< T, 0 >::value_type
Member Enumeration Documentation
template<typename T > anonymous enum
Enumerator
static_size
Member Function Documentation
template<typename T > reference madness::tr1::array::array< T, 0 >::at (size_type i) inline
template<typename T > const_reference madness::tr1::array::array< T, 0 >::at (size_type i) const inline
template<typename T > reference madness::tr1::array::array< T, 0 >::back () inline
template<typename T > const_reference madness::tr1::array::array< T, 0 >::back () const inline
template<typename T > iterator madness::tr1::array::array< T, 0 >::begin () inline
References c.
template<typename T > const_iterator madness::tr1::array::array< T, 0 >::begin () const inline
References c.
template<typename T > const T* madness::tr1::array::array< T, 0 >::data () const inline
template<typename T > T* madness::tr1::array::array< T, 0 >::data () inline
template<typename T > static bool madness::tr1::array::array< T, 0 >::empty () inline static
template<typename T > iterator madness::tr1::array::array< T, 0 >::end () inline
References c.
template<typename T > const_iterator madness::tr1::array::array< T, 0 >::end () const inline
References c.
template<typename T > reference madness::tr1::array::array< T, 0 >::front () inline
template<typename T > const_reference madness::tr1::array::array< T, 0 >::front () const inline
template<typename T > static size_type madness::tr1::array::array< T, 0 >::max_size () inline static
template<typename T > template<typename T2 > array< T,0 >& madness::tr1::array::array< T, 0 >::operator= (const array< T2, 0 > & rhs) inline
template<typename T > reference madness::tr1::array::array< T, 0 >::operator[] (size_type i) inline
template<typename T > const_reference madness::tr1::array::array< T, 0 >::operator[] (size_type i) const inline
template<typename T > reverse_iterator madness::tr1::array::array< T, 0 >::rbegin () inline
References madness::tr1::array::array< T, N >::end().
template<typename T > const_reverse_iterator madness::tr1::array::array< T, 0 >::rbegin () const inline
References madness::tr1::array::array< T, N >::end().
template<typename T > reverse_iterator madness::tr1::array::array< T, 0 >::rend () inline
References madness::tr1::array::array< T, N >::begin().
template<typename T > const_reverse_iterator madness::tr1::array::array< T, 0 >::rend () const inline
References madness::tr1::array::array< T, N >::begin().
template<typename T > static size_type madness::tr1::array::array< T, 0 >::size () inline static
template<typename T > void madness::tr1::array::array< T, 0 >::swap (array< T, 0 > & y) inline
Member Data Documentation
template<typename T > char madness::tr1::array::array< T, 0 >::c
The documentation for this class was generated from the following file:
stdarray_bits.h