MADNESS: madness::Subspace< T, NDIM > Class Template Reference
madness::Subspace< T, NDIM > Class Template Reference
MADNESS applications » Periodic Solver
The SubspaceK class is a container class holding previous orbitals and residuals.
#include <solver.h>
Public Member Functions
Subspace (World &world, const ElectronicStructureParams &params)
void update_subspace (vecfuncT &awfs_new, vecfuncT &bwfs_new, const vecfuncT &awfs_old, const vecfuncT &bwfs_old, const vecfuncT &rm)
void reproject ()
Detailed Description
template<typename T, int NDIM>
class madness::Subspace< T, NDIM >
The SubspaceK class is a container class holding previous orbitals and residuals.
The Solver class uses the Krylov Accelerated Inexact Newton Solver (KAIN) accelerate the convergence a given calculation. The KAIN solver needs to store a subspace of previous orbitals and residuals.
Constructor & Destructor Documentation
template<typename T, int NDIM> madness::Subspace< T, NDIM >::Subspace (World & world, const ElectronicStructureParams & params) inline
Member Function Documentation
template<typename T, int NDIM> void madness::Subspace< T, NDIM >::reproject () inline
template<typename T, int NDIM> void madness::Subspace< T, NDIM >::update_subspace (vecfuncT & awfs_new, vecfuncT & bwfs_new, const vecfuncT & awfs_old, const vecfuncT & bwfs_old, const vecfuncT & rm) inline
References madness::abs(), madness::WorldGopInterface::broadcast_serializable(), c, madness::compress(), madness::WorldGopInterface::fence(), madness::gaxpy(), madness::World::gop, madness::KAIN(), m, madness::ElectronicStructureParams::maxsub, one(), madness::print(), madness::World::rank(), madness::World::size(), madness::ElectronicStructureParams::spinpol, and madness::WorldGopInterface::sum().
Referenced by madness::Solver< T, NDIM >::update_orbitals().
The documentation for this class was generated from the following file:
solver.h