MADNESS: madness::MyPmap< D > Class Template Reference
madness::MyPmap< D > Class Template Reference
Procmap implemented using Tree of TreeCoords.
#include <mypmap.h>
Public Member Functions
MyPmap ()
MyPmap (World &world)
MyPmap (World &world, unsigned int map_type, int n=100)
MyPmap (World &world, std::vector< TreeCoords< D > > v)
MyPmap (const MyPmap< D > &other)
MyPmap< D > & operator= (const MyPmap< D > &other)
void print () const
ProcessID owner (const KeyD &key) const
Find the owner of a given key.
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< D > >
virtual ~WorldDCPmapInterface ()
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< D > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
Static Public Member Functions
static bool costmapcmp (const std::pair< KeyD, double > &a, const std::pair< KeyD, double > &b)
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< D > >
typedef
WorldDCRedistributeInterface
< Key< D > > * ptrT
Detailed Description
template<int D>
class madness::MyPmap< D >
Procmap implemented using Tree of TreeCoords.
Constructor & Destructor Documentation
template<int D> madness::MyPmap< D >::MyPmap () inline
template<int D> madness::MyPmap< D >::MyPmap (World & world) inline
template<int D> madness::MyPmap< D >::MyPmap (World & world, unsigned int map_type, int n = 100) inline
References mpfr::log(), and madness::World::size().
template<int D> madness::MyPmap< D >::MyPmap (World & world, std::vector< TreeCoords< D > > v) inline
template<int D> madness::MyPmap< D >::MyPmap (const MyPmap< D > & other) inline
Member Function Documentation
template<int D> static bool madness::MyPmap< D >::costmapcmp (const std::pair< KeyD, double > & a, const std::pair< KeyD, double > & b) inline static
template<int D> MyPmap<D>& madness::MyPmap< D >::operator= (const MyPmap< D > & other) inline
template<int D> ProcessID madness::MyPmap< D >::owner (const KeyD & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< D > >.
template<int D> void madness::MyPmap< D >::print () const inline virtual
Reimplemented from madness::WorldDCPmapInterface< Key< D > >.
References madness::print().
The documentation for this class was generated from the following file:
mypmap.h