MADNESS: madness::ContractedGaussianShell Class Reference
madness::ContractedGaussianShell Class Reference
Represents a single shell of contracted, Cartesian, Gaussian primitives.
#include <molecularbasis.h>
Public Member Functions
ContractedGaussianShell ()
ContractedGaussianShell (int type, const std::vector< double > &coeff, const std::vector< double > &expnt, bool donorm=true)
double rangesq () const
Returns square of the distance beyond which function is less than 1e-8.
double eval_radial (double rsq) const
Evaluates the radial part of the contracted function.
double * eval (double rsq, double x, double y, double z, double *bf) const
Evaluates the entire shell returning the incremented result pointer.
int angular_momentum () const
Returns the shell angular momentum.
int nbf () const
Returns the number of basis functions in the shell.
int nprim () const
Returns the number of primitives in the contraction.
const std::vector< double > & get_coeff () const
Returns a const reference to the coefficients.
const std::vector< double > & get_expnt () const
Returns a const reference to the exponents.
const char * get_desc (int ibf) const
Returns a string description of the basis function type.
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
Represents a single shell of contracted, Cartesian, Gaussian primitives.
Constructor & Destructor Documentation
madness::ContractedGaussianShell::ContractedGaussianShell () inline
madness::ContractedGaussianShell::ContractedGaussianShell (int type, const std::vector< double > & coeff, const std::vector< double > & expnt, bool donorm = true) inline
References mpfr::min().
Member Function Documentation
int madness::ContractedGaussianShell::angular_momentum () const inline
Returns the shell angular momentum.
Referenced by operator<<(), and madness::operator<<().
double* madness::ContractedGaussianShell::eval (double rsq, double x, double y, double z, double * bf) const inline
Evaluates the entire shell returning the incremented result pointer.
References eval_radial(), mpfr::fabs(), and R.
Referenced by AtomicBasisFunction::operator()(), and madness::AtomicBasisFunction::operator()().
double madness::ContractedGaussianShell::eval_radial (double rsq) const inline
Evaluates the radial part of the contracted function.
References mpfr::exp(), and mpfr::sum().
Referenced by ContractedGaussianShell::eval(), and eval().
const std::vector<double>& madness::ContractedGaussianShell::get_coeff () const inline
Returns a const reference to the coefficients.
Referenced by operator<<(), and madness::operator<<().
const char* madness::ContractedGaussianShell::get_desc (int ibf) const inline
Returns a string description of the basis function type.
Referenced by AtomicBasisFunction::get_desc(), and madness::AtomicBasisFunction::get_desc().
const std::vector<double>& madness::ContractedGaussianShell::get_expnt () const inline
Returns a const reference to the exponents.
Referenced by operator<<(), and madness::operator<<().
int madness::ContractedGaussianShell::nbf () const inline
Returns the number of basis functions in the shell.
Referenced by AtomicBasis::get_shell_from_basis_function(), and madness::AtomicBasis::get_shell_from_basis_function().
int madness::ContractedGaussianShell::nprim () const inline
Returns the number of primitives in the contraction.
Referenced by operator<<(), and madness::operator<<().
double madness::ContractedGaussianShell::rangesq () const inline
Returns square of the distance beyond which function is less than 1e-8.
Referenced by AtomicBasisFunction::rangesq().
template<typename Archive > void madness::ContractedGaussianShell::serialize (Archive & ar) inline
The documentation for this class was generated from the following file:
chem/molecularbasis.h