MADNESS: AtomicBasisFunction Class Reference
AtomicBasisFunction Class Reference
Used to represent one basis function from a shell on a specific center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
const ContractedGaussianShell & get_shell () const
int get_index () const
const char * get_desc () const
void get_coords (double &x, double &y, double &z) const
madness::Vector< double, 3 > get_coords_vec () const
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
const ContractedGaussianShell & get_shell () const
int get_index () const
const char * get_desc () const
void get_coords (double &x, double &y, double &z) const
double rangesq () const
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
const ContractedGaussianShell & get_shell () const
int get_index () const
const char * get_desc () const
void get_coords (double &x, double &y, double &z) const
Detailed Description
Used to represent one basis function from a shell on a specific center.
Constructor & Destructor Documentation
AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
Member Function Documentation
void AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
void AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
void AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
madness::Vector<double,3> AtomicBasisFunction::get_coords_vec () const inline
References madness::vec().
const char* AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc().
const char* AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc().
const char* AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc().
int AtomicBasisFunction::get_index () const inline
int AtomicBasisFunction::get_index () const inline
int AtomicBasisFunction::get_index () const inline
const ContractedGaussianShell& AtomicBasisFunction::get_shell () const inline
const ContractedGaussianShell& AtomicBasisFunction::get_shell () const inline
const ContractedGaussianShell& AtomicBasisFunction::get_shell () const inline
double AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval().
double AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval().
double AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval().
void AtomicBasisFunction::print_me (std::ostream & s) const
void AtomicBasisFunction::print_me (std::ostream & s) const
Referenced by operator<<().
void AtomicBasisFunction::print_me (std::ostream & s) const inline
double AtomicBasisFunction::rangesq () const inline
References madness::ContractedGaussianShell::rangesq().
The documentation for this class was generated from the following files:
DFcode/molecularbasis.h
jacob/molecularbasis.cc