MADNESS: madness::HartreeFockExchangeOp< T, NDIM > Class Template Reference
madness::HartreeFockExchangeOp< T, NDIM > Class Template Reference
#include <hartreefock.h>
Public Types
typedef Function< T, NDIM > funcT
Public Member Functions
HartreeFockExchangeOp (World &world, double coeff, double thresh)
virtual bool is_od ()
Is there an orbitally-dependent term?
virtual bool is_rd ()
Is there a density-dependent term?
virtual funcT op_o (const std::vector< funcT > &phis, const funcT &psi)
Orbital-dependent portion of operator.
Public Member Functions inherited from madness::EigSolverOp< T, NDIM >
EigSolverOp (World &world, double coeff, double thresh)
virtual ~EigSolverOp ()
virtual void prepare_op (funcT rho)
Build the potential from a density if a density-dependent operator.
virtual funcT op_r (const funcT &rho, const funcT &psi)
Density-dependent portion of operator.
virtual std::vector< funcT > multi_op_o (const std::vector< funcT > &phis)
Orbital-dependent portion of operator.
virtual std::vector< funcT > multi_op_r (const funcT &rho, const std::vector< funcT > &phis)
Density-dependent portion of operator.
double coeff ()
std::string messsageME ()
Additional Inherited Members
Public Attributes inherited from madness::EigSolverOp< T, NDIM >
World & _world
Protected Member Functions inherited from madness::EigSolverOp< T, NDIM >
double thresh ()
void messageME (std::string messageME)
Member Typedef Documentation
template<typename T , int NDIM> typedef Function<T,NDIM> madness::HartreeFockExchangeOp< T, NDIM >::funcT
Constructor & Destructor Documentation
template<typename T , int NDIM> madness::HartreeFockExchangeOp< T, NDIM >::HartreeFockExchangeOp (World & world, double coeff, double thresh)
References madness::EigSolverOp< T, NDIM >::messageME().
Member Function Documentation
template<typename T , int NDIM> virtual bool madness::HartreeFockExchangeOp< T, NDIM >::is_od () inline virtual
Is there an orbitally-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
template<typename T , int NDIM> virtual bool madness::HartreeFockExchangeOp< T, NDIM >::is_rd () inline virtual
Is there a density-dependent term?
Implements madness::EigSolverOp< T, NDIM >.
template<typename T , int NDIM> Function< T, NDIM > madness::HartreeFockExchangeOp< T, NDIM >::op_o (const std::vector< funcT > & phis, const funcT & psi) virtual
Orbital-dependent portion of operator.
Reimplemented from madness::EigSolverOp< T, NDIM >.
References madness::apply(), madness::FunctionDefaults< NDIM >::get_k(), psi(), thresh, and madness::Function< T, NDIM >::truncate().
The documentation for this class was generated from the following files:
hartreefock.h
hartreefock.cc