MADNESS: madness::WorldAmInterface Class Reference
madness::WorldAmInterface Class Reference
Implements AM interface.
#include <worldam.h>
Public Member Functions
WorldAmInterface (World &world)
virtual ~WorldAmInterface ()
void fence ()
Currently a noop.
RMI::Request send (const ProcessID dest, am_handlerT op, const AmArg *arg, const int attr=RMI::ATTR_ORDERED, const bool managed=true)
Sends an unmanaged non-blocking active message.
void free_managed_buffers ()
Frees as many send buffers as possible.
Public Attributes
const int msg_len
Max length of user payload in message.
Friends
class WorldGopInterface
class World
Detailed Description
Implements AM interface.
Constructor & Destructor Documentation
madness::WorldAmInterface::WorldAmInterface (World & world)
References madness::WorldMpiInterface::comm(), SafeMPI::COMM_WORLD, fred(), SafeMPI::Intracomm::Get_group(), madness::Mutex::lock(), madness::World::mpi, SafeMPI::Group::Translate_ranks(), and madness::Mutex::unlock().
madness::WorldAmInterface::~WorldAmInterface () virtual
References SafeMPI::Is_finalized().
Member Function Documentation
void madness::WorldAmInterface::fence () inline
Currently a noop.
void madness::WorldAmInterface::free_managed_buffers () inline
Frees as many send buffers as possible.
References madness::ScopedArray< ptrT >::get(), madness::Mutex::lock(), MPI_UNDEFINED, SafeMPI::Request::Testsome(), and madness::Mutex::unlock().
Referenced by madness::WorldGopInterface::fence().
RMI::Request madness::WorldAmInterface::send (const ProcessID dest, am_handlerT op, const AmArg * arg, const int attr = RMI::ATTR_ORDERED, const bool managed = true) inline
Sends an unmanaged non-blocking active message.
Sends a managed non-blocking active message
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::reset(), and madness::FutureImpl< bool >::set().
Friends And Related Function Documentation
friend class World friend
friend class WorldGopInterface friend
Member Data Documentation
const int madness::WorldAmInterface::msg_len
Max length of user payload in message.
The documentation for this class was generated from the following files:
worldam.h
worldam.cc