MADNESS: madness::FunctionDefaults< NDIM > Class Template Reference
madness::FunctionDefaults< NDIM > Class Template Reference
MADNESS libraries » Multiresolution analaysis
FunctionDefaults holds default paramaters as static class members.
#include <funcdefaults.h>
Static Public Member Functions
static void set_defaults (World &world)
Used to set defaults to k=7, thresh=1-5, for a unit cube [0,1].
static int get_k ()
Returns the default wavelet order.
static void set_k (int value)
Sets the default wavelet order.
static const double & get_thresh ()
Returns the default threshold.
static void set_thresh (double value)
Sets the default threshold.
static int get_initial_level ()
Returns the default initial projection level.
static void set_initial_level (int value)
Sets the default initial projection level.
static int get_max_refine_level ()
Gets the default maximum adaptive refinement level.
static void set_max_refine_level (int value)
Sets the default maximum adaptive refinement level.
static int get_truncate_mode ()
Gets the default truncation mode.
static void set_truncate_mode (int value)
Sets the default truncation mode.
static bool get_refine ()
Gets the default adaptive refinement flag.
static void set_refine (bool value)
Sets the default adaptive refinement flag.
static bool get_autorefine ()
Gets the default adaptive autorefinement flag.
static void set_autorefine (bool value)
Sets the default adaptive autorefinement flag.
static bool get_debug ()
Gets the default debug flag (is this used anymore?)
static void set_debug (bool value)
Sets the default debug flag (is this used anymore?)
static bool get_truncate_on_project ()
Gets the default truncate on project flag.
static void set_truncate_on_project (bool value)
Sets the default truncate on project flag.
static bool get_apply_randomize ()
Gets the random load balancing for integral operators flag.
static void set_apply_randomize (bool value)
Sets the random load balancing for integral operators flag.
static bool get_project_randomize ()
Gets the random load balancing for projection flag.
static void set_project_randomize (bool value)
Sets the random load balancing for projection flag.
static const
BoundaryConditions< NDIM > & get_bc ()
Returns the default boundary conditions.
static void set_bc (const BoundaryConditions< NDIM > &value)
Sets the default boundary conditions.
static TensorType get_tensor_type ()
Returns the default tensor type.
static void set_tensor_type (const TensorType &t)
Sets the default tensor type.
static const Tensor< double > & get_cell ()
Gets the user cell for the simulation.
static void set_cell (const Tensor< double > &value)
Gets the user cell for the simulation.
static void set_cubic_cell (double lo, double hi)
Sets the user cell to be cubic with each dimension having range [lo,hi].
static const Tensor< double > & get_cell_width ()
Returns the width of each user cell dimension.
static const Tensor< double > & get_rcell_width ()
Returns the reciprocal of the width of each user cell dimension.
static double get_cell_min_width ()
Returns the minimum width of any user cell dimension.
static double get_cell_volume ()
Returns the volume of the user cell.
static std::shared_ptr
< WorldDCPmapInterface< Key
< NDIM > > > & get_pmap ()
Returns the default process map.
static void set_pmap (const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &value)
Sets the default process map (does not redistribute existing functions)
static void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &newpmap)
Sets the default process map and redistributes all functions using the old map.
Detailed Description
template<std::size_t NDIM>
class madness::FunctionDefaults< NDIM >
FunctionDefaults holds default paramaters as static class members.
Declared and initialized in mra.cc and/or funcimpl::initialize.
Currently all functions of the same dimension share the same cell dimensions since they are stored inside FunctionDefaults ... if you change the cell dimensions all functions of that dimension are affected.
N.B. Ultimately, we may need to make these defaults specific to each world, as should be all global state.
Member Function Documentation
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_apply_randomize () inline static
Gets the random load balancing for integral operators flag.
Referenced by madness::FunctionImpl< Q, NDIM >::apply(), and madness::FunctionImpl< Q, NDIM >::apply_source_driven().
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_autorefine () inline static
Gets the default adaptive autorefinement flag.
template<std::size_t NDIM> static const BoundaryConditions<NDIM>& madness::FunctionDefaults< NDIM >::get_bc () inline static
Returns the default boundary conditions.
Referenced by madness::FunctionImpl< T, NDIM >::project_refine_op().
template<std::size_t NDIM> static const Tensor<double>& madness::FunctionDefaults< NDIM >::get_cell () inline static
Gets the user cell for the simulation.
Referenced by madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::do_print_plane(), madness::fcube(), madness::Solver< T, NDIM >::make_nuclear_potential(), madness::FunctionImpl< T, NDIM >::print_plane_local(), random_gaussian(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), save_function(), madness::Solver< T, NDIM >::solve(), and vtk_output().
template<std::size_t NDIM> static double madness::FunctionDefaults< NDIM >::get_cell_min_width () inline static
Returns the minimum width of any user cell dimension.
Referenced by madness::qm_free_particle_propagator(), madness::qm_free_particle_propagatorPtr(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
template<std::size_t NDIM> static double madness::FunctionDefaults< NDIM >::get_cell_volume () inline static
Returns the volume of the user cell.
template<std::size_t NDIM> static const Tensor<double>& madness::FunctionDefaults< NDIM >::get_cell_width () inline static
Returns the width of each user cell dimension.
Referenced by madness::DFT< T, NDIM >::calculate_tot_coulomb_energy(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::FunctionImpl< T, NDIM >::do_print_grid(), draw_plane(), madness::fcube(), madness::Solver< T, NDIM >::initial_guess(), madness::TwoElectronInterface< double, 6 >::initialize(), madness::trajectory< NDIM >::line_xyz(), madness::plot_plane(), madness::FunctionImpl< T, NDIM >::print_plane_local(), MolecularEntity::read_file(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), madness::SeparatedConvolution< T, NDIM >::SeparatedConvolution(), madness::EigSolver< T, NDIM >::solve(), solve(), madness::Solver< T, NDIM >::Solver(), test_modified(), test_recursive_application(), testNavierStokes(), and madness::TwoElectronInterface< double, 6 >::TwoElectronInterface().
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_debug () inline static
Gets the default debug flag (is this used anymore?)
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_initial_level () inline static
Returns the default initial projection level.
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_k () inline static
Returns the default wavelet order.
Referenced by madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::DFTCoulombOp< T, NDIM >::DFTCoulombOp(), madness::DFTCoulombPeriodicOp< T, NDIM >::DFTCoulombPeriodicOp(), madness::DFTNuclearChargeDensityOp< T, NDIM >::DFTNuclearChargeDensityOp(), madness::Solver< T, NDIM >::load_orbitals(), madness::EigSolver< T, NDIM >::make_bsh_operators(), madness::HartreeFockExchangeOp< T, NDIM >::op_o(), madness::HartreeFockCoulombOp< T, NDIM >::op_r(), madness::EigSolver< T, NDIM >::solve(), solve(), test_adaptive_tree(), and madness::TwoElectronFactory::TwoElectronFactory().
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_max_refine_level () inline static
Gets the default maximum adaptive refinement level.
template<std::size_t NDIM> static std::shared_ptr< WorldDCPmapInterface< Key<NDIM> > >& madness::FunctionDefaults< NDIM >::get_pmap () inline static
Returns the default process map.
Referenced by trotter().
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_project_randomize () inline static
Gets the random load balancing for projection flag.
template<std::size_t NDIM> static const Tensor<double>& madness::FunctionDefaults< NDIM >::get_rcell_width () inline static
Returns the reciprocal of the width of each user cell dimension.
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_refine () inline static
Gets the default adaptive refinement flag.
template<std::size_t NDIM> static TensorType madness::FunctionDefaults< NDIM >::get_tensor_type () inline static
Returns the default tensor type.
template<std::size_t NDIM> static const double& madness::FunctionDefaults< NDIM >::get_thresh () inline static
Returns the default threshold.
Referenced by SCF::apply_hf_exchange(), madness::GTHPseudopotential< double >::apply_potential(), madness::GTHPseudopotential< double >::apply_potential_simple(), madness::hartree_product(), iterate(), madness::Solver< T, NDIM >::load_orbitals(), main(), madness::EigSolver< T, NDIM >::make_bsh_operators(), madness::Solver< T, NDIM >::make_bsh_operators(), madness::PotentialManager::make_nuclear_potential(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), madness::SCF::set_protocol(), madness::TDA::setup(), madness::EigSolver< T, NDIM >::solve(), solve(), test_adaptive_tree(), testbsh(), madness::TwoElectronFactory::TwoElectronFactory(), and SCF::twoint().
template<std::size_t NDIM> static int madness::FunctionDefaults< NDIM >::get_truncate_mode () inline static
Gets the default truncation mode.
template<std::size_t NDIM> static bool madness::FunctionDefaults< NDIM >::get_truncate_on_project () inline static
Gets the default truncate on project flag.
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::redistribute (World & world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & newpmap) inline static
Sets the default process map and redistributes all functions using the old map.
Referenced by initial_loadbal(), iterate(), madness::load_balance(), load_balance(), loadbal(), main(), preloadbal(), projectL(), and test().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_apply_randomize (bool value) inline static
Sets the random load balancing for integral operators flag.
Referenced by doit(), main(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_autorefine (bool value) inline static
Sets the default adaptive autorefinement flag.
Existing functions are unaffected
Referenced by doit(), main(), moments(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_bc (const BoundaryConditions< NDIM > & value) inline static
Sets the default boundary conditions.
Referenced by main(), madness::Solver< T, NDIM >::Solver(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), and testNavierStokes().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_cell (const Tensor< double > & value) inline static
Gets the user cell for the simulation.
Existing functions are probably rendered useless
References madness::copy().
Referenced by doit(), and main().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_cubic_cell (double lo, double hi) inline static
Sets the user cell to be cubic with each dimension having range [lo,hi].
Existing functions are probably rendered useless
Referenced by doit(), madness::Solver< T, NDIM >::init(), main(), set_protocol(), madness::SCF::set_protocol(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_wannier(), and testNavierStokes().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_debug (bool value) inline static
Sets the default debug flag (is this used anymore?)
Not sure if this does anything useful
template<std::size_t NDIM> void madness::FunctionDefaults< NDIM >::set_defaults (World & world) static
Used to set defaults to k=7, thresh=1-5, for a unit cube [0,1].
References madness::BC_FREE, debug, NDIM, thresh, and madness::TT_FULL.
Referenced by madness::startup().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_initial_level (int value) inline static
Sets the default initial projection level.
Existing functions are unaffected
Referenced by doit(), main(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_k (int value) inline static
Sets the default wavelet order.
Existing functions are unaffacted.
Referenced by doit(), madness::Solver< T, NDIM >::init(), load_function(), main(), madness::Solver< T, NDIM >::reproject(), set_protocol(), madness::SCF::set_protocol(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_wannier(), and testNavierStokes().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_max_refine_level (int value) inline static
Sets the default maximum adaptive refinement level.
Existing functions are unaffected
Referenced by main().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_pmap (const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > & value) inline static
Sets the default process map (does not redistribute existing functions)
Existing functions are probably rendered useless
Referenced by doit(), loadbal(), main(), and trotter().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_project_randomize (bool value) inline static
Sets the random load balancing for projection flag.
Referenced by main(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_refine (bool value) inline static
Sets the default adaptive refinement flag.
Existing functions are unaffected
Referenced by doit(), main(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_tensor_type (const TensorType & t) inline static
Sets the default tensor type.
References madness::TT_FULL.
Referenced by main().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_thresh (double value) inline static
Sets the default threshold.
Existing functions are unaffected
Referenced by doit(), madness::Solver< T, NDIM >::init(), load_function(), main(), madness::StrongOrthogonalityProjector< double, 3 >::operator()(), projectPsi(), madness::Solver< T, NDIM >::reproject(), set_protocol(), madness::SCF::set_protocol(), test_gaussian_num_coeffs(), test_nuclear_energy(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), test_wannier(), and testNavierStokes().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_truncate_mode (int value) inline static
Sets the default truncation mode.
Existing functions are unaffected
Referenced by doit(), main(), set_protocol(), and madness::SCF::set_protocol().
template<std::size_t NDIM> static void madness::FunctionDefaults< NDIM >::set_truncate_on_project (bool value) inline static
Sets the default truncate on project flag.
Existing functions are unaffected
Referenced by doit(), and main().
The documentation for this class was generated from the following files:
funcdefaults.h
mraimpl.h