MADNESS: madness::AtomicBasisFunction Class Reference
madness::AtomicBasisFunction Class Reference
Used to represent one basis function from a shell on a specific center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell &shell, int ibf)
AtomicBasisFunction (const AtomicBasisFunction &aofunc)
double operator() (double x, double y, double z) const
void print_me (std::ostream &s) const
const ContractedGaussianShell & get_shell () const
int get_index () const
const char * get_desc () const
void get_coords (double &x, double &y, double &z) const
madness::Vector< double, 3 > get_coords_vec () const
Detailed Description
Used to represent one basis function from a shell on a specific center.
Constructor & Destructor Documentation
madness::AtomicBasisFunction::AtomicBasisFunction (double x, double y, double z, const ContractedGaussianShell & shell, int ibf) inline
madness::AtomicBasisFunction::AtomicBasisFunction (const AtomicBasisFunction & aofunc) inline
Member Function Documentation
void madness::AtomicBasisFunction::get_coords (double & x, double & y, double & z) const inline
Referenced by madness::WSTAtomicBasisFunctor::WSTAtomicBasisFunctor().
madness::Vector<double,3> madness::AtomicBasisFunction::get_coords_vec () const inline
References madness::vec().
Referenced by madness::AtomicBasisFunctor::special_points().
const char* madness::AtomicBasisFunction::get_desc () const inline
References madness::ContractedGaussianShell::get_desc().
Referenced by madness::AtomicBasisSet::print_anal(), and AtomicBasisSet::print_anal().
int madness::AtomicBasisFunction::get_index () const inline
const ContractedGaussianShell& madness::AtomicBasisFunction::get_shell () const inline
double madness::AtomicBasisFunction::operator() (double x, double y, double z) const inline
References madness::ContractedGaussianShell::eval().
void AtomicBasisFunction::print_me (std::ostream & s) const
Referenced by operator<<(), and madness::operator<<().
The documentation for this class was generated from the following files:
chem/molecularbasis.h
chem/molecularbasis.cc