MADNESS: DFTSolventSolver Class Reference
DFTSolventSolver Class Reference
#include <abinitdftsolventsolver.h>
Public Member Functions
realfunc make_epsilon () const
realfunc make_normconst () const
realfunc make_surface () const
realfunc make_characteristic_func () const
realfunc make_repsilon () const
realfunc make_depsilon_drho () const
realfunc make_ratioepsilon () const
double cavitation_energy () const
realfunc dfree_drho () const
realfunc depsilon_dr () const
realfunc make_surfcharge (const realfunc &u) const
real_function_3d make_Laplace_surface_charge (const real_function_3d &u, std::vector< double > E=std::vector< double >(3, 0.0)) const
realfunc ESP () const
real_function_3d Laplace_ESP (std::vector< double >E) const
realfunc dESP_drho (const realfunc &u) const
vector_real_function_3d make_electric_field (const real_function_3d &u) const
double ave_rxn_field (const real_function_3d &u, const real_function_3d &mask) const
DFTSolventSolver (const realfunc &rho, const realfunc &rhot, const double &rho_0, const double &epsilon, const int &maxiter, World &world, const double &Gamma, const double &beta, const double &minlen)
Constructor & Destructor Documentation
DFTSolventSolver::DFTSolventSolver (const realfunc & rho, const realfunc & rhot, const double & rho_0, const double & epsilon, const int & maxiter, World & world, const double & Gamma, const double & beta, const double & minlen) inline
Member Function Documentation
double DFTSolventSolver::ave_rxn_field (const real_function_3d & u, const real_function_3d & mask) const inline
References make_electric_field(), and sqrt().
double DFTSolventSolver::cavitation_energy () const inline
References make_surface(), and madness::Function< T, NDIM >::trace().
realfunc DFTSolventSolver::depsilon_dr () const inline
References madness::copy(), madness::Function< T, NDIM >::unaryop(), and madness::Function< T, NDIM >::world().
realfunc DFTSolventSolver::dESP_drho (const realfunc & u) const inline
References madness::binary_op(), make_depsilon_drho(), pi, madness::plot_line(), and madness::Function< T, NDIM >::scale().
realfunc DFTSolventSolver::dfree_drho () const inline
References make_surface(), madness::Function< T, NDIM >::norm2(), madness::scale(), madness::Function< T, NDIM >::scale(), and madness::Function< T, NDIM >::world().
realfunc DFTSolventSolver::ESP () const inline
References make_normconst(), make_repsilon(), make_surfcharge(), max, madness::Function< T, NDIM >::norm2(), madness::print(), print(), madness::truncate(), and madness::NonlinearSolverND< NDIM >::update().
real_function_3d DFTSolventSolver::Laplace_ESP (std::vector< double > E) const inline
(8.0*std::pow(L,3.0));
References make_Laplace_surface_charge(), max, madness::norm2(), pi, madness::plot_line(), madness::print(), print(), madness::scale(), madness::truncate(), and madness::wall_time().
realfunc DFTSolventSolver::make_characteristic_func () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
realfunc DFTSolventSolver::make_depsilon_drho () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by dESP_drho().
vector_real_function_3d DFTSolventSolver::make_electric_field (const real_function_3d & u) const inline
References pi, madness::plot_line(), and madness::scale().
Referenced by ave_rxn_field().
realfunc DFTSolventSolver::make_epsilon () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
real_function_3d DFTSolventSolver::make_Laplace_surface_charge (const real_function_3d & u, std::vector< double > E = std::vector<double>(3,0.0)) const inline
References make_ratioepsilon().
Referenced by Laplace_ESP().
realfunc DFTSolventSolver::make_normconst () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by ESP().
realfunc DFTSolventSolver::make_ratioepsilon () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by make_Laplace_surface_charge(), and make_surfcharge().
realfunc DFTSolventSolver::make_repsilon () const inline
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by ESP().
realfunc DFTSolventSolver::make_surface () const inline
References madness::copy(), madness::Function< T, NDIM >::unaryop(), and madness::Function< T, NDIM >::world().
Referenced by cavitation_energy(), and dfree_drho().
realfunc DFTSolventSolver::make_surfcharge (const realfunc & u) const inline
References make_ratioepsilon(), pi, madness::scale(), and madness::Function< T, NDIM >::world().
Referenced by ESP().
The documentation for this class was generated from the following file:
abinitdftsolventsolver.h