MADNESS: madness::detail::RemoteCounter Class Reference
madness::detail::RemoteCounter Class Reference
Remote reference counter.
#include <worldref.h>
Public Member Functions
RemoteCounter ()
RemoteCounter (const RemoteCounter &other)
template<typename T >
RemoteCounter (World &w, const std::shared_ptr< T > &p)
~RemoteCounter ()
RemoteCounter & operator= (const RemoteCounter &other)
long use_count () const
Counter accessor.
bool unique () const
bool empty () const
bool is_local () const
bool has_owner () const
ProcessID owner () const
template<typename T >
const std::shared_ptr< T > & get_shared () const
WorldPtr< implT >::worldidT get_worldid () const
World & get_world () const
void swap (RemoteCounter &other)
Friends
template<typename , typename >
struct archive::ArchiveLoadImpl
template<typename , typename >
struct archive::ArchiveStoreImpl
Detailed Description
Remote reference counter.
Automatically counts local and remote references to an object. The reference count is incremented when the object is copied locally or serialized as part of communication.
Constructor & Destructor Documentation
madness::detail::RemoteCounter::RemoteCounter () inline
madness::detail::RemoteCounter::RemoteCounter (const RemoteCounter & other) inline
References madness::detail::WorldPtr< T >::is_local().
template<typename T > madness::detail::RemoteCounter::RemoteCounter (World & w, const std::shared_ptr< T > & p) inline explicit
madness::detail::RemoteCounter::~RemoteCounter () inline
Member Function Documentation
bool madness::detail::RemoteCounter::empty () const inline
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::operator bool().
template<typename T > const std::shared_ptr<T>& madness::detail::RemoteCounter::get_shared () const inline
References std::tr1::T().
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::get_shared().
World& madness::detail::RemoteCounter::get_world () const inline
References madness::detail::WorldPtr< T >::get_world().
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::get_world().
WorldPtr<implT>::worldidT madness::detail::RemoteCounter::get_worldid () const inline
References madness::detail::WorldPtr< T >::get_worldid().
Referenced by madness::detail::operator<<().
bool madness::detail::RemoteCounter::has_owner () const inline
References madness::detail::WorldPtr< T >::has_owner().
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::reset().
bool madness::detail::RemoteCounter::is_local () const inline
References madness::detail::WorldPtr< T >::is_local().
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::get(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::get_shared(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::is_local(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::operator*(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::operator->(), and madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::reset().
RemoteCounter& madness::detail::RemoteCounter::operator= (const RemoteCounter & other) inline
ProcessID madness::detail::RemoteCounter::owner () const inline
References madness::detail::WorldPtr< T >::owner().
Referenced by madness::detail::operator<<(), and madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::owner().
void madness::detail::RemoteCounter::swap (RemoteCounter & other) inline
References madness::detail::swap().
Referenced by madness::detail::swap().
bool madness::detail::RemoteCounter::unique () const inline
References use_count().
Referenced by madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::unique().
long madness::detail::RemoteCounter::use_count () const inline
Counter accessor.
Returns
The number of local and remote references
Exceptions
none
References madness::detail::WorldPtr< T >::is_local().
Referenced by madness::detail::operator<<(), unique(), and madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::use_count().
Friends And Related Function Documentation
template<typename , typename > friend struct archive::ArchiveLoadImpl friend
template<typename , typename > friend struct archive::ArchiveStoreImpl friend
The documentation for this class was generated from the following files:
worldref.h
worldref.cc