MADNESS: madness::TDA Class Reference
madness::TDA Class Reference
The TDA class: computes TDA and CIS calculations.
#include <TDA.h>
Public Member Functions
TDA (World &world, const SCF &calc, const vecfuncT &mos, const std::string input)
void setup (const vecfuncT &mos, const std::string input)
reads the input file and calculates needed functions
double memwatch (const xfunctionsT &xfunctions, const bool printout) const
try to gain a little bit information about the used memory
void solve (xfunctionsT &xfunctions)
Solves the CIS or TDA equations.
void solve_sequential (xfunctionsT xfunctions)
Solves the CIS or TDA equations sequentially for a set of preconverged xfunctions.
const SCF & get_calc () const
Returns the MolDFT calulation.
const bool print_grid_TDA () const
xfunctionsT get_converged_xfunctions ()
Detailed Description
The TDA class: computes TDA and CIS calculations.
Constructor & Destructor Documentation
madness::TDA::TDA (World & world, const SCF & calc, const vecfuncT & mos, const std::string input) inline
the constructor
Parameters
[in] world the world
[in] calc the SCF calcualtion
[in] mos the occupied molecular orbitals from the scf calculation
[in] input name of the input file
[in] lowt will be used later to ditinguish between low and high threshold computations (not yet implemented)
References setup().
Member Function Documentation
const SCF& madness::TDA::get_calc () const inline
Returns the MolDFT calulation.
Referenced by main(), and setup().
xfunctionsT madness::TDA::get_converged_xfunctions () inline
Referenced by main().
double madness::TDA::memwatch (const xfunctionsT & xfunctions, const bool printout) const inline
try to gain a little bit information about the used memory
References madness::get_size(), MADNESS_EXCEPTION, and madness::print().
const bool madness::TDA::print_grid_TDA () const inline
void madness::TDA::setup (const vecfuncT & mos, const std::string input) inline
reads the input file and calculates needed functions
References madness::SCF::aeps, madness::f, get_calc(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::kain_solver_helper_struct::initialize(), madness::CalculationParameters::lo, MADNESS_EXCEPTION, madness::CalculationParameters::nalpha, madness::Function< T, NDIM >::norm2(), madness::SCF::param, madness::position_stream(), madness::print(), madness::World::rank(), and madness::truncate().
Referenced by TDA().
void TDA::solve (xfunctionsT & xfunctions)
Solves the CIS or TDA equations.
References madness::kain_solver_helper_struct::increase_subspace(), madness::TDA_TIMER::info(), madness::World::rank(), and madness::kain_solver_helper_struct::sanity_check().
Referenced by main().
void TDA::solve_sequential (xfunctionsT xfunctions)
Solves the CIS or TDA equations sequentially for a set of preconverged xfunctions.
References delta, madness::error(), mpfr::fabs(), madness::TDA_TIMER::info(), max, madness::plot_plane(), madness::print(), madness::XNonlinearSolver< T, C, Alloc >::set_maxsub(), madness::World::size(), madness::XNonlinearSolver< T, C, Alloc >::update(), and madness::xfunction::x.
The documentation for this class was generated from the following files:
TDA.h
TDA.cc