MADNESS: madness::LLRVDomainMask Class Reference
madness::LLRVDomainMask Class Reference
MADNESS libraries » Multiresolution analaysis » Preliminary support for interior boundary conditions
Provides the Li-Lowengrub-Ratz-Voight (LLRV) domain mask characteristic functions.
#include <sdf_domainmask.h>
Public Member Functions
LLRVDomainMask (double epsilon)
Constructor for the domain mask.
double mask (double d) const
Value of characteristic function at normal distance d from the surface.
double dmask (double d) const
Derivative of characteristic function with respect to the normal distance.
double surface (double d) const
Value of surface function at distance d normal to surface.
double dsurface (double d) const
Value of d(surface)/ddistance.
virtual ~LLRVDomainMask ()
Public Member Functions inherited from madness::DomainMaskInterface
virtual ~DomainMaskInterface ()
Protected Attributes
const double epsilon
The width of the transition region.
Detailed Description
Provides the Li-Lowengrub-Ratz-Voight (LLRV) domain mask characteristic functions.
See X. Li, J. Lowengrub, A. Rätz, and A. Voight, ``Solving PDEs in Complex Geometries: A Diffuse Domain Approach,'' Commun. Math. Sci., 7, p81-107, 2009.
Given a signed distance, this class implements in the domain mask and surface functions from the above reference. For the domain mask,
where is the signed distance. The normalized surface function is
The constant is chosen to fulfill
This class assumes the domain mask is uniformly 0 or 1 outside signed distances since the switching function becomes 0/1 to machine precision at these levels. Specifically, for this function the parameter is an effective measure of the full width of the surface layer since
and
Constructor & Destructor Documentation
madness::LLRVDomainMask::LLRVDomainMask (double epsilon) inline
Constructor for the domain mask.
Parameters
[in] epsilon The effective width of the surface
virtual madness::LLRVDomainMask::~LLRVDomainMask () inline virtual
Member Function Documentation
double madness::LLRVDomainMask::dmask (double d) const inline virtual
Derivative of characteristic function with respect to the normal distance.
Parameters
[in] d The signed distance
Returns
The derivative
Implements madness::DomainMaskInterface.
References epsilon, mpfr::fabs(), and mpfr::tanh().
Referenced by dsurface().
double madness::LLRVDomainMask::dsurface (double d) const inline virtual
Value of d(surface)/ddistance.
Parameters
[in] d The signed distance
Returns
The derivative of the surface function
Implements madness::DomainMaskInterface.
References dmask(), epsilon, and mask().
double madness::LLRVDomainMask::mask (double d) const inline virtual
Value of characteristic function at normal distance d from the surface.
Parameters
[in] d The signed distance. Negative is inside,'' positive isoutside.''
Returns
The domain mask
Implements madness::DomainMaskInterface.
References mpfr::tanh().
Referenced by dsurface(), and surface().
double madness::LLRVDomainMask::surface (double d) const inline virtual
Value of surface function at distance d normal to surface.
Parameters
[in] d The signed distance
Returns
The value of the surface function
Implements madness::DomainMaskInterface.
References epsilon, and mask().
Member Data Documentation
const double madness::LLRVDomainMask::epsilon protected
The width of the transition region.
Referenced by dmask(), dsurface(), and surface().
The documentation for this class was generated from the following file:
sdf_domainmask.h