MADNESS: ScreenSolventPotential Class Reference
ScreenSolventPotential Class Reference
#include <svpe.h>
Public Member Functions
ScreenSolventPotential (World &world, double &sigma, double &epsilon_1, double &epsilon_2, int &maxiter, std::vector< double > &atomic_radii, std::vector< madness::Vector< double, 3 > > atomic_coords)
realfunc make_surface_charge (const realfunc &u) const
Given the full Coulomb potential computes the surface charge.
double make_cav_energy (const double &surface_tension) const
realfunc ScreenReactionPotential (World &world, int maxiter, const realfunc rhot, bool solventplot) const
Constructor & Destructor Documentation
ScreenSolventPotential::ScreenSolventPotential (World & world, double & sigma, double & epsilon_1, double & epsilon_2, int & maxiter, std::vector< double > & atomic_radii, std::vector< madness::Vector< double, 3 > > atomic_coords) inline
References pi, madness::scale(), madness::truncate(), and madness::Function< T, NDIM >::truncate().
Member Function Documentation
double ScreenSolventPotential::make_cav_energy (const double & surface_tension) const inline
References madness::Function< T, NDIM >::trace().
realfunc ScreenSolventPotential::make_surface_charge (const realfunc & u) const inline
Given the full Coulomb potential computes the surface charge.
References madness::truncate(), and madness::Function< T, NDIM >::world().
Referenced by ScreenReactionPotential().
realfunc ScreenSolventPotential::ScreenReactionPotential (World & world, int maxiter, const realfunc rhot, bool solventplot) const inline
References make_surface_charge(), max, madness::Function< T, NDIM >::norm2(), op(), madness::plot_line(), madness::plotdx(), madness::print(), print(), madness::Function< T, NDIM >::trace(), madness::truncate(), and madness::NonlinearSolverND< NDIM >::update().
The documentation for this class was generated from the following file:
svpe.h