MADNESS: madness::AtomicBasis Class Reference
madness::AtomicBasis Class Reference
Represents multiple shells of contracted gaussians on a single center.
#include <molecularbasis.h>
Public Member Functions
AtomicBasis ()
AtomicBasis (const std::vector< ContractedGaussianShell > &g)
void set_guess_info (const Tensor< double > &dmat, const Tensor< double > &avec, const Tensor< double > &bvec)
int nbf () const
Returns the number of basis functions on the center.
int nshell () const
Returns the number of shells on the center.
const std::vector
< ContractedGaussianShell > & get_shells () const
Returns a const reference to the shells.
double * eval (double x, double y, double z, double *bf) const
Evaluates the basis functions at point x, y, z relative to atomic center.
double eval_guess_density (double x, double y, double z) const
Evaluates the guess atomic density at point x, y, z relative to atomic center.
const ContractedGaussianShell & get_shell_from_basis_function (int ibf, int &ibf_in_shell) const
Return shell that contains basis function ibf and also return index of function in the shell.
bool has_guess_info () const
const Tensor< double > & get_dmat () const
const Tensor< double > & get_avec () const
const Tensor< double > & get_bvec () const
template<typename Archive >
void serialize (Archive &ar)
Detailed Description
Represents multiple shells of contracted gaussians on a single center.
Constructor & Destructor Documentation
madness::AtomicBasis::AtomicBasis () inline
madness::AtomicBasis::AtomicBasis (const std::vector< ContractedGaussianShell > & g) inline
References max.
Member Function Documentation
double* madness::AtomicBasis::eval (double x, double y, double z, double * bf) const inline
Evaluates the basis functions at point x, y, z relative to atomic center.
The array bf[] must be large enough to hold nbf() values.
Returned is the incremented pointer.
Referenced by AtomicBasis::eval_guess_density(), and eval_guess_density().
double madness::AtomicBasis::eval_guess_density (double x, double y, double z) const inline
Evaluates the guess atomic density at point x, y, z relative to atomic center.
References eval(), has_guess_info(), and mpfr::sum().
const Tensor<double>& madness::AtomicBasis::get_avec () const inline
const Tensor<double>& madness::AtomicBasis::get_bvec () const inline
const Tensor<double>& madness::AtomicBasis::get_dmat () const inline
Referenced by operator<<(), and madness::operator<<().
const ContractedGaussianShell& madness::AtomicBasis::get_shell_from_basis_function (int ibf, int & ibf_in_shell) const inline
Return shell that contains basis function ibf and also return index of function in the shell.
References MADNESS_EXCEPTION, madness::ContractedGaussianShell::nbf(), and nbf().
const std::vector<ContractedGaussianShell>& madness::AtomicBasis::get_shells () const inline
Returns a const reference to the shells.
Referenced by operator<<(), and madness::operator<<().
bool madness::AtomicBasis::has_guess_info () const inline
Referenced by AtomicBasis::eval_guess_density(), eval_guess_density(), operator<<(), and madness::operator<<().
int madness::AtomicBasis::nbf () const inline
Returns the number of basis functions on the center.
Referenced by AtomicBasis::get_shell_from_basis_function(), and get_shell_from_basis_function().
int madness::AtomicBasis::nshell () const inline
Returns the number of shells on the center.
Referenced by operator<<(), and madness::operator<<().
template<typename Archive > void madness::AtomicBasis::serialize (Archive & ar) inline
void madness::AtomicBasis::set_guess_info (const Tensor< double > & dmat, const Tensor< double > & avec, const Tensor< double > & bvec) inline
References madness::copy().
The documentation for this class was generated from the following file:
chem/molecularbasis.h