MADNESS: madness::Hash_private::bin< keyT, valueT > Class Template Reference
madness::Hash_private::bin< keyT, valueT > Class Template Reference
#include <worldhashmap.h>
Public Member Functions
bin ()
~bin ()
void clear ()
entryT * find (const keyT &key, const int lockmode) const
std::pair< entryT *, bool > insert (const datumT &datum, int lockmode)
bool del (const keyT &key, int lockmode)
std::size_t size () const
Public Attributes
entryT *volatile p
int volatile ninbin
Constructor & Destructor Documentation
template<class keyT , class valueT > madness::Hash_private::bin< keyT, valueT >::bin () inline
template<class keyT , class valueT > madness::Hash_private::bin< keyT, valueT >::~bin () inline
References madness::Hash_private::bin< keyT, valueT >::clear().
Member Function Documentation
template<class keyT , class valueT > void madness::Hash_private::bin< keyT, valueT >::clear () inline
References madness::Spinlock::lock(), madness::Hash_private::entry< keyT, valueT >::next, madness::Hash_private::bin< keyT, valueT >::p, and madness::Spinlock::unlock().
Referenced by madness::Hash_private::bin< keyT, valueT >::~bin().
template<class keyT , class valueT > bool madness::Hash_private::bin< keyT, valueT >::del (const keyT & key, int lockmode) inline
References madness::Spinlock::lock(), madness::Hash_private::entry< keyT, valueT >::next, madness::Hash_private::bin< keyT, valueT >::ninbin, and madness::Spinlock::unlock().
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::erase().
template<class keyT , class valueT > entryT* madness::Hash_private::bin< keyT, valueT >::find (const keyT & key, const int lockmode) const inline
References madness::Spinlock::lock(), madness::MutexReaderWriter::try_lock(), madness::Spinlock::unlock(), and madness::MutexWaiter::wait().
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::find().
template<class keyT , class valueT > std::pair<entryT*,bool> madness::Hash_private::bin< keyT, valueT >::insert (const datumT & datum, int lockmode) inline
References madness::Spinlock::lock(), madness::Hash_private::bin< keyT, valueT >::ninbin, madness::MutexReaderWriter::try_lock(), madness::Spinlock::unlock(), and madness::MutexWaiter::wait().
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::insert().
template<class keyT , class valueT > std::size_t madness::Hash_private::bin< keyT, valueT >::size () const inline
References madness::Hash_private::bin< keyT, valueT >::ninbin.
Member Data Documentation
template<class keyT , class valueT > int volatile madness::Hash_private::bin< keyT, valueT >::ninbin
Referenced by madness::Hash_private::bin< keyT, valueT >::del(), madness::Hash_private::bin< keyT, valueT >::insert(), and madness::Hash_private::bin< keyT, valueT >::size().
template<class keyT , class valueT > entryT* volatile madness::Hash_private::bin< keyT, valueT >::p
Referenced by madness::Hash_private::bin< keyT, valueT >::clear().
The documentation for this class was generated from the following file:
worldhashmap.h