MADNESS: TiXmlUnknown Class Reference
TiXmlUnknown Class Reference
#include <tinyxml.h>
Public Member Functions
TiXmlUnknown ()
virtual ~TiXmlUnknown ()
TiXmlUnknown (const TiXmlUnknown &copy)
void operator= (const TiXmlUnknown &copy)
virtual TiXmlNode * Clone () const
Creates a copy of this Unknown and returns it.
virtual void Print (FILE *cfile, int depth) const
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Public Member Functions inherited from TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
const std::string & ValueStr () const
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
const TiXmlDocument * GetDocument () const
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
void CopyTo (TiXmlUnknown *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Protected Member Functions inherited from TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Additional Inherited Members
Public Types inherited from TiXmlNode
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_DOCUMENT_TOP_ONLY, TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
Any tag that tinyXml doesn't recognize is saved as an unknown. It is a tag of text, but should not be modified. It will be written back to the XML, unchanged, when the file is saved.
DTD tags get thrown into TiXmlUnknowns.
Constructor & Destructor Documentation
TiXmlUnknown::TiXmlUnknown () inline
Referenced by Clone().
virtual TiXmlUnknown::~TiXmlUnknown () inline virtual
TiXmlUnknown::TiXmlUnknown (const TiXmlUnknown & copy) inline
References CopyTo().
Member Function Documentation
bool TiXmlUnknown::Accept (TiXmlVisitor * content) const virtual
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
References TiXmlVisitor::Visit().
TiXmlNode * TiXmlUnknown::Clone () const virtual
Creates a copy of this Unknown and returns it.
Implements TiXmlNode.
References CopyTo(), and TiXmlUnknown().
void TiXmlUnknown::CopyTo (TiXmlUnknown * target) const protected
References TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlUnknown().
void TiXmlUnknown::operator= (const TiXmlUnknown & copy) inline
References CopyTo().
const char * TiXmlUnknown::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements TiXmlBase.
References TiXmlNode::GetDocument(), TiXmlBase::location, TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::TIXML_ERROR_PARSING_UNKNOWN, and TiXmlNode::value.
void TiXmlUnknown::Print (FILE * cfile, int depth) const virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
References TiXmlNode::value.
void TiXmlUnknown::StreamIn (std::istream * in, TIXML_STRING * tag) protected virtual
Implements TiXmlNode.
References c, TiXmlNode::GetDocument(), TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, and TiXmlBase::TIXML_ERROR_EMBEDDED_NULL.
virtual const TiXmlUnknown* TiXmlUnknown::ToUnknown () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
virtual TiXmlUnknown* TiXmlUnknown::ToUnknown () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc