MADNESS: testing::TestCase Class Reference
testing::TestCase Class Reference
#include <gtest.h>
Public Member Functions
TestCase (const char *name, const char *a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual ~TestCase ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
Friends
class Test
class internal::UnitTestImpl
Constructor & Destructor Documentation
testing::TestCase::TestCase (const char * name, const char * a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
testing::TestCase::~TestCase () virtual
References testing::internal::ForEach().
Member Function Documentation
const TestResult& testing::TestCase::ad_hoc_test_result () const inline
int testing::TestCase::disabled_test_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::disabled_test_count().
TimeInMillis testing::TestCase::elapsed_time () const inline
bool testing::TestCase::Failed () const inline
int testing::TestCase::failed_test_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::failed_test_count().
const TestInfo * testing::TestCase::GetTestInfo (int i) const
References testing::internal::GetElementOr().
const char* testing::TestCase::name () const inline
References name_.
Referenced by testing::internal::UnitTestImpl::FilterTests(), and testing::internal::UnitTestImpl::ListTestsMatchingFilter().
bool testing::TestCase::Passed () const inline
int testing::TestCase::reportable_disabled_test_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::reportable_disabled_test_count().
int testing::TestCase::reportable_test_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::reportable_test_count().
bool testing::TestCase::should_run () const inline
Referenced by testing::internal::UnitTestImpl::FilterTests().
int testing::TestCase::successful_test_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::successful_test_count().
int testing::TestCase::test_to_run_count () const
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::test_to_run_count().
int testing::TestCase::total_test_count () const
Referenced by testing::internal::UnitTestImpl::total_test_count().
const char* testing::TestCase::type_param () const inline
Referenced by testing::internal::UnitTestImpl::ListTestsMatchingFilter().
Friends And Related Function Documentation
friend class internal::UnitTestImpl friend
friend class Test friend
The documentation for this class was generated from the following files:
gtest.h
gtest.cc