MADNESS: LevelPmap Class Reference
LevelPmap Class Reference
#include <electronicstructureapp.h>
Public Member Functions
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Maps key to processor.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< NDIM > &key) const
Maps key to processor.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Maps key to processor.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
LevelPmap ()
LevelPmap (World &world)
ProcessID owner (const Key< 3 > &key) const
Find the owner of a given key.
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< 3 > >
virtual ~WorldDCPmapInterface ()
virtual void print () const
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
Public Member Functions inherited from madness::WorldDCPmapInterface< Key< NDIM > >
virtual ~WorldDCPmapInterface ()
virtual void print () const
void register_callback (ptrT ptr)
Registers object for receipt of redistribute callbacks.
void deregister_callback (ptrT ptr)
Deregisters object for receipt of redistribute callbacks.
void redistribute (World &world, const std::shared_ptr< WorldDCPmapInterface< Key< NDIM > > > &newpmap)
Invoking this switches all registered objects from this process map to the new one.
Additional Inherited Members
Public Types inherited from madness::WorldDCPmapInterface< Key< 3 > >
typedef
WorldDCRedistributeInterface
< Key< 3 > > * ptrT
Public Types inherited from madness::WorldDCPmapInterface< Key< NDIM > >
typedef
WorldDCRedistributeInterface
< Key< NDIM > > * ptrT
Constructor & Destructor Documentation
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
LevelPmap::LevelPmap () inline
LevelPmap::LevelPmap (World & world) inline
Member Function Documentation
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Find the owner of a given key.
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), madness::Key< NDIM >::level(), and madness::Key< NDIM >::parent().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), and madness::Key< NDIM >::level().
ProcessID LevelPmap::owner (const Key< NDIM > & key) const inline virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implements madness::WorldDCPmapInterface< Key< NDIM > >.
References madness::Key< NDIM >::hash(), and madness::Key< NDIM >::level().
ProcessID LevelPmap::owner (const Key< 3 > & key) const inline virtual
Maps key to processor.
Parameters
[in] key Key for container
Returns
Processor that logically owns the key
Implements madness::WorldDCPmapInterface< Key< 3 > >.
References madness::Key< NDIM >::hash(), and madness::Key< NDIM >::level().
The documentation for this class was generated from the following files:
electronicstructureapp.h
jacob/mcpfit.cc
jacob/moldft.cc
moldft-elem.cc
extra.h
tdse1.cc
tdse.confused.cc
plotao.cc