MADNESS: madness::Nemo Class Reference
madness::Nemo Class Reference
The Nemo class.
#include <nemo.h>
Public Member Functions
Nemo (World &world1, std::shared_ptr< SCF > calc)
ctor
double value ()
double value (const Tensor< double > &x)
Should return the value of the objective function.
Tensor< double > gradient (const Tensor< double > &x)
Should return the derivative of the function.
std::shared_ptr< SCF > get_calc () const
tensorT compute_fock_matrix (const vecfuncT &nemo, const tensorT &occ) const
compute the Fock matrix from scratch
Public Member Functions inherited from madness::OptimizationTargetInterface
virtual bool provides_gradient () const
Override this to return true if the derivative is implemented.
virtual void value_and_gradient (const Tensor< double > &x, double &value, Tensor< double > &gradient)
Reimplement if more efficient to evaluate both value and gradient in one call.
double test_gradient (Tensor< double > &x, double value_precision, bool doprint=true)
Numerical test of the derivative ... optionally prints to stdout, returns max abs error.
virtual ~OptimizationTargetInterface ()
Public Attributes
std::shared_ptr
< NuclearCorrelationFactor > nuclear_correlation
the nuclear correlation factor
real_function_3d R
the nuclear correlation factor
real_function_3d R_inverse
the inverse nuclear correlation factor
Detailed Description
The Nemo class.
Constructor & Destructor Documentation
madness::Nemo::Nemo (World & world1, std::shared_ptr< SCF > calc) inline
ctor
Parameters
[in] world the world
[in] calc the SCF
References madness::create_nuclear_correlation_factor(), SCFParameters::econv, SCFParameters::lo, nuclear_correlation, SCF::param, R, and R_inverse.
Member Function Documentation
tensorT madness::Nemo::compute_fock_matrix (const vecfuncT & nemo, const tensorT & occ) const
compute the Fock matrix from scratch
References madness::add(), madness::mul(), psi(), R, and madness::sub().
Referenced by value().
std::shared_ptr<SCF> madness::Nemo::get_calc () const inline
Referenced by main(), and madness::HartreeFock< T, NDIM >::value().
Tensor<double> madness::Nemo::gradient (const Tensor< double > & x) inline virtual
Should return the derivative of the function.
Reimplemented from madness::OptimizationTargetInterface.
References MADNESS_EXCEPTION.
double madness::Nemo::value () inline
References value().
Referenced by main(), madness::HartreeFock< T, NDIM >::value(), and value().
double madness::Nemo::value (const Tensor< double > & x) virtual
Should return the value of the objective function.
Implements madness::OptimizationTargetInterface.
References compute_fock_matrix(), energy(), madness::mul(), madness::print(), psi(), R, R_inverse, madness::World::rank(), and madness::truncate().
Member Data Documentation
std::shared_ptr<NuclearCorrelationFactor> madness::Nemo::nuclear_correlation
the nuclear correlation factor
Referenced by main(), Nemo(), and madness::HartreeFock< T, NDIM >::value().
real_function_3d madness::Nemo::R
the nuclear correlation factor
Referenced by compute_fock_matrix(), Nemo(), madness::HartreeFock< T, NDIM >::value(), and value().
real_function_3d madness::Nemo::R_inverse
the inverse nuclear correlation factor
Referenced by Nemo(), and value().
The documentation for this class was generated from the following files:
nemo.h
apps/chem/nemo.cc