MADNESS: mpfr::mpreal Class Reference
mpfr::mpreal Class Reference
#include <mpreal.h>
Public Member Functions
mpreal ()
mpreal (const mpreal &u)
mpreal (const mpfr_t u)
mpreal (const mpf_t u)
mpreal (const mpz_t u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const mpq_t u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const double u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const long double u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const unsigned long int u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const unsigned int u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const long int u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const int u, mp_prec_t prec=default_prec, mp_rnd_t mode=default_rnd)
mpreal (const char *s, mp_prec_t prec=default_prec, int base=default_base, mp_rnd_t mode=default_rnd)
~mpreal ()
mpreal & operator= (const mpreal &v)
mpreal & operator= (const mpf_t v)
mpreal & operator= (const mpz_t v)
mpreal & operator= (const mpq_t v)
mpreal & operator= (const long double v)
mpreal & operator= (const double v)
mpreal & operator= (const unsigned long int v)
mpreal & operator= (const unsigned int v)
mpreal & operator= (const long int v)
mpreal & operator= (const int v)
mpreal & operator= (const char *s)
mpreal & operator+= (const mpreal &v)
mpreal & operator+= (const mpf_t v)
mpreal & operator+= (const mpz_t v)
mpreal & operator+= (const mpq_t v)
mpreal & operator+= (const long double u)
mpreal & operator+= (const double u)
mpreal & operator+= (const unsigned long int u)
mpreal & operator+= (const unsigned int u)
mpreal & operator+= (const long int u)
mpreal & operator+= (const int u)
const mpreal operator+ () const
mpreal & operator++ ()
const mpreal operator++ (int)
mpreal & operator-= (const mpreal &v)
mpreal & operator-= (const mpz_t v)
mpreal & operator-= (const mpq_t v)
mpreal & operator-= (const long double u)
mpreal & operator-= (const double u)
mpreal & operator-= (const unsigned long int u)
mpreal & operator-= (const unsigned int u)
mpreal & operator-= (const long int u)
mpreal & operator-= (const int u)
const mpreal operator- () const
mpreal & operator-- ()
const mpreal operator-- (int)
mpreal & operator*= (const mpreal &v)
mpreal & operator*= (const mpz_t v)
mpreal & operator*= (const mpq_t v)
mpreal & operator*= (const long double v)
mpreal & operator*= (const double v)
mpreal & operator*= (const unsigned long int v)
mpreal & operator*= (const unsigned int v)
mpreal & operator*= (const long int v)
mpreal & operator*= (const int v)
mpreal & operator/= (const mpreal &v)
mpreal & operator/= (const mpz_t v)
mpreal & operator/= (const mpq_t v)
mpreal & operator/= (const long double v)
mpreal & operator/= (const double v)
mpreal & operator/= (const unsigned long int v)
mpreal & operator/= (const unsigned int v)
mpreal & operator/= (const long int v)
mpreal & operator/= (const int v)
mpreal & operator<<= (const unsigned long int u)
mpreal & operator<<= (const unsigned int u)
mpreal & operator<<= (const long int u)
mpreal & operator<<= (const int u)
mpreal & operator>>= (const unsigned long int u)
mpreal & operator>>= (const unsigned int u)
mpreal & operator>>= (const long int u)
mpreal & operator>>= (const int u)
operator long double () const
operator double () const
operator float () const
operator unsigned long () const
operator unsigned int () const
operator long () const
operator std::string () const
operator mpfr_ptr ()
mp_prec_t get_prec () const
void set_prec (mp_prec_t prec, mp_rnd_t rnd_mode=default_rnd)
void set_inf (int sign=+1)
void set_nan ()
void set_sign (int sign, mp_rnd_t rnd_mode=default_rnd)
mp_exp_t get_exp ()
int set_exp (mp_exp_t e)
int check_range (int t, mp_rnd_t rnd_mode=default_rnd)
int subnormalize (int t, mp_rnd_t rnd_mode=default_rnd)
bool fits_in_bits (double x, int n)
std::string to_string (size_t n=0, int b=default_base, mp_rnd_t mode=default_rnd) const
Static Public Member Functions
static void set_default_prec (mp_prec_t prec)
static mp_prec_t get_default_prec ()
static void set_default_base (int base)
static int get_default_base ()
static void set_double_bits (int dbits)
static int get_double_bits ()
static void set_default_rnd (mp_rnd_t rnd_mode)
static mp_rnd_t get_default_rnd ()
static mp_exp_t get_emin (void)
static mp_exp_t get_emax (void)
static mp_exp_t get_emin_min (void)
static mp_exp_t get_emin_max (void)
static mp_exp_t get_emax_min (void)
static mp_exp_t get_emax_max (void)
static int set_emin (mp_exp_t exp)
static int set_emax (mp_exp_t exp)
Static Public Attributes
static mp_rnd_t default_rnd = mpfr_get_default_rounding_mode()
static mp_prec_t default_prec = mpfr_get_default_prec()
static int default_base = 10
static int double_bits = -1
Friends
const mpreal operator- (const unsigned long int b, const mpreal &a)
const mpreal operator- (const unsigned int b, const mpreal &a)
const mpreal operator- (const long int b, const mpreal &a)
const mpreal operator- (const int b, const mpreal &a)
const mpreal operator- (const double b, const mpreal &a)
const mpreal operator/ (const unsigned long int b, const mpreal &a)
const mpreal operator/ (const unsigned int b, const mpreal &a)
const mpreal operator/ (const long int b, const mpreal &a)
const mpreal operator/ (const int b, const mpreal &a)
const mpreal operator/ (const double b, const mpreal &a)
bool operator> (const mpreal &a, const mpreal &b)
bool operator>= (const mpreal &a, const mpreal &b)
bool operator< (const mpreal &a, const mpreal &b)
bool operator<= (const mpreal &a, const mpreal &b)
bool operator== (const mpreal &a, const mpreal &b)
bool operator!= (const mpreal &a, const mpreal &b)
const mpreal sqr (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const unsigned long int v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal cbrt (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal root (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const mpz_t b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal fabs (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal abs (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal dim (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal mul_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal mul_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal div_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal div_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode=mpreal::default_rnd)
int cmpabs (const mpreal &a, const mpreal &b)
const mpreal log (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal log2 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal log10 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal exp (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal exp2 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal exp10 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal cos (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sin (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal tan (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sec (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal csc (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal cot (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
int sin_cos (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal acos (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal asin (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal atan (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal atan2 (const mpreal &y, const mpreal &x, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal cosh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sinh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal tanh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sech (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal csch (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal coth (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal acosh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal asinh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal atanh (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal fac_ui (unsigned long int v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal log1p (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal expm1 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal eint (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal gamma (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal lngamma (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal lgamma (const mpreal &v, int *signp, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal zeta (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal erf (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal erfc (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _j0 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _j1 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _jn (long n, const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _y0 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _y1 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal _yn (long n, const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal fma (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal fms (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal agm (const mpreal &v1, const mpreal &v2, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal hypot (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sum (const mpreal tab[], unsigned long int n, mp_rnd_t rnd_mode=mpreal::default_rnd)
int sgn (const mpreal &v)
int sinh_cosh (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal li2 (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal fmod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal rec_sqrt (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal frexp (const mpreal &v, mp_exp_t *exp)
const mpreal ldexp (const mpreal &v, mp_exp_t exp)
const mpreal modf (const mpreal &v, mpreal &n)
const mpreal const_log2 (mp_prec_t prec=mpreal::default_prec, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal const_pi (mp_prec_t prec=mpreal::default_prec, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal const_euler (mp_prec_t prec=mpreal::default_prec, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal const_catalan (mp_prec_t prec=mpreal::default_prec, mp_rnd_t rnd_mode=mpreal::default_rnd)
std::ostream & operator<< (std::ostream &os, const mpreal &v)
std::istream & operator>> (std::istream &is, mpreal &v)
const mpreal rint (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal ceil (const mpreal &v)
const mpreal floor (const mpreal &v)
const mpreal round (const mpreal &v)
const mpreal trunc (const mpreal &v)
const mpreal rint_ceil (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal rint_floor (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal rint_round (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal rint_trunc (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal frac (const mpreal &v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal remainder (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal remquo (long *q, const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal nexttoward (const mpreal &x, const mpreal &y)
const mpreal nextabove (const mpreal &x)
const mpreal nextbelow (const mpreal &x)
const mpreal urandomb (gmp_randstate_t &state)
const mpreal random2 (mp_size_t size, mp_exp_t exp)
bool _isnan (const mpreal &v)
bool _isinf (const mpreal &v)
bool _isnum (const mpreal &v)
bool _iszero (const mpreal &v)
bool _isint (const mpreal &v)
void swap (mpreal &x, mpreal &y)
const mpreal max (const mpreal &x, const mpreal &y)
const mpreal min (const mpreal &x, const mpreal &y)
Constructor & Destructor Documentation
mpfr::mpreal::mpreal ()
References default_prec, and default_rnd.
Referenced by operator*=(), operator+(), operator+=(), operator-=(), and operator/=().
mpfr::mpreal::mpreal (const mpreal & u)
References default_rnd.
mpfr::mpreal::mpreal (const mpfr_t u)
References default_rnd.
mpfr::mpreal::mpreal (const mpf_t u)
References default_rnd.
mpfr::mpreal::mpreal (const mpz_t u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
References default_rnd.
mpfr::mpreal::mpreal (const mpq_t u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
References default_rnd.
mpfr::mpreal::mpreal (const double u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
References double_bits, and fits_in_bits().
mpfr::mpreal::mpreal (const long double u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
mpfr::mpreal::mpreal (const unsigned long int u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
mpfr::mpreal::mpreal (const unsigned int u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
mpfr::mpreal::mpreal (const long int u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
mpfr::mpreal::mpreal (const int u, mp_prec_t prec = default_prec, mp_rnd_t mode = default_rnd)
mpfr::mpreal::mpreal (const char * s, mp_prec_t prec = default_prec, int base = default_base, mp_rnd_t mode = default_rnd)
mpfr::mpreal::~mpreal ()
Member Function Documentation
int mpfr::mpreal::check_range (int t, mp_rnd_t rnd_mode = default_rnd) inline
bool mpfr::mpreal::fits_in_bits (double x, int n) inline
References mpfr::frexp(), IsInf, mpfr::ldexp(), and mpfr::modf().
Referenced by mpreal(), and operator=().
int mpfr::mpreal::get_default_base () inline static
References default_base.
mp_prec_t mpfr::mpreal::get_default_prec () inline static
Referenced by conhyp().
mp_rnd_t mpfr::mpreal::get_default_rnd () inline static
int mpfr::mpreal::get_double_bits () inline static
References double_bits.
mp_exp_t mpfr::mpreal::get_emax (void) inline static
mp_exp_t mpfr::mpreal::get_emax_max (void) inline static
mp_exp_t mpfr::mpreal::get_emax_min (void) inline static
mp_exp_t mpfr::mpreal::get_emin (void) inline static
mp_exp_t mpfr::mpreal::get_emin_max (void) inline static
mp_exp_t mpfr::mpreal::get_emin_min (void) inline static
mp_exp_t mpfr::mpreal::get_exp () inline
Referenced by mpfr::frexp().
mp_prec_t mpfr::mpreal::get_prec () const inline
Referenced by mpfr::agm(), mpfr::atan2(), mpfr::fma(), mpfr::fmod(), mpfr::fms(), mpfr::hypot(), mpfr::operator*(), mpfr::operator+(), mpfr::operator-(), mpfr::operator/(), mpfr::remainder(), and mpfr::remquo().
mpfr::mpreal::operator double () const inline
mpfr::mpreal::operator float () const inline
mpfr::mpreal::operator long () const inline
mpfr::mpreal::operator long double () const inline
mpfr::mpreal::operator mpfr_ptr () inline
mpfr::mpreal::operator std::string () const inline
References mpfr::to_string().
mpfr::mpreal::operator unsigned int () const inline
mpfr::mpreal::operator unsigned long () const inline
mpreal & mpfr::mpreal::operator*= (const mpreal & v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const mpz_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const mpq_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const long double v) inline
References mpreal().
mpreal & mpfr::mpreal::operator*= (const double v) inline
References default_rnd, and mpreal().
mpreal & mpfr::mpreal::operator*= (const unsigned long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const unsigned int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator*= (const int v) inline
References default_rnd.
const mpreal mpfr::mpreal::operator+ () const inline
References mpreal().
mpreal & mpfr::mpreal::operator++ () inline
const mpreal mpfr::mpreal::operator++ (int) inline
mpreal & mpfr::mpreal::operator+= (const mpreal & v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const mpf_t v) inline
References mpreal().
mpreal & mpfr::mpreal::operator+= (const mpz_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const mpq_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const long double u) inline
References mpreal().
mpreal & mpfr::mpreal::operator+= (const double u) inline
References default_rnd, and mpreal().
mpreal & mpfr::mpreal::operator+= (const unsigned long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const unsigned int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator+= (const int u) inline
References default_rnd.
const mpreal mpfr::mpreal::operator- () const inline
References default_rnd.
mpreal & mpfr::mpreal::operator-- () inline
const mpreal mpfr::mpreal::operator-- (int) inline
mpreal & mpfr::mpreal::operator-= (const mpreal & v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const mpz_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const mpq_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const long double u) inline
References mpreal().
mpreal & mpfr::mpreal::operator-= (const double u) inline
References default_rnd, and mpreal().
mpreal & mpfr::mpreal::operator-= (const unsigned long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const unsigned int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator-= (const int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const mpreal & v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const mpz_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const mpq_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const long double v) inline
References mpreal().
mpreal & mpfr::mpreal::operator/= (const double v) inline
References default_rnd, and mpreal().
mpreal & mpfr::mpreal::operator/= (const unsigned long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const unsigned int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator/= (const int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator<<= (const unsigned long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator<<= (const unsigned int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator<<= (const long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator<<= (const int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const mpreal & v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const mpf_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const mpz_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const mpq_t v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const long double v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const double v) inline
References default_rnd, double_bits, and fits_in_bits().
mpreal & mpfr::mpreal::operator= (const unsigned long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const unsigned int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const long int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const int v) inline
References default_rnd.
mpreal & mpfr::mpreal::operator= (const char * s)
References default_base, and default_rnd.
mpreal & mpfr::mpreal::operator>>= (const unsigned long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator>>= (const unsigned int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator>>= (const long int u) inline
References default_rnd.
mpreal & mpfr::mpreal::operator>>= (const int u) inline
References default_rnd.
void mpfr::mpreal::set_default_base (int base) inline static
References default_base.
void mpfr::mpreal::set_default_prec (mp_prec_t prec) inline static
References default_prec.
Referenced by conhyp().
void mpfr::mpreal::set_default_rnd (mp_rnd_t rnd_mode) inline static
References default_rnd.
void mpfr::mpreal::set_double_bits (int dbits) inline static
References double_bits.
int mpfr::mpreal::set_emax (mp_exp_t exp) inline static
int mpfr::mpreal::set_emin (mp_exp_t exp) inline static
int mpfr::mpreal::set_exp (mp_exp_t e) inline
Referenced by mpfr::frexp().
void mpfr::mpreal::set_inf (int sign = +1) inline
void mpfr::mpreal::set_nan () inline
void mpfr::mpreal::set_prec (mp_prec_t prec, mp_rnd_t rnd_mode = default_rnd) inline
Referenced by mpfr::agm(), mpfr::atan2(), mpfr::const_catalan(), mpfr::const_euler(), mpfr::const_log2(), mpfr::const_pi(), mpfr::fma(), mpfr::fmod(), mpfr::fms(), mpfr::hypot(), mpfr::operator/(), mpfr::remainder(), and mpfr::remquo().
void mpfr::mpreal::set_sign (int sign, mp_rnd_t rnd_mode = default_rnd) inline
int mpfr::mpreal::subnormalize (int t, mp_rnd_t rnd_mode = default_rnd) inline
string mpfr::mpreal::to_string (size_t n = 0, int b = default_base, mp_rnd_t mode = default_rnd) const
References exp.
Referenced by mpfr::operator<<().
Friends And Related Function Documentation
bool _isinf (const mpreal & v) friend
bool _isint (const mpreal & v) friend
bool _isnan (const mpreal & v) friend
bool _isnum (const mpreal & v) friend
bool _iszero (const mpreal & v) friend
const mpreal _j0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal _j1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal _jn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal _y0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal _y1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal _yn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal abs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal acos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal acosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal agm (const mpreal & v1, const mpreal & v2, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal asin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal asinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal atan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal atan2 (const mpreal & y, const mpreal & x, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal atanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal cbrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal ceil (const mpreal & v) friend
int cmpabs (const mpreal & a, const mpreal & b) friend
const mpreal const_catalan (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal const_euler (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal const_log2 (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal const_pi (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal cos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal cosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal cot (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal coth (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal csc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal csch (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal dim (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal div_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal div_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal eint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal erf (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal erfc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal exp (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
Referenced by to_string().
const mpreal exp10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal exp2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal expm1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal fabs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal fac_ui (unsigned long int v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal floor (const mpreal & v) friend
const mpreal fma (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal fmod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal fms (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal frac (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal frexp (const mpreal & v, mp_exp_t * exp) friend
const mpreal gamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal hypot (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal ldexp (const mpreal & v, mp_exp_t exp) friend
const mpreal lgamma (const mpreal & v, int * signp, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal li2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal lngamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal log (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal log10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal log1p (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal log2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal max (const mpreal & x, const mpreal & y) friend
const mpreal min (const mpreal & x, const mpreal & y) friend
const mpreal modf (const mpreal & v, mpreal & n) friend
const mpreal mul_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal mul_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal nextabove (const mpreal & x) friend
const mpreal nextbelow (const mpreal & x) friend
const mpreal nexttoward (const mpreal & x, const mpreal & y) friend
bool operator!= (const mpreal & a, const mpreal & b) friend
const mpreal operator- (const unsigned long int b, const mpreal & a) friend
const mpreal operator- (const unsigned int b, const mpreal & a) friend
const mpreal operator- (const long int b, const mpreal & a) friend
const mpreal operator- (const int b, const mpreal & a) friend
const mpreal operator- (const double b, const mpreal & a) friend
const mpreal operator/ (const unsigned long int b, const mpreal & a) friend
const mpreal operator/ (const unsigned int b, const mpreal & a) friend
const mpreal operator/ (const long int b, const mpreal & a) friend
const mpreal operator/ (const int b, const mpreal & a) friend
const mpreal operator/ (const double b, const mpreal & a) friend
bool operator< (const mpreal & a, const mpreal & b) friend
std::ostream& operator<< (std::ostream & os, const mpreal & v) friend
bool operator<= (const mpreal & a, const mpreal & b) friend
bool operator== (const mpreal & a, const mpreal & b) friend
bool operator> (const mpreal & a, const mpreal & b) friend
bool operator>= (const mpreal & a, const mpreal & b) friend
std::istream& operator>> (std::istream & is, mpreal & v) friend
const mpreal pow (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal pow (const mpreal & a, const mpz_t b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal pow (const mpreal & a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal pow (const mpreal & a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal pow (const unsigned long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal random2 (mp_size_t size, mp_exp_t exp) friend
const mpreal rec_sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal remainder (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal remquo (long * q, const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal rint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal rint_ceil (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal rint_floor (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal rint_round (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal rint_trunc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal root (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal round (const mpreal & v) friend
const mpreal sec (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sech (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
int sgn (const mpreal & v) friend
const mpreal sin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
int sin_cos (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
int sinh_cosh (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sqr (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sqrt (const unsigned long int v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal sum (const mpreal tab[], unsigned long int n, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
Referenced by madness::FunctionImpl< T, NDIM >::tree_size().
void swap (mpfr::mpreal & x, mpfr::mpreal & y) friend
const mpreal tan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal tanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
const mpreal trunc (const mpreal & v) friend
const mpreal urandomb (gmp_randstate_t & state) friend
const mpreal zeta (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) friend
Member Data Documentation
int mpfr::mpreal::default_base = 10 static
Referenced by get_default_base(), operator=(), mpfr::operator>>(), and set_default_base().
mp_prec_t mpfr::mpreal::default_prec = mpfr_get_default_prec() static
Referenced by mpreal(), and set_default_prec().
mp_rnd_t mpfr::mpreal::default_rnd = mpfr_get_default_rounding_mode() static
Referenced by mpfr::ldexp(), mpfr::modf(), mpreal(), operator*=(), operator+=(), operator-(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), operator<<=(), operator=(), mpfr::operator>>(), operator>>=(), and set_default_rnd().
int mpfr::mpreal::double_bits = -1 static
Referenced by get_double_bits(), mpreal(), operator=(), and set_double_bits().
The documentation for this class was generated from the following files:
mpreal.h
mpreal.cc