MADNESS: madness::MutexReaderWriter Class Reference
madness::MutexReaderWriter Class Reference
#include <worldmutex.h>
Public Member Functions
MutexReaderWriter ()
bool try_read_lock () const
bool try_write_lock () const
bool try_lock (int lockmode) const
bool try_convert_read_lock_to_write_lock () const
void read_lock () const
void write_lock () const
void lock (int lockmode) const
void read_unlock () const
void write_unlock () const
void unlock (int lockmode) const
void convert_read_lock_to_write_lock () const
Converts read to write lock without releasing the read lock.
void convert_write_lock_to_read_lock () const
Always succeeds immediately.
virtual ~MutexReaderWriter ()
Static Public Attributes
static const int NOLOCK =0
static const int READLOCK =1
static const int WRITELOCK =2
Constructor & Destructor Documentation
madness::MutexReaderWriter::MutexReaderWriter () inline
virtual madness::MutexReaderWriter::~MutexReaderWriter () inline virtual
Member Function Documentation
void madness::MutexReaderWriter::convert_read_lock_to_write_lock () const inline
Converts read to write lock without releasing the read lock.
Note that deadlock is guaranteed if two+ threads wait to convert at the same time.
References madness::cpu_relax(), and try_convert_read_lock_to_write_lock().
void madness::MutexReaderWriter::convert_write_lock_to_read_lock () const inline
Always succeeds immediately.
void madness::MutexReaderWriter::lock (int lockmode) const inline
References madness::cpu_relax(), and madness::Spinlock::try_lock().
void madness::MutexReaderWriter::read_lock () const inline
References madness::cpu_relax(), and try_read_lock().
void madness::MutexReaderWriter::read_unlock () const inline
Referenced by unlock().
bool madness::MutexReaderWriter::try_convert_read_lock_to_write_lock () const inline
Referenced by convert_read_lock_to_write_lock().
bool madness::MutexReaderWriter::try_lock (int lockmode) const inline
References MADNESS_EXCEPTION, try_read_lock(), and try_write_lock().
Referenced by madness::Hash_private::bin< keyT, valueT >::find(), and madness::Hash_private::bin< keyT, valueT >::insert().
bool madness::MutexReaderWriter::try_read_lock () const inline
Referenced by read_lock(), and try_lock().
bool madness::MutexReaderWriter::try_write_lock () const inline
Referenced by try_lock(), and write_lock().
void madness::MutexReaderWriter::unlock (int lockmode) const inline
References MADNESS_EXCEPTION, read_unlock(), and write_unlock().
void madness::MutexReaderWriter::write_lock () const inline
References madness::cpu_relax(), and try_write_lock().
void madness::MutexReaderWriter::write_unlock () const inline
Referenced by unlock().
Member Data Documentation
const int madness::MutexReaderWriter::NOLOCK =0 static
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::erase(), madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::find(), and madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::insert().
const int madness::MutexReaderWriter::READLOCK =1 static
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::find(), and madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::insert().
const int madness::MutexReaderWriter::WRITELOCK =2 static
Referenced by madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::erase(), madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::find(), and madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::insert().
The documentation for this class was generated from the following file:
worldmutex.h