MADNESS: madness::tr1::array::array< T, N > Class Template Reference
madness::tr1::array::array< T, N > Class Template Reference
Array idential to C++0X arrays.
#include <stdarray_bits.h>
Public Types
enum { static_size = N }
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void swap (array< T, N > &y)
const T * data () const
T * data ()
template<typename T2 >
array< T, N > & operator= (const array< T2, N > &rhs)
void assign (const T &value)
Static Public Member Functions
static size_type size ()
static bool empty ()
static size_type max_size ()
Public Attributes
T elems [N]
Detailed Description
template<typename T, std::size_t N>
class madness::tr1::array::array< T, N >
Array idential to C++0X arrays.
Member Typedef Documentation
template<typename T, std::size_t N> typedef const T* madness::tr1::array::array< T, N >::const_iterator
template<typename T, std::size_t N> typedef const T& madness::tr1::array::array< T, N >::const_reference
template<typename T, std::size_t N> typedef std::reverse_iterator<const_iterator> madness::tr1::array::array< T, N >::const_reverse_iterator
template<typename T, std::size_t N> typedef std::ptrdiff_t madness::tr1::array::array< T, N >::difference_type
template<typename T, std::size_t N> typedef T* madness::tr1::array::array< T, N >::iterator
template<typename T, std::size_t N> typedef T& madness::tr1::array::array< T, N >::reference
template<typename T, std::size_t N> typedef std::reverse_iterator<iterator> madness::tr1::array::array< T, N >::reverse_iterator
template<typename T, std::size_t N> typedef std::size_t madness::tr1::array::array< T, N >::size_type
template<typename T, std::size_t N> typedef T madness::tr1::array::array< T, N >::value_type
Member Enumeration Documentation
template<typename T, std::size_t N> anonymous enum
Enumerator
static_size
Member Function Documentation
template<typename T, std::size_t N> void madness::tr1::array::array< T, N >::assign (const T & value) inline
Referenced by madness::Vector< int, 3 >::fill().
template<typename T, std::size_t N> reference madness::tr1::array::array< T, N >::at (size_type i) inline
Referenced by madness::Vector< int, 3 >::at().
template<typename T, std::size_t N> const_reference madness::tr1::array::array< T, N >::at (size_type i) const inline
template<typename T, std::size_t N> reference madness::tr1::array::array< T, N >::back () inline
Referenced by madness::Vector< int, 3 >::back().
template<typename T, std::size_t N> const_reference madness::tr1::array::array< T, N >::back () const inline
template<typename T, std::size_t N> iterator madness::tr1::array::array< T, N >::begin () inline
Referenced by madness::tr1::array::array< real_tensor, 118 >::assign(), madness::Vector< int, 3 >::begin(), madness::ConvolutionND< Q, NDIM >::ConvolutionND(), madness::archive::ArchiveLoadImpl< Archive, std::array< T, N > >::load(), madness::tr1::array::array< real_tensor, 118 >::operator=(), madness::Vector< int, 3 >::operator=(), madness::tr1::array::operator==(), madness::tr1::array::array< real_tensor, 118 >::rend(), madness::tr1::array::array< T, 0 >::rend(), madness::archive::ArchiveStoreImpl< Archive, std::array< T, N > >::store(), madness::tr1::array::array< real_tensor, 118 >::swap(), and madness::Vector< int, 3 >::Vector().
template<typename T, std::size_t N> const_iterator madness::tr1::array::array< T, N >::begin () const inline
template<typename T, std::size_t N> const T* madness::tr1::array::array< T, N >::data () const inline
Referenced by madness::Vector< int, 3 >::c_array(), madness::Vector< int, 3 >::data(), and madness::hash_value().
template<typename T, std::size_t N> T* madness::tr1::array::array< T, N >::data () inline
template<typename T, std::size_t N> static bool madness::tr1::array::array< T, N >::empty () inline static
Referenced by madness::Vector< int, 3 >::empty().
template<typename T, std::size_t N> iterator madness::tr1::array::array< T, N >::end () inline
Referenced by madness::ConvolutionND< Q, NDIM >::ConvolutionND(), madness::Vector< int, 3 >::end(), madness::archive::ArchiveLoadImpl< Archive, std::array< T, N > >::load(), madness::tr1::array::array< real_tensor, 118 >::operator=(), madness::tr1::array::operator==(), madness::tr1::array::array< real_tensor, 118 >::rbegin(), madness::tr1::array::array< T, 0 >::rbegin(), madness::archive::ArchiveStoreImpl< Archive, std::array< T, N > >::store(), and madness::tr1::array::array< real_tensor, 118 >::swap().
template<typename T, std::size_t N> const_iterator madness::tr1::array::array< T, N >::end () const inline
template<typename T, std::size_t N> reference madness::tr1::array::array< T, N >::front () inline
Referenced by madness::Vector< int, 3 >::front().
template<typename T, std::size_t N> const_reference madness::tr1::array::array< T, N >::front () const inline
template<typename T, std::size_t N> static size_type madness::tr1::array::array< T, N >::max_size () inline static
Referenced by madness::Vector< int, 3 >::max_size().
template<typename T, std::size_t N> template<typename T2 > array<T,N>& madness::tr1::array::array< T, N >::operator= (const array< T2, N > & rhs) inline
template<typename T, std::size_t N> reference madness::tr1::array::array< T, N >::operator[] (size_type i) inline
template<typename T, std::size_t N> const_reference madness::tr1::array::array< T, N >::operator[] (size_type i) const inline
template<typename T, std::size_t N> reverse_iterator madness::tr1::array::array< T, N >::rbegin () inline
Referenced by madness::Vector< int, 3 >::rbegin().
template<typename T, std::size_t N> const_reverse_iterator madness::tr1::array::array< T, N >::rbegin () const inline
template<typename T, std::size_t N> reverse_iterator madness::tr1::array::array< T, N >::rend () inline
Referenced by madness::Vector< int, 3 >::rend().
template<typename T, std::size_t N> const_reverse_iterator madness::tr1::array::array< T, N >::rend () const inline
template<typename T, std::size_t N> static size_type madness::tr1::array::array< T, N >::size () inline static
Referenced by madness::tr1::array::array< real_tensor, 118 >::assign(), and madness::Vector< int, 3 >::size().
template<typename T, std::size_t N> void madness::tr1::array::array< T, N >::swap (array< T, N > & y) inline
Referenced by madness::tr1::array::swap(), and madness::Vector< int, 3 >::swap().
Member Data Documentation
template<typename T, std::size_t N> T madness::tr1::array::array< T, N >::elems[N]
Referenced by madness::tr1::array::array< real_tensor, 118 >::begin(), and madness::tr1::array::array< real_tensor, 118 >::data().
The documentation for this class was generated from the following file:
stdarray_bits.h