MADNESS: MolecularSurface Class Reference
MolecularSurface Class Reference
#include <molecularmask.h>
Public Member Functions
MolecularSurface (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords)
virtual double operator() (const madness::coord_3d &r) const
std::vector< madness::Vector
< double, 3 > > special_points () const
Override this to return list of special points to be refined more deeply.
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const =0
You should implement this to return f(x)
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
Constructor & Destructor Documentation
MolecularSurface::MolecularSurface (double sigma, const std::vector< double > atomic_radii, const std::vector< madness::coord_3d > atomic_coords) inline
Member Function Documentation
virtual double MolecularSurface::operator() (const madness::coord_3d & r) const inline virtual
References MolecularMaskBase::gradient(), and sqrt().
std::vector< madness::Vector<double,3> > MolecularSurface::special_points () const inline virtual
Override this to return list of special points to be refined more deeply.
Reimplemented from madness::FunctionFunctorInterface< double, 3 >.
References MolecularMaskBase::special_points().
The documentation for this class was generated from the following file:
molecularmask.h