MADNESS: madness::DomainMaskSDFFunctor< NDIM > Class Template Reference
madness::DomainMaskSDFFunctor< NDIM > Class Template Reference
MADNESS libraries » Multiresolution analaysis » Preliminary support for interior boundary conditions
Framework for combining a signed distance function (sdf) with a domain mask to produce MADNESS functions.
#include <sdf_domainmask.h>
Public Member Functions
DomainMaskSDFFunctor (std::shared_ptr< DomainMaskInterface > mask, std::shared_ptr< SignedDFInterface< NDIM > > sdf)
Constructor for mask/sdf functor.
DomainMaskSDFFunctor (std::shared_ptr< DomainMaskInterface > mask, std::shared_ptr< SignedDFInterface< NDIM > > sdf, int _mswitch)
Constructor for mask/sdf function specifying the desired function (mask, surface, etc.)
double operator() (const Vector< double, NDIM > &x) const
Uses the functor interface to make a MADNESS function.
void setMaskFunction (int _mswitch)
Toggles which function from DomainMaskInterface to use when making the MADNESS function.
virtual ~DomainMaskSDFFunctor ()
Public Member Functions inherited from madness::FunctionFunctorInterface< double, NDIM >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Static Public Attributes
static const int MASK = 1
Use the mask() function in mask.
static const int MASK_COMPLEMENT = 2
Get the complement of mask()
static const int DMASK = 3
Use the dmask() function in mask.
static const int SURFACE = 4
Use the surface() function in mask.
static const int DSURFACE = 5
Use the dsurface() function in mask.
Additional Inherited Members
Public Types inherited from madness::FunctionFunctorInterface< double, NDIM >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
Detailed Description
template<std::size_t NDIM>
class madness::DomainMaskSDFFunctor< NDIM >
Framework for combining a signed distance function (sdf) with a domain mask to produce MADNESS functions.
This interface provides functor functionality to produce MADNESS functions for
the domain mask (given the sdf)
the derivative of the domain mask
the surface (given the sdf)
the normal derivative of the surface layer
The functor defaults to the domain mask; however, member functions can toggle between the other options.
Constructor & Destructor Documentation
template<std::size_t NDIM> madness::DomainMaskSDFFunctor< NDIM >::DomainMaskSDFFunctor (std::shared_ptr< DomainMaskInterface > mask, std::shared_ptr< SignedDFInterface< NDIM > > sdf) inline
Constructor for mask/sdf functor.
Parameters
mask Pointer to the domain mask
sdf Pointer to the signed distance function
template<std::size_t NDIM> madness::DomainMaskSDFFunctor< NDIM >::DomainMaskSDFFunctor (std::shared_ptr< DomainMaskInterface > mask, std::shared_ptr< SignedDFInterface< NDIM > > sdf, int _mswitch) inline
Constructor for mask/sdf function specifying the desired function (mask, surface, etc.)
Parameters
mask Pointer to the domain mask
sdf Pointer to the signed distance function
[in] _mswitch Which function to use (MASK, DMASK, SURFACE, DSURFACE, or MASK_COMPLEMENT)
References madness::error().
template<std::size_t NDIM> virtual madness::DomainMaskSDFFunctor< NDIM >::~DomainMaskSDFFunctor () inline virtual
Member Function Documentation
template<std::size_t NDIM> double madness::DomainMaskSDFFunctor< NDIM >::operator() (const Vector< double, NDIM > & x) const inline virtual
Uses the functor interface to make a MADNESS function.
Parameters
x Point to compute value
Returns
Value of the desired function
Implements madness::FunctionFunctorInterface< double, NDIM >.
References madness::error().
template<std::size_t NDIM> void madness::DomainMaskSDFFunctor< NDIM >::setMaskFunction (int _mswitch) inline
Toggles which function from DomainMaskInterface to use when making the MADNESS function.
Parameters
_mswitch The function to use (should be MASK, DMASK, SURFACE, DSURFACE, or MASK_COMPLEMENT)
References madness::error().
Member Data Documentation
template<std::size_t NDIM> const int madness::DomainMaskSDFFunctor< NDIM >::DMASK = 3 static
Use the dmask() function in mask.
template<std::size_t NDIM> const int madness::DomainMaskSDFFunctor< NDIM >::DSURFACE = 5 static
Use the dsurface() function in mask.
template<std::size_t NDIM> const int madness::DomainMaskSDFFunctor< NDIM >::MASK = 1 static
Use the mask() function in mask.
template<std::size_t NDIM> const int madness::DomainMaskSDFFunctor< NDIM >::MASK_COMPLEMENT = 2 static
Get the complement of mask()
template<std::size_t NDIM> const int madness::DomainMaskSDFFunctor< NDIM >::SURFACE = 4 static
Use the surface() function in mask.
The documentation for this class was generated from the following file:
sdf_domainmask.h