MADNESS: complex_fun.h File Reference
complex_fun.h File Reference
Classes
struct real_op< Q, NDIM >
Functions
template<typename Q , int NDIM>
Function< typename
TensorTypeData< Q >
::scalar_type, NDIM > real (const Function< Q, NDIM > &func)
void ln (const Key< 3 > &key, Tensor< std::complex< double > > &t)
Function Documentation
void ln (const Key< 3 > & key, Tensor< std::complex< double > > & t) inline
References mpfr::log(), and UNARY_OPTIMIZED_ITERATOR.
template<typename Q , int NDIM> Function<typename TensorTypeData<Q>::scalar_type,NDIM> real (const Function< Q, NDIM > & func)
References madness::unary_op_coeffs().
Referenced by real_op< Q, NDIM >::operator()().