MADNESS: csqrt.cc File Reference
csqrt.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <complex>
Typedefs
typedef Vector< double, 1 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< std::complex< double >, 1 > > functorT
typedef Function< std::complex
< double >, 1 > cfunctionT
typedef FunctionFactory
< std::complex< double >, 1 > factoryT
typedef SeparatedConvolution
< std::complex< double >, 1 > operatorT
Functions
int main (int argc, char **argv)
Typedef Documentation
typedef Function<std::complex<double>,1> cfunctionT
typedef Vector<double,1> coordT
typedef FunctionFactory<std::complex<double>,1> factoryT
typedef std::shared_ptr< FunctionFunctorInterface<std::complex<double>,1> > functorT
typedef SeparatedConvolution<std::complex<double>,1> operatorT
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::copy(), madness::error(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), L, madness::norm2(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), madness::Function< T, NDIM >::truncate(), and madness::Function< T, NDIM >::unaryop().