MADNESS: dataloadbal.cc File Reference
dataloadbal.cc File Reference
Illustrates how to use static data/load balancing of functions.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/vmra.h>
#include <madness/mra/lbdeux.h>
#include <madness/constants.h>
Classes
class Gaussian
Functions
real_functor_3d random_gaussian ()
void test (World &world, bool doloadbal=false)
int main (int argc, char **argv)
Detailed Description
Illustrates how to use static data/load balancing of functions.
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::finalize(), madness::initialize(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), and test().
real_functor_3d random_gaussian ()
References mpfr::exp(), madness::FunctionDefaults< NDIM >::get_cell(), mpfr::log(), madness::constants::pi, and madness::RandomValue< double >().
Referenced by test().
void test (World & world, bool doloadbal = false)
References madness::LoadBalanceDeux< NDIM >::add_tree(), madness::apply(), madness::default_random_generator, madness::f, madness::WorldGopInterface::fence(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), loadbal(), op(), random_gaussian(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), madness::Random::setstate(), madness::truncate(), and madness::wall_time().
Referenced by madness::FunctionImpl< T, NDIM >::autorefine_square_test(), conhyp(), madness::SimpleCache< madness::SeparatedConvolutionData< Q, NDIM >, 2 *NDIM >::getptr(), main(), madness::detail::adqtest::runtest(), and testbsh().