MADNESS: xcfunctional_ldaonly.cc File Reference
DFcode/xcfunctional_ldaonly.cc File Reference
#include <madness/madness_config.h>
#include <DFcode/xcfunctional.h>
#include <madness/tensor/tensor.h>
#include <sstream>
Functions
int x_rks_s__ (const double *r__, double *f, double *dfdra)
int c_rks_vwn5__ (const double *r__, double *f, double *dfdra)
int x_uks_s__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
int c_uks_vwn5__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
Function Documentation
int c_rks_vwn5__ (const double * r__, double * f, double * dfdra) inline
Referenced by XCfunctional::exc(), and XCfunctional::vxc().
int c_uks_vwn5__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb) inline
References a1, a2, mpfr::atan(), c_b14, madness::c_b14, c_b7, madness::c_b7, std::tr1::f1, std::tr1::f2, std::tr1::f3, std::tr1::f4, mpfr::log(), sqrt(), ss1, and zeta.
Referenced by madness::XCfunctional::exc(), XCfunctional::exc(), madness::XCfunctional::vxc(), and XCfunctional::vxc().
int x_rks_s__ (const double * r__, double * f, double * dfdra) inline
Referenced by XCfunctional::exc(), and XCfunctional::vxc().
int x_uks_s__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb) inline
References c_b2, and madness::c_b2.
Referenced by madness::XCfunctional::exc(), XCfunctional::exc(), madness::XCfunctional::vxc(), and XCfunctional::vxc().