MADNESS: lda.cc File Reference
DFcode/lda.cc File Reference
#include <cmath>
Functions
int x_rks_s__ (const double *r__, double *f, double *dfdra)
int x_uks_s__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
int c_rks_vwn5__ (const double *r__, double *f, double *dfdra)
int c_uks_vwn5__ (double *ra, double *rb, double *f, double *dfdra, double *dfdrb)
Variables
const double c_b2 = 0.333333333333333333333333333333333
const double c_b7 = 0.333333333333333333333333333333
const double c_b14 = 1.333333333333333333333333333333
Function Documentation
int c_rks_vwn5__ (const double * r__, double * f, double * dfdra)
References a2, mpfr::atan(), c_b7, mpfr::log(), and sqrt().
int c_uks_vwn5__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb)
References a1, a2, mpfr::atan(), c_b14, c_b7, std::tr1::f1, std::tr1::f2, std::tr1::f3, std::tr1::f4, mpfr::log(), sqrt(), ss1, and zeta.
int x_rks_s__ (const double * r__, double * f, double * dfdra)
References c_b2.
int x_uks_s__ (double * ra, double * rb, double * f, double * dfdra, double * dfdrb)
References c_b2.
Variable Documentation
const double c_b14 = 1.333333333333333333333333333333
Referenced by c_uks_vwn5__().
const double c_b2 = 0.333333333333333333333333333333333
Referenced by x_rks_s__(), and x_uks_s__().
const double c_b7 = 0.333333333333333333333333333333
Referenced by c_rks_vwn5__(), and c_uks_vwn5__().