MADNESS: moldft.cc File Reference
DFcode/moldft.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/mra/qmprop.h>
#include <madness/misc/misc.h>
#include <madness/misc/ran.h>
#include <madness/tensor/systolic.h>
#include <madness/tensor/solvers.h>
#include <madness/tensor/elem.h>
#include <ctime>
#include <list>
#include <madness/TAU.h>
#include <DFcode/molecule.h>
#include <DFcode/molecularbasis.h>
#include <DFcode/corepotential.h>
#include <DFcode/xcfunctional.h>
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
typedef std::pair< vecfuncT,
vecfuncT > pairvecfuncT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
typedef SeparatedConvolution
< double, 3 > operatorT
typedef std::shared_ptr
< operatorT > poperatorT
typedef Function< std::complex
< double >, 3 > complex_functionT
typedef std::vector
< complex_functionT > cvecfuncT
typedef Convolution1D
< double_complex > complex_operatorT
Functions
Function< double_complex, 3 > make_exp (double t, const Function< double, 3 > &v)
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
tensorT distributed_localize_PM (World &world, const vecfuncT &mo, const vecfuncT &ao, const std::vector< int > &set, const std::vector< int > &at_to_bf, const std::vector< int > &at_nbf, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true, const bool doprint=false)
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
double mask1 (double x)
double mask3 (const coordT &ruser)
double rsquared (const coordT &r)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
tensorT sqrt (const tensorT &s, double tol=1e-8)
Computes matrix square root (not used any more?)
int main (int argc, char **argv)
Typedef Documentation
typedef Function<std::complex<double>,3> complex_functionT
typedef Convolution1D<double_complex> complex_operatorT
typedef Vector<double,3> coordT
typedef std::vector<complex_functionT> cvecfuncT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef SeparatedConvolution<double,3> operatorT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef std::shared_ptr<operatorT> poperatorT
typedef std::vector<pairvecfuncT> subspaceT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
tensorT distributed_localize_PM (World & world, const vecfuncT & mo, const vecfuncT & ao, const std::vector< int > & set, const std::vector< int > & at_to_bf, const std::vector< int > & at_nbf, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true, const bool doprint = false)
References a(), madness::concatenate_rows(), madness::copy(), madness::DistributedMatrix< T >::copy_to_replicated(), madness::DistributedMatrix< T >::extract_columns(), madness::DistributedMatrix< T >::fill_identity(), madness::matrix_inner(), and madness::transpose().
Referenced by madness::SCF::localize_PM().
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void END_TIMER (World & world, const char * msg)
References madness::World::rank(), and madness::wall_time().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::QuasiNewton::optimize(), madness::print(), madness::print_meminfo(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::QuasiNewton::set_test(), madness::QuasiNewton::set_update(), madness::World::size(), madness::startup(), TAU_START, TAU_STOP, madness::MolecularEnergy::value(), and madness::vector_factory().
Function<double_complex,3> make_exp (double t, const Function< double, 3 > & v)
References expV(), make_exp(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::unaryop().
Referenced by make_exp(), and propagate().
double mask1 (double x) inline
double mask3 (const coordT & ruser)
References madness::mask1(), and mask3().
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
double rsquared (const coordT & r)
References rsquared().
Referenced by rsquared().
tensorT sqrt (const tensorT & s, double tol = 1e-8)
Computes matrix square root (not used any more?)
References c, MADNESS_EXCEPTION, madness::print(), and madness::syev().
Referenced by madness::FunctionImpl< T, NDIM >::add_scalar_inplace(), Akernel(), madness::SCF::analyze_vectors(), apply_U_mix(), apply_U_ncf(), apply_V(), SVPEColloidSolver::ave_rxn_field(), DFTSolventSolver::ave_rxn_field(), c_rks_vwn5__(), c_uks_vwn5__(), madness::Function< double, 6 >::check_symmetry(), madness::SlaterF12Interface::coeff(), madness::FunctionImpl< Q, NDIM >::coeffs2values(), compute_energy(), compute_madelung_energy(), compute_madelung_energy_PWSCF(), compute_R2f2_psi(), converge(), converge2s(), madness::Solver< T, NDIM >::csqrt(), madness::TensorTrain< T >::decompose(), delta(), distance(), madness::distance(), distance1(), distances(), MolecularMaskBase::dmask(), madness::GaussianDomainMask::dmask(), madness::FunctionImpl< Q, NDIM >::do_binary_op(), madness::FunctionImpl< Q, NDIM >::do_mul(), doit(), madness::GaussianDomainMask::dsurface(), E0(), electronic_charge_function(), madness::Function< double, 6 >::err(), madness::FunctionImpl< Q, NDIM >::err_box(), madness::FunctionImpl< T, NDIM >::eval_cube(), madness::detail::adqtest::exact(), exact_function(), Expikr::Expikr(), madness::FunctionImpl< Q, NDIM >::fcube_for_mul(), gen_ce(), generate_G_vectors(), generate_R_vectors(), madness::GaussianConvolution1DCache< Q >::get(), PhiK::getk(), madness::GMRES(), madness::SDFCircle::grad_sdf(), madness::SDFSphere::grad_sdf(), TipMolecule::Inhomogeneity(), ScatteringWF::Init(), madness::TwoElectronInterface< double, 6 >::initialize(), madness::initialize_legendre_stuff(), iterate(), iterate_excite(), iterate_ground(), iterate_xy(), jacobi(), madness::GTHPseudopotential< double >::load_pseudo_from_file(), loadParameters(), main(), make_bsh_operators(), madness::EigSolver< T, NDIM >::make_bsh_operators(), madness::SCF::make_bsh_operators(), madness::Solver< T, NDIM >::make_bsh_operators(), madness::GaussianDomainMask::mask(), madness::FunctionImpl< Q, NDIM >::mul(), myf(), madness::VectorSpace< T, NDIM >::norm(), madness::VectorOfFunctionsSpace< T, VDIM, FDIM >::norm(), madness::norm(), madness::norm2(), madness::Function< double, 6 >::norm2(), madness::norm2s(), madness::FunctionImpl< T, NDIM >::norm_tree_op(), normalize2(), madness::Vector< int, 3 >::normf(), madness::FunctionImpl< Q, NDIM >::NS_fcube_for_mul(), madness::FunctionImpl< Q, NDIM >::NScoeffs2values(), MolecularEntity::nuclear_charge_density(), Molecule::nuclear_charge_density(), madness::Molecule::nuclear_charge_density(), madness::VLocalFunctor::operator()(), gauss_function::operator()(), ParserHandler< T, NDIM >::operator()(), madness::ProjRLMFunctor::operator()(), PhiK::operator()(), BoundWF::operator()(), Yl0::operator()(), MolecularSurface::operator()(), madness::diffuse_functions::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::hartree_convolute_leaf_op< T, NDIM, LDIM, opT >::operator()(), madness::GenericConvolution1D< Q, opT >::Shmoo::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), opt(), optimize_coeffs(), madness::ortho3(), madness::ortho5(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::plot_line(), madness::FunctionImpl< T, NDIM >::print_plane_local(), madness::FunctionImpl< T, NDIM >::print_size(), madness::FunctionImpl< T, NDIM >::project(), madness::ProjRLMFunctor::ProjRLMFunctor(), psi(), reconstruct_psi(), rho_func(), madness::GaussianConvolution1D< Q >::rnlp(), madness::SDFCircle::sdf(), madness::SDFSphere::sdf(), madness::SDFCone::sdf(), madness::SDFParaboloid::sdf(), madness::SDFCylinder::sdf(), madness::SeparatedConvolution< T, NDIM >::SeparatedConvolution(), smoothed_potential(), madness::EigSolver< T, NDIM >::solve(), madness::MP2::solve_residual_equations(), madness::SpectralPropagatorGaussLobatto::SpectralPropagatorGaussLobatto(), madness::GaussianDomainMask::surface(), target(), test(), Test6(), test_adaptive_tree(), test_compress(), test_modified(), test_nuclear_potential2(), test_nuclear_potential_big_unit_cell(), test_recursive_application(), test_U_el(), testNavierStokes(), TipMolecule::TipMolecule(), madness::FunctionImpl< T, NDIM >::trace_local(), madness::TensorTrain< T >::truncate(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_op(), V(), madness::FunctionImpl< Q, NDIM >::values2coeffs(), madness::FunctionImpl< Q, NDIM >::values2NScoeffs(), madness::SCF::vector_stats(), and weight().
void START_TIMER (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, and madness::wall_time().