MADNESS: distpm.cc File Reference
DFcode/distpm.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/world/world.h>
#include <madness/misc/ran.h>
#include <madness/tensor/tensor.h>
#include <madness/tensor/systolic.h>
#include <utility>
#include <vector>
Typedefs
typedef Tensor< double > tensorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
Functions
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
template<typename T , std::size_t NDIM>
void matrix_inner (DistributedMatrix< T > &A, const std::vector< Function< T, NDIM > > &f, const std::vector< Function< T, NDIM > > &g, bool sym=false)
tensorT distributed_localize_PM (World &world, const vecfuncT &mo, const vecfuncT &ao, const std::vector< int > &set, const std::vector< int > &at_to_bf, const std::vector< int > &at_nbf, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true, const bool doprint=false)
Typedef Documentation
typedef Function<double,3> functionT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
tensorT distributed_localize_PM (World & world, const vecfuncT & mo, const vecfuncT & ao, const std::vector< int > & set, const std::vector< int > & at_to_bf, const std::vector< int > & at_nbf, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true, const bool doprint = false)
References a(), madness::concatenate_rows(), madness::copy(), madness::DistributedMatrix< T >::copy_to_replicated(), madness::DistributedMatrix< T >::extract_columns(), madness::DistributedMatrix< T >::fill_identity(), madness::matrix_inner(), and madness::transpose().
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
template<typename T , std::size_t NDIM> void matrix_inner (DistributedMatrix< T > & A, const std::vector< Function< T, NDIM > > & f, const std::vector< Function< T, NDIM > > & g, bool sym = false)
References madness::DistributedMatrix< T >::coldim(), madness::DistributedMatrix< T >::copy_from_replicated_patch(), madness::f, madness::g, madness::DistributedMatrix< T >::get_world(), m, madness::matrix_inner(), mpfr::min(), and madness::DistributedMatrix< T >::rowdim().
Referenced by kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), and MolecularSystem::load().