MADNESS: atomutil.cc File Reference
DFcode/atomutil.cc File Reference
#include <madness/constants.h>
#include <DFcode/atomutil.h>
#include <madness/misc/misc.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
Functions
const AtomicData & get_atomic_data (unsigned int atomic_number)
unsigned int symbol_to_atomic_number (const std::string &symbol)
double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
double smoothed_potential (double r)
Smoothed 1/r potential.
double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
Function Documentation
double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
dV/dx = (x/r) * du(r/c)/(c*c)
References a().
const AtomicData& get_atomic_data (unsigned int atomic_number)
double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
Invoke as rho(r/c)/c^3 where c is the radius of the smoothed volume.
References mpfr::exp(), and madness::constants::pi.
double smoothed_potential (double r)
Smoothed 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References a().
double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, and mpfr::min().
unsigned int symbol_to_atomic_number (const std::string & symbol)
References madness::lowercase(), and AtomicData::symbol_lowercase.