MADNESS: molecularbasis.cc File Reference
DFcode/molecularbasis.cc File Reference
#include <DFcode/molecularbasis.h>
Functions
std::ostream & operator<< (std::ostream &s, const ContractedGaussianShell &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasis &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasisFunction &a)
Function Documentation
std::ostream& operator<< (std::ostream & s, const ContractedGaussianShell & c)
References madness::ContractedGaussianShell::angular_momentum(), madness::ContractedGaussianShell::get_coeff(), madness::ContractedGaussianShell::get_expnt(), and madness::ContractedGaussianShell::nprim().
std::ostream& operator<< (std::ostream & s, const AtomicBasis & c)
References madness::AtomicBasis::get_dmat(), madness::AtomicBasis::get_shells(), madness::AtomicBasis::has_guess_info(), and madness::AtomicBasis::nshell().
std::ostream& operator<< (std::ostream & s, const AtomicBasisFunction & a)
References madness::AtomicBasisFunction::print_me().