MADNESS: eigen_solver.cc File Reference
eigen_solver.cc File Reference
#include <madness/world/world.h>
#include <utility>
#include <madness/tensor/tensor.h>
#include <ii/systolic.h>
#include <cmath>
#include <ctime>
#include <cstdlib>
Functions
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
int main (int argc, char **argv)
Variables
double ttt
double sss
Function Documentation
void END_TIMER (World & world, const char * msg)
int main (int argc, char ** argv)
References madness::WorldGopInterface::broadcast(), SafeMPI::COMM_WORLD, madness::DistributedMatrix< T >::copyin(), madness::DistributedMatrix< T >::copyout(), error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::inner(), print(), madness::World::rank(), sss, madness::transpose(), ttt, and madness::wall_time().
void START_TIMER (World & world)
Variable Documentation
double sss
Referenced by END_TIMER(), main(), and START_TIMER().
double ttt
Referenced by madness::FunctionImpl< T, NDIM >::add_scalar_inplace(), END_TIMER(), main(), and START_TIMER().