MADNESS: hello.cc File Reference
examples/hello.cc File Reference
Simplest example program for MADNESS.
#include <madness/world/world.h>
Functions
int main (int argc, char **argv)
Detailed Description
Simplest example program for MADNESS.
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::finalize(), madness::initialize(), madness::print(), and madness::World::rank().