MADNESS: extra.cc File Reference
extra.cc File Reference
#include "extra.h"
#include <madness/world/parar.h>
Functions
std::ostream & operator<< (std::ostream &s, const InputParameters &p)
const char * wave_function_filename (int step)
bool wave_function_exists (World &world, int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
complex_functionT wave_function_load (World &world, int step)
template<class T >
std::string toString (const T &a)
void loadDefaultBasis (World &world, std::vector< WF > &boundList, double Z)
void loadList (World &world, std::vector< std::string > &boundList, std::vector< std::string > &unboundList)
complexd zdipole (const vector3D &r)
void projectZdip (World &world, std::vector< WF > stateList)
void compare1F1 (World &world, double cutoff)
double myreal (double t)
double myreal (const double_complex &t)
complexd V (const vector3D &r)
template<typename T >
double energy (World &world, const Function< T, 3 > &psi, const Function< T, 3 > &potn)
void converge (World &world, complex_functionT &potn, complex_functionT &psi, double &eps)
void compareGroundState (World &world, double Z)
void printBasis (World &world, double Z, double cutoff)
void belkic (World &world, double cutoff)
Variables
InputParameters param
Function Documentation
void belkic (World & world, double cutoff)
References ScatteringWF::Init(), madness::inner(), and PRINTLINE.
void compare1F1 (World & world, double cutoff)
References ScatteringWF::aForm(), conhyp(), madness::f, I(), madness::imag(), k, PRINT, PRINTLINE, real(), and madness::vec().
void compareGroundState (World & world, double Z)
References madness::conj(), converge(), InputParameters::cut, energy(), madness::inner(), madness::Function< T, NDIM >::norm2(), PRINT, PRINTLINE, madness::World::rank(), InputParameters::read(), real(), madness::Function< T, NDIM >::scale(), InputParameters::thresh, madness::Function< T, NDIM >::truncate(), and V().
void converge (World & world, complex_functionT & potn, complex_functionT & psi, double & eps)
References madness::apply(), InputParameters::cut, madness::inner(), max, madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), psi(), real(), madness::Function< T, NDIM >::scale(), sqrt(), InputParameters::thresh, and madness::Function< T, NDIM >::truncate().
Referenced by compareGroundState().
template<typename T > double energy (World & world, const Function< T, 3 > & psi, const Function< T, 3 > & potn)
References madness::Function< T, NDIM >::clear(), madness::Function< T, NDIM >::compress(), madness::WorldGopInterface::fence(), madness::World::gop, madness::inner(), myreal(), madness::Function< T, NDIM >::reconstruct(), and std::tr1::T().
Referenced by madness::SCF::analyze_vectors(), compareGroundState(), compute_energy_with_U(), compute_madelung_energy(), compute_madelung_energy_PWSCF(), iterate(), main(), madness::MP2::solve_residual_equations(), test_modified(), and madness::Nemo::value().
void loadDefaultBasis (World & world, std::vector< WF > & boundList, double Z)
References PRINT, PRINTLINE, and toString().
void loadList (World & world, std::vector< std::string > & boundList, std::vector< std::string > & unboundList)
References m, and PRINTLINE.
Referenced by main().
double myreal (double t)
Referenced by energy().
double myreal (const double_complex & t)
std::ostream& operator<< (std::ostream & s, const InputParameters & p)
void printBasis (World & world, double Z, double cutoff)
References mpfr::cos(), madness::f, madness::imag(), k, PRINT, PRINTLINE, real(), mpfr::sin(), and madness::vec().
void projectZdip (World & world, std::vector< WF > stateList)
References madness::conj(), madness::Function< T, NDIM >::func, madness::inner(), PRINT, real(), and zdipole().
template<class T > std::string toString (const T & a)
Referenced by loadDefaultBasis().
complexd V (const vector3D & r)
References InputParameters::cut, InputParameters::natom, InputParameters::R, madness::smoothed_potential(), sqrt(), mpfr::sum(), and InputParameters::Z.
Referenced by compareGroundState().
bool wave_function_exists (World & world, int step)
Referenced by projectL(), projectPsi(), and zSlice().
const char * wave_function_filename (int step)
Referenced by wave_function_exists(), wave_function_load(), and wave_function_store().
complex_functionT wave_function_load (World & world, int step)
Referenced by projectL(), projectPsi(), and zSlice().
void wave_function_store (World & world, int step, const complex_functionT & psi)
complexd zdipole (const vector3D & r)
Referenced by projectZdip().
Variable Documentation
InputParameters param
Referenced by madness::CIS::CIS().