MADNESS: fred.cc File Reference
fred.cc File Reference
#include <iostream>
#include <cmath>
#include <madness/tensor/tensor.h>
#include <madness/tensor/tensor_lapack.h>
#include <madness/world/print.h>
Functions
void drot (long n, double *restrict a, double *restrict b, double s, double c)
int main ()
Function Documentation
void drot (long n, double *restrict a, double *restrict b, double s, double c)
int main ()
References mpfr::atan(), c, madness::copy(), mpfr::cos(), madness::drot(), mpfr::fabs(), IND, madness::inner(), ITERATOR, pi, madness::print(), mpfr::sin(), mpfr::sum(), thresh, and madness::transpose().