MADNESS: functionio.cc File Reference
functionio.cc File Reference
Example of I/O with functions.
#include <madness/mra/mra.h>
#include <madness/constants.h>
Functions
int main (int argc, char **argv)
Detailed Description
Example of I/O with functions.
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::f, madness::finalize(), madness::g, madness::initialize(), L, madness::norm2(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), and madness::startup().