MADNESS: gygi_soltion.cc File Reference
gygi_soltion.cc File Reference
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include <ctime>
#include <madness/tensor/solvers.h>
#include <madness/mra/funcplot.h>
#include "nonlinsol.h"
Macros
#define TIME(MSG, X)
Typedefs
typedef real_function_3d realfunc
Functions
double nuc_func (const coord_3d &r)
double rho_func (const coord_3d &r)
int main (int argc, char **argv)
Variables
const double epsilon = 78.304
const double beta = 1.300
const double rho_0 = 0.0004
const double Gamma = 0.07197
const int k = 8
const double L = 10
const double thresh = 1e-6
const int maxiter = 20
double XXstart
Macro Definition Documentation
#define TIME (MSG, X)
Value:
XXstart=wall_time();          \
                    X; \
                    if (world.rank() == 0)print("timer: ", MSG,"used",wall_time() - XXstart) \
Referenced by main().
Typedef Documentation
typedef real_function_3d realfunc
Function Documentation
int main (int argc, char ** argv)
References madness::BC_FREE, beta, SafeMPI::COMM_WORLD, madness::f, madness::finalize(), madness::initialize(), k, L, nuc_func(), madness::plot_line(), madness::plotdx(), madness::print(), rho_func(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), thresh, TIME, and madness::Function< T, NDIM >::trace().
double nuc_func (const coord_3d & r)
References mpfr::exp(), and madness::constants::pi.
Referenced by main().
double rho_func (const coord_3d & r)
References mpfr::exp(), madness::constants::pi, R, and sqrt().
Referenced by main().
Variable Documentation
const double beta = 1.300
Referenced by madness::Function< double, 6 >::gaxpy(), madness::Function< double, 6 >::gaxpy_ext(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext(), madness::FunctionImpl< Q, NDIM >::gaxpy_ext_recursive(), madness::FunctionNode< T, NDIM >::gaxpy_inplace(), madness::FunctionImpl< Q, NDIM >::gaxpy_inplace(), madness::Function< double, 6 >::gaxpy_oop(), madness::gaxpy_oop_reconstructed(), madness::GaussianConvolution1D< Q >::issmall(), main(), and madness::GaussianConvolution1D< Q >::rnlp().
const double epsilon = 78.304
Referenced by cfrac(), jacobi(), main(), opt(), series(), and test().
const double Gamma = 0.07197
const int k = 8
Referenced by main().
const double L = 10
Referenced by main().
const int maxiter = 20
Referenced by main(), opt(), SVPEColloidSolver::solve(), solve(), and SVPEColloidSolver::solve_Laplace().
const double rho_0 = 0.0004
const double thresh = 1e-6
Referenced by main().
double XXstart