MADNESS: h2dynamic.cc File Reference
h2dynamic.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include "nonlinsol.h"
Functions
double rifunction (const coord_3d &r)
double iterate_ground (World &world, NonlinearSolver &solver, real_function_3d &V, real_function_3d &psi, double &eps)
double iterate_excite (World &world, NonlinearSolver &solver, real_function_3d &V, real_function_3d &psi, real_function_3d &dpsi, double &eps, real_function_3d &ri)
double iterate_xy (World &world, real_function_3d &V, real_function_3d &psi, real_function_3d &dpsi, double &eps, real_function_3d &ri, real_function_3d &x, real_function_3d &y, double omega)
int main (int argc, char **argv)
Function Documentation
double iterate_excite (World & world, NonlinearSolver & solver, real_function_3d & V, real_function_3d & psi, real_function_3d & dpsi, double & eps, real_function_3d & ri)
References madness::Function< T, NDIM >::norm2(), op(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::scale(), sqrt(), madness::Function< T, NDIM >::truncate(), and madness::NonlinearSolverND< NDIM >::update().
Referenced by main().
double iterate_ground (World & world, NonlinearSolver & solver, real_function_3d & V, real_function_3d & psi, double & eps)
References madness::inner(), madness::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), sqrt(), madness::Function< T, NDIM >::truncate(), and madness::NonlinearSolverND< NDIM >::update().
Referenced by main().
double iterate_xy (World & world, real_function_3d & V, real_function_3d & psi, real_function_3d & dpsi, double & eps, real_function_3d & ri, real_function_3d & x, real_function_3d & y, double omega)
References madness::inner(), madness::norm2(), madness::print(), psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), sqrt(), and madness::Function< T, NDIM >::truncate().
Referenced by main().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e1(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), madness::inner(), iterate_excite(), iterate_ground(), iterate_xy(), k, L, madness::Function< T, NDIM >::norm2(), op(), potential(), madness::print(), psi(), R, madness::World::rank(), rifunction(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::square(), madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), and V().
double rifunction (const coord_3d & r)
Referenced by main().