MADNESS: he.cc File Reference
he.cc File Reference
Solves the Hartree-Fock equations for the helium atom.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/lbdeux.h>
Functions
void distances (const coord_6d &r, double &r1, double &r2, double &r12)
real_function_6d multiply_by_V (const real_function_6d &psi)
double energy (World &world, const real_function_6d &psi)
int main (int argc, char **argv)
Detailed Description
Solves the Hartree-Fock equations for the helium atom.
Function Documentation
void distances (const coord_6d & r, double & r1, double & r2, double & r12)
References sqrt().
double energy (World & world, const real_function_6d & psi)
References madness::inner(), k, L, multiply_by_V(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::size(), and thresh.
Referenced by main().
int main (int argc, char ** argv)
References madness::LoadBalanceDeux< NDIM >::add_tree(), SafeMPI::COMM_WORLD, energy(), madness::FunctionFactory< T, NDIM >::f(), madness::finalize(), madness::initialize(), k, L, madness::LoadBalanceDeux< NDIM >::load_balance(), psi(), madness::World::rank(), madness::FunctionDefaults< NDIM >::redistribute(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), thresh, madness::TT_2D, and madness::wall_time().
real_function_6d multiply_by_V (const real_function_6d & psi)
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by energy().