MADNESS: heat2.cc File Reference
heat2.cc File Reference
Example Green function for the 3D heat equation with a linear term.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Functions
int main (int argc, char **argv)
Detailed Description
Example Green function for the 3D heat equation with a linear term.
Function Documentation
int main (int argc, char ** argv)
References c, SafeMPI::COMM_WORLD, madness::Function< T, NDIM >::err(), madness::WorldGopInterface::fence(), madness::finalize(), G, madness::World::gop, madness::initialize(), k, L, madness::Function< T, NDIM >::norm2(), madness::constants::pi, madness::print(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), uexact(), and madness::Function< T, NDIM >::unaryop().