MADNESS: molecularbasis.h File Reference
hf/molecularbasis.h File Reference
#include <madness/madness_config.h>
#include <madness/constants.h>
#include "mentity.h"
#include <madness/tinyxml/tinyxml.h>
#include <madness/tensor/tensor.h>
#include <vector>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <cstdio>
Classes
class ContractedGaussianShell
Represents a single shell of contracted, Cartesian, Gaussian primitives.
class AtomicBasis
Represents multiple shells of contracted gaussians on a single center.
class AtomicBasisFunction
Used to represent one basis function from a shell on a specific center.
class AtomicBasisSet
Contracted Gaussian basis.
class AtomicBasisSet::AnalysisSorter< T >
Functions
std::ostream & operator<< (std::ostream &s, const ContractedGaussianShell &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasis &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasisFunction &a)
Function Documentation
std::ostream& operator<< (std::ostream & s, const ContractedGaussianShell & c)
References madness::ContractedGaussianShell::angular_momentum(), madness::ContractedGaussianShell::get_coeff(), madness::ContractedGaussianShell::get_expnt(), and madness::ContractedGaussianShell::nprim().
std::ostream& operator<< (std::ostream & s, const AtomicBasis & c)
References madness::AtomicBasis::get_dmat(), madness::AtomicBasis::get_shells(), madness::AtomicBasis::has_guess_info(), and madness::AtomicBasis::nshell().
std::ostream& operator<< (std::ostream & s, const AtomicBasisFunction & a)
References madness::AtomicBasisFunction::print_me().