MADNESS: hyp.h File Reference
hyp.h File Reference
#include <iostream>
#include <complex>
#include <algorithm>
#include <cstdio>
#include <cmath>
#include <nick/mpreal.h>
Typedefs
typedef mpfr::mpreal extended_real
typedef std::complex
< extended_real > extended_complex
typedef std::complex< double > complexd
Functions
complexd conhyp (const complexd &a_arg, const complexd &b_arg, const complexd &z_arg)
Computes 1F1(a,b,z) internally using extended precision.
Typedef Documentation
typedef std::complex<double> complexd
typedef std::complex<extended_real> extended_complex
typedef mpfr::mpreal extended_real
Function Documentation
complexd conhyp (const complexd & a_arg, const complexd & b_arg, const complexd & z_arg)
Computes 1F1(a,b,z) internally using extended precision.
If result is larger than 1.0, result should be accurate to full double precision, otherwise result is accurate to somewhat better than 1e-17. However, the termination test is not very smart so there may be failures.
References a(), madness::abs(), b(), mpfr::mpreal::get_default_prec(), max, mpfr::mpreal::set_default_prec(), mpfr::sum(), and test().
Referenced by compare1F1(), PhiK::f11(), and Phikl::f11().