MADNESS: hyp.cc File Reference
hyp.cc File Reference
#include <nick/hyp.h>
Functions
complexd conhyp (const complexd &a_arg, const complexd &b_arg, const complexd &z_arg)
Computes 1F1(a,b,z) internally using extended precision.
Function Documentation
complexd conhyp (const complexd & a_arg, const complexd & b_arg, const complexd & z_arg)
Computes 1F1(a,b,z) internally using extended precision.
If result is larger than 1.0, result should be accurate to full double precision, otherwise result is accurate to somewhat better than 1e-17. However, the termination test is not very smart so there may be failures.
References a(), madness::abs(), b(), mpfr::mpreal::get_default_prec(), max, mpfr::mpreal::set_default_prec(), mpfr::sum(), and test().
Referenced by compare1F1(), PhiK::f11(), and Phikl::f11().