MADNESS: mcpfit.cc File Reference
jacob/mcpfit.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
#include <moldft/corepotential.h>
#include <iostream>
#include <iomanip>
#include <set>
#include <cstdio>
Classes
class LevelPmap
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef vector< functionT > vecfuncT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
typedef SeparatedConvolution
< double, 3 > operatorT
typedef std::shared_ptr
< operatorT > poperatorT
Functions
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
double mask1 (double x)
double mask3 (const coordT &ruser)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
void print (const tensorT &t)
int main (int argc, char **argv)
Typedef Documentation
typedef Vector<double,3> coordT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef SeparatedConvolution<double,3> operatorT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef std::shared_ptr<operatorT> poperatorT
typedef Tensor<double> tensorT
typedef vector<functionT> vecfuncT
Function Documentation
void END_TIMER (World & world, const char * msg)
References madness::World::rank(), sss, ttt, and madness::wall_time().
int main (int argc, char ** argv)
References madness::CorePotential::alpha, b(), SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::print_stats(), madness::FunctionDefaults< NDIM >::set_pmap(), and madness::startup().
double mask1 (double x) inline
double mask3 (const coordT & ruser)
References madness::mask1(), and mask3().
void print (const tensorT & t)
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
void START_TIMER (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().