MADNESS: moldft.cc File Reference
jacob/moldft.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/misc/ran.h>
#include <madness/tensor/solvers.h>
#include <ctime>
#include <list>
#include <madness/mra/sdf_shape_3D.h>
#include <madness/mra/funcplot.h>
#include <madness/constants.h>
#include <vector>
#include <examples/molecularmask.h>
#include <jacob/svpe_molecule_colloid.h>
#include <examples/nonlinsol.h>
#include <jacob/molecule.h>
#include <jacob/molecularbasis.h>
#include <jacob/corepotential.h>
#include <jacob/abinitdftsolventsolver.h>
#include <jacob/svpe.h>
Classes
class LevelPmap
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
typedef std::pair< vecfuncT,
vecfuncT > pairvecfuncT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
typedef SeparatedConvolution
< double, 3 > operatorT
typedef std::shared_ptr
< operatorT > poperatorT
typedef real_function_3d realfunc
typedef real_derivative_3d realderiv
typedef real_functor_3d realfunct
Functions
int x_rks_s__ (const double *rho, double *f, double *dfdra)
int c_rks_vwn5__ (const double *rho, double *f, double *dfdra)
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
double mask1 (double x)
double mask3 (const coordT &ruser)
double rsquared (const coordT &r)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
tensorT sqrt (const tensorT &s, double tol=1e-8)
Computes matrix square root (not used any more?)
int main (int argc, char **argv)
Variables
double ttt
double sss
Typedef Documentation
typedef Vector<double,3> coordT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef SeparatedConvolution<double,3> operatorT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef std::shared_ptr<operatorT> poperatorT
typedef real_derivative_3d realderiv
typedef real_function_3d realfunc
typedef real_functor_3d realfunct
typedef std::vector<pairvecfuncT> subspaceT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
int c_rks_vwn5__ (const double * rho, double * f, double * dfdra) inline
References a2, mpfr::atan(), c_b7, madness::c_b7, mpfr::log(), and sqrt().
Referenced by madness::XCfunctional::exc(), xc_lda_potential::operator()(), madness::xc_lda_potential::operator()(), and madness::XCfunctional::vxc().
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void END_TIMER (World & world, const char * msg)
References madness::World::rank(), and madness::wall_time().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::World::size(), madness::startup(), and madness::MolecularEnergy::value().
double mask1 (double x) inline
double mask3 (const coordT & ruser)
References madness::mask1(), and mask3().
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
double rsquared (const coordT & r)
References rsquared().
tensorT sqrt (const tensorT & s, double tol = 1e-8)
Computes matrix square root (not used any more?)
References c, MADNESS_EXCEPTION, madness::print(), and madness::syev().
void START_TIMER (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, and madness::wall_time().
int x_rks_s__ (const double * rho, double * f, double * dfdra) inline
References c_b2, and madness::c_b2.
Referenced by madness::XCfunctional::exc(), xc_lda_potential::operator()(), madness::xc_lda_potential::operator()(), and madness::XCfunctional::vxc().
Variable Documentation
double sss
double ttt