MADNESS: atomutil.h File Reference
jacob/atomutil.h File Reference
#include <string>
Classes
struct AtomicData
Functions
const AtomicData & get_atomic_data (unsigned int atn)
const AtomicData & get_atomic_radius (unsigned int atn)
unsigned int symbol_to_atomic_number (const std::string &symbol)
double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
double smoothed_potential (double r)
Smoothed 1/r potential.
double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
Function Documentation
double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
dV/dx = (x/r) * du(r/c)/(c*c)
References a().
Referenced by madness::CorePotential::eval_derivative(), Molecule::nuclear_attraction_potential_derivative(), and madness::Molecule::nuclear_attraction_potential_derivative().
const AtomicData& get_atomic_data (unsigned int atn)
Referenced by madness::Molecule::add_atom(), Molecule::print(), madness::Molecule::print(), madness::AtomicBasisSet::print(), AtomicBasisSet::print(), madness::AtomicBasisSet::print_all(), AtomicBasisSet::print_all(), madness::AtomicBasisSet::print_anal(), and AtomicBasisSet::print_anal().
const AtomicData& get_atomic_radius (unsigned int atn)
double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
Invoke as rho(r/c)/c^3 where c is the radius of the smoothed volume.
References mpfr::exp(), and madness::constants::pi.
Referenced by madness::Molecule::mol_nuclear_charge_density(), MolecularEntity::nuclear_charge_density(), Molecule::nuclear_charge_density(), and madness::Molecule::nuclear_charge_density().
double smoothed_potential (double r)
Smoothed 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References a(), madness::abs(), mpfr::erf(), mpfr::exp(), madness::constants::pi, and sqrt().
Referenced by madness::CorePotential::eval(), madness::CorePotential::eval_derivative(), MolecularEntity::nuclear_attraction_potential(), Molecule::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential(), and V().
double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, and mpfr::min().
Referenced by MolecularEntity::add_atom(), Molecule::add_atom(), madness::Molecule::add_atom(), Molecule::read_core_file(), madness::Molecule::read_core_file(), Molecule::set_eprec(), madness::Molecule::set_eprec(), and madness::CorePotentialManager::set_eprec().
unsigned int symbol_to_atomic_number (const std::string & symbol)
References madness::lowercase(), AtomicData::symbol_lowercase, and madness::AtomicData::symbol_lowercase.
Referenced by madness::get_charge_from_file(), madness::GTHPseudopotential< double >::load_pseudo_from_file(), MolecularEntity::read_file(), Molecule::read_file(), madness::Molecule::read_file(), AtomicBasisSet::read_file(), and madness::AtomicBasisSet::read_file().