MADNESS: molecularbasis.cc File Reference
jacob/molecularbasis.cc File Reference
#include <moldft/molecularbasis.h>
Functions
std::ostream & operator<< (std::ostream &s, const ContractedGaussianShell &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasis &c)
std::ostream & operator<< (std::ostream &s, const AtomicBasisFunction &a)
Function Documentation
std::ostream& operator<< (std::ostream & s, const ContractedGaussianShell & c)
References ContractedGaussianShell::angular_momentum(), ContractedGaussianShell::get_coeff(), ContractedGaussianShell::get_expnt(), and ContractedGaussianShell::nprim().
std::ostream& operator<< (std::ostream & s, const AtomicBasis & c)
References AtomicBasis::get_dmat(), AtomicBasis::get_shells(), AtomicBasis::has_guess_info(), and AtomicBasis::nshell().
std::ostream& operator<< (std::ostream & s, const AtomicBasisFunction & a)
References AtomicBasisFunction::print_me().