MADNESS: jimkernel.cc File Reference
jimkernel.cc File Reference
#include <madness/tensor/tensor.h>
#include <madness/tensor/mtxmq.h>
#include <madness/world/print.h>
#include <madness/world/worldtime.h>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
Functions
int main ()
Function Documentation
int main ()
References madness::aligned_add(), madness::aligned_sub(), c, k, m, madness::mTxmq(), and madness::print().