MADNESS: lineplot.cc File Reference
lineplot.cc File Reference
#include <madness/mra/mra.h>
#include <madness/world/parar.h>
#include <madness/constants.h>
#include <madness/tensor/vmath.h>
#include <madness/mra/lbdeux.h>
#include <complex>
Macros
#define PRINT(str) if(world.rank()==0) std::cout << str
#define PRINTLINE(str) if(world.rank()==0) std::cout << str << std::endl
Typedefs
typedef std::complex< double > double_complex
typedef Function
< double_complex, 3 > complex_functionT
typedef Vector< double, 3 > coordT
Functions
const char * wave_function_filename (int step)
bool wave_function_exists (World &world, int step)
complex_functionT wave_function_load (World &world, int step)
void line_plot (World &world, int step, complex_functionT &psi)
int main (int argc, char **argv)
Macro Definition Documentation
#define PRINT (str) if(world.rank()==0) std::cout << str
Referenced by compare1F1(), compareGroundState(), loadDefaultBasis(), printBasis(), projectL(), projectPsi(), projectZdip(), testIntegral(), and zSlice().
#define PRINTLINE (str) if(world.rank()==0) std::cout << str << std::endl
Referenced by belkic(), compare1F1(), compareGroundState(), doWork(), loadDefaultBasis(), loadList(), loadParameters(), loadParameters2(), main(), printBasis(), projectL(), projectPsi(), testIntegral(), and zSlice().
Typedef Documentation
typedef Function<double_complex,3> complex_functionT
typedef Vector<double,3> coordT
typedef std::complex<double> double_complex
Function Documentation
void line_plot (World & world, int step, complex_functionT & psi)
References madness::Function< T, NDIM >::eval(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, L, madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::World::size(), madness::WorldGopInterface::sum(), and wave_function_filename().
Referenced by main().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), line_plot(), madness::print(), madness::print_stats(), PRINTLINE, psi(), madness::World::rank(), madness::World::size(), madness::startup(), wave_function_exists(), and wave_function_load().
bool wave_function_exists (World & world, int step)
References wave_function_filename().
Referenced by main().
const char* wave_function_filename (int step)
Referenced by line_plot(), wave_function_exists(), and wave_function_load().
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by main().