MADNESS: localize_boys.cc File Reference
localize_boys.cc File Reference
#include <madness/world/world.h>
#include <madness/mra/mra.h>
#include <utility>
#include <ctime>
#include <cmath>
#include <madness/tensor/tensor.h>
#include <ii/systolic.h>
Functions
template<typename T >
DistributedMatrix< T > plocalize_boys (World &world, const std::vector< Function< T, 3 > > &mo, const std::vector< int > &set, const double vtol, const double thresh=1e-9, const double thetamax=0.5, const bool randomize=true)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
image of usage
References SafeMPI::COMM_WORLD, madness::error(), madness::finalize(), madness::initialize(), madness::print(), and madness::redirectio().
template<typename T > DistributedMatrix<T> plocalize_boys (World & world, const std::vector< Function< T, 3 > > & mo, const std::vector< int > & set, const double vtol, const double thresh = 1e-9, const double thetamax = 0.5, const bool randomize = true)
This is an adapter function. returns a distributed and localized set
Parameters
mo molecules
set basis set
do print
number of molecule
make big matrix such like ... +—+-——+-——+-——+ | I | dip_x | dip_y | dip_z | +—+-——+-——+-——+
for all axis, make dipole function
image of usage
References madness::concatenate_rows(), madness::DistributedMatrix< T >::copyin(), madness::idMatrix(), madness::FunctionFactory< T, NDIM >::initial_level(), madness::matrix_inner(), madness::mul_sparse(), madness::SystolicMatrixAlgorithm< T >::solve(), and thresh.