MADNESS: lookup3.c File Reference
lookup3.c File Reference
#include <stdio.h>
#include <time.h>
#include <stdint.h>
#include <sys/param.h>
Macros
#define HASH_LITTLE_ENDIAN 0
#define HASH_BIG_ENDIAN 0
#define hashsize(n) ((uint32_t)1<<(n))
#define hashmask(n) (hashsize(n)-1)
#define rot(x, k) (((x)<<(k)) | ((x)>>(32-(k))))
#define mix(a, b, c)
#define final(a, b, c)
Functions
uint32_t hashword (const uint32_t *k, size_t length, uint32_t initval)
uint32_t hashlittle (const void *key, size_t length, uint32_t initval)
void hashlittle2 (const void *key, size_t length, uint32_t *pc, uint32_t *pb)
uint32_t hashbig (const void *key, size_t length, uint32_t initval)
Macro Definition Documentation
#define final (a, b, c)
Value:
{ \
  c ^= b; c -= rot(b,14); \
  a ^= c; a -= rot(c,11); \
  b ^= a; b -= rot(a,25); \
  c ^= b; c -= rot(b,16); \
  a ^= c; a -= rot(c,4);  \
  b ^= a; b -= rot(a,14); \
  c ^= b; c -= rot(b,24); \
}
#define HASH_BIG_ENDIAN 0
Referenced by hashbig().
#define HASH_LITTLE_ENDIAN 0
Referenced by hashlittle(), and hashlittle2().
#define hashmask (n) (hashsize(n)-1)
#define hashsize (n) ((uint32_t)1<<(n))
#define mix (a, b, c)
Value:
{ \
  a -= c;  a ^= rot(c, 4);  c += b; \
  b -= a;  b ^= rot(a, 6);  a += c; \
  c -= b;  c ^= rot(b, 8);  b += a; \
  a -= c;  a ^= rot(c,16);  c += b; \
  b -= a;  b ^= rot(a,19);  a += c; \
  c -= b;  c ^= rot(b, 4);  b += a; \
}
Referenced by hashbig(), hashlittle(), hashlittle2(), and hashword().
#define rot (x, k) (((x)<<(k)) | ((x)>>(32-(k))))
Referenced by SCF::diag_fock_matrix(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), and madness::SCF::get_fock_transformation().
Function Documentation
uint32_t hashbig (const void * key, size_t length, uint32_t initval)
References a(), b(), c, HASH_BIG_ENDIAN, k, and mix.
uint32_t hashlittle (const void * key, size_t length, uint32_t initval)
References a(), b(), c, HASH_LITTLE_ENDIAN, k, and mix.
Referenced by madness::hash_range(), and madness::hash_value().
void hashlittle2 (const void * key, size_t length, uint32_t * pc, uint32_t * pb)
References a(), b(), c, HASH_LITTLE_ENDIAN, k, and mix.
uint32_t hashword (const uint32_t * k, size_t length, uint32_t initval)
References a(), b(), c, and mix.
Referenced by madness::hash_range(), and madness::hash_value().