MADNESS: moldft.cc File Reference
moldft/moldft.cc File Reference
#include <chem/SCF.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References madness::CalculationParameters::algopt, SafeMPI::COMM_WORLD, madness::CalculationParameters::derivatives, madness::SCF::derivatives(), madness::CalculationParameters::dipole, madness::SCF::dipole(), madness::SCF::do_plots(), madness::CalculationParameters::econv, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Molecule::get_all_coords(), madness::CalculationParameters::gmaxiter, madness::World::gop, madness::CalculationParameters::gopt, madness::CalculationParameters::gprec, madness::CalculationParameters::gprint(), madness::CalculationParameters::gtest, madness::CalculationParameters::gtol, madness::CalculationParameters::gval, madness::SCF::initial_load_bal(), madness::initialize(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::Molecule::natom(), madness::QuasiNewton::optimize(), madness::SCF::param, madness::print(), madness::Molecule::print(), madness::CalculationParameters::print(), madness::print_meminfo(), madness::print_stats(), madness::SCF::propagate(), madness::CalculationParameters::protocol_data, madness::World::rank(), madness::QuasiNewton::set_hessian(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::SCF::set_protocol(), madness::QuasiNewton::set_test(), madness::QuasiNewton::set_update(), madness::World::size(), madness::startup(), TAU_START, TAU_STOP, madness::CalculationParameters::tdksprop, and madness::MolecularEnergy::value().