MADNESS: crayio.c File Reference
moldft/fci/crayio.c File Reference
#include <stdio.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/file.h>
#include <fcntl.h>
Macros
#define L_XTND SEEK_END
#define max_file 99
Typedefs
typedef int integer
Functions
char * malloc ()
off_t lseek ()
char * strncpy ()
void walltm_ (double *ai)
void InitFileStats (struct w_file *file)
void PrintFileStats (struct w_file *unit, struct w_file *file)
void InitFileData (struct w_file *file)
void FirstCall ()
void wclose_ (integer *unit, integer *ierr)
void wopen_ (integer *unit, char *name, integer *blocks, integer *stats, integer *ierr, int lennam)
void getwa_ (integer *unit, double *result, integer *addr, integer *count, integer *ierr)
void putwa_ (integer *unit, double *source, integer *addr, integer *count, integer *ierr)
Macro Definition Documentation
#define L_XTND SEEK_END
Referenced by wopen_().
#define max_file 99
Referenced by FirstCall(), and wopen_().
Typedef Documentation
typedef int integer
Function Documentation
void FirstCall ()
References InitFileData(), InitFileStats(), and max_file.
Referenced by getwa_(), putwa_(), wclose_(), and wopen_().
void getwa_ (integer * unit, double * result, integer * addr, integer * count, integer * ierr)
References FirstCall(), lseek(), and walltm_().
void InitFileData (struct w_file * file)
Referenced by FirstCall(), and wclose_().
void InitFileStats (struct w_file * file)
Referenced by FirstCall(), and wclose_().
off_t lseek ()
Referenced by getwa_(), putwa_(), and wopen_().
char* malloc ()
Referenced by wopen_().
void PrintFileStats (struct w_file * unit, struct w_file * file)
Referenced by wclose_().
void putwa_ (integer * unit, double * source, integer * addr, integer * count, integer * ierr)
References FirstCall(), lseek(), and walltm_().
char* strncpy ()
Referenced by wopen_().
void walltm_ (double * ai)
Referenced by getwa_(), and putwa_().
void wclose_ (integer * unit, integer * ierr)
References FirstCall(), InitFileData(), InitFileStats(), and PrintFileStats().
void wopen_ (integer * unit, char * name, integer * blocks, integer * stats, integer * ierr, int lennam)
References FirstCall(), L_XTND, lseek(), malloc(), max_file, and strncpy().