MADNESS: moldft-elem.cc File Reference
moldft-elem.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/misc/ran.h>
#include <madness/tensor/solvers.h>
#include <madness/mra/qmprop.h>
#include <ctime>
#include <list>
#include <moldft/molecule.h>
#include <moldft/molecularbasis.h>
#include <moldft/corepotential.h>
#include <moldft/xcfunctional.h>
#include <elemental.hpp>
Classes
class LevelPmap
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
typedef std::pair< vecfuncT,
vecfuncT > pairvecfuncT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
typedef SeparatedConvolution
< double, 3 > operatorT
typedef std::shared_ptr
< operatorT > poperatorT
typedef Function< std::complex
< double >, 3 > complex_functionT
typedef std::vector
< complex_functionT > cvecfuncT
typedef Convolution1D
< double_complex > complex_operatorT
Functions
Function< double_complex, 3 > make_exp (double t, const Function< double, 3 > &v)
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
double mask1 (double x)
double mask3 (const coordT &ruser)
double rsquared (const coordT &r)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
tensorT sqrt (const tensorT &s, double tol=1e-8)
Computes matrix square root (not used any more?)
int main (int argc, char **argv)
Variables
double ttt
double sss
Typedef Documentation
typedef Function<std::complex<double>,3> complex_functionT
typedef Convolution1D<double_complex> complex_operatorT
typedef Vector<double,3> coordT
typedef std::vector<complex_functionT> cvecfuncT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef SeparatedConvolution<double,3> operatorT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef std::shared_ptr<operatorT> poperatorT
typedef std::vector<pairvecfuncT> subspaceT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void END_TIMER (World & world, const char * msg)
References madness::World::rank(), and madness::wall_time().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::QuasiNewton::optimize(), madness::print(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::QuasiNewton::set_test(), madness::QuasiNewton::set_update(), madness::World::size(), madness::startup(), and madness::MolecularEnergy::value().
Function<double_complex,3> make_exp (double t, const Function< double, 3 > & v)
References expV(), make_exp(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::unaryop().
double mask1 (double x) inline
double mask3 (const coordT & ruser)
References madness::mask1(), and mask3().
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
double rsquared (const coordT & r)
References rsquared().
tensorT sqrt (const tensorT & s, double tol = 1e-8)
Computes matrix square root (not used any more?)
References c, MADNESS_EXCEPTION, madness::print(), and madness::syev().
void START_TIMER (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, and madness::wall_time().
Variable Documentation
double sss
double ttt