MADNESS: molecularmask.h File Reference
molecularmask.h File Reference
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include <cmath>
#include <vector>
Classes
class MolecularMaskBase
class MolecularVolumeMask
class MolecularVolumeComplementMask
class MolecularVolumeExponentialSwitch
Switches between positive values Vint and Vext with special log derivative.
class MolecularVolumeExponentialSwitchReciprocal
Computes the reciprocal of MolecularVolumeExponentialSwitch.
class MolecularSurface
class MolecularVolumeMaskGrad
class MolecularVolumeExponentialSwitchLogGrad
Returns the requested component of the derivative of the log of MolecularVolumeExponentialSwitch.
Functions
double distance (const madness::coord_3d &a, const madness::coord_3d &b)
Function Documentation
double distance (const madness::coord_3d & a, const madness::coord_3d & b) inline
References sqrt().
Referenced by Molecule::core_potential_derivative(), madness::distance(), MolecularMaskBase::grad_sdf(), MolecularEntity::inter_atomic_distance(), Molecule::inter_atomic_distance(), Molecule::molecular_core_potential(), MolecularEntity::nuclear_attraction_potential(), Molecule::nuclear_attraction_potential(), Molecule::nuclear_attraction_potential_derivative(), MolecularMaskBase::sdf(), and madness::SpectralPropagatorGaussLobatto::step().