MADNESS: mxm.h File Reference
mxm.h File Reference
Internal use only.
Functions
template<>
void mTxm (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b)
Matrix transpose * matrix (hand unrolled version)
template<>
void mxmT (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b)
Matrix * matrix transpose (hand unrolled version)
template<>
void mxm (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b)
Matrix * matrix (hand unrolled version)
template<>
void mTxmT (long dimi, long dimj, long dimk, double *restrict csave, const double *restrict asave, const double *restrict b)
Matrix transpose * matrix transpose (hand tiled and unrolled)
Detailed Description
Internal use only.
Function Documentation
template<> void mTxm (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b) inline
Matrix transpose * matrix (hand unrolled version)
References b(), and k.
Referenced by madness::fast_transform(), madness::inner_result(), transform3d(), and transform3d_3c().
template<> void mTxmT (long dimi, long dimj, long dimk, double *restrict csave, const double *restrict asave, const double *restrict b) inline
Matrix transpose * matrix transpose (hand tiled and unrolled)
References a(), b(), k, restrict, and mpfr::sum().
Referenced by madness::inner_result().
template<> void mxm (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b) inline
Matrix * matrix (hand unrolled version)
References b(), and k.
Referenced by madness::inner_result().
template<> void mxmT (long dimi, long dimj, long dimk, double *restrict c, const double *restrict a, const double *restrict b) inline
Matrix * matrix transpose (hand unrolled version)
References k, restrict, and mpfr::sum().
Referenced by madness::inner_result().