MADNESS: mpfr Namespace Reference
mpfr Namespace Reference
Classes
class conversion_overflow
class mpreal
Functions
const mpreal fma (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode)
const mpreal fms (const mpreal &v1, const mpreal &v2, const mpreal &v3, mp_rnd_t rnd_mode)
const mpreal agm (const mpreal &v1, const mpreal &v2, mp_rnd_t rnd_mode)
const mpreal hypot (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal sum (const mpreal tab[], unsigned long int n, mp_rnd_t rnd_mode)
const mpreal remainder (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal remquo (long *q, const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
template<class T >
std::string to_string (T t, std::ios_base &(*f)(std::ios_base &))
ostream & operator<< (ostream &os, const mpreal &v)
istream & operator>> (istream &is, mpreal &v)
const mpreal operator+ (const mpreal &a, const mpreal &b)
const mpreal operator+ (const mpreal &a, const mpz_t b)
const mpreal operator+ (const mpreal &a, const mpq_t b)
const mpreal operator+ (const mpreal &a, const long double b)
const mpreal operator+ (const mpreal &a, const double b)
const mpreal operator+ (const mpreal &a, const unsigned long int b)
const mpreal operator+ (const mpreal &a, const unsigned int b)
const mpreal operator+ (const mpreal &a, const long int b)
const mpreal operator+ (const mpreal &a, const int b)
const mpreal operator+ (const mpreal &a, const char *b)
const mpreal operator+ (const char *a, const mpreal &b)
const std::string operator+ (const mpreal &a, const std::string b)
const std::string operator+ (const std::string a, const mpreal &b)
const mpreal operator+ (const mpz_t b, const mpreal &a)
const mpreal operator+ (const mpq_t b, const mpreal &a)
const mpreal operator+ (const long double b, const mpreal &a)
const mpreal operator+ (const double b, const mpreal &a)
const mpreal operator+ (const unsigned long int b, const mpreal &a)
const mpreal operator+ (const unsigned int b, const mpreal &a)
const mpreal operator+ (const long int b, const mpreal &a)
const mpreal operator+ (const int b, const mpreal &a)
const mpreal operator- (const mpreal &a, const mpreal &b)
const mpreal operator- (const mpreal &a, const mpz_t b)
const mpreal operator- (const mpreal &a, const mpq_t b)
const mpreal operator- (const mpreal &a, const long double b)
const mpreal operator- (const mpreal &a, const double b)
const mpreal operator- (const mpreal &a, const unsigned long int b)
const mpreal operator- (const mpreal &a, const unsigned int b)
const mpreal operator- (const mpreal &a, const long int b)
const mpreal operator- (const mpreal &a, const int b)
const mpreal operator- (const mpreal &a, const char *b)
const mpreal operator- (const char *a, const mpreal &b)
const mpreal operator- (const mpz_t b, const mpreal &a)
const mpreal operator- (const mpq_t b, const mpreal &a)
const mpreal operator- (const long double b, const mpreal &a)
const mpreal operator* (const mpreal &a, const mpreal &b)
const mpreal operator* (const mpreal &a, const mpz_t b)
const mpreal operator* (const mpreal &a, const mpq_t b)
const mpreal operator* (const mpreal &a, const long double b)
const mpreal operator* (const mpreal &a, const double b)
const mpreal operator* (const mpreal &a, const unsigned long int b)
const mpreal operator* (const mpreal &a, const unsigned int b)
const mpreal operator* (const mpreal &a, const long int b)
const mpreal operator* (const mpreal &a, const int b)
const mpreal operator* (const mpz_t b, const mpreal &a)
const mpreal operator* (const mpq_t b, const mpreal &a)
const mpreal operator* (const long double b, const mpreal &a)
const mpreal operator* (const double b, const mpreal &a)
const mpreal operator* (const unsigned long int b, const mpreal &a)
const mpreal operator* (const unsigned int b, const mpreal &a)
const mpreal operator* (const long int b, const mpreal &a)
const mpreal operator* (const int b, const mpreal &a)
const mpreal operator/ (const mpreal &a, const mpreal &b)
const mpreal operator/ (const mpreal &a, const mpz_t b)
const mpreal operator/ (const mpreal &a, const mpq_t b)
const mpreal operator/ (const mpreal &a, const long double b)
const mpreal operator/ (const mpreal &a, const double b)
const mpreal operator/ (const mpreal &a, const unsigned long int b)
const mpreal operator/ (const mpreal &a, const unsigned int b)
const mpreal operator/ (const mpreal &a, const long int b)
const mpreal operator/ (const mpreal &a, const int b)
const mpreal operator/ (const long double b, const mpreal &a)
const mpreal operator<< (const mpreal &v, const unsigned long int k)
const mpreal operator<< (const mpreal &v, const unsigned int k)
const mpreal operator<< (const mpreal &v, const long int k)
const mpreal operator<< (const mpreal &v, const int k)
const mpreal operator>> (const mpreal &v, const unsigned long int k)
const mpreal operator>> (const mpreal &v, const unsigned int k)
const mpreal operator>> (const mpreal &v, const long int k)
const mpreal operator>> (const mpreal &v, const int k)
bool operator< (const mpreal &a, const unsigned long int b)
bool operator< (const mpreal &a, const unsigned int b)
bool operator< (const mpreal &a, const long int b)
bool operator< (const mpreal &a, const int b)
bool operator< (const mpreal &a, const long double b)
bool operator< (const mpreal &a, const double b)
bool operator< (const unsigned long int a, const mpreal &b)
bool operator< (const unsigned int a, const mpreal &b)
bool operator< (const long int a, const mpreal &b)
bool operator< (const int a, const mpreal &b)
bool operator< (const long double a, const mpreal &b)
bool operator< (const double a, const mpreal &b)
bool operator> (const mpreal &a, const unsigned long int b)
bool operator> (const mpreal &a, const unsigned int b)
bool operator> (const mpreal &a, const long int b)
bool operator> (const mpreal &a, const int b)
bool operator> (const mpreal &a, const long double b)
bool operator> (const mpreal &a, const double b)
bool operator> (const unsigned long int a, const mpreal &b)
bool operator> (const unsigned int a, const mpreal &b)
bool operator> (const long int a, const mpreal &b)
bool operator> (const int a, const mpreal &b)
bool operator> (const long double a, const mpreal &b)
bool operator> (const double a, const mpreal &b)
bool operator>= (const mpreal &a, const unsigned long int b)
bool operator>= (const mpreal &a, const unsigned int b)
bool operator>= (const mpreal &a, const long int b)
bool operator>= (const mpreal &a, const int b)
bool operator>= (const mpreal &a, const long double b)
bool operator>= (const mpreal &a, const double b)
bool operator>= (const unsigned long int a, const mpreal &b)
bool operator>= (const unsigned int a, const mpreal &b)
bool operator>= (const long int a, const mpreal &b)
bool operator>= (const int a, const mpreal &b)
bool operator>= (const long double a, const mpreal &b)
bool operator>= (const double a, const mpreal &b)
bool operator<= (const mpreal &a, const unsigned long int b)
bool operator<= (const mpreal &a, const unsigned int b)
bool operator<= (const mpreal &a, const long int b)
bool operator<= (const mpreal &a, const int b)
bool operator<= (const mpreal &a, const long double b)
bool operator<= (const mpreal &a, const double b)
bool operator<= (const unsigned long int a, const mpreal &b)
bool operator<= (const unsigned int a, const mpreal &b)
bool operator<= (const long int a, const mpreal &b)
bool operator<= (const int a, const mpreal &b)
bool operator<= (const long double a, const mpreal &b)
bool operator<= (const double a, const mpreal &b)
bool operator== (const mpreal &a, const unsigned long int b)
bool operator== (const mpreal &a, const unsigned int b)
bool operator== (const mpreal &a, const long int b)
bool operator== (const mpreal &a, const int b)
bool operator== (const mpreal &a, const long double b)
bool operator== (const mpreal &a, const double b)
bool operator== (const unsigned long int a, const mpreal &b)
bool operator== (const unsigned int a, const mpreal &b)
bool operator== (const long int a, const mpreal &b)
bool operator== (const int a, const mpreal &b)
bool operator== (const long double a, const mpreal &b)
bool operator== (const double a, const mpreal &b)
bool operator!= (const mpreal &a, const unsigned long int b)
bool operator!= (const mpreal &a, const unsigned int b)
bool operator!= (const mpreal &a, const long int b)
bool operator!= (const mpreal &a, const int b)
bool operator!= (const mpreal &a, const long double b)
bool operator!= (const mpreal &a, const double b)
bool operator!= (const unsigned long int a, const mpreal &b)
bool operator!= (const unsigned int a, const mpreal &b)
bool operator!= (const long int a, const mpreal &b)
bool operator!= (const int a, const mpreal &b)
bool operator!= (const long double a, const mpreal &b)
bool operator!= (const double a, const mpreal &b)
const mpreal sqrt (const unsigned int v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const long int v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const int v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const long double v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal sqrt (const double v, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const mpreal &a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const mpreal &b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned long int a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const unsigned int a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long int a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const int a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const long double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const long double a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const double b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const unsigned long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const unsigned int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const long int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal pow (const double a, const int b, mp_rnd_t rnd_mode=mpreal::default_rnd)
const mpreal operator- (const double b, const mpreal &a)
const mpreal operator- (const unsigned long int b, const mpreal &a)
const mpreal operator- (const unsigned int b, const mpreal &a)
const mpreal operator- (const long int b, const mpreal &a)
const mpreal operator- (const int b, const mpreal &a)
const mpreal operator/ (const unsigned long int b, const mpreal &a)
const mpreal operator/ (const unsigned int b, const mpreal &a)
const mpreal operator/ (const long int b, const mpreal &a)
const mpreal operator/ (const int b, const mpreal &a)
const mpreal operator/ (const double b, const mpreal &a)
const mpreal mul_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal mul_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode)
const mpreal div_2ui (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal div_2si (const mpreal &v, long int k, mp_rnd_t rnd_mode)
bool operator> (const mpreal &a, const mpreal &b)
bool operator>= (const mpreal &a, const mpreal &b)
bool operator< (const mpreal &a, const mpreal &b)
bool operator<= (const mpreal &a, const mpreal &b)
bool operator== (const mpreal &a, const mpreal &b)
bool operator!= (const mpreal &a, const mpreal &b)
bool _isnan (const mpreal &v)
bool _isinf (const mpreal &v)
bool _isnum (const mpreal &v)
bool _iszero (const mpreal &v)
bool _isint (const mpreal &v)
int sgn (const mpreal &v)
const mpreal frexp (const mpreal &v, mp_exp_t *exp)
const mpreal ldexp (const mpreal &v, mp_exp_t exp)
const mpreal modf (const mpreal &v, mpreal &n)
const mpreal sqr (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sqrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sqrt (const unsigned long int v, mp_rnd_t rnd_mode)
const mpreal cbrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal root (const mpreal &v, unsigned long int k, mp_rnd_t rnd_mode)
const mpreal fabs (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal abs (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal dim (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode)
int cmpabs (const mpreal &a, const mpreal &b)
const mpreal log (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal log2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal log10 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal exp10 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal cos (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sin (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal tan (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sec (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal csc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal cot (const mpreal &v, mp_rnd_t rnd_mode)
int sin_cos (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acos (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asin (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atan (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atan2 (const mpreal &y, const mpreal &x, mp_rnd_t rnd_mode)
const mpreal cosh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sinh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal tanh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal sech (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal csch (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal coth (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal acosh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal asinh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal atanh (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal fac_ui (unsigned long int v, mp_rnd_t rnd_mode)
const mpreal log1p (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal expm1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal eint (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal gamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal lngamma (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal lgamma (const mpreal &v, int *signp, mp_rnd_t rnd_mode)
const mpreal zeta (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal erf (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal erfc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _j0 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _j1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _jn (long n, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _y0 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _y1 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal _yn (long n, const mpreal &v, mp_rnd_t rnd_mode)
int sinh_cosh (mpreal &s, mpreal &c, const mpreal &v, mp_rnd_t rnd_mode)
const mpreal li2 (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal fmod (const mpreal &x, const mpreal &y, mp_rnd_t rnd_mode)
const mpreal rec_sqrt (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal const_log2 (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_pi (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_euler (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal const_catalan (mp_prec_t prec, mp_rnd_t rnd_mode)
const mpreal rint (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal ceil (const mpreal &v)
const mpreal floor (const mpreal &v)
const mpreal round (const mpreal &v)
const mpreal trunc (const mpreal &v)
const mpreal rint_ceil (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_floor (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_round (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal rint_trunc (const mpreal &v, mp_rnd_t rnd_mode)
const mpreal frac (const mpreal &v, mp_rnd_t rnd_mode)
void swap (mpreal &a, mpreal &b)
const mpreal max (const mpreal &x, const mpreal &y)
const mpreal min (const mpreal &x, const mpreal &y)
const mpreal nexttoward (const mpreal &x, const mpreal &y)
const mpreal nextabove (const mpreal &x)
const mpreal nextbelow (const mpreal &x)
const mpreal urandomb (gmp_randstate_t &state)
const mpreal pow (const mpreal &a, const mpreal &b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const mpz_t b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const unsigned long int b, mp_rnd_t rnd_mode)
const mpreal pow (const mpreal &a, const long int b, mp_rnd_t rnd_mode)
const mpreal pow (const unsigned long int a, const mpreal &b, mp_rnd_t rnd_mode)
const mpreal pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode)
Function Documentation
bool mpfr::_isinf (const mpreal & v) inline
bool mpfr::_isint (const mpreal & v) inline
bool mpfr::_isnan (const mpreal & v) inline
bool mpfr::_isnum (const mpreal & v) inline
bool mpfr::_iszero (const mpreal & v) inline
const mpreal mpfr::_j0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::_j1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::_jn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::_y0 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::_y1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::_yn (long n, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::abs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::acos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by SCF::localize_PM_task_kernel().
const mpreal mpfr::acosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::agm (const mpreal & v1, const mpreal & v2, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::asin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::asinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::atan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by c_rks_vwn5__(), c_uks_vwn5__(), madness::gauss_legendre_numeric(), main(), rks_c_vwn5__(), and test().
const mpreal mpfr::atan2 (const mpreal & y, const mpreal & x, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::atanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::cbrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::ceil (const mpreal & v) inline
Referenced by TipMolecule::TipMolecule().
int mpfr::cmpabs (const mpreal & a, const mpreal & b) inline
const mpreal mpfr::const_catalan (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References mpfr::mpreal::set_prec().
const mpreal mpfr::const_euler (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References mpfr::mpreal::set_prec().
const mpreal mpfr::const_log2 (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References mpfr::mpreal::set_prec().
const mpreal mpfr::const_pi (mp_prec_t prec = mpreal::default_prec, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References mpfr::mpreal::set_prec().
const mpreal mpfr::cos (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::trajectory< NDIM >::circle2(), madness::trajectory< NDIM >::circle_6d(), ScatteringWF::gamma(), madness::gauss_legendre_numeric(), madness::LocalizeBoys< T >::kernel(), SCF::localize_boys(), SCF::localize_PM_task_kernel(), main(), madness::detail::adqtest::operator()(), madness::VextCosFunctor< T >::operator()(), printBasis(), projectL(), MolecularMaskBase::special_points(), test(), and zSlice().
const mpreal mpfr::cosh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::cot (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::coth (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::csc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::csch (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::dim (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::FunctionImpl< T, NDIM >::coeffs_for_jun(), madness::SRConf< T >::dim_per_vector(), madness::SRConf< T >::get_configs(), madness::ConvolutionND< Q, NDIM >::getop(), madness::SRConf< T >::has_structure(), madness::GTHPseudopotential< double >::make_pseudo_potential(), madness::TensorIterator< T, Q, R >::operator++(), madness::FunctionImpl< T, NDIM >::print_stats(), madness::Function< double, 6 >::project_out(), madness::FunctionImpl< Q, NDIM >::project_out2(), madness::ConvolutionND< Q, NDIM >::setop(), and madness::TensorIterator< T, Q, R >::TensorIterator().
const mpreal mpfr::div_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by operator>>().
const mpreal mpfr::div_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by operator>>().
const mpreal mpfr::eint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::erf (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by exact_function(), madness::GaussianDomainMask::mask(), madness::VLocalFunctor::operator()(), and smoothed_potential().
const mpreal mpfr::erfc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by compute_madelung_energy(), compute_madelung_energy_PWSCF(), and MolecularMaskBase::mask().
const mpreal mpfr::exp (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by a(), ScatteringWF::aForm(), charge_function(), compute_madelung_energy(), compute_madelung_energy_PWSCF(), delsqfred(), delta(), MolecularMaskBase::dmask(), madness::GaussianDomainMask::dmask(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::GaussianDomainMask::dsurface(), dVsq(), electronic_charge_function(), madness::CorePotential::eval(), madness::CorePotential::eval_derivative(), ContractedGaussianShell::eval_radial(), madness::ContractedGaussianShell::eval_radial(), madness::CoreOrbital::eval_radial(), madness::CoreOrbital::eval_radial_derivative(), madness::detail::adqtest::exact(), fit(), fred(), ScatteringWF::gamma(), gen_ce(), guess(), TipMolecule::Inhomogeneity(), ScatteringWF::Init(), makedata(), myexp(), nuc_func(), nuclear_charge_function(), nuclear_potential(), madness::VLocalFunctor::operator()(), gauss_function::operator()(), madness::ProjRLMFunctor::operator()(), madness::detail::adqtest::operator()(), madness::ComplexExp< NDIM >::operator()(), SBF::operator()(), noise::operator()(), PhiK::operator()(), madness::WSTAtomicBasisFunctor::operator()(), Gaussian::operator()(), BoundWF::operator()(), PBF::operator()(), Expikr::operator()(), MolecularVolumeExponentialSwitch::operator()(), DBF::operator()(), madness::diffuse_functions::operator()(), madness::GaussianGenericFunctor< Q >::operator()(), madness::Convolution1D< Q >::phase(), madness::SCF::propagate(), psi(), psi_exact(), random_gaussian(), rho_func(), madness::GaussianConvolution1D< Q >::rnlp(), smoothed_density(), smoothed_potential(), madness::stheta_fd(), madness::GaussianDomainMask::surface(), test(), test_G_R_vectors(), test_gence(), V(), and vzExp().
const mpreal mpfr::exp10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::exp2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::expm1 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::fabs (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::abs(), MolecularEntity::bounding_cube(), Molecule::bounding_cube(), madness::Molecule::bounding_cube(), cfrac(), SCF::diag_fock_matrix(), MolecularMaskBase::dmask(), madness::LLRVDomainMask::dmask(), madness::GaussianDomainMask::dmask(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), testing::internal::DoubleNearPredFormat(), dVsq(), CubicInterpolationTable< complexd >::err(), madness::CoreOrbital::eval(), ContractedGaussianShell::eval(), madness::ContractedGaussianShell::eval(), madness::CoreOrbital::eval_derivative(), madness::SDFParaboloid::find_root(), madness::Solver< T, NDIM >::fix_occupations(), madness::SCF::get_fock_transformation(), madness::SDFParaboloid::get_roots(), is_equal(), jacobi(), madness::LocalizeBoys< T >::kernel(), SCF::localize_boys(), SCF::localize_PM_task_kernel(), LSQ(), main(), myf(), noise::noise(), PhiK::operator()(), Phikl::operator()(), opt(), Molecule::orient(), madness::Molecule::orient(), psi_exact(), FrequencyHandler::read_file(), madness::FunctionImpl< Q, NDIM >::read_grid(), madness::FunctionImpl< Q, NDIM >::read_grid2(), madness::SDFRectangle::sdf(), madness::SDFParaboloid::sdf(), madness::SDFBox::sdf(), madness::SDFCylinder::sdf(), series(), SCFParameters::set_molecular_info(), madness::CalculationParameters::set_molecular_info(), madness::TDA::solve_sequential(), test(), V(), and madness::MP2::value().
const mpreal mpfr::fac_ui (unsigned long int v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::floor (const mpreal & v) inline
Referenced by gen_ce(), and ScatteringWF::Init().
const mpreal mpfr::fma (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::fmod (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::fms (const mpreal & v1, const mpreal & v2, const mpreal & v3, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::frac (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by modf().
const mpreal mpfr::frexp (const mpreal & v, mp_exp_t * exp) inline
References mpfr::mpreal::get_exp(), and mpfr::mpreal::set_exp().
Referenced by mpfr::mpreal::fits_in_bits().
const mpreal mpfr::gamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::hypot (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::ldexp (const mpreal & v, mp_exp_t exp) inline
References mpfr::mpreal::default_rnd.
Referenced by mpfr::mpreal::fits_in_bits().
const mpreal mpfr::lgamma (const mpreal & v, int * signp, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::li2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::lngamma (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::log (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by c_rks_vwn5__(), c_uks_vwn5__(), calcEpshat(), gen_ce(), ln(), main(), madness::MyPmap< D >::MyPmap(), random_gaussian(), rks_c_vwn5__(), madness::GaussianConvolution1D< Q >::rnlp(), series(), test(), test_gaussian_num_coeffs(), and TipMolecule::TipMolecule().
const mpreal mpfr::log10 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by gen_ce(), and madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator()().
const mpreal mpfr::log1p (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::log2 (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::max (const mpreal & x, const mpreal & y) inline
const mpreal mpfr::min (const mpreal & x, const mpreal & y) inline
Referenced by madness::add(), madness::apply(), madness::GTHPseudopotential< double >::apply_potential(), madness::BinSorter< T, inserterT >::BinSorter(), madness::column_distributed_matrix(), madness::compress(), madness::SCF::compute_residual(), ContractedGaussianShell::ContractedGaussianShell(), madness::ContractedGaussianShell::ContractedGaussianShell(), madness::DistributedMatrix< double >::copy_from_replicated_patch(), madness::DistributedMatrix< double >::copy_to_replicated_patch(), CoreOrbital::CoreOrbital(), madness::CoreOrbital::CoreOrbital(), madness::TensorTrain< T >::decompose(), dgelss_(), dgesvd_(), SCF::diag_fock_matrix(), madness::SCF::diag_fock_matrix(), madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), madness::DistributedMatrix< double >::extract_columns(), madness::gaxpy(), madness::gelss(), madness::geqp3(), madness::DistributedMatrix< double >::get_colrange(), madness::DistributedMatrixDistribution::get_range(), madness::Random::getbytes(), madness::Random::getv(), PointGroup::ircell(), jacobi(), MolecularSystem::load(), SCF::localize_PM_task_kernel(), madness::lq(), main(), madness::matrix_inner(), matrix_inner(), madness::mul(), madness::mul_sparse(), madness::nonstandard(), madness::norm2s(), madness::norm_tree(), madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator()(), opt(), madness::SCF::orthonormalize(), madness::FunctionImpl< T, NDIM >::plot_cube_kernel(), madness::DQueue< madness::PoolTaskInterface * >::pop_front(), madness::FunctionImpl< T, NDIM >::project(), madness::qr(), madness::reconstruct(), madness::row_distributed_matrix(), madness::scale(), SCFParameters::set_molecular_info(), madness::CalculationParameters::set_molecular_info(), madness::SCF::set_protocol(), smoothing_parameter(), madness::SCF::solve(), SVPEColloidSolver::solve_Laplace(), madness::standard(), madness::sub(), madness::svd(), madness::transform(), madness::truncate(), madness::TensorTrain< T >::truncate(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
const mpreal mpfr::modf (const mpreal & v, mpreal & n) inline
References mpfr::mpreal::default_rnd, and frac().
Referenced by mpfr::mpreal::fits_in_bits().
const mpreal mpfr::mul_2si (const mpreal & v, long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by operator<<().
const mpreal mpfr::mul_2ui (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by operator<<().
const mpreal mpfr::nextabove (const mpreal & x) inline
References a().
const mpreal mpfr::nextbelow (const mpreal & x) inline
References a().
const mpreal mpfr::nexttoward (const mpreal & x, const mpreal & y) inline
References a().
bool mpfr::operator!= (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator!= (const mpreal & a, const unsigned int b) inline
bool mpfr::operator!= (const mpreal & a, const long int b) inline
bool mpfr::operator!= (const mpreal & a, const int b) inline
bool mpfr::operator!= (const mpreal & a, const long double b) inline
bool mpfr::operator!= (const mpreal & a, const double b) inline
bool mpfr::operator!= (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const int a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const double a, const mpreal & b) inline
References b().
bool mpfr::operator!= (const mpreal & a, const mpreal & b) inline
const mpreal mpfr::operator* (const mpreal & a, const mpreal & b) inline
References a(), b(), and mpfr::mpreal::get_prec().
const mpreal mpfr::operator* (const mpreal & a, const mpz_t b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const mpq_t b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const long double b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const double b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const unsigned long int b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const unsigned int b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const long int b) inline
References b().
const mpreal mpfr::operator* (const mpreal & a, const int b) inline
References b().
const mpreal mpfr::operator* (const mpz_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const mpq_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const long double b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const double b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const unsigned long int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const unsigned int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const long int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator* (const int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const mpreal & b) inline
References a(), b(), and mpfr::mpreal::get_prec().
const mpreal mpfr::operator+ (const mpreal & a, const mpz_t b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const mpq_t b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const long double b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const double b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const unsigned long int b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const unsigned int b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const long int b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const int b) inline
References b().
const mpreal mpfr::operator+ (const mpreal & a, const char * b) inline
const mpreal mpfr::operator+ (const char * a, const mpreal & b) inline
References b().
const std::string mpfr::operator+ (const mpreal & a, const std::string b) inline
References b().
const std::string mpfr::operator+ (const std::string a, const mpreal & b) inline
const mpreal mpfr::operator+ (const mpz_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const mpq_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const long double b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const double b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const unsigned long int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const unsigned int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const long int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator+ (const int b, const mpreal & a) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const mpreal & b) inline
References a(), b(), and mpfr::mpreal::get_prec().
const mpreal mpfr::operator- (const mpreal & a, const mpz_t b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const mpq_t b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const long double b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const double b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const unsigned long int b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const unsigned int b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const long int b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const int b) inline
References b().
const mpreal mpfr::operator- (const mpreal & a, const char * b) inline
const mpreal mpfr::operator- (const char * a, const mpreal & b) inline
References b().
const mpreal mpfr::operator- (const mpz_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator- (const mpq_t b, const mpreal & a) inline
References b().
const mpreal mpfr::operator- (const long double b, const mpreal & a) inline
References b().
const mpreal mpfr::operator- (const double b, const mpreal & a) inline
References b(), and mpfr::mpreal::default_rnd.
const mpreal mpfr::operator- (const unsigned long int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator- (const unsigned int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator- (const long int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator- (const int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator/ (const mpreal & a, const mpreal & b) inline
References b(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::operator/ (const mpreal & a, const mpz_t b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const mpq_t b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const long double b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const double b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const unsigned long int b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const unsigned int b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const long int b) inline
References b().
const mpreal mpfr::operator/ (const mpreal & a, const int b) inline
References b().
const mpreal mpfr::operator/ (const long double b, const mpreal & a) inline
References a().
const mpreal mpfr::operator/ (const unsigned long int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator/ (const unsigned int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator/ (const long int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator/ (const int b, const mpreal & a) inline
References mpfr::mpreal::default_rnd.
const mpreal mpfr::operator/ (const double b, const mpreal & a) inline
References a(), and mpfr::mpreal::default_rnd.
bool mpfr::operator< (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator< (const mpreal & a, const unsigned int b) inline
bool mpfr::operator< (const mpreal & a, const long int b) inline
bool mpfr::operator< (const mpreal & a, const int b) inline
bool mpfr::operator< (const mpreal & a, const long double b) inline
bool mpfr::operator< (const mpreal & a, const double b) inline
bool mpfr::operator< (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator< (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator< (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator< (const int a, const mpreal & b) inline
References b().
bool mpfr::operator< (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator< (const double a, const mpreal & b) inline
References b().
bool mpfr::operator< (const mpreal & a, const mpreal & b) inline
ostream& mpfr::operator<< (ostream & os, const mpreal & v)
References mpfr::mpreal::to_string().
const mpreal mpfr::operator<< (const mpreal & v, const unsigned long int k) inline
References mul_2ui().
const mpreal mpfr::operator<< (const mpreal & v, const unsigned int k) inline
References mul_2ui().
const mpreal mpfr::operator<< (const mpreal & v, const long int k) inline
References mul_2si().
const mpreal mpfr::operator<< (const mpreal & v, const int k) inline
References mul_2si().
bool mpfr::operator<= (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator<= (const mpreal & a, const unsigned int b) inline
bool mpfr::operator<= (const mpreal & a, const long int b) inline
bool mpfr::operator<= (const mpreal & a, const int b) inline
bool mpfr::operator<= (const mpreal & a, const long double b) inline
bool mpfr::operator<= (const mpreal & a, const double b) inline
bool mpfr::operator<= (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const int a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const double a, const mpreal & b) inline
References b().
bool mpfr::operator<= (const mpreal & a, const mpreal & b) inline
bool mpfr::operator== (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator== (const mpreal & a, const unsigned int b) inline
bool mpfr::operator== (const mpreal & a, const long int b) inline
bool mpfr::operator== (const mpreal & a, const int b) inline
bool mpfr::operator== (const mpreal & a, const long double b) inline
bool mpfr::operator== (const mpreal & a, const double b) inline
bool mpfr::operator== (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator== (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator== (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator== (const int a, const mpreal & b) inline
References b().
bool mpfr::operator== (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator== (const double a, const mpreal & b) inline
References b().
bool mpfr::operator== (const mpreal & a, const mpreal & b) inline
bool mpfr::operator> (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator> (const mpreal & a, const unsigned int b) inline
bool mpfr::operator> (const mpreal & a, const long int b) inline
bool mpfr::operator> (const mpreal & a, const int b) inline
bool mpfr::operator> (const mpreal & a, const long double b) inline
bool mpfr::operator> (const mpreal & a, const double b) inline
bool mpfr::operator> (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator> (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator> (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator> (const int a, const mpreal & b) inline
References b().
bool mpfr::operator> (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator> (const double a, const mpreal & b) inline
References b().
bool mpfr::operator> (const mpreal & a, const mpreal & b) inline
bool mpfr::operator>= (const mpreal & a, const unsigned long int b) inline
bool mpfr::operator>= (const mpreal & a, const unsigned int b) inline
bool mpfr::operator>= (const mpreal & a, const long int b) inline
bool mpfr::operator>= (const mpreal & a, const int b) inline
bool mpfr::operator>= (const mpreal & a, const long double b) inline
bool mpfr::operator>= (const mpreal & a, const double b) inline
bool mpfr::operator>= (const unsigned long int a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const unsigned int a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const long int a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const int a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const long double a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const double a, const mpreal & b) inline
References b().
bool mpfr::operator>= (const mpreal & a, const mpreal & b) inline
istream& mpfr::operator>> (istream & is, mpreal & v)
References c, mpfr::mpreal::default_base, and mpfr::mpreal::default_rnd.
const mpreal mpfr::operator>> (const mpreal & v, const unsigned long int k) inline
References div_2ui().
const mpreal mpfr::operator>> (const mpreal & v, const unsigned int k) inline
References div_2ui().
const mpreal mpfr::operator>> (const mpreal & v, const long int k) inline
References div_2si().
const mpreal mpfr::operator>> (const mpreal & v, const int k) inline
References div_2si().
const mpreal mpfr::pow (const mpreal & a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by pow().
const mpreal mpfr::pow (const mpreal & a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const mpreal & a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const mpreal & a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned long int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned long int a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned long int a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned long int a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned long int a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const unsigned int a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long int a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const int a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const long double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const long double a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const double b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const double a, const int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References pow().
const mpreal mpfr::pow (const mpreal & a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::pow (const mpreal & a, const mpz_t b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::pow (const mpreal & a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::pow (const mpreal & a, const long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::pow (const unsigned long int a, const mpreal & b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::pow (const unsigned long int a, const unsigned long int b, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::rec_sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::remainder (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::remquo (long * q, const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::default_rnd)
References a(), mpfr::mpreal::get_prec(), and mpfr::mpreal::set_prec().
const mpreal mpfr::rint (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::rint_ceil (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::rint_floor (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::rint_round (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::rint_trunc (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::root (const mpreal & v, unsigned long int k, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::WorldGopInterface::all_reduce(), madness::WorldGopInterface::bcast(), SafeMPI::Intracomm::binary_tree_info(), madness::WorldGopInterface::broadcast_serializable(), root::operator-(), and madness::WorldGopInterface::reduce().
const mpreal mpfr::round (const mpreal & v) inline
Referenced by madness::FunctionImpl< T, NDIM >::plot_cube_kernel().
const mpreal mpfr::sec (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sech (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
int mpfr::sgn (const mpreal & v) inline
const mpreal mpfr::sin (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::trajectory< NDIM >::circle2(), madness::trajectory< NDIM >::circle_6d(), func(), ScatteringWF::gamma(), madness::LocalizeBoys< T >::kernel(), laser(), SCF::localize_boys(), SCF::localize_PM_task_kernel(), main(), myf(), CFFT::Perform(), printBasis(), projectL(), MolecularMaskBase::special_points(), and zSlice().
int mpfr::sin_cos (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sinh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
int mpfr::sinh_cosh (mpreal & s, mpreal & c, const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sqr (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sqrt (const unsigned int v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by sqrt().
const mpreal mpfr::sqrt (const long int v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References sqrt().
const mpreal mpfr::sqrt (const int v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References sqrt().
const mpreal mpfr::sqrt (const long double v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References sqrt().
const mpreal mpfr::sqrt (const double v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
References sqrt().
const mpreal mpfr::sqrt (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sqrt (const unsigned long int v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::sum (const mpreal tab[], unsigned long int n, mp_rnd_t rnd_mode = mpreal::default_rnd)
Referenced by PointGroup::cart_ir(), madness::checksum_file(), conhyp(), madness::do_adq(), errsq(), madness::FunctionImpl< T, NDIM >::eval_cube(), AtomicBasis::eval_guess_density(), madness::AtomicBasis::eval_guess_density(), madness::AtomicBasisSet::eval_guess_density(), AtomicBasisSet::eval_guess_density(), ContractedGaussianShell::eval_radial(), madness::ContractedGaussianShell::eval_radial(), Expikr::Expikr(), fit(), madness::inner_result(), SCF::localize_boys(), SCF::localize_PM_task_kernel(), LSQ(), main(), makedata(), Molecule::molecular_core_potential(), madness::Molecule::molecular_core_potential(), mTxmT(), mxmT(), Molecule::n_core_orb_all(), madness::Molecule::n_core_orb_all(), madness::FunctionImpl< T, NDIM >::norm_tree_op(), MolecularEntity::nuclear_attraction_potential(), Molecule::nuclear_attraction_potential(), madness::Molecule::nuclear_attraction_potential(), Molecule::nuclear_dipole(), madness::Molecule::nuclear_dipole(), Molecule::nuclear_repulsion_derivative(), madness::Molecule::nuclear_repulsion_derivative(), MolecularEntity::nuclear_repulsion_energy(), Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_energy(), madness::Molecule::nuclear_repulsion_energy_pseudo(), madness::Projector< double, 3 >::operator()(), madness::ComplexExp< NDIM >::operator()(), madness::WSTAtomicBasisFunctor::operator()(), Gaussian::operator()(), BoundWF::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local< R >::operator()(), opt(), madness::plot_line(), Molecule::Qnxx(), Molecule::Qnxy(), Molecule::Qnxz(), Molecule::Qnyy(), Molecule::Qnyz(), Molecule::Qnzz(), madness::FunctionImpl< T, NDIM >::real_size(), madness::WorldTaskQueue::reduce(), madness::SDFEllipsoid::sdf(), series(), madness::ConcurrentHashMap< uniqueidT, void *, uniqueidT >::size(), madness::FunctionImpl< T, NDIM >::size(), madness::LocalizeBoys< T >::start_iteration_hook(), test(), Test7(), MolecularEntity::total_nuclear_charge(), Molecule::total_nuclear_charge(), madness::Molecule::total_nuclear_charge(), madness::FunctionImpl< T, NDIM >::trace_local(), transform3d(), madness::FunctionImpl< T, NDIM >::tree_size(), and V().
void mpfr::swap (mpreal & a, mpreal & b) inline
Referenced by std::swap().
const mpreal mpfr::tan (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
const mpreal mpfr::tanh (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline
Referenced by madness::LLRVDomainMask::dmask(), and madness::LLRVDomainMask::mask().
template<class T > std::string mpfr::to_string (T t, std::ios_base &(*)(std::ios_base &) f)
References madness::f.
Referenced by mpfr::mpreal::operator std::string().
const mpreal mpfr::trunc (const mpreal & v) inline
Referenced by madness::ThreadPool::begin(), and main().
const mpreal mpfr::urandomb (gmp_randstate_t & state) inline
const mpreal mpfr::zeta (const mpreal & v, mp_rnd_t rnd_mode = mpreal::default_rnd) inline