MADNESS: madness::tr1::array Namespace Reference
madness::tr1::array Namespace Reference
Classes
class array
Array idential to C++0X arrays.
class array< T, 0 >
Functions
template<class T , std::size_t N>
bool operator== (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator< (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator!= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator> (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator<= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
bool operator>= (const array< T, N > &x, const array< T, N > &y)
template<class T , std::size_t N>
void swap (array< T, N > &x, array< T, N > &y)
Function Documentation
template<class T , std::size_t N> bool madness::tr1::array::operator!= (const array< T, N > & x, const array< T, N > & y)
template<class T , std::size_t N> bool madness::tr1::array::operator< (const array< T, N > & x, const array< T, N > & y)
template<class T , std::size_t N> bool madness::tr1::array::operator<= (const array< T, N > & x, const array< T, N > & y)
template<class T , std::size_t N> bool madness::tr1::array::operator== (const array< T, N > & x, const array< T, N > & y)
References madness::tr1::array::array< T, N >::begin(), and madness::tr1::array::array< T, N >::end().
template<class T , std::size_t N> bool madness::tr1::array::operator> (const array< T, N > & x, const array< T, N > & y)
template<class T , std::size_t N> bool madness::tr1::array::operator>= (const array< T, N > & x, const array< T, N > & y)
template<class T , std::size_t N> void madness::tr1::array::swap (array< T, N > & x, array< T, N > & y) inline
References madness::tr1::array::array< T, N >::swap().