MADNESS: madness::tr1::shptr Namespace Reference
madness::tr1::shptr Namespace Reference
Namespaces
detail
Classes
struct bad_weak_ptr
class enable_shared_from_this
class enable_shared_from_this2
class shared_ptr
class weak_ptr
Functions
template<class T , class U >
bool operator== (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T , class U >
bool operator!= (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T , class U >
bool operator< (shared_ptr< T > const &a, shared_ptr< U > const &b)
template<class T >
void swap (shared_ptr< T > &a, shared_ptr< T > &b)
template<class T , class U >
shared_ptr< T > static_pointer_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > const_pointer_cast (shared_ptr< U > const &r)
template<class T , class U >
shared_ptr< T > dynamic_pointer_cast (shared_ptr< U > const &r)
template<class T >
T * get_pointer (shared_ptr< T > const &p)
template<class Y >
std::ostream & operator<< (std::ostream &os, shared_ptr< Y > const &p)
template<class D , class T >
D * get_deleter (shared_ptr< T > const &p)
template<class T >
std::size_t hash_value (shared_ptr< T > const &p)
template<class T , class U >
bool operator< (weak_ptr< T > const &a, weak_ptr< U > const &b)
template<class T >
void swap (weak_ptr< T > &a, weak_ptr< T > &b)
Function Documentation
template<class T , class U > shared_ptr<T> madness::tr1::shptr::const_pointer_cast (shared_ptr< U > const & r)
template<class T , class U > shared_ptr<T> madness::tr1::shptr::dynamic_pointer_cast (shared_ptr< U > const & r)
template<class D , class T > D* madness::tr1::shptr::get_deleter (shared_ptr< T > const & p)
References madness::tr1::shptr::shared_ptr< T >::_internal_get_deleter().
template<class T > T* madness::tr1::shptr::get_pointer (shared_ptr< T > const & p) inline
References madness::tr1::shptr::shared_ptr< T >::get().
template<class T > std::size_t madness::tr1::shptr::hash_value (shared_ptr< T > const & p)
References madness::tr1::shptr::shared_ptr< T >::get().
template<class T , class U > bool madness::tr1::shptr::operator!= (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
References madness::tr1::shptr::shared_ptr< T >::get().
template<class T , class U > bool madness::tr1::shptr::operator< (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
References b().
template<class T , class U > bool madness::tr1::shptr::operator< (weak_ptr< T > const & a, weak_ptr< U > const & b) inline
References b().
template<class Y > std::ostream& madness::tr1::shptr::operator<< (std::ostream & os, shared_ptr< Y > const & p)
template<class T , class U > bool madness::tr1::shptr::operator== (shared_ptr< T > const & a, shared_ptr< U > const & b) inline
References madness::tr1::shptr::shared_ptr< T >::get().
template<class T , class U > shared_ptr<T> madness::tr1::shptr::static_pointer_cast (shared_ptr< U > const & r)
template<class T > void madness::tr1::shptr::swap (shared_ptr< T > & a, shared_ptr< T > & b) inline
References madness::tr1::shptr::shared_ptr< T >::swap().
template<class T > void madness::tr1::shptr::swap (weak_ptr< T > & a, weak_ptr< T > & b)