MADNESS: madness::archive Namespace Reference
madness::archive Namespace Reference
MADNESS libraries » Multiresolution analaysis » FunctionMADNESS libraries » | Parallel programming environment
Classes
class archive_array
Wrapper for dynamic arrays and pointers.
class archive_ptr
Wrapper for opaque pointer ... bitwise copy of the pointer ... no remapping performed.
struct archive_typeinfo
struct ArchiveImpl
Default implementation of wrap_store and wrap_load.
struct ArchiveImpl< Archive, archive_array< T > >
Partial specialization for archive_array.
struct ArchiveImpl< Archive, T[n]>
Partial specialization for fixed dimension array redirects to archive_array.
struct ArchiveImpl< ParallelInputArchive, archive_array< T > >
Read archive array and broadcast.
struct ArchiveImpl< ParallelInputArchive, T >
struct ArchiveImpl< ParallelInputArchive, T[n]>
Forward fixed size array to archive_array.
struct ArchiveImpl< ParallelOutputArchive, archive_array< T > >
Write archive array only from process zero.
struct ArchiveImpl< ParallelOutputArchive, T >
struct ArchiveImpl< ParallelOutputArchive, T[n]>
Forward fixed size array to archive_array.
struct ArchiveLoadImpl
Default load of a thingy via serialize(ar,t)
struct ArchiveLoadImpl< Archive, const DerivativeBase< T, NDIM > * >
struct ArchiveLoadImpl< Archive, const FunctionImpl< T, NDIM > * >
struct ArchiveLoadImpl< Archive, const SeparatedConvolution< T, NDIM > * >
struct ArchiveLoadImpl< Archive, detail::RemoteCounter >
struct ArchiveLoadImpl< Archive, detail::WorldPtr< T > >
struct ArchiveLoadImpl< Archive, FunctionImpl< T, NDIM > * >
struct ArchiveLoadImpl< Archive, Future< T > >
Deserialize a future into an unassigned future.
struct ArchiveLoadImpl< Archive, Future< void > >
Deserialize a future into an unassigned future.
struct ArchiveLoadImpl< Archive, Future< Void > >
Deserialize a future into an unassigned future.
struct ArchiveLoadImpl< Archive, GenTensor< T > >
Deserialize a tensor ... existing tensor is replaced.
struct ArchiveLoadImpl< Archive, Key< NDIM > >
struct ArchiveLoadImpl< Archive, std::array< T, N > >
struct ArchiveLoadImpl< Archive, std::complex< T > >
Deserialize a complex number.
struct ArchiveLoadImpl< Archive, std::map< T, Q > >
Deserialize an STL map. Map is NOT cleared; duplicate elements are replaced.
struct ArchiveLoadImpl< Archive, std::shared_ptr< const FunctionImpl< T, NDIM > > >
struct ArchiveLoadImpl< Archive, std::shared_ptr< FunctionImpl< T, NDIM > > >
struct ArchiveLoadImpl< Archive, std::string >
Deserialize STL string. Clears & resizes as necessary.
struct ArchiveLoadImpl< Archive, std::vector< bool > >
Deserialize STL vector<bool>. Clears & resizes as necessary.
struct ArchiveLoadImpl< Archive, std::vector< Future< T > > >
Deserialize a future into an unassigned future.
struct ArchiveLoadImpl< Archive, std::vector< T > >
Deserialize STL vector. Clears & resizes as necessary.
struct ArchiveLoadImpl< Archive, Tensor< T > >
Deserialize a tensor ... existing tensor is replaced.
struct ArchiveLoadImpl< Archive, World * >
struct ArchiveLoadImpl< BinaryFstreamInputArchive, Key< NDIM > >
struct ArchiveLoadImpl< BufferInputArchive, const WorldObject< Derived > * >
struct ArchiveLoadImpl< BufferInputArchive, WorldObject< Derived > * >
struct ArchiveLoadImpl< ParallelInputArchive, Function< T, NDIM > >
struct ArchiveLoadImpl< ParallelInputArchive, WorldContainer< keyT, valueT > >
struct ArchivePrePostImpl
Default implementation of pre/postamble.
struct ArchivePrePostImpl< BufferInputArchive, T >
struct ArchivePrePostImpl< BufferOutputArchive, T >
struct ArchivePrePostImpl< MPIInputArchive, T >
struct ArchivePrePostImpl< MPIOutputArchive, T >
struct ArchivePrePostImpl< MPIRawInputArchive, T >
struct ArchivePrePostImpl< MPIRawOutputArchive, T >
struct ArchivePrePostImpl< ParallelInputArchive, T >
Disable type info for parallel input archives.
struct ArchivePrePostImpl< ParallelOutputArchive, T >
Disable type info for parallel output archives.
struct ArchivePrePostImpl< TextFstreamInputArchive, T >
struct ArchivePrePostImpl< TextFstreamOutputArchive, T >
struct ArchiveSerializeImpl
Default symmetric serialization of a non-fundamental thingy.
struct ArchiveSerializeImpl< Archive, std::pair< T, Q > >
(de)Serialize an STL pair.
struct ArchiveStoreImpl
Default store of a thingy via serialize(ar,t)
struct ArchiveStoreImpl< Archive, const DerivativeBase< T, NDIM > * >
struct ArchiveStoreImpl< Archive, const FunctionImpl< T, NDIM > * >
struct ArchiveStoreImpl< Archive, const SeparatedConvolution< T, NDIM > * >
struct ArchiveStoreImpl< Archive, detail::RemoteCounter >
struct ArchiveStoreImpl< Archive, detail::WorldPtr< T > >
struct ArchiveStoreImpl< Archive, FunctionImpl< T, NDIM > * >
struct ArchiveStoreImpl< Archive, Future< T > >
Serialize an assigned future.
struct ArchiveStoreImpl< Archive, Future< void > >
Serialize an assigned future.
struct ArchiveStoreImpl< Archive, Future< Void > >
Serialize an assigned future.
struct ArchiveStoreImpl< Archive, GenTensor< T > >
Serialize a tensor.
struct ArchiveStoreImpl< Archive, Key< NDIM > >
struct ArchiveStoreImpl< Archive, std::array< T, N > >
struct ArchiveStoreImpl< Archive, std::complex< T > >
Serialize a complex number.
struct ArchiveStoreImpl< Archive, std::map< T, Q > >
Serialize an STL map (crudely).
struct ArchiveStoreImpl< Archive, std::shared_ptr< const FunctionImpl< T, NDIM > > >
struct ArchiveStoreImpl< Archive, std::shared_ptr< FunctionImpl< T, NDIM > > >
struct ArchiveStoreImpl< Archive, std::string >
Serialize STL string.
struct ArchiveStoreImpl< Archive, std::vector< bool > >
Serialize STL vector<bool> (as plain array of bool)
struct ArchiveStoreImpl< Archive, std::vector< Future< T > > >
struct ArchiveStoreImpl< Archive, std::vector< T > >
Serialize STL vector.
struct ArchiveStoreImpl< Archive, Tensor< T > >
Serialize a tensor.
struct ArchiveStoreImpl< Archive, World * >
struct ArchiveStoreImpl< BufferOutputArchive, const WorldObject< Derived > * >
struct ArchiveStoreImpl< BufferOutputArchive, WorldObject< Derived > * >
struct ArchiveStoreImpl< ParallelOutputArchive, Function< T, NDIM > >
struct ArchiveStoreImpl< ParallelOutputArchive, WorldContainer< keyT, valueT > >
Write container to parallel archive with optional fence.
class BaseArchive
Base class for all archives classes.
class BaseInputArchive
Base class for input archives classes.
class BaseOutputArchive
Base class for output archives classes.
class BaseParallelArchive
Base class for input and output parallel archives.
class BinaryFstreamInputArchive
Wraps an archive around a binary file stream for input.
class BinaryFstreamOutputArchive
Wraps an archive around a binary file stream for output.
class BufferInputArchive
Wraps an archive around a memory buffer for input.
class BufferOutputArchive
Wraps an archive around a memory buffer for output.
struct is_archive
Checks that T is an archive type.
struct is_input_archive
Checks that T is an input archive type.
struct is_output_archive
Checks that T is an output archive type.
class MPIInputArchive
class MPIOutputArchive
class MPIRawInputArchive
class MPIRawOutputArchive
class ParallelInputArchive
An archive for storing local or parallel data wrapping BinaryFstreamInputArchive.
class ParallelOutputArchive
An archive for storing local or parallel data wrapping BinaryFstreamOutputArchive.
class ParallelSerializableObject
Objects that implement their own parallel archive interface should derive from this.
class TextFstreamInputArchive
Wraps an archive around a text file stream for input.
class TextFstreamOutputArchive
Wraps an archive around a text file stream for output.
class VectorInputArchive
Wraps an archive around an STL vector for input.
class VectorOutputArchive
Wraps an archive around an STL vector for output.
Functions
template<class T >
archive_array< T > wrap (const T *ptr, unsigned int n)
Factory function to wrap dynamically allocated pointer as typed archive_array.
template<class T >
archive_array< unsigned char > wrap_opaque (const T *ptr, unsigned int n)
Factory function to wrap pointer to contiguous data as opaque (uchar) archive_array.
template<class T >
archive_array< unsigned char > wrap_opaque (const T &t)
Factory function to wrap contiguous scalar as opaque (uchar) archive_array.
void archive_initialize_type_names ()
template<typename T >
const char * get_type_name ()
ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned char, 0)
ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned short, 1)
ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned int, 2)
ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned long, 3)
ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned long long, 4)
ARCHIVE_REGISTER_TYPE_AND_PTR (signed char, 5)
ARCHIVE_REGISTER_TYPE_AND_PTR (char, 5)
ARCHIVE_REGISTER_TYPE_AND_PTR (signed short, 6)
ARCHIVE_REGISTER_TYPE_AND_PTR (signed int, 7)
ARCHIVE_REGISTER_TYPE_AND_PTR (signed long, 8)
ARCHIVE_REGISTER_TYPE_AND_PTR (signed long long, 9)
ARCHIVE_REGISTER_TYPE_AND_PTR (bool, 10)
ARCHIVE_REGISTER_TYPE_AND_PTR (float, 11)
ARCHIVE_REGISTER_TYPE_AND_PTR (double, 12)
ARCHIVE_REGISTER_TYPE_AND_PTR (long double, 13)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::complex< float >, 14)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::complex< double >, 15)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< char >, 20)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned char >, 21)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< short >, 22)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned short >, 23)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< int >, 24)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned int >, 25)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< long >, 26)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned long >, 27)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< bool >, 28)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< float >, 29)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< double >, 30)
ARCHIVE_REGISTER_TYPE_AND_PTR (std::string, 31)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< int >, 32)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< long >, 33)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< float >, 34)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< double >, 35)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< std::complex< float > >, 36)
ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< std::complex< double > >, 37)
template<class Archive , class T >
enable_if_c< is_serializable
< T >::value
&&is_output_archive< Archive >
::value >::type serialize (const Archive &ar, const T *t, unsigned int n)
template<class Archive , class T >
enable_if_c< is_serializable
< T >::value
&&is_input_archive< Archive >
::value >::type serialize (const Archive &ar, const T *t, unsigned int n)
template<class Archive , class T >
enable_if_c< !is_serializable
< T >::value &&is_archive
< Archive >::value >::type serialize (const Archive &ar, const T *t, unsigned int n)
template<class Archive , class T >
enable_if_c< is_serializable
< T >::value &&is_archive
< Archive >::value >::type serialize (const Archive &ar, const T &t)
template<class Archive , class T >
enable_if_c< !is_serializable
< T >::value &&is_archive
< Archive >::value >::type serialize (const Archive &ar, const T &t)
template<class Archive , class T >
enable_if< is_output_archive
< Archive >, const Archive & >
::type operator<< (const Archive &ar, const T &t)
template<class Archive , class T >
enable_if< is_input_archive
< Archive >, const Archive & >
::type operator>> (const Archive &ar, const T &t)
template<class Archive , class T >
enable_if< is_output_archive
< Archive >, const Archive & >
::type operator& (const Archive &ar, const T &t)
template<class Archive , class T >
enable_if< is_input_archive
< Archive >, const Archive & >
::type operator& (const Archive &ar, const T &t)
template<class T >
archive_ptr< T > wrap_ptr (T *p)
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H , typename I , typename J >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e, const F &f, const G &g, const H &h, const I &i, const J &j)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H , typename I >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e, const F &f, const G &g, const H &h, const I &i)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e, const F &f, const G &g, const H &h)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e, const F &f, const G &g)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D , typename E , typename F >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e, const F &f)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D , typename E >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d, const E &e)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C , typename D >
size_t bufar_size (const A &a, const B &b, const C &c, const D &d)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B , typename C >
size_t bufar_size (const A &a, const B &b, const C &c)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A , typename B >
size_t bufar_size (const A &a, const B &b)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename A >
size_t bufar_size (const A &a)
Convenience template computing the size of a buffer archive containing the arguments.
template<typename T >
archive_array< unsigned char > wrap_opaque (const RemoteReference< T > &t)
Variables
const char * archive_type_names [256]
Function Documentation
void madness::archive::archive_initialize_type_names ()
References ARCHIVE_REGISTER_TYPE_AND_PTR_NAMES, archive_type_names, and madness::initialized().
Referenced by madness::archive::BaseArchive::BaseArchive().
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned char, 0)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned short, 1)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned int, 2)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned long, 3)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (unsigned long long, 4)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (signed char, 5)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (char , 5)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (signed short, 6)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (signed int, 7)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (signed long, 8)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (signed long long, 9)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (bool , 10)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (float , 11)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (double , 12)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (long double, 13)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::complex< float > , 14)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::complex< double > , 15)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< char > , 20)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned char > , 21)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< short > , 22)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned short > , 23)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< int > , 24)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned int > , 25)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< long > , 26)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< unsigned long > , 27)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< bool > , 28)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< float > , 29)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::vector< double > , 30)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (std::string , 31)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< int > , 32)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< long > , 33)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< float > , 34)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< double > , 35)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< std::complex< float > > , 36)
madness::archive::ARCHIVE_REGISTER_TYPE_AND_PTR (Tensor< std::complex< double > > , 37)
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H , typename I , typename J > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e, const F & f, const G & g, const H & h, const I & i, const J & j) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::archive::BufferOutputArchive::size().
Referenced by madness::new_am_arg().
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H , typename I > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e, const F & f, const G & g, const H & h, const I & i) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G , typename H > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e, const F & f, const G & g, const H & h) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C , typename D , typename E , typename F , typename G > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e, const F & f, const G & g) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::g, and madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C , typename D , typename E , typename F > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e, const F & f) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::f, and madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C , typename D , typename E > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d, const E & e) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C , typename D > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c, const D & d) inline
Convenience template computing the size of a buffer archive containing the arguments.
References madness::archive::BufferOutputArchive::size().
template<typename A , typename B , typename C > size_t madness::archive::bufar_size (const A & a, const B & b, const C & c) inline
Convenience template computing the size of a buffer archive containing the arguments.
References c, and madness::archive::BufferOutputArchive::size().
template<typename A , typename B > size_t madness::archive::bufar_size (const A & a, const B & b) inline
Convenience template computing the size of a buffer archive containing the arguments.
References b(), and madness::archive::BufferOutputArchive::size().
template<typename A > size_t madness::archive::bufar_size (const A & a) inline
Convenience template computing the size of a buffer archive containing the arguments.
References a(), and madness::archive::BufferOutputArchive::size().
template<typename T > const char* madness::archive::get_type_name ()
template<class Archive , class T > enable_if<is_output_archive<Archive>, const Archive&>::type madness::archive::operator& (const Archive & ar, const T & t) inline
References madness::archive::ArchiveImpl< Archive, T >::wrap_store().
template<class Archive , class T > enable_if<is_input_archive<Archive>, const Archive&>::type madness::archive::operator& (const Archive & ar, const T & t) inline
References madness::archive::ArchiveImpl< Archive, T >::wrap_load().
template<class Archive , class T > enable_if<is_output_archive<Archive>, const Archive&>::type madness::archive::operator<< (const Archive & ar, const T & t) inline
References madness::archive::ArchiveImpl< Archive, T >::wrap_store().
template<class Archive , class T > enable_if<is_input_archive<Archive>, const Archive&>::type madness::archive::operator>> (const Archive & ar, const T & t) inline
References madness::archive::ArchiveImpl< Archive, T >::wrap_load().
template<class Archive , class T > enable_if_c< is_serializable<T>::value && is_output_archive<Archive>::value >::type madness::archive::serialize (const Archive & ar, const T * t, unsigned int n)
References MAD_ARCHIVE_DEBUG.
Referenced by madness::archive::ArchiveLoadImpl< Archive, T >::load(), serialize(), madness::archive::ArchiveStoreImpl< Archive, T >::store(), madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load(), and madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store().
template<class Archive , class T > enable_if_c< is_serializable<T>::value && is_input_archive<Archive>::value >::type madness::archive::serialize (const Archive & ar, const T * t, unsigned int n)
References MAD_ARCHIVE_DEBUG, and std::tr1::T().
template<class Archive , class T > enable_if_c< ! is_serializable<T>::value && is_archive<Archive>::value >::type madness::archive::serialize (const Archive & ar, const T * t, unsigned int n)
References MAD_ARCHIVE_DEBUG.
template<class Archive , class T > enable_if_c< is_serializable<T>::value && is_archive<Archive>::value >::type madness::archive::serialize (const Archive & ar, const T & t) inline
References MAD_ARCHIVE_DEBUG, and serialize().
template<class Archive , class T > enable_if_c< !is_serializable<T>::value && is_archive<Archive>::value >::type madness::archive::serialize (const Archive & ar, const T & t) inline
References MAD_ARCHIVE_DEBUG, madness::archive::ArchiveSerializeImpl< Archive, T >::serialize(), and std::tr1::T().
template<class T > archive_array< T > madness::archive::wrap (const T * ptr, unsigned int n) inline
Factory function to wrap dynamically allocated pointer as typed archive_array.
Referenced by madness::archive::ArchiveLoadImpl< Archive, GenTensor< T > >::load(), madness::archive::ArchiveLoadImpl< Archive, Key< NDIM > >::load(), madness::archive::ArchiveLoadImpl< BinaryFstreamInputArchive, Key< NDIM > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< T > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::vector< bool > >::load(), madness::archive::ArchiveLoadImpl< Archive, std::string >::load(), madness::archive::ArchiveLoadImpl< Archive, Tensor< T > >::load(), InputParameters::serialize(), madness::KeyChildIterator< NDIM >::serialize(), madness::archive::ArchiveStoreImpl< Archive, GenTensor< T > >::store(), madness::archive::ArchiveStoreImpl< Archive, Key< NDIM > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::vector< T > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::vector< bool > >::store(), madness::archive::ArchiveStoreImpl< Archive, std::string >::store(), madness::archive::ArchiveStoreImpl< Archive, Tensor< T > >::store(), madness::archive::ArchiveImpl< ParallelInputArchive, T[n]>::wrap_load(), madness::archive::ArchiveImpl< Archive, T[n]>::wrap_load(), madness::archive::ArchiveImpl< ParallelOutputArchive, T[n]>::wrap_store(), and madness::archive::ArchiveImpl< Archive, T[n]>::wrap_store().
template<class T > archive_array< unsigned char > madness::archive::wrap_opaque (const T * ptr, unsigned int n) inline
Factory function to wrap pointer to contiguous data as opaque (uchar) archive_array.
References std::tr1::T().
Referenced by madness::detail::WorldPtr< madness::detail::RemoteCounterBase >::load_internal_(), madness::detail::info_base< memfunT >::serialize(), madness::LBNodeDeux< NDIM >::serialize(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::serialize(), madness::archive::archive_ptr< T >::serialize(), madness::FunctionImpl< T, NDIM >::do_op_args< OPDIM >::serialize(), and madness::detail::WorldPtr< madness::detail::RemoteCounterBase >::store_internal_().
template<class T > archive_array< unsigned char > madness::archive::wrap_opaque (const T & t) inline
Factory function to wrap contiguous scalar as opaque (uchar) archive_array.
template<typename T > archive_array<unsigned char> madness::archive::wrap_opaque (const RemoteReference< T > & t)
template<class T > archive_ptr<T> madness::archive::wrap_ptr (T * p) inline
Variable Documentation
const char* madness::archive::archive_type_names[256]
Referenced by archive_initialize_type_names(), madness::archive::TextFstreamInputArchive::check_start_tag(), and madness::archive::TextFstreamOutputArchive::open().