MADNESS: madness::tr1::shptr::detail Namespace Reference
madness::tr1::shptr::detail Namespace Reference
Classes
struct const_cast_tag
struct dynamic_cast_tag
struct enable_if_convertible
struct enable_if_convertible_impl
struct enable_if_convertible_impl< false >
struct enable_if_convertible_impl< true >
class esft2_deleter_wrapper
class shared_count
struct shared_ptr_traits
struct shared_ptr_traits< void >
struct shared_ptr_traits< void const >
struct shared_ptr_traits< void const volatile >
struct shared_ptr_traits< void volatile >
struct sp_convertible
class sp_counted_base
class sp_counted_impl_p
class sp_counted_impl_pd
struct sp_empty
struct sp_nothrow_tag
struct static_cast_tag
class weak_count
Functions
template<class X , class Y , class T >
void sp_enable_shared_from_this (shared_ptr< X > const *ppx, Y const *py, enable_shared_from_this< T > const *pe)
template<class X , class Y , class T >
void sp_enable_shared_from_this (shared_ptr< X > *ppx, Y const *py, enable_shared_from_this2< T > const *pe)
void sp_enable_shared_from_this (...)
Function Documentation
template<class X , class Y , class T > void madness::tr1::shptr::detail::sp_enable_shared_from_this (shared_ptr< X > const * ppx, Y const * py, enable_shared_from_this< T > const * pe) inline
References madness::tr1::shptr::enable_shared_from_this< T >::_internal_accept_owner().
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::shared_ptr().
template<class X , class Y , class T > void madness::tr1::shptr::detail::sp_enable_shared_from_this (shared_ptr< X > * ppx, Y const * py, enable_shared_from_this2< T > const * pe) inline
References madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner().
void madness::tr1::shptr::detail::sp_enable_shared_from_this (...) inline