MADNESS: std Namespace Reference
std Namespace Reference
Namespaces
tr1
Functions
template<>
void swap (mpfr::mpreal &x, mpfr::mpreal &y)
madness::hashT hash_value (const madness::DistributedID &id)
Hash a DistributedID.
template<typename hashT , typename distT >
void advance (madness::Hash_private::HashIterator< hashT > &it, const distT &dist)
template<typename hashT >
int distance (const madness::Hash_private::HashIterator< hashT > &it, const madness::Hash_private::HashIterator< hashT > &jt)
Function Documentation
template<typename hashT , typename distT > void std::advance (madness::Hash_private::HashIterator< hashT > & it, const distT & dist) inline
References madness::Hash_private::HashIterator< hashT >::advance().
template<typename hashT > int std::distance (const madness::Hash_private::HashIterator< hashT > & it, const madness::Hash_private::HashIterator< hashT > & jt) inline
References madness::Hash_private::HashIterator< hashT >::distance().
madness::hashT std::hash_value (const madness::DistributedID & id) inline
Hash a DistributedID.
Parameters
id The distributed id to be hashed
Returns
The hash value of id
References madness::detail::combine_hash(), and madness::hash_value().
template<> void std::swap (mpfr::mpreal & x, mpfr::mpreal & y) inline
References mpfr::swap().
Referenced by SCF::diag_fock_matrix(), madness::fast_transform(), madness::SCF::get_fock_transformation(), jacobi(), madness::SRConf< T >::orthonormalize(), madness::LBNodeDeux< NDIM >::partition(), testing::internal::ShuffleRange(), madness::swap(), madness::detail::WorldPtr< madness::detail::RemoteCounterBase >::swap(), madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::swap(), madness::RemoteReference< FutureImpl< REMFUTURE(MEMFUN_RETURNT(memfunT)) > >::swap(), madness::tr1::shptr::weak_ptr< T >::swap(), madness::TensorIterator< T, Q, R >::TensorIterator(), and madness::FunctionImpl< Q, NDIM >::vtransform_doit().