MADNESS: nonlinschro.cc File Reference
nonlinschro.cc File Reference
Solves 1D nonlinear Schrödinger equation.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <algorithm>
Functions
double munge (double x, double xmin, double xmax)
real_function_1d make_potential (World &world, const real_function_1d &rho)
void iterate (World &world, real_function_1d &psi)
int main (int argc, char **argv)
Detailed Description
Solves 1D nonlinear Schrödinger equation.
Function Documentation
void iterate (World & world, real_function_1d & psi)
References energy(), madness::inner(), make_potential(), madness::Function< T, NDIM >::norm2(), op(), madness::print(), psi(), madness::Function< T, NDIM >::scale(), sqrt(), and madness::Function< T, NDIM >::verify_tree().
Referenced by main().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, guess(), madness::initialize(), iterate(), k, L, make_potential(), madness::Function< T, NDIM >::norm2(), madness::plot_line(), madness::print(), psi(), madness::scale(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), and thresh.
real_function_1d make_potential (World & world, const real_function_1d & rho)
References madness::copy(), and madness::Function< T, NDIM >::unaryop().
Referenced by iterate(), and main().
double munge (double x, double xmin, double xmax)