MADNESS: plotao.cc File Reference
plotao.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include <vector>
#include <iomanip>
#include <algorithm>
#include <cstring>
#include <cstdlib>
#include <cmath>
Classes
class LevelPmap
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
Functions
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
void set_protocol (World &world, double thresh)
int main (int argc, char *argv[])
Typedef Documentation
typedef Vector<double,3> coordT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
int main (int argc, char * argv[])
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::print(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), set_protocol(), and madness::startup().
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
void set_protocol (World & world, double thresh)
References madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::FunctionDefaults< NDIM >::set_truncate_mode().
Referenced by main().