MADNESS: projPsi.cc File Reference
projPsi.cc File Reference
#include "wavef.h"
#include "extra.h"
#include <madness/mra/lbdeux.h>
#include <string>
#include <fstream>
#include <stdlib.h>
Functions
const complexd I (0, 1)
const complexd one (1, 0)
void projectL (World &world, const double L, const int wf, const int n, const int lMAX, const double cutoff)
void zSlice (World &world, const int n, double L, double th, double phi, const int wf)
void testIntegral (World &world, double L, const double Z, double k)
void debugSlice (World &world, const int n, double L, double Z, double k)
Evaluate phi_k along the z-axis.
void projectPsi (World &world, std::vector< std::string > boundList, std::vector< std::string > unboundList, const double Z, double cutoff)
void loadParameters2 (World &world, int &nGrid, double &th, double &phi, int &wf, double &kMomentum, int &lMAX, int &nPhoton)
void loadParameters (World &world, double &thresh, int &kMAD, double &L, double &Z, int &nPhoton, double &cutoff)
int main (int argc, char **argv)
Variables
const double PI = M_PI
Function Documentation
void debugSlice (World & world, const int n, double L, double Z, double k)
Evaluate phi_k along the z-axis.
References a(), b(), madness::imag(), ScatteringWF::Init(), and madness::real().
const complexd I (0 , 1)
Referenced by apply_potential(), compare1F1(), kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), madness::Solver< T, NDIM >::make_kinetic_matrix(), madness::WSTAtomicBasisFunctor::operator()(), Molecule::orient(), madness::Molecule::orient(), and q_c().
void loadParameters (World & world, double & thresh, int & kMAD, double & L, double & Z, int & nPhoton, double & cutoff)
Atomic Units: m = hbar = e = 1 E_n = n hbar omega I_p = Z^2 / 2 KE = E_n - I_p 0.5 v^2 = n omega - Z^2/2 v = sqrt(2 n omega - Z^2) dMAX = v tMAX
FUTURE: Include logic for Tunneling vs Multiphoton regime
References madness::f, PRINTLINE, and sqrt().
Referenced by main().
void loadParameters2 (World & world, int & nGrid, double & th, double & phi, int & wf, double & kMomentum, int & lMAX, int & nPhoton)
References madness::f, and PRINTLINE.
Referenced by main().
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), L, loadList(), loadParameters(), loadParameters2(), madness::print(), PRINTLINE, projectPsi(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::FunctionDefaults< NDIM >::set_project_randomize(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::World::size(), madness::startup(), and thresh.
const complexd one (1 , 0)
Referenced by apply_potential(), cfrac(), jacobi(), kinetic_energy_matrix(), kinetic_energy_matrix2(), makedata(), opt(), test(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), and updatex().
void projectL (World & world, const double L, const int wf, const int n, const int lMAX, const double cutoff)
References madness::LoadBalanceDeux< NDIM >::add_tree(), after, before, madness::conj(), mpfr::cos(), madness::Function< T, NDIM >::eval_local_only(), madness::World::gop, madness::LoadBalanceDeux< NDIM >::load_balance(), madness::Function< T, NDIM >::max_local_depth(), PI, PRINT, PRINTLINE, psi(), R, madness::World::rank(), madness::real(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::redistribute(), mpfr::sin(), madness::WorldGopInterface::sum(), madness::vec(), madness::wall_time(), wave_function_exists(), and wave_function_load().
void projectPsi (World & world, std::vector< std::string > boundList, std::vector< std::string > unboundList, const double Z, double cutoff)
References after, before, madness::conj(), madness::f, WF::func, madness::Function< T, NDIM >::func, ScatteringWF::Init(), madness::inner(), L, N, PRINT, PRINTLINE, madness::World::rank(), madness::real(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::Function< T, NDIM >::size(), madness::wall_time(), wave_function_exists(), and wave_function_load().
Referenced by main().
void testIntegral (World & world, double L, const double Z, double k)
References a(), ScatteringWF::Init(), madness::inner(), PRINT, PRINTLINE, and madness::wall_time().
void zSlice (World & world, const int n, double L, double th, double phi, const int wf)
References a(), b(), mpfr::cos(), PRINT, PRINTLINE, madness::real(), mpfr::sin(), wave_function_exists(), and wave_function_load().
Variable Documentation
const double PI = M_PI
Referenced by madness::ProjRLMFunctor::operator()(), and projectL().