MADNESS: madness::ScopedPtr< ptrT > Class Template Reference
madness::ScopedPtr< ptrT > Class Template Reference
Scoped pointer.
#include <scopedptr.h>
Public Types
typedef ptrT element_type
the pointer type
Public Member Functions
ScopedPtr (ptrT *p=NULL)
Construct a scoped pointer.
~ScopedPtr ()
Destructor.
void reset (ptrT *p=NULL)
Reset the current pointer.
ptrT & operator* () const
Dereference operator.
ptrT * operator-> () const
Pointer member accessor.
ptrT * get () const
Pointer accessor.
operator bool () const
bool conversion operator
bool operator! () const
Not operator.
void swap (ScopedPtr< ptrT > &other)
Swap the pointers.
Detailed Description
template<typename ptrT>
class madness::ScopedPtr< ptrT >
Scoped pointer.
Holds a pointer until it goes out of scope, then automatically deletes it. A scoped pointer should be used to wrap pointers where the lifetime of the pointer should be limited to a specific scope. The pointer cannot be copied. The pointer will be deleted with the delete operator.
Template Parameters
ptrT The pointer type
Note
A pointer to type ptrT must be a complete type
This class is based on Boost scoped_ptr.
Member Typedef Documentation
template<typename ptrT> typedef ptrT madness::ScopedPtr< ptrT >::element_type
the pointer type
Constructor & Destructor Documentation
template<typename ptrT> madness::ScopedPtr< ptrT >::ScopedPtr (ptrT * p = NULL) inline explicit
Construct a scoped pointer.
Parameters
p The pointer to hold [default = NULL]
Exceptions
nothing
template<typename ptrT> madness::ScopedPtr< ptrT >::~ScopedPtr () inline
Destructor.
calls delete operator
Member Function Documentation
template<typename ptrT> ptrT* madness::ScopedPtr< ptrT >::get () const inline
Pointer accessor.
Returns
The pointer
Exceptions
nothing
Referenced by madness::get_pointer().
template<typename ptrT> madness::ScopedPtr< ptrT >::operator bool () const inline
bool conversion operator
Returns
pointer != NULL
Exceptions
nothing
template<typename ptrT> bool madness::ScopedPtr< ptrT >::operator! () const inline
Not operator.
Returns
pointer == NULL
Exceptions
nothing
template<typename ptrT> ptrT& madness::ScopedPtr< ptrT >::operator* () const inline
Dereference operator.
Returns
A reference to the pointer's data
Exceptions
madness::MadnessException If the pointer is NULL
template<typename ptrT> ptrT* madness::ScopedPtr< ptrT >::operator-> () const inline
Pointer member accessor.
Returns
The pointer
Exceptions
madness::MadnessException If the pointer is NULL
template<typename ptrT> void madness::ScopedPtr< ptrT >::reset (ptrT * p = NULL) inline
Reset the current pointer.
This will destroy the current pointer. If an new pointer is provided this pointer will be set to that value.
Parameters
p The pointer that will replace this pointer after deletion
Exceptions
madness::MadnessException If p is the same as this pointer, except when this pointer is NULL.
References madness::ScopedPtr< ptrT >::swap().
template<typename ptrT> void madness::ScopedPtr< ptrT >::swap (ScopedPtr< ptrT > & other) inline
Swap the pointers.
Parameters
other The pointer to swap with this pointer
Exceptions
nothing
Referenced by madness::ScopedPtr< ptrT >::reset(), and madness::swap().
The documentation for this class was generated from the following file:
scopedptr.h