MADNESS: madness::GenTensor< T > Singleton Reference
madness::GenTensor< T > Singleton Reference
#include <gentensor.h>
Public Member Functions
GenTensor ()
GenTensor (const Tensor< T > &t1)
GenTensor (const Tensor< T > &t1, const TensorArgs &targs)
GenTensor (const Tensor< T > &t1, double eps, const TensorType tt)
GenTensor (const TensorType tt)
GenTensor (std::vector< long > v, const TensorType &tt)
GenTensor (std::vector< long > v, const TensorArgs &targs)
GenTensor (const SRConf< T > &sr1)
template<class Q >
operator GenTensor< Q > () const
Type conversion makes a deep copy.
GenTensor< T > reconstruct_tensor () const
GenTensor< T > full_tensor () const
GenTensor< T > & full_tensor ()
GenTensor< T > full_tensor_copy () const
GenTensor< T > full_tensor_copy ()
bool has_data () const
bool has_no_data () const
long rank () const
double svd_normf () const
size_t real_size () const
void reduce_rank (const double &eps)
void normalize ()
std::string what_am_i () const
TensorType tensor_type () const
void add_SVD (const GenTensor< T > &rhs, const double &eps)
SRConf< T > config () const
SRConf< T > get_configs (const int &start, const int &end) const
template<typename Q >
GenTensor< T > general_transform (const Tensor< Q > c[]) const
Static Public Member Functions
static double fac_reduce ()
return the additional safety for rank reduction
Constructor & Destructor Documentation
template<typename T> madness::GenTensor< T >::GenTensor () inline
template<typename T> madness::GenTensor< T >::GenTensor (const Tensor< T > & t1) inline
template<typename T> madness::GenTensor< T >::GenTensor (const Tensor< T > & t1, const TensorArgs & targs) inline
template<typename T> madness::GenTensor< T >::GenTensor (const Tensor< T > & t1, double eps, const TensorType tt) inline
template<typename T> madness::GenTensor< T >::GenTensor (const TensorType tt) inline
template<typename T> madness::GenTensor< T >::GenTensor (std::vector< long > v, const TensorType & tt) inline
template<typename T> madness::GenTensor< T >::GenTensor (std::vector< long > v, const TensorArgs & targs) inline
template<typename T> madness::GenTensor< T >::GenTensor (const SRConf< T > & sr1) inline
References MADNESS_EXCEPTION.
Member Function Documentation
template<typename T> void madness::GenTensor< T >::add_SVD (const GenTensor< T > & rhs, const double & eps) inline
Referenced by madness::FunctionNode< T, NDIM >::accumulate(), and madness::FunctionNode< T, NDIM >::consolidate_buffer().
template<typename T> SRConf<T> madness::GenTensor< T >::config () const inline
References MADNESS_EXCEPTION.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::FunctionImpl< T, NDIM >::multiply(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen().
template<typename T> static double madness::GenTensor< T >::fac_reduce () inline static
return the additional safety for rank reduction
template<typename T> GenTensor<T> madness::GenTensor< T >::full_tensor () const inline
Referenced by madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::FunctionImpl< T, NDIM >::multiply(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen(), and madness::FunctionImpl< Q, NDIM >::unary_op_coeff_inplace().
template<typename T> GenTensor<T>& madness::GenTensor< T >::full_tensor () inline
template<typename T> GenTensor<T> madness::GenTensor< T >::full_tensor_copy () const inline
Referenced by madness::FunctionImpl< T, NDIM >::assemble_coefficients(), madness::FunctionImpl< T, NDIM >::autorefine_square_test(), madness::FunctionImpl< T, NDIM >::coeffs_for_jun(), madness::FunctionImpl< Q, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< Q, NDIM >::err_box(), madness::FunctionImpl< T, NDIM >::eval(), madness::FunctionImpl< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::make_childrens_sum_coeffs(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::parent_to_child_NS(), and madness::FunctionImpl< T, NDIM >::trace_local().
template<typename T> GenTensor<T> madness::GenTensor< T >::full_tensor_copy () inline
template<typename T> template<typename Q > GenTensor<T> madness::GenTensor< T >::general_transform (const Tensor< Q > c[]) const inline
References madness::general_transform().
template<typename T> SRConf<T> madness::GenTensor< T >::get_configs (const int & start, const int & end) const inline
References MADNESS_EXCEPTION.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2().
template<typename T> bool madness::GenTensor< T >::has_data () const inline
References madness::BaseTensor::size().
Referenced by madness::FunctionNode< T, NDIM >::accumulate(), madness::FunctionImpl< Q, NDIM >::apply_source_driven(), madness::FunctionImpl< T, NDIM >::assemble_coefficients(), madness::FunctionNode< T, NDIM >::consolidate_buffer(), madness::FunctionNode< T, NDIM >::has_coeff(), madness::GenTensor< T >::has_no_data(), madness::FunctionImpl< T, NDIM >::do_truncate_NS_leafs::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator()(), madness::FunctionImpl< Q, NDIM >::project_out2(), madness::FunctionImpl< T, NDIM >::reconstruct_op(), madness::FunctionNode< T, NDIM >::set_coeff(), madness::FunctionImpl< T, NDIM >::sum_down_spawn(), and madness::FunctionImpl< T, NDIM >::verify_tree().
template<typename T> bool madness::GenTensor< T >::has_no_data () const inline
References madness::GenTensor< T >::has_data().
Referenced by madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::error_leaf_op< T, NDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::reconstruct_op(), and madness::FunctionImpl< T, NDIM >::trickle_down_op().
template<typename T> void madness::GenTensor< T >::normalize () inline
Referenced by madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()().
template<typename T> template<class Q > madness::GenTensor< T >::operator GenTensor< Q > () const inline
Type conversion makes a deep copy.
References madness::BaseTensor::_dim, madness::BaseTensor::_ndim, BINARY_OPTIMIZED_ITERATOR, and std::tr1::T().
template<typename T> long madness::GenTensor< T >::rank () const inline
Referenced by madness::FunctionNode< T, NDIM >::accumulate(), madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::FunctionImpl< Q, NDIM >::apply_source_driven(), madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::FunctionImpl< T, NDIM >::evalR(), madness::has_zero_rank(), madness::FunctionImpl< T, NDIM >::multiply(), madness::LBCost::operator()(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::print_plane_local(), madness::FunctionImpl< T, NDIM >::print_stats(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen().
template<typename T> size_t madness::GenTensor< T >::real_size () const inline
References madness::BaseTensor::size().
Referenced by madness::FunctionImpl< T, NDIM >::real_size().
template<typename T> GenTensor<T> madness::GenTensor< T >::reconstruct_tensor () const inline
template<typename T> void madness::GenTensor< T >::reduce_rank (const double & eps) inline
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::FunctionImpl< T, NDIM >::add_op::operator()(), madness::FunctionImpl< T, NDIM >::reconstruct_op(), madness::FunctionNode< T, NDIM >::reduceRank(), madness::FunctionImpl< Q, NDIM >::refine_op(), and madness::FunctionImpl< T, NDIM >::trickle_down_op().
template<typename T> double madness::GenTensor< T >::svd_normf () const inline
Referenced by madness::FunctionImpl< Q, NDIM >::do_apply_kernel3().
template<typename T> TensorType madness::GenTensor< T >::tensor_type () const inline
References madness::TT_FULL.
Referenced by madness::SeparatedConvolution< T, NDIM >::apply2(), madness::SeparatedConvolution< T, NDIM >::apply2_lowdim(), madness::FunctionImpl< Q, NDIM >::do_apply_kernel2(), madness::FunctionImpl< Q, NDIM >::do_project_out(), madness::SeparatedConvolution< T, NDIM >::estimate_costs(), madness::has_zero_rank(), madness::FunctionImpl< T, NDIM >::multiply(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::operator()(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::screen().
template<typename T> std::string madness::GenTensor< T >::what_am_i () const inline
The documentation for this singleton was generated from the following file:
gentensor.h