MADNESS: madness::tr1::shptr::enable_shared_from_this2< T > Class Template Reference
madness::tr1::shptr::enable_shared_from_this2< T > Class Template Reference
#include <shared_ptr_bits.h>
Public Member Functions
shared_ptr< T > shared_from_this ()
shared_ptr< T const > shared_from_this () const
template<class X , class Y >
void _internal_accept_owner (shared_ptr< X > *ppx, Y *py) const
Protected Member Functions
enable_shared_from_this2 ()
enable_shared_from_this2 (enable_shared_from_this2 const &)
enable_shared_from_this2 & operator= (enable_shared_from_this2 const &)
~enable_shared_from_this2 ()
Constructor & Destructor Documentation
template<class T> madness::tr1::shptr::enable_shared_from_this2< T >::enable_shared_from_this2 () inline protected
template<class T> madness::tr1::shptr::enable_shared_from_this2< T >::enable_shared_from_this2 (enable_shared_from_this2< T > const &) inline protected
template<class T> madness::tr1::shptr::enable_shared_from_this2< T >::~enable_shared_from_this2 () inline protected
Member Function Documentation
template<class T> template<class X , class Y > void madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner (shared_ptr< X > * ppx, Y * py) const inline
References madness::tr1::shptr::shared_ptr< T >::get(), madness::tr1::shptr::shared_ptr< T >::reset(), madness::tr1::shptr::shared_ptr< T >::unique(), and madness::tr1::shptr::shared_ptr< T >::use_count().
Referenced by madness::tr1::shptr::detail::sp_enable_shared_from_this().
template<class T> enable_shared_from_this2& madness::tr1::shptr::enable_shared_from_this2< T >::operator= (enable_shared_from_this2< T > const &) inline protected
template<class T> shared_ptr<T> madness::tr1::shptr::enable_shared_from_this2< T >::shared_from_this () inline
template<class T> shared_ptr<T const> madness::tr1::shptr::enable_shared_from_this2< T >::shared_from_this () const inline
The documentation for this class was generated from the following file:
shared_ptr_bits.h