MADNESS: madness::tr1::shptr::weak_ptr< T > Class Template Reference
madness::tr1::shptr::weak_ptr< T > Class Template Reference
#include <shared_ptr_bits.h>
Public Types
typedef T element_type
Public Member Functions
weak_ptr ()
template<class Y >
weak_ptr (weak_ptr< Y > const &r, typename detail::enable_if_convertible< Y, T >::type=detail::sp_empty())
template<class Y >
weak_ptr (shared_ptr< Y > const &r, typename detail::enable_if_convertible< Y, T >::type=detail::sp_empty())
shared_ptr< T > lock () const
long use_count () const
bool expired () const
void reset ()
void swap (this_type &other)
void _internal_assign (T *px2, detail::shared_count const &pn2)
template<class Y >
bool _internal_less (weak_ptr< Y > const &rhs) const
Friends
template<class Y >
class weak_ptr
template<class Y >
class shared_ptr
Member Typedef Documentation
template<class T> typedef T madness::tr1::shptr::weak_ptr< T >::element_type
Constructor & Destructor Documentation
template<class T> madness::tr1::shptr::weak_ptr< T >::weak_ptr () inline
template<class T> template<class Y > madness::tr1::shptr::weak_ptr< T >::weak_ptr (weak_ptr< Y > const & r, typename detail::enable_if_convertible< Y, T >::type = detail::sp_empty()) inline
template<class T> template<class Y > madness::tr1::shptr::weak_ptr< T >::weak_ptr (shared_ptr< Y > const & r, typename detail::enable_if_convertible< Y, T >::type = detail::sp_empty()) inline
Member Function Documentation
template<class T> void madness::tr1::shptr::weak_ptr< T >::_internal_assign (T * px2, detail::shared_count const & pn2) inline
template<class T> template<class Y > bool madness::tr1::shptr::weak_ptr< T >::_internal_less (weak_ptr< Y > const & rhs) const inline
template<class T> bool madness::tr1::shptr::weak_ptr< T >::expired () const inline
References madness::tr1::shptr::detail::weak_count::use_count().
template<class T> shared_ptr<T> madness::tr1::shptr::weak_ptr< T >::lock () const inline
template<class T> void madness::tr1::shptr::weak_ptr< T >::reset () inline
template<class T> void madness::tr1::shptr::weak_ptr< T >::swap (this_type & other) inline
References madness::tr1::shptr::detail::weak_count::swap(), and std::swap().
template<class T> long madness::tr1::shptr::weak_ptr< T >::use_count () const inline
References madness::tr1::shptr::detail::weak_count::use_count().
Friends And Related Function Documentation
template<class T> template<class Y > friend class shared_ptr friend
template<class T> template<class Y > friend class weak_ptr friend
The documentation for this class was generated from the following file:
shared_ptr_bits.h