MADNESS: madness::tr1::shptr::enable_shared_from_this< T > Class Template Reference
madness::tr1::shptr::enable_shared_from_this< T > Class Template Reference
#include <shared_ptr_bits.h>
Public Member Functions
shared_ptr< T > shared_from_this ()
shared_ptr< T const > shared_from_this () const
template<class X , class Y >
void _internal_accept_owner (shared_ptr< X > const *ppx, Y *py) const
Protected Member Functions
enable_shared_from_this ()
enable_shared_from_this (enable_shared_from_this const &)
enable_shared_from_this & operator= (enable_shared_from_this const &)
~enable_shared_from_this ()
Constructor & Destructor Documentation
template<class T> madness::tr1::shptr::enable_shared_from_this< T >::enable_shared_from_this () inline protected
template<class T> madness::tr1::shptr::enable_shared_from_this< T >::enable_shared_from_this (enable_shared_from_this< T > const &) inline protected
template<class T> madness::tr1::shptr::enable_shared_from_this< T >::~enable_shared_from_this () inline protected
Member Function Documentation
template<class T> template<class X , class Y > void madness::tr1::shptr::enable_shared_from_this< T >::_internal_accept_owner (shared_ptr< X > const * ppx, Y * py) const inline
Referenced by madness::tr1::shptr::detail::sp_enable_shared_from_this().
template<class T> enable_shared_from_this& madness::tr1::shptr::enable_shared_from_this< T >::operator= (enable_shared_from_this< T > const &) inline protected
template<class T> shared_ptr<T> madness::tr1::shptr::enable_shared_from_this< T >::shared_from_this () inline
References madness::tr1::shptr::shared_ptr< T >::get().
template<class T> shared_ptr<T const> madness::tr1::shptr::enable_shared_from_this< T >::shared_from_this () const inline
References madness::tr1::shptr::shared_ptr< T >::get().
The documentation for this class was generated from the following file:
shared_ptr_bits.h