MADNESS: madness::tr1::shptr::shared_ptr< T > Class Template Reference
madness::tr1::shptr::shared_ptr< T > Class Template Reference
#include <shared_ptr_bits.h>
Public Types
typedef T element_type
typedef T value_type
typedef T * pointer
typedef
detail::shared_ptr_traits< T >
::reference reference
Public Member Functions
shared_ptr ()
template<class Y >
shared_ptr (Y *p)
template<class Y , class D >
shared_ptr (Y *p, D d)
template<class Y >
shared_ptr (weak_ptr< Y > const &r)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, typename detail::enable_if_convertible< Y, T >::type=detail::sp_empty())
template<class Y >
shared_ptr (shared_ptr< Y > const &r, T *p)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, detail::static_cast_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, detail::const_cast_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, detail::dynamic_cast_tag)
shared_ptr & operator= (shared_ptr const &r)
void reset ()
template<class Y >
void reset (Y *p)
template<class Y , class D >
void reset (Y *p, D d)
template<class Y >
void reset (shared_ptr< Y > const &r, T *p)
reference operator* () const
T * operator-> () const
T * get () const
operator bool () const
bool operator! () const
bool unique () const
long use_count () const
void swap (shared_ptr< T > &other)
template<class Y >
bool _internal_less (shared_ptr< Y > const &rhs) const
void * _internal_get_deleter (std::type_info const &ti) const
bool _internal_equiv (shared_ptr const &r) const
Friends
template<class Y >
class shared_ptr
template<class Y >
class weak_ptr
Member Typedef Documentation
template<class T> typedef T madness::tr1::shptr::shared_ptr< T >::element_type
template<class T> typedef T* madness::tr1::shptr::shared_ptr< T >::pointer
template<class T> typedef detail::shared_ptr_traits<T>::reference madness::tr1::shptr::shared_ptr< T >::reference
template<class T> typedef T madness::tr1::shptr::shared_ptr< T >::value_type
Constructor & Destructor Documentation
template<class T> madness::tr1::shptr::shared_ptr< T >::shared_ptr () inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (Y * p) inline explicit
template<class T> template<class Y , class D > madness::tr1::shptr::shared_ptr< T >::shared_ptr (Y * p, D d) inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (weak_ptr< Y > const & r) inline explicit
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, typename detail::enable_if_convertible< Y, T >::type = detail::sp_empty()) inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, T * p) inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, detail::static_cast_tag) inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, detail::const_cast_tag) inline
template<class T> template<class Y > madness::tr1::shptr::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, detail::dynamic_cast_tag) inline
Member Function Documentation
template<class T> bool madness::tr1::shptr::shared_ptr< T >::_internal_equiv (shared_ptr< T > const & r) const inline
template<class T> void* madness::tr1::shptr::shared_ptr< T >::_internal_get_deleter (std::type_info const & ti) const inline
Referenced by madness::tr1::shptr::get_deleter().
template<class T> template<class Y > bool madness::tr1::shptr::shared_ptr< T >::_internal_less (shared_ptr< Y > const & rhs) const inline
template<class T> T* madness::tr1::shptr::shared_ptr< T >::get () const inline
Referenced by madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner(), madness::WorldContainer< keyT, nodeT >::begin(), madness::Function< double, 6 >::do_hartree_product(), madness::WorldContainer< keyT, nodeT >::end(), madness::WorldContainer< keyT, nodeT >::find(), madness::Future< bool >::get(), madness::tr1::shptr::get_pointer(), madness::tr1::shptr::hash_value(), madness::Function< double, 6 >::is_initialized(), madness::detail::RemoteCounterImpl< T >::key(), madness::archive::BinaryFstreamOutputArchive::open(), madness::archive::BinaryFstreamInputArchive::open(), madness::tr1::shptr::operator!=(), madness::tr1::shptr::operator==(), q_c(), madness::WorldContainer< keyT, nodeT >::serialize(), madness::Future< bool >::set(), and madness::tr1::shptr::enable_shared_from_this< T >::shared_from_this().
template<class T> madness::tr1::shptr::shared_ptr< T >::operator bool () const inline
template<class T> bool madness::tr1::shptr::shared_ptr< T >::operator! () const inline
template<class T> reference madness::tr1::shptr::shared_ptr< T >::operator* () const inline
template<class T> T* madness::tr1::shptr::shared_ptr< T >::operator-> () const inline
template<class T> shared_ptr& madness::tr1::shptr::shared_ptr< T >::operator= (shared_ptr< T > const & r) inline
template<class T> void madness::tr1::shptr::shared_ptr< T >::reset () inline
Referenced by madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner(), madness::Function< double, 6 >::clear(), madness::archive::BinaryFstreamOutputArchive::close(), madness::archive::BinaryFstreamInputArchive::close(), SafeMPI::Finalize(), madness::detail::WorldMpi::finalize(), madness::Future< bool >::Future(), madness::Function< double, 6 >::gaxpy_oop(), madness::detail::WorldMpi::initialize(), SafeMPI::Intracomm::Intracomm(), madness::Function< double, 6 >::load(), main(), madness::Function< double, 6 >::mapdim(), madness::FunctionFactory< double, 6 >::no_functor(), madness::archive::BinaryFstreamOutputArchive::open(), madness::archive::BinaryFstreamInputArchive::open(), madness::tr1::shptr::detail::esft2_deleter_wrapper::operator()(), madness::WorldContainer< keyT, nodeT >::serialize(), madness::Function< double, 6 >::unary_op_coeffs(), and madness::detail::WorldMpiRuntime::~WorldMpiRuntime().
template<class T> template<class Y > void madness::tr1::shptr::shared_ptr< T >::reset (Y * p) inline
template<class T> template<class Y , class D > void madness::tr1::shptr::shared_ptr< T >::reset (Y * p, D d) inline
template<class T> template<class Y > void madness::tr1::shptr::shared_ptr< T >::reset (shared_ptr< Y > const & r, T * p) inline
template<class T> void madness::tr1::shptr::shared_ptr< T >::swap (shared_ptr< T > & other) inline
Referenced by madness::tr1::shptr::shared_ptr< FunctionImpl< T, MDIM > >::operator=(), and madness::tr1::shptr::swap().
template<class T> bool madness::tr1::shptr::shared_ptr< T >::unique () const inline
Referenced by madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner().
template<class T> long madness::tr1::shptr::shared_ptr< T >::use_count () const inline
Referenced by madness::tr1::shptr::enable_shared_from_this2< T >::_internal_accept_owner(), and madness::tr1::shptr::detail::esft2_deleter_wrapper::operator()().
Friends And Related Function Documentation
template<class T> template<class Y > friend class shared_ptr friend
template<class T> template<class Y > friend class weak_ptr friend
The documentation for this class was generated from the following file:
shared_ptr_bits.h