MADNESS: madness::ScopedArray< ptrT > Class Template Reference
madness::ScopedArray< ptrT > Class Template Reference
Scoped array.
#include <scopedptr.h>
Public Types
typedef ptrT element_type
the pointer type
Public Member Functions
ScopedArray (ptrT *p=NULL)
Construct a scoped pointer.
~ScopedArray ()
Destructor.
void reset (ptrT *p=NULL)
Reset the current pointer.
ptrT & operator[] (std::size_t i) const
Array element accessor.
ptrT * get () const
Pointer accessor.
operator bool () const
bool conversion operator
bool operator! () const
Not operator.
void swap (ScopedArray< ptrT > &other)
Swap the pointers.
Detailed Description
template<typename ptrT>
class madness::ScopedArray< ptrT >
Scoped array.
Holds a pointer to an array until it goes out of scope, then automatically deletes it. A scoped array pointer should be used to wrap pointers where the lifetime of the array pointer should be limited to a specific scope. The pointer cannot be copied. The pointer will be deleted with the delete operator.
Template Parameters
ptrT The pointer type
Note
A pointer to type ptrT must be a complete type
This class is based on Boost scoped_array.
Member Typedef Documentation
template<typename ptrT> typedef ptrT madness::ScopedArray< ptrT >::element_type
the pointer type
Constructor & Destructor Documentation
template<typename ptrT> madness::ScopedArray< ptrT >::ScopedArray (ptrT * p = NULL) inline explicit
Construct a scoped pointer.
Parameters
p The pointer to hold [default = NULL]
Exceptions
nothing
template<typename ptrT> madness::ScopedArray< ptrT >::~ScopedArray () inline
Destructor.
Calls delete[] operator
Member Function Documentation
template<typename ptrT> ptrT* madness::ScopedArray< ptrT >::get () const inline
Pointer accessor.
Returns
The pointer
Exceptions
nothing
Referenced by madness::WorldAmInterface::free_managed_buffers(), SafeMPI::Request::Testany(), and SafeMPI::Request::Testsome().
template<typename ptrT> madness::ScopedArray< ptrT >::operator bool () const inline
bool conversion operator
Returns
pointer != NULL
Exceptions
nothing
template<typename ptrT> bool madness::ScopedArray< ptrT >::operator! () const inline
Not operator.
Returns
pointer == NULL
Exceptions
nothing
template<typename ptrT> ptrT& madness::ScopedArray< ptrT >::operator[] (std::size_t i) const inline
Array element accessor.
Returns
The pointer
Exceptions
madness::MadnessException If the pointer is NULL
template<typename ptrT> void madness::ScopedArray< ptrT >::reset (ptrT * p = NULL) inline
Reset the current pointer.
This will destroy the current pointer. If an new pointer is provided this pointer will be set to that value.
Parameters
p The array pointer that will replace this pointer after deletion
Exceptions
madness::MadnessException If p is the same as this pointer, except when this pointer is NULL.
template<typename ptrT> void madness::ScopedArray< ptrT >::swap (ScopedArray< ptrT > & other) inline
Swap the pointers.
Parameters
other The pointer to swap with this pointer
Exceptions
nothing
Referenced by madness::ScopedArray< counterT >::reset().
The documentation for this class was generated from the following file:
scopedptr.h