MADNESS: madness::FunctionImpl< T, NDIM >::do_mapdim Struct Reference
madness::FunctionImpl< T, NDIM >::do_mapdim Struct Reference
map this on f
#include <funcimpl.h>
Public Types
typedef Range< typename
dcT::iterator > rangeT
Public Member Functions
do_mapdim ()
do_mapdim (const std::vector< long > map, implT &f)
bool operator() (typename rangeT::iterator &it) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
std::vector< long > map
implT * f
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_mapdim
map this on f
Member Typedef Documentation
template<typename T, std::size_t NDIM> typedef Range<typename dcT::iterator> madness::FunctionImpl< T, NDIM >::do_mapdim::rangeT
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mapdim::do_mapdim () inline
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_mapdim::do_mapdim (const std::vector< long > map, implT & f) inline
Member Function Documentation
template<typename T, std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_mapdim::operator() (typename rangeT::iterator & it) const inline
References c, cc, madness::FunctionNode< T, NDIM >::coeff(), madness::copy(), madness::GenTensor< T >::full_tensor_copy(), madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::FunctionNode< T, NDIM >::has_children(), madness::Key< NDIM >::level(), NDIM, madness::WorldContainer< keyT, valueT, hashfunT >::replace(), and madness::Key< NDIM >::translation().
template<typename T, std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_mapdim::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
template<typename T, std::size_t NDIM> implT* madness::FunctionImpl< T, NDIM >::do_mapdim::f
template<typename T, std::size_t NDIM> std::vector<long> madness::FunctionImpl< T, NDIM >::do_mapdim::map
The documentation for this struct was generated from the following file:
funcimpl.h