MADNESS: madness::archive::ArchiveImpl< Archive, T > Struct Template Reference
madness::archive::ArchiveImpl< Archive, T > Struct Template Reference
Default implementation of wrap_store and wrap_load.
#include <archive.h>
Static Public Member Functions
static const Archive & wrap_store (const Archive &ar, const T &t)
static const Archive & wrap_load (const Archive &ar, const T &t)
Detailed Description
template<class Archive, class T>
struct madness::archive::ArchiveImpl< Archive, T >
Default implementation of wrap_store and wrap_load.
Member Function Documentation
template<class Archive , class T > static const Archive& madness::archive::ArchiveImpl< Archive, T >::wrap_load (const Archive & ar, const T & t) inline static
References madness::archive::ArchiveLoadImpl< Archive, T >::load(), MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_load(), and std::tr1::T().
Referenced by madness::archive::operator&(), and madness::archive::operator>>().
template<class Archive , class T > static const Archive& madness::archive::ArchiveImpl< Archive, T >::wrap_store (const Archive & ar, const T & t) inline static
References MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store(), and madness::archive::ArchiveStoreImpl< Archive, T >::store().
Referenced by madness::archive::operator&(), and madness::archive::operator<<().
The documentation for this struct was generated from the following file:
archive.h