MADNESS: madness::FunctionImpl< T, NDIM >::do_inner_ext_local Struct Reference
madness::FunctionImpl< T, NDIM >::do_inner_ext_local Struct Reference
#include <funcimpl.h>
Public Member Functions
do_inner_ext_local (T(*f)(const coordT &), const implT *impl, const bool leaf_refine)
T operator() (typename dcT::const_iterator &it) const
T operator() (T a, T b) const
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
T(* fptr)(const coordT &)
const implT * impl
const bool leaf_refine
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_inner_ext_local::do_inner_ext_local (T(*)(const coordT &) f, const implT * impl, const bool leaf_refine) inline
Member Function Documentation
template<typename T, std::size_t NDIM> T madness::FunctionImpl< T, NDIM >::do_inner_ext_local::operator() (typename dcT::const_iterator & it) const inline
References cc, madness::FunctionImpl< T, NDIM >::do_inner_ext_local::fptr, madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), and std::tr1::T().
template<typename T, std::size_t NDIM> T madness::FunctionImpl< T, NDIM >::do_inner_ext_local::operator() (T a, T b) const inline
template<typename T, std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_inner_ext_local::serialize (const Archive & ar) inline
Member Data Documentation
template<typename T, std::size_t NDIM> T(* madness::FunctionImpl< T, NDIM >::do_inner_ext_local::fptr)(const coordT &)
Referenced by madness::FunctionImpl< T, NDIM >::do_inner_ext_local::operator()().
template<typename T, std::size_t NDIM> const implT* madness::FunctionImpl< T, NDIM >::do_inner_ext_local::impl
template<typename T, std::size_t NDIM> const bool madness::FunctionImpl< T, NDIM >::do_inner_ext_local::leaf_refine
The documentation for this struct was generated from the following file:
funcimpl.h