MADNESS: madness::archive::ArchiveLoadImpl< Archive, FunctionImpl< T, NDIM > * > Struct Template Reference
madness::archive::ArchiveLoadImpl< Archive, FunctionImpl< T, NDIM > * > Struct Template Reference
#include <funcimpl.h>
Static Public Member Functions
static void load (const Archive &ar, FunctionImpl< T, NDIM > *&ptr)
Member Function Documentation
template<class Archive , class T , std::size_t NDIM> static void madness::archive::ArchiveLoadImpl< Archive, FunctionImpl< T, NDIM > * >::load (const Archive & ar, FunctionImpl< T, NDIM > *& ptr) inline static
References madness::WorldObject< FunctionImpl< T, NDIM > >::id(), madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), MADNESS_EXCEPTION, madness::World::ptr_from_id(), and madness::World::world_from_id().
The documentation for this struct was generated from the following file:
funcimpl.h