MADNESS: madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R > Struct Template Reference
madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R > Struct Template Reference
merge the coefficent boxes of this into other's tree
#include <funcimpl.h>
Public Types
typedef Range< typename
dcT::const_iterator > rangeT
Public Member Functions
do_merge_trees ()
do_merge_trees (const T alpha, const R beta, FunctionImpl< Q, NDIM > &other)
bool operator() (typename rangeT::iterator &it) const
return the norm of the difference of this node and its "mirror" node
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
FunctionImpl< Q, NDIM > * other
T alpha
R beta
Detailed Description
template<typename T, std::size_t NDIM>
template<typename Q, typename R>
struct madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >
merge the coefficent boxes of this into other's tree
no comm, and the tree should be in an consistent state by virtue of FunctionNode::gaxpy_inplace
Member Typedef Documentation
template<typename T, std::size_t NDIM> template<typename Q , typename R > typedef Range<typename dcT::const_iterator> madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::rangeT
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> template<typename Q , typename R > madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::do_merge_trees () inline
template<typename T, std::size_t NDIM> template<typename Q , typename R > madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::do_merge_trees (const T alpha, const R beta, FunctionImpl< Q, NDIM > & other) inline
Member Function Documentation
template<typename T, std::size_t NDIM> template<typename Q , typename R > bool madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::operator() (typename rangeT::iterator & it) const inline
return the norm of the difference of this node and its "mirror" node
References madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::FunctionNode< T, NDIM >::gaxpy_inplace(), madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::WorldContainer< keyT, valueT, hashfunT >::replace(), and madness::FunctionNode< T, NDIM >::scale().
template<typename T, std::size_t NDIM> template<typename Q , typename R > template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::serialize (const Archive & ar) inline
References MADNESS_EXCEPTION.
Member Data Documentation
template<typename T, std::size_t NDIM> template<typename Q , typename R > T madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::alpha
template<typename T, std::size_t NDIM> template<typename Q , typename R > R madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::beta
template<typename T, std::size_t NDIM> template<typename Q , typename R > FunctionImpl<Q,NDIM>* madness::FunctionImpl< T, NDIM >::do_merge_trees< Q, R >::other
The documentation for this struct was generated from the following file:
funcimpl.h