MADNESS: madness::FunctionImpl< T, NDIM >::add_op Struct Reference
madness::FunctionImpl< T, NDIM >::add_op Struct Reference
add two functions f and g: result=alpha * f + beta * g
#include <funcimpl.h>
Public Types
typedef CoeffTracker< T, NDIM > ctT
typedef add_op this_type
Public Member Functions
bool randomize () const
add_op ()
add_op (const ctT &f, const ctT &g, const double alpha, const double beta)
std::pair< bool, coeffT > operator() (const keyT &key) const
if we are at the bottom of the trees, return the sum of the coeffs
this_type make_child (const keyT &child) const
Future< this_type > activate () const
retrieve the coefficients (parent coeffs might be remote)
this_type forward_ctor (const ctT &f1, const ctT &g1, const double alpha, const double beta)
taskq-compatible ctor
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
ctT f
tracking coeffs of first and second addend
ctT g
double alpha
prefactor for f, g
double beta
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::add_op
add two functions f and g: result=alpha * f + beta * g
Member Typedef Documentation
template<typename T, std::size_t NDIM> typedef CoeffTracker<T,NDIM> madness::FunctionImpl< T, NDIM >::add_op::ctT
template<typename T, std::size_t NDIM> typedef add_op madness::FunctionImpl< T, NDIM >::add_op::this_type
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::add_op::add_op () inline
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::add_op::add_op (const ctT & f, const ctT & g, const double alpha, const double beta) inline
Member Function Documentation
template<typename T, std::size_t NDIM> Future<this_type> madness::FunctionImpl< T, NDIM >::add_op::activate () const inline
retrieve the coefficients (parent coeffs might be remote)
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), std::tr1::f1, madness::FunctionImpl< T, NDIM >::add_op::forward_ctor(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::World::taskq, and madness::FunctionImpl< T, NDIM >::world.
template<typename T, std::size_t NDIM> this_type madness::FunctionImpl< T, NDIM >::add_op::forward_ctor (const ctT & f1, const ctT & g1, const double alpha, const double beta) inline
taskq-compatible ctor
Referenced by madness::FunctionImpl< T, NDIM >::add_op::activate().
template<typename T, std::size_t NDIM> this_type madness::FunctionImpl< T, NDIM >::add_op::make_child (const keyT & child) const inline
References madness::FunctionImpl< T, NDIM >::add_op::alpha, madness::FunctionImpl< T, NDIM >::add_op::beta, and madness::CoeffTracker< T, NDIM >::make_child().
template<typename T, std::size_t NDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::add_op::operator() (const keyT & key) const inline
if we are at the bottom of the trees, return the sum of the coeffs
References madness::CoeffTracker< T, NDIM >::coeff(), madness::copy(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_tensor_args(), madness::CoeffTracker< T, NDIM >::is_leaf(), madness::CoeffTracker< T, NDIM >::key(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::GenTensor< T >::reduce_rank(), and madness::TensorArgs::thresh.
template<typename T, std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::add_op::randomize () const inline
template<typename T, std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::add_op::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::add_op::beta.
Member Data Documentation
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::add_op::alpha
prefactor for f, g
Referenced by madness::FunctionImpl< T, NDIM >::add_op::make_child().
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::add_op::beta
Referenced by madness::FunctionImpl< T, NDIM >::add_op::make_child(), and madness::FunctionImpl< T, NDIM >::add_op::serialize().
template<typename T, std::size_t NDIM> ctT madness::FunctionImpl< T, NDIM >::add_op::f
tracking coeffs of first and second addend
template<typename T, std::size_t NDIM> ctT madness::FunctionImpl< T, NDIM >::add_op::g
The documentation for this struct was generated from the following file:
funcimpl.h