MADNESS: madness::FunctionImpl< T, NDIM >::do_convert_to_color Struct Reference
madness::FunctionImpl< T, NDIM >::do_convert_to_color Struct Reference
#include <funcimpl.h>
Public Member Functions
do_convert_to_color ()
do_convert_to_color (const double limit, const bool log)
double operator() (double val) const
Static Public Member Functions
static double lower ()
Public Attributes
double limit
bool log
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::FunctionImpl< T, NDIM >::do_convert_to_color
convert a number [0,limit] to a hue color code [blue,red], or, if log is set, a number [1.e-10,limit]
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_convert_to_color::do_convert_to_color () inline
template<typename T, std::size_t NDIM> madness::FunctionImpl< T, NDIM >::do_convert_to_color::do_convert_to_color (const double limit, const bool log) inline
Member Function Documentation
template<typename T, std::size_t NDIM> static double madness::FunctionImpl< T, NDIM >::do_convert_to_color::lower () inline static
Referenced by madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator()().
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator() (double val) const inline
References madness::FunctionImpl< T, NDIM >::do_convert_to_color::limit, mpfr::log10(), madness::FunctionImpl< T, NDIM >::do_convert_to_color::lower(), max, and mpfr::min().
Member Data Documentation
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_convert_to_color::limit
Referenced by madness::FunctionImpl< T, NDIM >::do_convert_to_color::operator()().
template<typename T, std::size_t NDIM> bool madness::FunctionImpl< T, NDIM >::do_convert_to_color::log
The documentation for this struct was generated from the following file:
funcimpl.h