MADNESS: madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM > Struct Template Reference
madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM > Struct Template Reference
recursive part of recursive_apply
#include <funcimpl.h>
Public Types
typedef recursive_apply_op
< opT, LDIM > this_type
Public Member Functions
bool randomize () const
recursive_apply_op ()
recursive_apply_op (implT *result, const CoeffTracker< T, LDIM > &iaf, const CoeffTracker< T, LDIM > &iag, const opT *apply_op)
recursive_apply_op (const recursive_apply_op &other)
std::pair< bool, coeffT > operator() (const Key< NDIM > &key) const
make the NS-coefficients and send off the application of the operator
std::pair< bool, coeffT > finalize (const double kernel_norm, const keyT &key, const coeffT &coeff) const
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
this_type make_child (const keyT &child) const
Future< this_type > activate () const
this_type forward_ctor (implT *r, const CoeffTracker< T, LDIM > &f1, const CoeffTracker< T, LDIM > &g1, const opT *apply_op1)
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * result
CoeffTracker< T, LDIM > iaf
CoeffTracker< T, LDIM > iag
opT * apply_op
Detailed Description
template<typename T, std::size_t NDIM>
template<typename opT, std::size_t LDIM>
struct madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >
recursive part of recursive_apply
Member Typedef Documentation
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> typedef recursive_apply_op<opT,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::this_type
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op () inline
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op (implT * result, const CoeffTracker< T, LDIM > & iaf, const CoeffTracker< T, LDIM > & iag, const opT * apply_op) inline
References madness::FunctionImpl< T, NDIM >::MADNESS_ASSERT(), and NDIM.
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op (const recursive_apply_op< opT, LDIM > & other) inline
Member Function Documentation
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> Future<this_type> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate () const inline
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), std::tr1::f1, madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::forward_ctor(), madness::World::taskq, and madness::FunctionImpl< T, NDIM >::world.
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize (const double kernel_norm, const keyT & key, const coeffT & coeff) const inline
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
References madness::FunctionImpl< T, NDIM >::get_thresh(), madness::Key< NDIM >::level(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()().
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::forward_ctor (implT * r, const CoeffTracker< T, LDIM > & f1, const CoeffTracker< T, LDIM > & g1, const opT * apply_op1) inline
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate().
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child (const keyT & child) const inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, madness::Key< NDIM >::break_apart(), and madness::CoeffTracker< T, NDIM >::make_child().
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator() (const Key< NDIM > & key) const inline
make the NS-coefficients and send off the application of the operator
Returns
a Future<bool,coeffT>(is_leaf,coeffT())
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op, madness::Key< NDIM >::break_apart(), madness::CoeffTracker< T, NDIM >::coeff(), madness::copy(), madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::finalize(), madness::GenTensor< T >::full_tensor(), madness::CoeffTracker< T, NDIM >::get_impl(), madness::FunctionImpl< T, NDIM >::get_k(), madness::outer_low_rank(), madness::World::rank(), std::tr1::T(), madness::WorldObject< Derived >::task(), and madness::FunctionImpl< T, NDIM >::world.
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> bool madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::randomize () const inline
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op.
Member Data Documentation
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> opT* madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::apply_op
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::serialize().
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iaf
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> CoeffTracker<T,LDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::iag
template<typename T, std::size_t NDIM> template<typename opT , std::size_t LDIM> implT* madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::result
The documentation for this struct was generated from the following file:
funcimpl.h