MADNESS: madness::perturbed_vxc Struct Reference
madness::perturbed_vxc Struct Reference
#include <TDA_XC.h>
Public Member Functions
perturbed_vxc (const XCfunctional &xc, int ispin, int what)
madness::Tensor< double > operator() (const madness::Key< 3 > &key, const std::vector< madness::Tensor< double > > &t) const
Public Attributes
const XCfunctional * xc
const int what
const int ispin
Constructor & Destructor Documentation
madness::perturbed_vxc::perturbed_vxc (const XCfunctional & xc, int ispin, int what) inline
Member Function Documentation
madness::Tensor<double> madness::perturbed_vxc::operator() (const madness::Key< 3 > & key, const std::vector< madness::Tensor< double > > & t) const inline
References madness::XCfunctional::fxc(), madness::XCfunctional::is_gga(), madness::XCfunctional::is_lda(), MADNESS_EXCEPTION, and madness::XCfunctional::vxc().
Member Data Documentation
const int madness::perturbed_vxc::ispin
const int madness::perturbed_vxc::what
const XCfunctional* madness::perturbed_vxc::xc
The documentation for this struct was generated from the following file:
TDA_XC.h