MADNESS: madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT > Struct Template Reference
madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT > Struct Template Reference
recursive part of recursive_apply
#include <funcimpl.h>
Public Types
typedef recursive_apply_op2< opT > this_type
typedef CoeffTracker< T, NDIM > ctT
typedef std::pair< bool, coeffT > argT
Public Member Functions
bool randomize () const
recursive_apply_op2 ()
recursive_apply_op2 (implT *result, const ctT &iaf, const opT *apply_op)
recursive_apply_op2 (const recursive_apply_op2 &other)
argT operator() (const Key< NDIM > &key) const
send off the application of the operator
argT finalize (const double kernel_norm, const keyT &key, const coeffT &coeff, const implT *r) const
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
this_type make_child (const keyT &child) const
Future< this_type > activate () const
retrieve the coefficients (parent coeffs might be remote)
this_type forward_ctor (implT *result1, const ctT &iaf1, const opT *apply_op1)
taskq-compatible ctor
template<typename Archive >
void serialize (const Archive &ar)
Public Attributes
implT * result
ctT iaf
const opT * apply_op
need this for randomization
Detailed Description
template<typename T, std::size_t NDIM>
template<typename opT>
struct madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >
recursive part of recursive_apply
Member Typedef Documentation
template<typename T, std::size_t NDIM> template<typename opT > typedef std::pair<bool,coeffT> madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::argT
template<typename T, std::size_t NDIM> template<typename opT > typedef CoeffTracker<T,NDIM> madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::ctT
template<typename T, std::size_t NDIM> template<typename opT > typedef recursive_apply_op2<opT> madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::this_type
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::recursive_apply_op2 () inline
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::recursive_apply_op2 (implT * result, const ctT & iaf, const opT * apply_op) inline
template<typename T, std::size_t NDIM> template<typename opT > madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::recursive_apply_op2 (const recursive_apply_op2< opT > & other) inline
Member Function Documentation
template<typename T, std::size_t NDIM> template<typename opT > Future<this_type> madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::activate () const inline
retrieve the coefficients (parent coeffs might be remote)
References madness::CoeffTracker< T, NDIM >::activate(), madness::WorldTaskQueue::add(), std::tr1::f1, madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::forward_ctor(), madness::World::taskq, and madness::FunctionImpl< T, NDIM >::world.
template<typename T, std::size_t NDIM> template<typename opT > argT madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::finalize (const double kernel_norm, const keyT & key, const coeffT & coeff, const implT * r) const inline
sole purpose is to wait for the kernel norm, wrap it and send it back to caller
References madness::FunctionImpl< T, NDIM >::get_thresh(), madness::Key< NDIM >::level(), and madness::FunctionImpl< T, NDIM >::truncate_tol().
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator()().
template<typename T, std::size_t NDIM> template<typename opT > this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::forward_ctor (implT * result1, const ctT & iaf1, const opT * apply_op1) inline
taskq-compatible ctor
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::activate().
template<typename T, std::size_t NDIM> template<typename opT > this_type madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::make_child (const keyT & child) const inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::apply_op, and madness::CoeffTracker< T, NDIM >::make_child().
template<typename T, std::size_t NDIM> template<typename opT > argT madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator() (const Key< NDIM > & key) const inline
send off the application of the operator
the first (core) neighbor (ie. the box itself) is processed immediately, all other ones are shoved into the taskq
Returns
a pair<bool,coeffT>(is_leaf,coeffT())
References madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::apply_op, madness::CoeffTracker< T, NDIM >::coeff(), madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::finalize(), madness::GenTensor< T >::has_data(), madness::CoeffTracker< T, NDIM >::is_leaf(), madness::World::rank(), std::tr1::T(), madness::WorldObject< Derived >::task(), and madness::FunctionImpl< T, NDIM >::world.
template<typename T, std::size_t NDIM> template<typename opT > bool madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::randomize () const inline
template<typename T, std::size_t NDIM> template<typename opT > template<typename Archive > void madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::serialize (const Archive & ar) inline
References madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::apply_op.
Member Data Documentation
template<typename T, std::size_t NDIM> template<typename opT > const opT* madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::apply_op
need this for randomization
Referenced by madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::make_child(), madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::operator()(), and madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::serialize().
template<typename T, std::size_t NDIM> template<typename opT > ctT madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::iaf
template<typename T, std::size_t NDIM> template<typename opT > implT* madness::FunctionImpl< T, NDIM >::recursive_apply_op2< opT >::result mutable
The documentation for this struct was generated from the following file:
funcimpl.h