MADNESS: madness::archive::ArchiveImpl< Archive, archive_array< T > > Struct Template Reference
madness::archive::ArchiveImpl< Archive, archive_array< T > > Struct Template Reference
Partial specialization for archive_array.
#include <archive.h>
Static Public Member Functions
static const Archive & wrap_store (const Archive &ar, const archive_array< T > &t)
static const Archive & wrap_load (const Archive &ar, const archive_array< T > &t)
Detailed Description
template<class Archive, class T>
struct madness::archive::ArchiveImpl< Archive, archive_array< T > >
Partial specialization for archive_array.
This makes use of stuff that user specializations need not
Member Function Documentation
template<class Archive , class T > static const Archive& madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_load (const Archive & ar, const archive_array< T > & t) inline static
References MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_load(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_load(), madness::archive::serialize(), and std::tr1::T().
template<class Archive , class T > static const Archive& madness::archive::ArchiveImpl< Archive, archive_array< T > >::wrap_store (const Archive & ar, const archive_array< T > & t) inline static
References MAD_ARCHIVE_DEBUG, madness::archive::ArchivePrePostImpl< Archive, T >::postamble_store(), madness::archive::ArchivePrePostImpl< Archive, T >::preamble_store(), madness::archive::serialize(), and std::tr1::T().
The documentation for this struct was generated from the following file:
archive.h