MADNESS: noise Struct Reference
noise Struct Reference
Try to create noise using random gauss functions.
#include <tdhf_CIS.h>
Public Types
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
Public Types inherited from madness::FunctionFunctorInterface< double, 3 >
typedef GenTensor< double > coeffT
typedef Key< NDIM > keyT
Public Member Functions
noise (double size)
noise (double size, double width)
double operator() (const coord_3d &r) const
Public Member Functions inherited from madness::FunctionFunctorInterface< double, 3 >
virtual bool screened (const Vector< double, NDIM > &c1, const Vector< double, NDIM > &c2) const
Can we screen this function based on the bounding box information?
virtual bool supports_vectorized () const
Does the interface support a vectorized operator()?
virtual void operator() (const Vector< double *, 1 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 2 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 3 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 4 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 5 > &xvals, double *fvals, int npts) const
virtual void operator() (const Vector< double *, 6 > &xvals, double *fvals, int npts) const
virtual double operator() (const Vector< double, NDIM > &x) const =0
You should implement this to return f(x)
virtual std::vector< Vector
< double, NDIM > > special_points () const
Override this to return list of special points to be refined more deeply.
virtual Level special_level ()
Override this change level refinement for special points (default is 6)
virtual ~FunctionFunctorInterface ()
virtual coeffT coeff (const keyT &) const
virtual coeffT values (const keyT &key, const Tensor< double > &tensor) const
virtual bool provides_coeff () const
does this functor directly provide sum coefficients? or only function values?
Detailed Description
Try to create noise using random gauss functions.
Member Typedef Documentation
typedef std::shared_ptr<FunctionFunctorInterface<double,3> > noise::functorT
Constructor & Destructor Documentation
noise::noise (double size) inline
References noise().
Referenced by noise().
noise::noise (double size, double width) inline
References mpfr::fabs(), madness::Random::get(), sigma, and madness::wall_time().
Member Function Documentation
double noise::operator() (const coord_3d & r) const inline
References mpfr::exp().
The documentation for this struct was generated from the following file:
tdhf_CIS.h