MADNESS: madness::GaussianConvolution1DCache< Q > Struct Template Reference
madness::GaussianConvolution1DCache< Q > Struct Template Reference
MADNESS libraries » Multiresolution analaysis » Function
#include <convolution1d.h>
Public Types
typedef ConcurrentHashMap
< hashT, std::shared_ptr
< GaussianConvolution1D< Q >
> >::iterator iterator
typedef ConcurrentHashMap
< hashT, std::shared_ptr
< GaussianConvolution1D< Q >
> >::datumT datumT
Public Member Functions
template<>
ConcurrentHashMap< hashT,
std::shared_ptr
< GaussianConvolution1D
< double > > > map
template<>
ConcurrentHashMap< hashT,
std::shared_ptr
< GaussianConvolution1D
< double_complex > > > map
Static Public Member Functions
static std::shared_ptr
< GaussianConvolution1D< Q > > get (int k, double expnt, int m, bool periodic)
Static Public Attributes
static ConcurrentHashMap
< hashT, std::shared_ptr
< GaussianConvolution1D< Q > > > map
Member Typedef Documentation
template<typename Q > typedef ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > >::datumT madness::GaussianConvolution1DCache< Q >::datumT
template<typename Q > typedef ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > >::iterator madness::GaussianConvolution1DCache< Q >::iterator
Member Function Documentation
template<typename Q > static std::shared_ptr< GaussianConvolution1D<Q> > madness::GaussianConvolution1DCache< Q >::get (int k, double expnt, int m, bool periodic) inline static
References madness::ConcurrentHashMap< keyT, valueT, hashfunT >::end(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::find(), madness::hash_combine(), madness::hash_value(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::insert(), k, madness::constants::pi, and sqrt().
template<> ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double > > > madness::GaussianConvolution1DCache< double >::map ()
template<> ConcurrentHashMap< hashT, std::shared_ptr< GaussianConvolution1D< double_complex > > > madness::GaussianConvolution1DCache< double_complex >::map ()
Member Data Documentation
template<typename Q > ConcurrentHashMap<hashT, std::shared_ptr< GaussianConvolution1D<Q> > > madness::GaussianConvolution1DCache< Q >::map static
The documentation for this struct was generated from the following file:
convolution1d.h