MADNESS: madness::error_leaf_op< T, NDIM > Struct Template Reference
madness::error_leaf_op< T, NDIM > Struct Template Reference
returns true if the node is well represented compared to its parent
#include <funcimpl.h>
Public Types
typedef FunctionImpl< T, NDIM > implT
typedef GenTensor< T > coeffT
Public Member Functions
bool do_error_leaf_op () const
error_leaf_op ()
error_leaf_op (const implT *f)
bool operator() (const Key< NDIM > &key) const
no pre-determination
bool operator() (const Key< NDIM > &key, const GenTensor< T > &coeff) const
no post-determination
bool operator() (const Key< NDIM > &key, const coeffT &coeff, const coeffT &parent) const
post-determination
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
const implT * f
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::error_leaf_op< T, NDIM >
returns true if the node is well represented compared to its parent
Member Typedef Documentation
template<typename T, std::size_t NDIM> typedef GenTensor<T> madness::error_leaf_op< T, NDIM >::coeffT
template<typename T, std::size_t NDIM> typedef FunctionImpl<T,NDIM> madness::error_leaf_op< T, NDIM >::implT
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::error_leaf_op< T, NDIM >::error_leaf_op () inline
template<typename T, std::size_t NDIM> madness::error_leaf_op< T, NDIM >::error_leaf_op (const implT * f) inline
Member Function Documentation
template<typename T, std::size_t NDIM> bool madness::error_leaf_op< T, NDIM >::do_error_leaf_op () const inline
template<typename T, std::size_t NDIM> bool madness::error_leaf_op< T, NDIM >::operator() (const Key< NDIM > & key) const inline
no pre-determination
template<typename T, std::size_t NDIM> bool madness::error_leaf_op< T, NDIM >::operator() (const Key< NDIM > & key, const GenTensor< T > & coeff) const inline
no post-determination
template<typename T, std::size_t NDIM> bool madness::error_leaf_op< T, NDIM >::operator() (const Key< NDIM > & key, const coeffT & coeff, const coeffT & parent) const inline
post-determination
Parameters
[in] key the FunctionNode which we want to determine if it's a leaf node
[in] coeff the coeffs of key
[in] parent the coeffs of key's parent node
Returns
is the FunctionNode of key a leaf node?
References madness::FunctionImpl< T, NDIM >::get_thresh(), madness::GenTensor< T >::has_no_data(), madness::Key< NDIM >::level(), madness::FunctionImpl< T, NDIM >::truncate_tol(), and madness::FunctionImpl< T, NDIM >::upsample().
template<typename T, std::size_t NDIM> template<typename Archive > void madness::error_leaf_op< T, NDIM >::serialize (Archive & ar) inline
References madness::error_leaf_op< T, NDIM >::f.
Member Data Documentation
template<typename T, std::size_t NDIM> const implT* madness::error_leaf_op< T, NDIM >::f
Referenced by madness::error_leaf_op< T, NDIM >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h