MADNESS: madness::TDA_TIMER Struct Reference
madness::TDA_TIMER Struct Reference
Strucutre for TIMER.
#include <TDA.h>
Public Member Functions
TDA_TIMER (World &world, std::string msg)
void update_time ()
void info (bool debug=true)
print out information about the passed time since the TDA_TIMER object was created
Public Attributes
World & world
const double start_wall
const double start_cpu
std::string operation
double end_wall
double end_cpu
Detailed Description
Strucutre for TIMER.
Constructor & Destructor Documentation
madness::TDA_TIMER::TDA_TIMER (World & world, std::string msg) inline
TDA_TIMER contructor
Parameters
[in] world the world
[in] msg a string that contains the desired printout when info function is called
Member Function Documentation
void madness::TDA_TIMER::info (bool debug = true) inline
print out information about the passed time since the TDA_TIMER object was created
References debug, madness::World::rank(), and update_time().
Referenced by madness::TDA::solve(), and madness::TDA::solve_sequential().
void madness::TDA_TIMER::update_time () inline
References start_cpu, start_wall, and madness::wall_time().
Referenced by info().
Member Data Documentation
double madness::TDA_TIMER::end_cpu
double madness::TDA_TIMER::end_wall
std::string madness::TDA_TIMER::operation
const double madness::TDA_TIMER::start_cpu
Referenced by update_time().
const double madness::TDA_TIMER::start_wall
Referenced by update_time().
World& madness::TDA_TIMER::world
The documentation for this struct was generated from the following file:
TDA.h