MADNESS: madness::leaf_op< T, NDIM > Struct Template Reference
madness::leaf_op< T, NDIM > Struct Template Reference
returns true if the function has a leaf node at key (works only locally)
#include <funcimpl.h>
Public Types
typedef FunctionImpl< T, NDIM > implT
Public Member Functions
bool do_error_leaf_op () const
leaf_op ()
leaf_op (const implT *f)
bool operator() (const Key< NDIM > &key, const GenTensor< T > &coeff=GenTensor< T >()) const
pre/post-determination is the same here
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
const implT * f
Detailed Description
template<typename T, std::size_t NDIM>
struct madness::leaf_op< T, NDIM >
returns true if the function has a leaf node at key (works only locally)
Member Typedef Documentation
template<typename T, std::size_t NDIM> typedef FunctionImpl<T,NDIM> madness::leaf_op< T, NDIM >::implT
Constructor & Destructor Documentation
template<typename T, std::size_t NDIM> madness::leaf_op< T, NDIM >::leaf_op () inline
template<typename T, std::size_t NDIM> madness::leaf_op< T, NDIM >::leaf_op (const implT * f) inline
Member Function Documentation
template<typename T, std::size_t NDIM> bool madness::leaf_op< T, NDIM >::do_error_leaf_op () const inline
template<typename T, std::size_t NDIM> bool madness::leaf_op< T, NDIM >::operator() (const Key< NDIM > & key, const GenTensor< T > & coeff = GenTensor<T>()) const inline
pre/post-determination is the same here
References madness::WorldContainer< keyT, valueT, hashfunT >::find(), madness::FunctionImpl< T, NDIM >::get_coeffs(), and madness::WorldContainer< keyT, valueT, hashfunT >::is_local().
template<typename T, std::size_t NDIM> template<typename Archive > void madness::leaf_op< T, NDIM >::serialize (Archive & ar) inline
References madness::leaf_op< T, NDIM >::f.
Member Data Documentation
template<typename T, std::size_t NDIM> const implT* madness::leaf_op< T, NDIM >::f
Referenced by madness::leaf_op< T, NDIM >::serialize().
The documentation for this struct was generated from the following file:
funcimpl.h