MADNESS: madness::FunctionImpl< T, NDIM >::do_norm2sq_local Struct Reference
madness::FunctionImpl< T, NDIM >::do_norm2sq_local Struct Reference
#include <funcimpl.h>
Public Member Functions
double operator() (typename dcT::const_iterator &it) const
double operator() (double a, double b) const
template<typename Archive >
void serialize (const Archive &ar)
Member Function Documentation
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_norm2sq_local::operator() (typename dcT::const_iterator & it) const inline
References madness::FunctionNode< T, NDIM >::coeff(), madness::FunctionNode< T, NDIM >::has_coeff(), and madness::norm().
template<typename T, std::size_t NDIM> double madness::FunctionImpl< T, NDIM >::do_norm2sq_local::operator() (double a, double b) const inline
template<typename T, std::size_t NDIM> template<typename Archive > void madness::FunctionImpl< T, NDIM >::do_norm2sq_local::serialize (const Archive & ar) inline
The documentation for this struct was generated from the following file:
funcimpl.h