MADNESS: CoupledPurturbation Struct Reference
CoupledPurturbation Struct Reference
#include <response.h>
Public Member Functions
CoupledPurturbation (madness::World &world, SCF &calc, double freq, bool enableTD=false)
void guess_excite (int axis)
void project_diag_space (int axis)
vecfuncT calcBSH (vecfuncT &rmo, double eval)
double max_norm (int axis)
void make_vpsi (int axis)
void solve (int axis, PurturbationOperator &purturb)
void dipole_response ()
Public Attributes
madness::World & world
World object.
SCF & calc
SCF object including solved MOs with HF/DFT.
double freq
frequency
MolecularSystem rsys
virtual orbitals
MolecularSystem Vrsys
potential applied virtual orbitals
int nXY
Tamm-Dancoff 1: ON 2: OFF.
Constructor & Destructor Documentation
CoupledPurturbation::CoupledPurturbation (madness::World & world, SCF & calc, double freq, bool enableTD = false) inline
Member Function Documentation
vecfuncT CoupledPurturbation::calcBSH (vecfuncT & rmo, double eval)
void CoupledPurturbation::dipole_response ()
References solve().
void CoupledPurturbation::guess_excite (int axis)
References madness::compress(), madness::END_TIMER(), madness::mul(), madness::START_TIMER(), and madness::truncate().
void CoupledPurturbation::make_vpsi (int axis)
References madness::apply(), madness::Function< T, NDIM >::clear(), and madness::Function< T, NDIM >::truncate().
double CoupledPurturbation::max_norm (int axis)
References max, and madness::norm().
void CoupledPurturbation::project_diag_space (int axis)
References k.
void CoupledPurturbation::solve (int axis, PurturbationOperator & purturb)
References madness::END_TIMER(), max, madness::print(), madness::World::rank(), and madness::START_TIMER().
Member Data Documentation
SCF& CoupledPurturbation::calc
SCF object including solved MOs with HF/DFT.
double CoupledPurturbation::freq
frequency
int CoupledPurturbation::nXY
Tamm-Dancoff 1: ON 2: OFF.
MolecularSystem CoupledPurturbation::rsys
virtual orbitals
MolecularSystem CoupledPurturbation::Vrsys
potential applied virtual orbitals
madness::World& CoupledPurturbation::world
World object.
The documentation for this struct was generated from the following files:
response.h
response.cc