MADNESS: madness::trajectory< NDIM > Struct Template Reference
madness::trajectory< NDIM > Struct Template Reference
#include <funcplot.h>
Public Types
typedef Vector< double, NDIM > coordT
Public Member Functions
trajectory ()
trajectory (double radius, long npt)
trajectory (double radius, coord_3d el2, long npt)
Vector< double, NDIM > operator() (int ipt)
Static Public Member Functions
static double hueCode (const int rank)
some tools for plotting MRA ranks of low order tensors
static void print_psdot (FILE *f, double x, double y, double color)
static coord_3d circle2 (double lo, double hi, double radius, coord_3d el2, long npt, long ipt)
static coord_6d circle_6d (const coord_6d &lo, const coord_6d &hi, double radius, coord_3d el2, long npt, long ipt)
static Vector< double, NDIM > line_internal (const coordT &lo, const coordT &hi, double radius, coord_3d el2, long npt, long ipt)
static trajectory line2 (const coordT start, const coordT end, const long npt)
constructor for a line
static trajectory line_xyz (const int xyz, const long npt)
EZ ctor for a line a direction xyz={0,1,2,..,NDIM-1} thru the origin.
Public Attributes
double lo
double hi
double radius
long npt
coordT start
coordT end
coord_3d el2
coordT(* curve)(const coordT &lo, const coordT &hi, double radius, coord_3d el2, long npt, long ipt)
Member Typedef Documentation
template<size_t NDIM> typedef Vector<double,NDIM> madness::trajectory< NDIM >::coordT
Constructor & Destructor Documentation
template<size_t NDIM> madness::trajectory< NDIM >::trajectory () inline
template<size_t NDIM> madness::trajectory< NDIM >::trajectory (double radius, long npt) inline
template<size_t NDIM> madness::trajectory< NDIM >::trajectory (double radius, coord_3d el2, long npt) inline
Member Function Documentation
template<size_t NDIM> static coord_3d madness::trajectory< NDIM >::circle2 (double lo, double hi, double radius, coord_3d el2, long npt, long ipt) inline static
References mpfr::cos(), madness::trajectory< NDIM >::npt, madness::constants::pi, and mpfr::sin().
template<size_t NDIM> static coord_6d madness::trajectory< NDIM >::circle_6d (const coord_6d & lo, const coord_6d & hi, double radius, coord_3d el2, long npt, long ipt) inline static
References mpfr::cos(), madness::trajectory< NDIM >::npt, madness::constants::pi, and mpfr::sin().
template<size_t NDIM> static double madness::trajectory< NDIM >::hueCode (const int rank) inline static
some tools for plotting MRA ranks of low order tensors
References max.
template<size_t NDIM> static trajectory madness::trajectory< NDIM >::line2 (const coordT start, const coordT end, const long npt) inline static
constructor for a line
References madness::trajectory< NDIM >::curve, madness::trajectory< NDIM >::end, madness::trajectory< NDIM >::line_internal(), madness::trajectory< NDIM >::npt, and madness::trajectory< NDIM >::start.
Referenced by draw_line(), madness::trajectory< NDIM >::line_xyz(), solve(), test_modified(), and test_recursive_application().
template<size_t NDIM> static Vector<double, NDIM> madness::trajectory< NDIM >::line_internal (const coordT & lo, const coordT & hi, double radius, coord_3d el2, long npt, long ipt) inline static
References madness::trajectory< NDIM >::lo.
Referenced by madness::trajectory< NDIM >::line2().
template<size_t NDIM> static trajectory madness::trajectory< NDIM >::line_xyz (const int xyz, const long npt) inline static
EZ ctor for a line a direction xyz={0,1,2,..,NDIM-1} thru the origin.
References madness::FunctionDefaults< NDIM >::get_cell_width(), madness::trajectory< NDIM >::hi, L, madness::trajectory< NDIM >::line2(), and madness::trajectory< NDIM >::lo.
template<size_t NDIM> Vector<double,NDIM> madness::trajectory< NDIM >::operator() (int ipt) inline
References madness::trajectory< NDIM >::curve.
template<size_t NDIM> static void madness::trajectory< NDIM >::print_psdot (FILE * f, double x, double y, double color) inline static
Referenced by madness::plot_along().
Member Data Documentation
template<size_t NDIM> coordT(* madness::trajectory< NDIM >::curve)(const coordT &lo, const coordT &hi, double radius, coord_3d el2, long npt, long ipt)
Referenced by madness::trajectory< NDIM >::line2(), and madness::trajectory< NDIM >::operator()().
template<size_t NDIM> coord_3d madness::trajectory< NDIM >::el2
template<size_t NDIM> coordT madness::trajectory< NDIM >::end
Referenced by madness::trajectory< NDIM >::line2().
template<size_t NDIM> double madness::trajectory< NDIM >::hi
Referenced by madness::trajectory< NDIM >::line_xyz().
template<size_t NDIM> double madness::trajectory< NDIM >::lo
Referenced by madness::trajectory< NDIM >::line_internal(), and madness::trajectory< NDIM >::line_xyz().
template<size_t NDIM> long madness::trajectory< NDIM >::npt
Referenced by madness::trajectory< NDIM >::circle2(), madness::trajectory< NDIM >::circle_6d(), madness::trajectory< NDIM >::line2(), and madness::plot_along().
template<size_t NDIM> double madness::trajectory< NDIM >::radius
template<size_t NDIM> coordT madness::trajectory< NDIM >::start
Referenced by madness::trajectory< NDIM >::line2().
The documentation for this struct was generated from the following file:
funcplot.h