MADNESS: madness::detail::adqtest Struct Reference
madness::detail::adqtest Struct Reference
#include <adquad.h>
Public Types
typedef double returnT
Public Member Functions
double operator() (double x) const
Static Public Member Functions
static double exact ()
static bool runtest ()
Member Typedef Documentation
typedef double madness::detail::adqtest::returnT
Member Function Documentation
static double madness::detail::adqtest::exact () inline static
References mpfr::exp(), pi, and sqrt().
Referenced by runtest().
double madness::detail::adqtest::operator() (double x) const inline
References mpfr::cos(), and mpfr::exp().
static bool madness::detail::adqtest::runtest () inline static
References madness::adq(), exact(), and test().
The documentation for this struct was generated from the following file:
adquad.h