MADNESS: tdhf.cc File Reference
tdhf.cc File Reference
compute the time-dependent HF equations (currently CIS approximation)
#include <chem/TDA.h>
#include <iomanip>
#include <iostream>
Functions
int main (int argc, char **argv)
Detailed Description
compute the time-dependent HF equations (currently CIS approximation)
The source is <a href=http://code.google.com/p/m-a-d-n-e-s-s/source/browse/local /trunk/src/apps/examples/tdhf.cc>here.
Function Documentation
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::xfunction::converged, madness::copy(), madness::xfunction::delta, madness::xfunction::error, madness::xfunction::expectation_value, madness::f, madness::finalize(), madness::TDA::get_calc(), madness::TDA::get_converged_xfunctions(), madness::Function< T, NDIM >::get_impl(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::initialize(), madness::xfunction::iterations, madness::SCF::make_density(), madness::SCF::molecule, madness::xfunction::number, madness::xfunction::omega, madness::position_stream(), madness::print(), madness::Molecule::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::Function< T, NDIM >::set_thresh(), madness::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::TDA::solve(), sqrt(), madness::startup(), madness::MolecularEnergy::value(), madness::wall_time(), and madness::xfunction::x.