MADNESS: tinystr.cc File Reference
tinystr.cc File Reference
#include "tinystr.h"
Functions
TiXmlString operator+ (const TiXmlString &a, const TiXmlString &b)
TiXmlString operator+ (const TiXmlString &a, const char *b)
TiXmlString operator+ (const char *a, const TiXmlString &b)
Function Documentation
TiXmlString operator+ (const TiXmlString & a, const TiXmlString & b)
References a(), b(), TiXmlString::length(), and TiXmlString::reserve().
TiXmlString operator+ (const TiXmlString & a, const char * b)
References a(), TiXmlString::append(), TiXmlString::length(), and TiXmlString::reserve().
TiXmlString operator+ (const char * a, const TiXmlString & b)
References TiXmlString::append(), b(), TiXmlString::length(), and TiXmlString::reserve().