MADNESS: moldft.cc File Reference
tkato/moldft.cc File Reference
#include <madness/mra/mra.h>
#include <madness/tensor/solvers.h>
#include <tkato/scfparam.h>
#include <tkato/scf.h>
#include <moldft/molecule.h>
#include <moldft/molecularbasis.h>
#include <moldft/corepotential.h>
#include <moldft/xcfunctional.h>
Classes
class LevelPmap
Typedefs
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
Functions
int main (int argc, char **argv)
Typedef Documentation
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
Function Documentation
int main (int argc, char ** argv)
References madness::CalculationParameters::algopt, SafeMPI::COMM_WORLD, madness::CalculationParameters::derivatives, madness::SCF::derivatives(), madness::CalculationParameters::dipole, madness::SCF::dipole(), madness::SCF::do_plots(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Molecule::get_all_coords(), madness::CalculationParameters::gmaxiter, madness::World::gop, madness::CalculationParameters::gopt, madness::CalculationParameters::gprec, madness::CalculationParameters::gprint(), madness::CalculationParameters::gtest, madness::CalculationParameters::gtol, madness::CalculationParameters::gval, madness::SCF::initial_load_bal(), madness::initialize(), madness::SCF::make_nuclear_potential(), madness::SCF::molecule, madness::QuasiNewton::optimize(), madness::SCF::param, madness::print(), madness::Molecule::print(), madness::CalculationParameters::print(), madness::print_stats(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_pmap(), madness::SCF::set_protocol(), madness::QuasiNewton::set_test(), madness::QuasiNewton::set_update(), madness::World::size(), madness::startup(), and madness::MolecularEnergy::value().