MADNESS: scf.cc File Reference
tkato/SCF.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/misc/ran.h>
#include <madness/tensor/solvers.h>
#include <ctime>
#include <vector>
#include <tkato/scfparam.h>
#include <tkato/scf.h>
#include <moldft/molecule.h>
#include <moldft/molecularbasis.h>
#include <moldft/corepotential.h>
#include <moldft/xcfunctional.h>
Typedefs
typedef Vector< double, 3 > coordT
typedef std::shared_ptr
< FunctionFunctorInterface
< double, 3 > > functorT
typedef Function< double, 3 > functionT
typedef std::vector< functionT > vecfuncT
typedef std::pair< vecfuncT,
vecfuncT > pairvecfuncT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef FunctionFactory
< double, 3 > factoryT
typedef SeparatedConvolution
< double, 3 > operatorT
typedef std::shared_ptr
< operatorT > poperatorT
Functions
void START_TIMER (World &world)
void END_TIMER (World &world, const char *msg)
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
double mask1 (double x)
double mask3 (const coordT &ruser)
double rsquared (const coordT &r)
tensorT Q3 (const tensorT &s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
tensorT sqrt (const tensorT &s, double tol=1e-8)
Computes matrix square root (not used any more?)
Typedef Documentation
typedef Vector<double,3> coordT
typedef FunctionFactory<double,3> factoryT
typedef Function<double,3> functionT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
typedef SeparatedConvolution<double,3> operatorT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
typedef std::shared_ptr<operatorT> poperatorT
typedef std::vector<pairvecfuncT> subspaceT
typedef Tensor<double> tensorT
typedef std::vector<functionT> vecfuncT
Function Documentation
void drot (long n, double *restrict a, double *restrict b, double s, double c, long inc)
Simple (?) version of BLAS-1 DROT(N, DX, INCX, DY, INCY, DC, DS)
void drot3 (long n, double *restrict a, double *restrict b, double s, double c, long inc)
void END_TIMER (World & world, const char * msg)
References madness::World::rank(), sss, ttt, and madness::wall_time().
double mask1 (double x) inline
double mask3 (const coordT & ruser)
References madness::mask1(), and mask3().
tensorT Q3 (const tensorT & s)
Given overlap matrix, return rotation with 3rd order error to orthonormalize the vectors.
References madness::inner().
double rsquared (const coordT & r)
References rsquared().
tensorT sqrt (const tensorT & s, double tol = 1e-8)
Computes matrix square root (not used any more?)
References c, MADNESS_EXCEPTION, madness::print(), and madness::syev().
Referenced by SCF::localize_PM_task_kernel(), and SCF::vector_stats().
void START_TIMER (World & world)
References madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().