MADNESS: wavef.h File Reference
wavef.h File Reference
#include <madness/mra/mra.h>
#include <complex>
#include <iostream>
#include <stdio.h>
#include <iomanip>
#include <time.h>
#include "hyp.h"
#include "interp.h"
Classes
class baseWF
class ScatteringWF
struct ScatteringWF::MemberFuncPtr
class PhiK
class Phikl
class BoundWF
class Expikr
class Gaussian
class Yl0
Macros
#define PRINT(str) if(world.rank()==0) std::cout << str
#define PRINTLINE(str) if(world.rank()==0) std::cout << str << std::endl
Typedefs
typedef std::complex< double > complexd
typedef madness::Vector
< double, NDIM > vector3D
typedef Function< complexd, NDIM > complex_functionT
typedef Function< double, NDIM > functionT
typedef FunctionFactory
< complexd, NDIM > complex_factoryT
typedef FunctionFactory
< double, NDIM > factoryT
typedef std::shared_ptr
< madness::FunctionFunctorInterface
< complexd, NDIM > > functorT
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
Functions
const char * wave_function_filename (int step)
bool wave_function_exists (World &world, int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
complex_functionT wave_function_load (World &world, int step)
Variables
const int nIOProcessors =1
const std::string prefix = "data"
const int NDIM = 3
Macro Definition Documentation
#define PRINT (str) if(world.rank()==0) std::cout << str
#define PRINTLINE (str) if(world.rank()==0) std::cout << str << std::endl
Typedef Documentation
typedef FunctionFactory<complexd,NDIM> complex_factoryT
typedef Function<complexd,NDIM> complex_functionT
typedef std::complex<double> complexd
typedef FunctionFactory<double,NDIM> factoryT
typedef Function<double,NDIM> functionT
typedef std::shared_ptr< madness::FunctionFunctorInterface<complexd,NDIM> > functorT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef madness::Vector<double,NDIM> vector3D
Function Documentation
bool wave_function_exists (World & world, int step)
References madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), and wave_function_filename().
Referenced by doit(), doWork(), main(), projectL(), projectPsi(), and zSlice().
const char* wave_function_filename (int step)
References InputParameters::prefix, and prefix.
Referenced by line_plot(), wave_function_exists(), wave_function_load(), and wave_function_store().
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by doWork(), main(), projectL(), projectPsi(), propagate(), and zSlice().
void wave_function_store (World & world, int step, const complex_functionT & psi)
References InputParameters::nio, nIOProcessors, psi(), and wave_function_filename().
Referenced by doit(), and propagate().
Variable Documentation
const int NDIM = 3
const int nIOProcessors =1
Referenced by wave_function_store().
const std::string prefix = "data"
Referenced by main(), InputParameters::read(), and wave_function_filename().