MADNESS: wfSlice.cc File Reference
wfSlice.cc File Reference
#include <fstream>
#include <iomanip>
#include <string>
#include <sstream>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include "wavef.h"
Classes
struct WF
Macros
#define PRINT(str) if(world.rank()==0) std::cout << str
#define PRINTLINE(str) if(world.rank()==0) std::cout << str << std::endl
Typedefs
typedef std::complex< double > complexd
typedef Vector< double, NDIM > vector3D
typedef Function< complexd, NDIM > complex_functionT
typedef Function< double, NDIM > functionT
typedef FunctionFactory
< complexd, NDIM > complex_factoryT
typedef FunctionFactory
< double, NDIM > factoryT
typedef std::shared_ptr
< WorldDCPmapInterface< Key< 3 > > > pmapT
Functions
const char * wave_function_filename (int step)
bool wave_function_exists (World &world, int step)
void wave_function_store (World &world, int step, const complex_functionT &psi)
complex_functionT wave_function_load (World &world, int step)
void loadParameters2 (World &world, int &nGrid, double &th, double &phi, int &wf, double &kMomentum, int &lMAX, int &nPhoton)
void loadParameters (World &world, double &thresh, int &kMAD, double &L, double &Z, int &nPhoton, double &cutoff, double &Llarge)
string toString (int &i)
void doplot (World &world, int step, const complex_functionT &psi, double Lplot, long numpt, const char *fname)
int main (int argc, char **argv)
Macro Definition Documentation
#define PRINT (str) if(world.rank()==0) std::cout << str
#define PRINTLINE (str) if(world.rank()==0) std::cout << str << std::endl
Referenced by loadParameters(), loadParameters2(), and main().
Typedef Documentation
typedef FunctionFactory<complexd,NDIM> complex_factoryT
typedef Function<complexd,NDIM> complex_functionT
typedef std::complex<double> complexd
typedef FunctionFactory<double,NDIM> factoryT
typedef Function<double,NDIM> functionT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
typedef Vector<double,NDIM> vector3D
Function Documentation
void doplot (World & world, int step, const complex_functionT & psi, double Lplot, long numpt, const char * fname)
References madness::plotdx(), madness::print(), madness::World::rank(), and madness::wall_time().
Referenced by main().
void loadParameters (World & world, double & thresh, int & kMAD, double & L, double & Z, int & nPhoton, double & cutoff, double & Llarge)
Atomic Units: m = hbar = e = 1 E_n = n hbar omega I_p = Z^2 / 2 KE = E_n - I_p 0.5 v^2 = n omega - Z^2/2 v = sqrt(2 n omega - Z^2) dMAX = v tMAX
References madness::f, PRINTLINE, and sqrt().
Referenced by main().
void loadParameters2 (World & world, int & nGrid, double & th, double & phi, int & wf, double & kMomentum, int & lMAX, int & nPhoton)
References madness::f, and PRINTLINE.
Referenced by main().
int main (int argc, char ** argv)
xMax: the largest x & z coordinate An odd number of grid points ensures zero is a gird point
Output for GNUPLOT binary matrix n+1> <y0> <y1> <y2> ... <yN> x0> <x0,0> <z0,1> <z0,2> ... <z0,N> x1> <x1,0> <z1,1> <z1,2> ... <z1,N> . . . . ... . . . . . ... . float buffer[n+1];
References SafeMPI::COMM_WORLD, doplot(), madness::error(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, loadParameters(), loadParameters2(), madness::print(), PRINTLINE, madness::World::rank(), madness::real(), madness::FunctionDefaults< NDIM >::set_apply_randomize(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), madness::startup(), thresh, wave_function_exists(), and wave_function_load().
string toString (int & i)
bool wave_function_exists (World & world, int step)
References madness::archive::BaseParallelArchive< BinaryFstreamInputArchive >::exists(), and wave_function_filename().
Referenced by main().
const char* wave_function_filename (int step)
References prefix.
Referenced by wave_function_exists(), wave_function_load(), and wave_function_store().
complex_functionT wave_function_load (World & world, int step)
References psi(), and wave_function_filename().
Referenced by main().
void wave_function_store (World & world, int step, const complex_functionT & psi)
References nIOProcessors, psi(), and wave_function_filename().